### PR TITLE
LSNBLDR-646; drop duplicate index

### PR DESCRIPTION
**Pull request by clhedrick**

### CODE REVIEW

**Comment by ottenhoff** [comment]
I'm confused why you didn't use my PR ?

**Comment by clhedrick** [comment]
I looked at the Jira and didn’t see a PR. Sorry if I missed it.

On Jun 3, 2016, at 12:34 PM, Sam Ottenhoff <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm confused why you didn't use my PR ?

**Comment by clhedrick** [comment]
You’re PR is more complete, so I’ll do something with it (not sure If I can still merge it).

By the way, there’s a copy of the 11 conversion script in both master (12) and 11.x. They’re similar, but different. Are they supposed to be in sync? If the copy in master is not being maintained, maybe it should be removed.

On Jun 3, 2016, at 12:34 PM, Sam Ottenhoff <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm confused why you didn't use my PR ?

**Comment by ottenhoff** [comment]
No, it will probably conflict. I will close it.

**Comment by clhedrick** [comment]
what I'm doing is removing mine.

**Pull request merged**
