### PR TITLE
LSNBLDR-486 - Customized css file could not be found

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
I believe the alternative to this would be to just change the message for simplepage.broken-css to provide more instruction from

-simplepage.broken-css=The customized CSS file could not be found.
+simplepage.broken-css=The customized CSS file could not be found. Please use the settings to select the "Use Default" as the Custom CSS or add a new CSS file.

Kind of leaning more toward this.

**Comment by ottenhoff** [comment]
@jonespm do you want this merged in? Or do you want the alternative change you proposed?

**Comment by jonespm** [comment]
@ottenhoff  I don't know, I kind of was hoping for @clhedrick opinion. It's either we don't display the error message every time when the system can't find a CSS file (for whatever reason) or we give them some additional information on how to fix it. This seems like it typically happens when someone goes into resources and just deletes this file without knowing that it's used for something, then the UI just keeps bugging the user.

**Comment by clhedrick** [comment]
Sorry, I’m working on another issue. I will review this and check it in. I’m currently trying to get part of the LEAP design functioning. If Expresslab is going to start doing CSS for Lessons, I think it’s time-critical to get the functionality there for them to style.

**Pull request merged**
