### PR TITLE
SAK-41502 - Excusing an individual grade should be reflected in score…

### PR DESCRIPTION
**Pull request by jonespm**
…'s Grade Log

### CODE REVIEW

**Comment by jonespm** [comment]
This was the easiest I could find to do this, insert a i18n'd string into the grade field, then attempt to get the message back when it was displayed. Not sure if there's a better idea here.

**Comment by steveswinsburg** [comment]
This is confusing. It would be far better to pass in a flag regarding the grade being excused and then rendering appropriately, rather than changing the grade to be a translation and checking for a string vs number.

**Comment by jonespm** [comment]
I was trying to avoid any database alteration. [GB_GRADING_EVENT_T](https://github.com/sakaiproject/sakai/blob/master/edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradingEvent.hbm.xml) currently is just GRADER_ID, STUDENT_ID, DATE_GRADED, GRADE (as a string value rather than double in some other columns). I didn't think this needed a new column that would be 99% empty and no straightforward way to convert this field. 

`String grade = gradeLog.getGrade(); `

Currently returns a just the string and it would need to be translated somewhere. There's currently no i18n in edu-services so it seemed like gradebook was the place to do that. 

I'm happy to close this or modify but I don't know what you mean by "pass in a flag". I feel like it would be good to have a more centralized "user facing event" service rather than having to have duplicate functionality for Gradebook, Samigo, Assignment and everything else that's recording specific events that we want to keep forever and display to the user (verses the event table that tracks everything and is often warehoused) though then that gets to be much, much bigger than this. :/

**Comment by jonespm** [comment]
Based on @steveswinsburg 's comments, I think I'm just going to close this and mark "Won't Fix" on the jira. I don't see any way of representing this action in the current GradingEvent backend without a redesign of the GradingEvent (and possibly the the every other tools event). While it seems like it would be nice to know this kind of information it would probably involve storing these event values as JSON/XML rather than a single score value.

**Pull request closed without merging**
