### PR TITLE
SAK-31645: fix cache expiration problems in profile2

### PR DESCRIPTION
**Pull request by mgolden-noodle**
This fixes the cache expiration issues in profile2,

https://jira.sakaiproject.org/browse/SAK-31645

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Are there meant to be two PRs?

**Comment by steveswinsburg** [comment]
Rerunning Travis to check this out. Lots of failures lately, most likely unrelated.

**Comment by mgolden-noodle** [comment]
One for 11.x and one for 12.


On August 5, 2016 5:29:57 PM EDT, Steve Swinsburg <notifications@github.com> wrote:
>Are there meant to be two PRs?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sakaiproject/sakai/pull/3137#issuecomment-237970790

Mitch Golden
CTO, Noodle Partners

**Comment by steveswinsburg** [comment]
The current process for an 11.x merge is to just set the merge status flag in Jira. I've pushed this in though so save the trouble.

**Pull request merged**
