### PR TITLE
SAK-41721 this fixes the scenario where an admin user duplicates a site

### PR DESCRIPTION
**Pull request by ottenhoff**
that contains a private LTI tool. The new behavior copies the LTI tool
while the old behavior was an NPE

### CODE REVIEW

**Comment by ottenhoff** [comment]
@csev my main worry here is that it doesn't seem to solve for the use case of an admin duplicating a site (e.g., via webservices) and the Instructor viewing the site. The instructor has no permission to find the old lti_tool (in the template site) and can't copy the data over to the new site

**Comment by lgekeler** [comment]
> GTG. You've left a comment about the non admin user's ability to copy tools, so it's on the record.

@csev Notre Dame's main use case is via web services. The private tool is in that site because it does not have an enterprise license, so that site is being copied only to sites owned by a given department.

**Comment by lgekeler** [comment]
@csev Hey Chuck, I think this is being held up because we'd like a review from you.

**Comment by csev** [comment]
Looks good to me.

**Pull request merged**
