### PR TITLE
SAK-40738: CKEditor autosave alerts about saved text for ckeditor oth…

### PR DESCRIPTION
**Pull request by hornersa**
…er than the one that originated the autosave

### CODE REVIEW

**Comment by ern** [comment]
Is it possible the contents are simply not being cleared correctly?

**Comment by hornersa** [comment]
> Is it possible the contents are simply not being cleared correctly?

A core problem at hand pertains to the definition of the key storing autosaves (SaveKey). By default, CKEditor autosave uses the location URL (what the browser presents in the URL field) and just a handful of other data to define the SaveKey. 

For the vast majority of Sakai tool views, the entity being edited (e.g., an announcement in the Announcements tool) is not distinctly represented in the location URL, whereby one announcement is not distinguished from another in the SaveKey. 

The vast majority of code proposed in this PR injects the entity ID (and some context) into the DOM for the Sakai ckeditor.launch.js to detect as it constructs a SaveKey. The SaveKey I propose consists of the following items delimited by an underscore character:

- the string "autosave"
- the URL (though this is conditionally modified in a few cases for the Overview and Tests & Quizzes tools to improve UX with auto-saving)
- the CKEditor's "name" or "id" attribute for its corresponding "textarea" element
- the value for the hidden input field, ckeditor-autosave-context
- the value for the hidden input field, ckeditor-autosave-entity-id
- the current user's username (as an aid to alleviate, though not resolve, a problem described in SAK-45798)

**Comment by ern** [comment]
I guess I was hoping there was enough entropy to not have to add all this info!

**Comment by hornersa** [comment]
> I guess I was hoping there was enough entropy to not have to add all this info!

Understandable. Bides the thee additional bits of data I append to the SaveKey with my approach, lots of files are admittedly affected with this PR. Nevertheless it represents the most expedient approach I could devise to address most of the many facets of the problem of getting ckeditor autosave to work properly within (most of) the various views in Sakai. (E.g., autosave behaves in counter-intuitive ways for the comments tool in Lessons, given how the editor is loaded, per SAK-45845.) It's also the approach actively working in our instance of Sakai.

In hindsight, a different approach using a webcomponent to instantiate the ckeditor with all the requisite context in the DOM for autosave to work correctly is conceivable. Though such an approach is mere speculation on my part, I would expect that it would nevertheless need affect all views that load ckeditor (i.e. roughly the same number of files).

**Comment by ern** [comment]
Yep the sakai-editor webcomponent would reduce this!

**Review by ern — APPROVED** [review]

**Pull request merged**
