### PR TITLE
KNL-1351 - Fix HikariCP startup errors under Oracle

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by ottenhoff** [comment]
LGTM

**Comment by jonespm** [comment]
Yeah, every JDBC drive should be JDBC4 compliant now and support the isValid method to do the query validation. I think having this string in the kernel.properties was causing a lot of problems that I couldn't figure out since I couldn't null it out via properties (but was setting it in null explicitly in the bean)

**Comment by seththeriault** [comment]
Yes, this is a good fix. Defining something like this in kernel.properties was a recipe for a disaster since it's not well-surfaced and databases configs should be explicitly set.

**Comment by jonespm** [comment]
Of course without this string the tests (using hsqldb) are currently failing because it doesn't support this JDBC4 isValid.

- It looks like SakaiKernelTestBase is going to have to be modified to include this property in every case
- Or the Hikari SakaiBasicDataSource is going to have to have a way to set this to null via a property.

I'll look at the first option

**Comment by jonespm** [comment]
The easiest fix I could think of was to add a new property ${sakai.test}/test.properties and add these properties to that file so they'd be used in every test. It has some logic to override a sakai.home for each case but not all of the tests use this and all of the kernel tests need this to work.

Maybe there's a better way to do this to retain this property during the tests but I can't think of it yet.

**Comment by steveswinsburg** [comment]
Maybe the better way is to rip out the hsqldb support ;)

**Comment by buckett** [comment]
Having simple integration tests that don't require people to setup a DB is a big plus. Dropping HSQLDB from the kernel means without configuration it's not easy to have everyone able to run the integration tests.

**Comment by jonespm** [comment]
Right you'd need to replace the hsqldb in all the unit tests with some other in memory engine by default. I'm all for someone doing that but I'm not going to have the time in the short term to experiment with it. Really all this fix does is keeps the validationQuery being passed by default for the hsqldb unit tests and provides a null query by default when running so Oracle and MySQL (JDBC4 compliant drivers) work better.

The unit tests in kernel all have directories that override various configurations (test/resources/filesystem/sakai-configuration.xml) so it's seems like a good amount of work just to convert kernel over, even to an in memory DB that emulates Oracle/MySQL.

**Comment by jonespm** [comment]
I'm going to merge this. The major change is to remove the forced validationQuery property from the kernel.properties. This is not needed at all in MySQL or Oracle and having it defined causes problems with HikariCP. The HSQLDB problems are not really related, and if someone wants to remove that and rewrite it with something else that seems like a completely different issue, that I'd be for, which wouldn't have any effect on this change.

**Pull request merged**
