### PR TITLE
KNL-1484 Reduce column lengths to support mysql utf8mb4 databases

### PR DESCRIPTION
**Pull request by smarquard**
Reduce column lengths to avoid total row width exceeding 64K with utf8mb4

### CODE REVIEW

**Comment by ottenhoff** [comment]
LGTM do we need to convert everyone?

**Comment by jonespm** [comment]
We won't actually need to convert until the default becomes utf8mb4, and there's more work to do before that happens. But this should have a conversion script.

**Comment by smarquard** [comment]
You could actually run utf8 as long as you want, I think, so long as it's never removed from mysql (i.e. even after utf8mb4 becomes the default).

This change is required for scenario of starting up Sakai in an empty database in mysql 5.7+ with the db created by "create database sakai default character set utf8mb4;"

We recently converted our mysql 5.5 utf8 db to mysql 5.7 utf8mb4 by exporting the schema with mysqldump, replacing utf8 with utf8mb4 in the "create table ..." statements, dumping the data to .txt files with mysqldump from the 5.5 db and importing it with mysqlimport to the 5.7 db. We had to do that anyway because export & import is the recommended 5.5 to 5.6 upgrade route.

There may be another way to get a mysql 5.6 or mysql 5.7 utf8 to utf8mb4 db (i.e. without exporting and importing data). In general, the db schema for an existing Sakai 10.x or 11.x db won't be valid for a utf8mb4 db without changes.

The parent issue for this is SAK-31945.

**Comment by smarquard** [comment]
On the topic of conversion, this also depends on how your SAKAI_CONFIG_ITEM table in Sakai 11 came to be created. For example, if you upgraded to Sakai 11 from Sakai 10, then this table is created by the conversion script with a slightly different schema, i.e. LONGTEXT fields rather than large varchar fields.

-- ---------------------------------------------------------------------------
-- SAKAI_CONFIG_ITEM - KNL-1063 - MYSQL
-- ---------------------------------------------------------------------------

CREATE TABLE SAKAI_CONFIG_ITEM (
        ID                              BIGINT(20) NOT NULL AUTO_INCREMENT,
        NODE                    VARCHAR(255),
        NAME                    VARCHAR(255) NOT NULL,
        VALUE                   LONGTEXT,
        RAW_VALUE               LONGTEXT,
        TYPE                    VARCHAR(255) NOT NULL,
        DEFAULT_VALUE   LONGTEXT,
        DESCRIPTION             LONGTEXT,
        SOURCE                  VARCHAR(255) DEFAULT NULL,
        DEFAULTED               BIT(1) NOT NULL,
        REGISTERED              BIT(1) NOT NULL,
        SECURED                 BIT(1) NOT NULL,
        DYNAMIC                 BIT(1) NOT NULL,
        CREATED                 DATETIME NOT NULL,
        MODIFIED                DATETIME NOT NULL,
        POLL_ON                 DATETIME DEFAULT NULL,
        PRIMARY KEY (ID)
);

and there is also kernel/kernel-impl/src/main/sql/mysql/sakai_config_item.sql which matches what's in the conversion script, but doesn't seem to get run because Hibernate creates it first from the hbm.xml file.

**Comment by ern** [comment]
why not just enable innodb_large_prefix whic is enabled by default in MySQL 5.7.7

**Comment by ottenhoff** [comment]
>why not just enable innodb_large_prefix which is enabled by default in MySQL 5.7.7

A lot of requirements for deployers:

> for InnoDB tables that use the DYNAMIC and COMPRESSED row formats. (Creating such tables also requires the option values innodb_file_format=barracuda and innodb_file_per_table=true.)

**Comment by smarquard** [comment]
innodb_large_prefix is about maximum key lengths. This issue is about the maximum row length of 64K (bytes), not key lengths. 64K bytes = 16K characters in utf8mb4.

**Comment by ern** [comment]
Sorry for confusing this PR with the other PR!

**Pull request merged**
