### PR TITLE
LSNBLDR-711 Added Twitter Timeline component for lessons.

### PR DESCRIPTION
**Pull request by ouit0408**
Added new dialog for twitter option in 'ShowPage.html', related variables
and function are added in 'SimplePageBean.java' to create/edit
SimplePageItem for Twitter widget.'messages.properties' is edited
to add new texts.Default height parameter is added if in case there is no
height value passed.
Twitter widget id should be added in the placeholder.properties for each
institution.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Can you post a screenshot of this?

**Comment by ouit0408** [comment]
twitter

**Comment by clhedrick** [comment]
I installed this. A couple of things:
1) The tool is always added to the end of the page. It needs to work if you click the + in the middle of page. In the popup menu that lists tools, to the add the class add-before-param. That will cause the item number of the item you're supposed to add the before to be put in the addBefore parameter of the URL. The picker has to get that parameter and add it as a hidden field in the form that's submitted to the bean. Look at any of the existing pickers for the code.
2) If i add the tool and then refresh the page, it gets added an additional time
3) Please look at formatting the display. The calendar is white on a white column background. I'm not sure how I'd handle that. Either put blue behind the whole thing (e.g. look at the Checklist tool) or maybe put blue behind the header and a margin around the rest. Look at the latest version of the forums summary.
4) Using your example twitter feed I don't see any entries.

**Comment by ouit0408** [comment]
I have implemented  review comments but changing the style of twitter feed does not work the same way as it works for other widgets. So for now I have left it as it is.

**Comment by clhedrick** [comment]
I'm not seeing anything useful. Here's the DOM that's generated. There's no src on the iframe.
Are you trying this in 10 or 11? 

<div class="right-col">
                        <div class="edit-col"><div><a href="http://heidelberg.rutgers.edu:8080/lessonbuilder-tool/templates/" class="usebutton edit-twitter ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="return false" role="button"><span class="ui-button-text"><span aria-hidden="true" class="fa-edit fa-edit-icon"></span></span></a><a aria-hidden="true" href="#" class="usebutton del-item-link ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="return false" role="button" title="Delete this item"><span class="ui-button-text"><span class="fa-trash-o fa-edit-icon"></span></span></a><a href="#" class="usebutton add-link ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="return false" role="button" title="Add new item above this one"><span class="ui-button-text"><span class="fa-plus fa-edit-icon plus-edit-icon"></span></span></a></div></div>
                        
                        <div class="textbox"><div align="left" style="height:300px;" class="twitter-div"><iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true" class="twitter-timeline twitter-timeline-rendered" style="position: absolute; visibility: hidden; display: block; width: 0px; height: 0px; padding: 0px; border: none;"></iframe><a class="twitter-timeline" href="https://twitter.com/twitter" data-widget-id="" data-tweet-limit="5" data-dnt="true" data-screen-name="twitter" data-twitter-extracted-i1473364521546630866="true">Tweets by @'twitter'</a></div></div>
                        <span style="display:none" class="twitter-id">2574</span>
                        <span style="display:none" class="username">twitter</span>
                        <span style="display:none" class="tweetLimit">5</span>
                        <span style="display:none" class="twitterHeight">300</span>
                    </div>

**Comment by clhedrick** [comment]
FYI, I used @twitter as my example. Their main web page seems to show that there is a feed with that name. I also used the example from the dialog box, and that didn't change anything.

**Comment by ouit0408** [comment]
image


I have just tried adding '@twitter' username and can see timeline added , have attached the screenshot. And all this work if for 11.

**Comment by clhedrick** [comment]
Wait a sec. You're saying that for every twitter feed that I want a faculty member to access, I need to do something in sakai.properties? I think that's a bad UI. We're trying to make Sakai more dynamic, not put more stuff in sakai.properties. I suggest adding a new table, and letting both admin and individual site owners be able to add stuff. Kind of the way LTI is handled.

This actually seems like one of the more generally useful Oxford features, but as usual I'm concerned about the UI.

**Comment by nicholaswilson100** [comment]
I'm taking over this PR because Neelam has stopped working on it and I need to add to and rebase it so I'll add a new PR

**Comment by nicholaswilson100** [comment]
The new PR is https://github.com/sakaiproject/sakai/pull/3659

**Comment by ern** [comment]
closing as there is a new PR that incorporates #3659

**Pull request closed without merging**
