### PR TITLE
SAK-32224 - Ability to disable the animated tool menu by property

### PR DESCRIPTION
**Pull request by mpellicer**
Ability to disable the animated tool menu by property

### CODE REVIEW

**Comment by buckett** [comment]
This is the PR for directly to 11.x Is the code so different that is needs a different PR?

**Comment by mpellicer** [comment]
There is a difference with Master, just to make things easier.

 $PBJQ(window).scroll(function(){
vs
function animateToolBar() {

**Comment by jonespm** [comment]
I think for 11 we wanted this to default to true. I'm also not sure about this property name. I feel like 

portal.scrolling.toolbar.enabled=true/false 

seems more appropriate and clear? (If it's true the tool bar follows the scroll, otherwise false it doesn't)

Then here "false" as-is would be the default, and in the other it would be true.

**Comment by mpellicer** [comment]
Cool @jonespm good morning!

**Comment by ncaidin** [comment]
Yes. I thought that was the decision on the Sakai Core team call. Should be turned off by default for 11 since it would be introducing a new interface in a maintenance release.

**Comment by mpellicer** [comment]
@jonespm PR updated!

**Pull request merged**
