### PR TITLE
SAK-41858 - Whitespaces between ip addresses prevent saving exam's se…

### PR DESCRIPTION
**Pull request by danielmerino**
…ttings

### CODE REVIEW

**Comment by mpellicer** [comment]
Thanks @danielmerino , would you mind using StringUtils?

Look at this:

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#deleteWhitespace-java.lang.String-

Patch will be something like 
StringUtils.deleteWhitespace(assessmentSettings.getIpAddresses().trim())

**Comment by danielmerino** [comment]
@mpellicer Sure, it's done. Take a look and let me know if it's ok. Thanks!

**Comment by danielmerino** [comment]
As a side note, just in case somebody wants to use this in Sakai 11, this patch doesn't work with commons.lang because deleteWhitespace() also deletes newline characters so IP settings just stop working!

Finally in 11.4 I have done this with String replace() function.

**Comment by mpellicer** [comment]
Is this working in Master after the change?

**Comment by danielmerino** [comment]
S2U will verify it, but I'm not sure who. :-) It should work as master uses commons.lang3

**Comment by mpellicer** [comment]
Ok thanks Daniel, please reopen the Jira in case the implementation needs a review.

**Comment by danielmerino** [comment]
@mpellicer this patch doesn't work as isWhitespace also deletes newline characters. It deletes characters according to [isWhitespace()](https://docs.oracle.com/javase/6/docs/api/java/lang/Character.html?is-external=true#isWhitespace(char)) function.

It's weird because in my local tests it worked with newlines, but I don't know what really happened.

If StringUtils is the preferred library, I have found that strip function can receive a list of characters to be removed (similar to String replace function). So StringUtils.strip(ipAddresses," ") should do the trick.

**Comment by danielmerino** [comment]
I can't do a rebase in this branch as it has been merged. Not sure what to do next.

**Comment by mpellicer** [comment]
If it doesn't work, please make a new PR using the same Jira fixing the problem, we can use a direct Java replace if you don't find other options. Thanks @danielmerino

**Comment by danielmerino** [comment]
@mpellicer I have done a new PR creating a branch with the same name.

https://github.com/sakaiproject/sakai/pull/6981

Can you merge that one?

**Comment by danielmerino** [comment]
@mpellicer this doesn't work neither, I have done another PR in https://github.com/sakaiproject/sakai/pull/6986

StringUtils.strip() only deletes characters in the beginning/end of the string, not in the middle.

I understand that StringUtils library has very useful methods, but IMHO is a really counter-intuitive library and is very frustrating using methods whose names don't reflect what they really do... I have used the old reliable replace() method of String class.

**Comment by danielmerino** [comment]
@mpellicer I have deleted the last PR and have done another without rebasing.
https://github.com/sakaiproject/sakai/pull/6992

**Pull request merged**
