### PR TITLE
KNL-1325 improvements around refreshAuthzGroup efficiency

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by ottenhoff** [comment]
This looks pretty promising... I'll defer to the S2U team for testing.

**Comment by juanjmerono** [comment]
It looks good to me, but I need to test it with real data next week.
I have one suggestion. You have refresh.interval and refresh.max.time, but max time is checking if one of the elements of the queue reach the limit, so if you have N elements and each one takes T seconds (less than max), your run method spends N*T seconds to end, that could be greater than max.time or even greater than interval, and that could cause get multiple runs at the same time (concurrent access to queue and some overload). In the other hand in a cluster environment you could be running a refresh at the same time over the same realm in multiple nodes and that could cause some overload, but trying to avoid it could be worst :smile:

**Comment by ern** [comment]
Yeah max.time is just how long an individual refresh can take before backing off. If you happen to be processing a bunch of refreshes lets say a 100 and they each take around 5 seconds then this would take approx. 500 seconds to finish which is fine. 

Interval is just how long to wait between each consecutive execution i.e. execution takes 120 seconds to finish it waits 60 seconds then runs the next one. It always waits 60 seconds before processing the next batch.

You need to  read this:
public static ScheduledExecutorService newSingleThreadScheduledExecutor()
Creates a single-threaded executor that can schedule commands to run after a given delay, or to execute periodically. Tasks are guaranteed to execute sequentially, and no more than one task will be active at any given time. 

Only one thread can be active at a time don't confuse this with a TimerTask.

**Comment by ern** [comment]
Also see the JIRA for some additional information.

**Comment by juanjmerono** [comment]
It's working as expected. I didn't test performance yet, but I've got another suggestion. It would be great to be able to enable/disable some specific log to get info of the work done by this background task. Something like: "RefreshAuthzGroup X realms processed in T milliseconds, max S ms in realm R."
With this additional info you will be able to adjust interval and maxtime properly. What do you think?

**Comment by juanjmerono** [comment]
No, debug is the right level for this log. I was thinking in some kind of summary, one line per execution with summary info instead of one line per refreshed realm, something that let you know how much work is being doing in background. If you need more details you could enable debug logging.

With the default interval you could see one line in log every minute (info level), with total number of realms and time to process. If you enable debug you also see one line for each realm with the specific info.

But this is only a suggestion to keep easy track of this background process, without being too verbose.

**Comment by ern** [comment]
Log messages will look like:
RefreshAuthzGroupTask.run() refreshed 6 realms in 0.041 seconds
RefreshAuthzGroupTask.run() refreshed 0 realms in 0.0 seconds

**Comment by ern** [comment]
Using Juanjo's input added a few more stats and some logging clean up. Sample info message looks like:

`INFO pool-1-thread-1 org.sakaiproject.authz.impl.DbAuthzGroupService - RefreshAuthzGroupTask.run() refreshed 2 realms in 0.024 seconds, longest realm was /site/SDOZ_141B_3474 at 0.018 seconds`

Also eliminated useless info messages when there are no realms to refresh.

**Comment by ottenhoff** [comment]
Looking good.  Can you squash this down to one commit and merge it?

**Comment by juanjmerono** [comment]
Amazing Earl !! That's what I'm looking for !! Thank you !!

**Pull request merged**
