### PR TITLE
SAK-32401 Added portal connection manager

### PR DESCRIPTION
**Pull request by adrianfish**
SAK-32401 Included existing connections in search results.

SAK-32401 Updated to return search hits on current connections
Fixed some layout issues and updated labels

SAK-32401 Added callback to i18n loader

SAK-32401 Fixed problem with accept from popup

Pending count wasn't being updated.

SAK-32401 Added clearsearch to dropdown search box.

CONNECTIONMANAGER ui changes

Fixed cross colour.
Fixed tab backgrounds and colours.
Fixed modal backdrop colour and opacity.

CONNECTIONMANAGER Enter key on search launches more results view.

CONNECTIONMANAGER Click outside search closes results

SAK-32401 Turned off pointer events for the active tab

### CODE REVIEW

**Comment by adrianfish** [comment]
screen shot 2017-06-26 at 14 08 29
screen shot 2017-06-26 at 14 08 41
screen shot 2017-06-26 at 14 08 58
screen shot 2017-06-26 at 14 10 02

**Comment by ern** [comment]
Very nice Adrian, looks pretty solid.

**Comment by adrianfish** [comment]
@ern Is that an LGTM, then? :)

**Comment by steveswinsburg** [comment]
Clearly it is only an LPS.

Nice one.

sent from my mobile

**Comment by adrianfish** [comment]
I've had a LPS (Looks Pretty Solid) from @ern and a NO (Nice One) from @steveswinsburg. I'm going to add those together to make a PR (Positive Review).

**Comment by steveswinsburg** [comment]
Very clever.

**Pull request merged**
