### PR TITLE
SAK-41111: Change startTime to not leave 12:00AM out of range

### PR DESCRIPTION
**Pull request by alejandromf**
Change startTime to not leave 12:00AM out of range

### CODE REVIEW

**Comment by alejandromf** [comment]
In other lines of CalendarAction.java "startTime" is already changed (892, 933, 964). It had also happened with "endTime" (SAK-17299) and it was corrected.
In the SAK-41111 I attached a video explaining the error and justifying the change.

**Comment by alejandromf** [comment]
The Jira SAK-33755 that was merged a few days ago, fix the daily and weekly views in a similar way.
The SAK-41111 would fix the monthly and annual views.

**Comment by jesusmmp** [comment]
I have just applied in my local SAK-33755 and this one SAK-41111. All views work fine. LGTM!

**Comment by mpellicer** [comment]
Duplicated of https://github.com/sakaiproject/sakai/pull/6465 ??

**Pull request closed without merging**
