### PR TITLE
SAK-32659 Moved commons tool to portal.i18n

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by ern** [comment]
Should this be using Sakai18n webservice?

A lot of this Javascript i18n doesn't get handled the way java properties do.

**Comment by adrianfish** [comment]
Going to get on it tonight - I've been a bit snowed under with Lancs stuff. Setting up JIRA Service Desk :)

**Comment by adrianfish** [comment]
Merge #4629 first. I'll refactor this after to use the new approach.

**Comment by adrianfish** [comment]
I've refactored this PR now, so commons uses SakaiI18n.

**Pull request merged**
