### PR TITLE
LSNBLDR-796 : Buttons overlap breadcrumb bar in mobile view.

### PR DESCRIPTION
**Pull request by frasese**

### CODE REVIEW

**Comment by ern** [comment]
JIRA indicates this issue may have been resolved.

**Comment by frasese** [comment]
Yes, Javier from JIRA is the owner of this patch.

**Comment by ern** [comment]
When submitting patches on behalf of others can you set to the author or have the author submit the patch?

**Comment by mpellicer** [comment]
@ern This PR is ready to be merged.

Miguel

**Pull request merged**
