### PR TITLE
LSNBLDR-542: New Lessons component: Add Resources Folder

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
This rebased Pr replaces this one: https://github.com/sakaiproject/sakai/pull/3622

**Comment by nicholaswilson100** [comment]
@adrianfish : Hi Adrian. I've rebased the previous PR into a new request here.  How does it look to you?

**Comment by buckett** [comment]
It still has the ckeditor files in the wrong place, /reference/library was moved to /library.

**Comment by adrianfish** [comment]
@nicholaswilson100 You need, as Matthew says, to move the stuff from reference/library up into library. You may then get conflicts with the latest tip and you'll need to resolve those. Maybe not, with luck. When you've sorted that I'll build it locally and have a test out with it. What I don't know, though, is whether we can merge this in for 12 now. It's a feature and we've passed the feature freeze. It could go into a point release.

**Comment by nicholaswilson100** [comment]
Thnaks @adrianfish , I've moved the files into the library module.

**Pull request merged**
