### PR TITLE
LSNBLDR-787 Moved itemSave save into an explicit transaction

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by adrianfish** [comment]
@ern I tried save and flush on the template and it still behaved the same. I also tried getSessionFactory().getCurrentSession().setFlushMode(AUTO), which also didn't work. So, I've gone for the last resort. I think we probably need an audit of how hibernate is being used across LessonBuilder, there is a mix and match of approaches and it should probably be standardised.

**Comment by adrianfish** [comment]
@ern Can I merge this in?

**Comment by ern** [comment]
The reason this probably didn't work is because this method was called outside the proxy where the method is not advised. It would be better to use springs transaction template for these cases, see http://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/transaction.html#transaction-programmatic

There is also an example in PrivacyManagerImpl.

**Comment by adrianfish** [comment]
I tried out TransactionTemplate using this code:

transactionTemplate.execute(new TransactionCallbackWithoutResult() {
                protected void doInTransactionWithoutResult(TransactionStatus transactionStatus) {
                    getHibernateTemplate().save(o);
                }
            });

Same result: when you pull the comment you sometimes get nulls as the comment hasn't been saved yet. Does findCommentById need to be wrapped in a transaction as well, like a mutex type thing?

**Comment by ottenhoff** [comment]
@ern questions for you here

**Comment by adrianfish** [comment]
@ern What do you reckon to this?

**Comment by ern** [comment]
Sorry for taking so long to comment on this,

See [TransactionTemplate](sakai/tree/master/common/privacy-comp-impl/src/java/org/sakaiproject/component/privacy/PrivacyManagerImpl.java#L452) example.

**Comment by ottenhoff** [comment]
@adrianfish you want to continue working on this one? Is this important?

**Comment by adrianfish** [comment]
@ottenhoff It is important as the bullhorn service can't get the link to the lesson comment if it hasn't been saved. You get an exception in the logs and a broken link in the bullhorn alert. Earle's given me the TransactionTemplate tutorial, so I'm all tooled up. I'll look at it this evening in fact.

**Comment by adrianfish** [comment]
@ern Done. In the end flushing etc just didn't work as I suspect the proxy wrapper means explicit flushing is ignored. So, I added a listener for the commit and I fire the events there. Simple :)

**Pull request merged**
