### PR TITLE
SAK-32235 Bullhorns trigger error on a fresh database

### PR DESCRIPTION
**Pull request by juanjmerono**
https://jira.sakaiproject.org/browse/SAK-32235?focusedCommentId=212540&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-212540

### CODE REVIEW

**Comment by juanjmerono** [comment]
Oracle nightly server is down due to this problem.

**Comment by steveswinsburg** [comment]
This SQL should not be part of portal, it should be in the proper conversion scripts.

**Comment by adrianfish** [comment]
@steveswinsburg Why do you reckon that? Hibernate tools generate and emit db commands and we have to sync up the conversions scripts. It's the same, isn't it?

**Comment by adrianfish** [comment]
@steveswinsburg Something should go in the conversion scripts as well, I'll JIRA that.

**Comment by steveswinsburg** [comment]
The pattern is that all DDL goes in the conversion scripts. Hibernate tools can generate DDL (often poorly, mind you) but that then goes in the conversion also. Hibernate doesn't create tables itself. If DDL is spread all over the place it makes it a nightmare to figure out what is creating what.

**Comment by adrianfish** [comment]
What happens when people are just developing on master and don't run the conversion scripts? I never have - only when upgrading a production database. I thought you just left auto ddl on and let the tools create their tables? I know hibernate used to at least add columns to tables that existed already.

**Comment by buckett** [comment]
I agree that it would be good support developers being able to upgrade as they go, but at the moment we don't support this and doing different things all over the codebase makes it harder to maintain in the long run.

Using something like: https://flywaydb.org/ to manage our database migrations would be one way to solve this but I think we should have a joined up approach.

**Comment by adrianfish** [comment]
At the moment, if you want build a fresh master on a fresh database do you need to run a script to create the database? I think I'm missing something. I thought the conversion scripts were used to upgrade Sakai versions, not do an initial creation of the tables. I thought each service was responsible for creating its data structures, not some centralised ddl file. Hence the auto ddl flag.

**Comment by steveswinsburg** [comment]
We might have our wires crossed. The conversion scripts are for updating, not for creating. If using Hibernate, you can turn on auto.ddl and let Sakai build the tables for you, assuming they don't already exist and some other condition doesn't prevent them from being created. But yeah if you are on master you might need to run SQL to bring your schema up to date. In this case it isn't using Hibernate so the initial creation is ok (not great though). But yes this has to go in the conversion script.

**Comment by jonespm** [comment]
Yeah sounds like a few separate discussions here. For doing development on master you frequently get into situations where you just have to drop and re-create your database. Tools that use hibernate typically take care of this better (which is why we recommend hibernate) since we don't have something like flyway like @buckett mentioned. 

I think the ideal is that flyway would be doing everything, that on some future release we'd get a schema dump for MySQL and Oracle, and that would be flyway version 1. And then just continue to add upgrade scripts from there. Then the local ddls would never run anymore and we wouldn't have to run conversions.

But yeah this entire script for version the initial creation needs to be in the 12 conversion script for now. Though when we do the database diff we'd have noticed it was missing.

**Comment by adrianfish** [comment]
Jira'd at:
https://jira.sakaiproject.org/browse/SAK-32266

**Pull request merged**
