### PR TITLE
SAK-40253: Samigo > Improve the warning message for deleting a Question Pool

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-40253

Change the wording of the warning message that you get when you delete a Question Pool to warn the user that this erases the pool(s) across their whole account. Also change the styling of the message from blue (information message) to yellow (warning message).

screenshot_20180629_105730
screenshot_20180629_110657

### CODE REVIEW

**Comment by ottenhoff** [comment]
My first read: the new warning somehow implies that your pools are _replicated_ across worksites as opposed to central ownership.

**Comment by ottenhoff** [comment]
removing their availability from all your sites?

**Comment by bjones86** [comment]
Sounds good, I'll make the amendment. Thanks.

**Comment by fostersdesign** [comment]
Do either of you know: when a question pool is removed, do existing quizzes using a deleted question pool remain unchanged because the quiz uses a copy of question pool's questions in both cases (copy from question pool and random draw)?

**Comment by bjones86** [comment]
I _think_ it's a copy in both situations, but I'm not certain about that.

**Comment by Rainribbon** [comment]
The best way to understand random draw is to think of it as a "snapshot" of the question pool taken at the time of publication.  When you publish a quiz with a random draw part, all the questions from the pool are copied into the new quiz in the published copies tab, then the questions are randomly distributed to students taking the quiz.

If you delete a question pool, it will not impact any quizzes to which you copied questions individually or any existing **published** random draw quizzes that use those questions (because these quizzes already had the questions copied to them).  However, working copies of quizzes that drew from the pool will no longer have access to it.  I'm not sure if an error is generated on attempting to edit one of these working copies, or if the part will simply warn the user that the affected question pool no longer exists and you need to select a new pool to draw from.

Regarding the warning message, I'm not sure it is helpful to mention sites at all, since question pools do not have any relationship to sites.  However, it might be good to indicate that neither you nor anyone with whom the pool is shared will have access to it anymore, and that you will not be able to use the questions in future assessments, e.g.:

> This will remove the selected question pools and their questions from your account, removing their availability from you and any other users with whom they have been shared.  You will not be able to copy or randomly draw questions from deleted pools in new assessments.

**Comment by fostersdesign** [comment]
Thank you for the explanation, @Rainribbon. 

You made a good addition by mentioning the shared people. 

The reason we had mentioned sites in the message was to make it obvious that this action has implications outside of the current site, which was an issue that we addressed for our instructors when we made this change locally.

**Pull request merged**
