### PR TITLE
SAK-49462 T&Q Ability to set the rounding decimals when grading

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by ottenhoff** [comment]
I'm not a big fan of this change .... what about precision in the gradebook and all of the exports? it just seems like a crazy dive into lots and lots of places

**Comment by mpellicer** [comment]
> I'm not a big fan of this change .... what about precision in the gradebook and all of the exports? it just seems like a crazy dive into lots and lots of places

Me neither to be honest, I invited UPV to the Jira to provide more information about what problems they found, what they fixed and why they are using 4 decimals.

**Comment by ottenhoff** [comment]
ok, cool, i will subscribe to the JIRA

**Comment by mpellicer** [comment]
> ok, cool, i will subscribe to the JIRA

I'm in a process of contributing custom patches from UPV [here](https://sakaiproject.atlassian.net/browse/SAK-49458), they are working in production for 15 years or more, but of course we accept that some of them are not going to be accepted. 

And I cleaned up the list a lot, contributing the ones that have possibilities.

**Pull request closed without merging**
