### PR TITLE
Upgrade Apache Commons Collections to v3.2.2

### PR DESCRIPTION
**Pull request by jart**
Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!

https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

### CODE REVIEW

**Comment by ern** [comment]
Probably the more appropriate fix would be to remove the version from those maven dependencies so that they inherit the version from master/pom.xml which is already version 3.2.2.

**Comment by jart** [comment]
I'm in the process of updating dozens of other projects. Perhaps you could merge and then perform that refactoring?

**Comment by ottenhoff** [comment]
Thank you very much for the PR and explanation!

@jart do you want credit on the git commit here? If not, we'll go ahead and close this PR and update directly. If you want credit on the git commit, I believe we'll need a signed CLA.

**Comment by ern** [comment]
Also here is a related JIRA https://jira.sakaiproject.org/browse/SAK-30091 which addresses this issue. Looks like that change didn't get them all and all the more reason use inheritance!

**Comment by jart** [comment]
Closing this ticket due to CLA requirement. I still strongly recommend you guys upgrade your collections dependency.

**Pull request closed without merging**
