### PR TITLE
SAK-49445 Grader & Document Viewer: Upgrade pdf.js to use the latest …

### PR DESCRIPTION
**Pull request by mpellicer**
…features (4.0.189)

### CODE REVIEW

**Review by adrianfish — APPROVED** [review]
Nice, thanks Miguel.

**Comment by mpellicer** [comment]
> Nice, thanks Miguel.

It doesn't work yet, we should wait for the library to be released in webjars and there's some errors related to the mimetype serving '.mjs' files, I'll keep you posted.

**Comment by mpellicer** [comment]
> Nice, thanks Miguel.

You might want to revisit this PR because I needed a change in the library's web.xml, the MJS extension needs mapping or it fails loading the modules.

**Review by adrianfish — APPROVED** [review]
That mjs thing is weird, isn't it? I wonder why pdf-js is using Node's file extension for ES6 modules. Anyway, it's good to map it. Cheers.

**Comment by mpellicer** [comment]
> That mjs thing is weird, isn't it? I wonder why pdf-js is using Node's file extension for ES6 modules. Anyway, it's good to map it. Cheers.

Yeah, it fails loading the modules because needs the content-type in the response :( I feel we will have similar issues like this in other webjars when they transition from .js to .mjs

**Comment by mpellicer** [comment]
Thanks for the review @adrianfish

**Pull request merged**
