### PR TITLE
SAK-32227 Hibernate 4 remove remaining getHibernateTemplate().find()

### PR DESCRIPTION
**Pull request by ern**
when using positional params

### CODE REVIEW

**Comment by ottenhoff** [comment]
Are these uses okay

`
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
617:		List<AssessmentData> list = (List<AssessmentData>) getHibernateTemplate().find("from AssessmentData a order by a." + orderBy);
1028:		return getHibernateTemplate().find(

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/authz/integrated/AuthzQueriesFacade.java
229:    List l = getHibernateTemplate().find(query+clause);

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java
116:    return getHibernateTemplate().find("from ItemData");

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
964:		List<PublishedAssessmentData> list = (List<PublishedAssessmentData>) getHibernateTemplate().find("from PublishedAssessmentData p order by p." + orderBy);
1203:		// List list = getHibernateTemplate().find(query,
1603:		List<PublishedAssessmentData> l = (List<PublishedAssessmentData>) getHibernateTemplate().find(query);

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
92:    return getHibernateTemplate().find("from QuestionPoolData");
131:    List questionPoolAccessList = getHibernateTemplate().find(
1122:    List l = getHibernateTemplate().find(query);

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/TypeFacadeQueries.java
132:    	return (List<TypeD>) getHibernateTemplate().find("from TypeD");
`

**Comment by ern** [comment]
Yeah those uses don't have any parameters, I made a reference to them on the JIRA.

**Comment by jonespm** [comment]
Yeah using ordinal parameters in find() seem like they work but put up a warning now. Using it with out any parameters looks fine. Using named parameters on .find() doesn't work based on the docs.

It seems kind of confusing since the entire API is deprecated, but still looks like they're carrying support for it through to hibernate5.

**Comment by ern** [comment]
Yeah Hibernate officially deprecated support for ordinal parameters the only ones I think that are allowed are those when using JPQL, probably since that is part of the JPA spec. So the strategy I used was to move completely away from using ordinal parameters. These were just a few that I had already changed from using ordinal to named parameters but forgot to change the method from find() to findByNamedParam()... I double checked and with code of that of 11.x and there were 117 total uses of using find() which I converted 100 of using this strategy, 11 don't use params and are the ones Sam listed above and the remaining 6 will be fixed by this PR.

**Pull request merged**
