### PR TITLE
SAK-30095 Course Offering provider doesn't work properly

### PR DESCRIPTION
**Pull request by annuelo**

### CODE REVIEW

**Comment by juanjmerono** [comment]
I think this is wrong. What you exposed in the jira is the right behaviour of Course Offering. If you have one role at Course Offering level you have it for all the sections below the Course Offering, no matter if you are member or not. If the role has only sense in a Section you must grant the role in the Section not in the Course Offering. I have a diagram with the relation between Section, Course Offering, Canonical Courses and Course Set.
cm sakai integration

**Comment by sinmsinm** [comment]
I think Juanjo is right. The desired behavior is provide that role to all the sections below.

**Comment by annuelo** [comment]
Ok, thank you both. It's a pity because that scheme was very suited to our needs.

**Comment by juanjmerono** [comment]
You are able to do the same granting this role at section level (only in the section that the instructor is member). Granting roles at CO level lets you create supervisor roles, for example one person acting as  coordinator in all sections without being member of them. We would like to know your usecase to see if we can help to find a different solution. Please, join the next S2U Open Call on wednesday (in spanish), we will send the connection details to the sakai-spanish@apereo.org mailing list, see you there, Thanks!!

**Pull request closed without merging**
