### PR TITLE
SAK-31986  - Fix references to turnitin in content review for French locale

### PR DESCRIPTION
**Pull request by mpellicer**
Fix references to turnitin in content review for French locale

### CODE REVIEW

**Comment by ottenhoff** [comment]
Are you sure this is a correct change? 

There are now 3 different content-review providers in master. Why is one service being hard-coded?

**Comment by mpellicer** [comment]
@ottenhoff Precisely is what it does, change the hardcoded Turnitin reference to something more generic.

This only affects the fr_FR translation, English is fine

**Comment by ottenhoff** [comment]
Thanks! I read the diff in reverse!

**Comment by mpellicer** [comment]
@ottenhoff Thanks to you!

**Pull request merged**
