### PR TITLE
SAK-45824 CKEditor Autosave content comparison omissions when embed…

### PR DESCRIPTION
**Pull request by hornersa**
…ded in Sakai

### CODE REVIEW

**Comment by hornersa** [comment]
The coding standards cited in the Codacy report, if enforced, would contradict a core intent with the proposed code which is to copy the autosave plugin code (in this case version 0.18.6) and to apply only the changes necessary which resolve the issue described in the bug that emerges when the CKEditor is embedded in Sakai (but not on a standard webpage). 

The nature of the change I am making to the autossave plugin to fix this bug is described in a comment in https://jira.sakaiproject.org/browse/SAK-45824.

**Review by ern — CHANGES_REQUESTED** [review]
We should try and get the fix in the upstream project not move the source into Sakai.

**Comment by adrianfish** [comment]
I'd work off the code from their git repo, not a deminified file. That'll make it a little easier to read. Only a little though, I've checked :)

Have you thought about replacing the function RenderDiff (from plugin.js) and then replacing sm.find_longest_match in that? Minimising it a bit? You could create a script that ran later which just made those more fine grained alterations. Or, if you think your code is actually good for the upstream project, just put in a PR and see what happens.

The project https://github.com/w8tcha/CKEditor-AutoSave-Plugin has only had 2 commits in the last 12 months, and only has two contributors, which is a bit of a worry :)

@profmikegreene What do you think about this? I know you've been deep in the ckeditor code recently.

**Comment by profmikegreene** [comment]
With ckeditor 4 due for end of life in 2023, I wouldn't be surprised if the autosave plugin's efforts had been completely dedicated to the v5 plugin. I agree that the preferred paths forward are
1. have your fix merged in the plugin repo upstream
2. or, create a custom plugin that only overrides what's necessary, inheriting most functions from the upstream plugin
3. or, fork the plugin in our repo as this PR has done.

I think the 3rd is still a valid option if the upstream cke folks have no plans to fix this and Sakai has no plans to move to ckeditor 5. My js foo isn't strong enough to know if option 2 is achievable.

**Comment by hornersa** [comment]
Thank you all for your feedback on this. Later this week I hope to elaborate on some of the points raised here and share other aspects of the autosave plugin code (0.18.6) where I decided to essentially fork that code  to make other local fixes (for our institution's instance of Sakai)-- mostly as ways to address problems described in:

SAK-45798 - CKEditor: Autosaved content exposed to different users on shared devices
SAK-45845 - UX problems with Lessons comments tool & CKEditor autosave

A move to ckeditor 5 might obviate a number of these concerns, though I'm not at all familiar with how that code behaves except that [autosaves are supposed to be sent to the serve](https://ckeditor.com/docs/ckeditor5/latest/api/module_autosave_autosave-Autosave.html)r (instead of the browser which theoretically renders SAK-45798 moot).

**Comment by ern** [comment]
@hornersa feel free to reopen when your time allows

**Comment by hornersa** [comment]
@ern, will do. Thanks.

**Pull request closed without merging**
