### PR TITLE
SAK-29226 - Intermittent test failures in sitestats

### PR DESCRIPTION
**Pull request by jonespm**
Just added predictable order, cannot reproduce failure over 150 tests run

### CODE REVIEW

**Comment by buckett** [comment]
I tried this and I think I still got errors, but I think it's worth a punt as these are a real pain.

**Comment by jonespm** [comment]
Yeah, well I can iterate the test some more, but I'm not getting errors in this test. Maybe StatsManagerTest, ReportMangerTest, and EventAggregatorTestPref need fixes too. Do you know if your error was in one of those or in this? This ticket was about StatsUpdateManagerTest. I just committed since it was super low risk and forced predictability is better than none.

**Comment by buckett** [comment]
I think just merge.

**Comment by jonespm** [comment]
I think you're right here though @buckett, it fixed one random error but still one comes up, I'm adding more logging to try to track down the other one.

**Pull request merged**
