### PR TITLE
SAK-32664 Alter default site title for synoptic tools.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**
Pre-change:
prefixmercurysite

Post-change:
postfixmercurysite

### CODE REVIEW

**Comment by ottenhoff** [comment]
Anyone have thoughts here?

**Comment by lardo-de-arnaud** [comment]
let me ping the user and UX groups. This has been moaned about on those lists, hence our work in this area

**Comment by RebeccaOxfordUni** [comment]
I have changed the message to 'Welcome'
postfixwelcome

**Comment by lardo-de-arnaud** [comment]
can this be reviewed. Everybody agreed that "Welcome" was the way forward.

**Comment by jonespm** [comment]
There are other places in the code this needs to be updated

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
web/web-portlet/src/webapp/WEB-INF/sakai/PortletIFrame.xml
webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java

Also the help documents need to be updated on screensteps for 
How-do-I-add-a-site-using-the-Sites-tool-.html
How-do-I-edit-a-site-using-the-Sites-tool-.html

**Comment by RebeccaOxfordUni** [comment]
Changes made, new Jira created (SAK-33320) so that the help files are updated.

**Comment by RebeccaOxfordUni** [comment]
Are you able to merge this now Matthew @jonespm ?  It is a simple change.

Thanks.

**Pull request merged**
