### PR TITLE
SAK-40892: Nested SqlService calls can lead to pool connection deadlock under certain conditions

### PR DESCRIPTION
**Pull request by jesusmmp**
https://jira.sakaiproject.org/browse/SAK-40892

Please, we need some opinions. Thanks!

### CODE REVIEW

**Comment by SedueRey** [comment]
This is a WIP PR. Can anybody put the tag on it? Thanks.

**Comment by juanjmerono** [comment]
We are using this patch on production since last week without issues. We will keep this patch activated until we face enough load to compare its behaviour.

**Comment by mpellicer** [comment]
@ottenhoff what do you think about this patch? Looks like Murcia tested it for more than one month and the results look good. Any other thoughts @juanjmerono?

This is a critical issue for Sakai 20.x

**Comment by ottenhoff** [comment]
So this has been tested under heavy load? At an institution with more than 10k users?

**Comment by mpellicer** [comment]
> So this has been tested under heavy load? At an institution with more than 10k users?

@juanjmerono may provide more details, I'm sure they are under heavy load these days....

**Comment by ottenhoff** [comment]
Okay I'm okay with it if confirmed working in heavy production

**Comment by juanjmerono** [comment]
Yes this fix is in production with really high traffic now believe me.

**Pull request merged**
