### PR TITLE
SAK-29143 - Signup smtpFrom property

### PR DESCRIPTION
**Pull request by mcarropellicer**
SAK-29143 - Signup smtpFrom property

### CODE REVIEW

**Comment by buckett** [comment]
Is there a reason for dropping the nice display name from the email address?

**Comment by mcarropellicer** [comment]
Nope, added the service name.

**Comment by buckett** [comment]
Ok, so it's ideal if you squash all the commit down into one when fixing issue, this isn't simple but you for this pull request can be done with.
```
git checkout master # This checks out the branch from which this pull request is created
git reset --hard HEAD^ # Drop the merge commit as it's not needed.
git reset --soft HEAD^^ # Reset the index back 2 commits.
git commit -C HEAD@{1} # Re-use the commit from original pull request
git push -f origin master # Push you're updated branch back to the pull request.
```
I'm happy to push you're commit (keeping you as the author), or if you want to you can try and update your pull request.

**Comment by mcarropellicer** [comment]
Go on, no problem Matthew, thank you so much

**Comment by buckett** [comment]
Merged in a9d1cba0a

**Pull request closed without merging**
