### PR TITLE
SAK-45110 Library CSS Performance tuning

### PR DESCRIPTION
**Pull request by profmikegreene**
https://jira.sakaiproject.org/browse/SAK-45110

1. Add node/npm to library project in order to ...
2. Upgrade from libsass to dartsass
3. ~~Add eslint to library project~~
4. Refactor color palette generation to use HEX instead of HSL colors, also use less characters in each color name
5. Replace color classes with `@include sakai-colorize(sakai-red-60, sakai-red-10)` works with one or two arguments
5. Add watch-sass profile to speed up CSS development. The watch-sass profile does not currently work with -Dcustomization.file and only SCSS changes from files included in tool.scss or properties.scss will be reflected
6. ~~Add an eslint profile to aide JS development~~
7. Add custom js lib and main files to aide those managing multiple skins
8. Add stylelint to help prevent codacy errors in library PRs

This is  big PR but the vast majority of the changes are just adding the package-lock.json so don't be too daunted :)

### CODE REVIEW

**Comment by profmikegreene** [comment]
Is there a way to have codacy use the configs we have in the codebase? I've added a `.stylelintrc.json` which is the config file for stylelint, the linter codacy uses for SCSS but it didn't pick up that configuration in it's check.

**Comment by ottenhoff** [comment]
Docs say that Codacy will look for it once it's committed: https://docs.codacy.com/repositories-configure/configuring-code-patterns/

We can also add a linter to the Github Actions build steps which would prevent any non-confirming new code to be rejected

**Comment by profmikegreene** [comment]
I don't know how many languages that would work for, but I'd be happy to work on moving SCSS, CSS, and JS from Codacy to github actions with stylint and eslint if others like the idea. I did some work on Cypress for Conversations testing earlier this month, would be open to exploring that with Github Actions as well.

**Comment by ottenhoff** [comment]
@profmikegreene what's the fundamental reason for leaving libsaas behind? Is it just not maintained well?

**Comment by profmikegreene** [comment]
Yea, libsass is depreciated and not getting new features. It hasn't caused us much issues yet but I think it'll only get harder as time goes on. Any new/upgraded ui libraries that need to be built with SCSS will most likely require dartsass moving forward, bootstrap 5 has already done that.

It may be that a maven package will be created for dartsass directly, i didn't see one a few months ago when I began down this path. Since so much frontend workflows are built around node and we already had node in /webcomponents, this approach seemed viable but it is definitely a large change worth pausing on.

I also use a containerized dev environment that was running into permission issues at the start because maven was building as root, definitely want others to verify this builds with their config.

**Comment by profmikegreene** [comment]
for reference
https://sass-lang.com/libsass
https://getbootstrap.com/docs/5.1/getting-started/contribute/#sass

**Comment by ottenhoff** [comment]
Thanks for the links. I agree this is the best path.

**Comment by profmikegreene** [comment]
Upgrading to npm 7 to match what was recently put in the components project has broken something. converting to draft to explore options.

**Comment by profmikegreene** [comment]
I bumped the npm version back down to 6 to resolve the build issues. Also added some more documentation and some sample mvn builds in the compile-skin.md

**Comment by profmikegreene** [comment]
I don't know if I'll have time to split this apart before the branch is cut. I agree there's multiple things accomplished in this PR that should be split if given time.

My rationale for pushing it through for 22 was out of concern for back merging stuff from 23 knowing that Bootstrap 5 requires dartsass to compile. Undoubtedly, library will change completely between 22 and 23 as a result of the trinity work, so that rationale may be moot anyway.

Assuming we move forward with the strategy of creating a trinity branch for that work in the next couple weeks, would you prefer to hold this change until then and put this work there?

**Comment by ern** [comment]
Agreed if this is trinity work we need NOT to merge this at this time. For others looking at this Trinity is a project for a 23 release. Lets keep this as a Draft.

**Pull request closed without merging**
