### PR TITLE
Revert SAK-41821 assignment submission status confirmation 

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by adrianfish** [comment]
They just talked about this on the UX call and decided to leave it in place and just fix the bugs. Unless I'm on the wrong track.

**Comment by ottenhoff** [comment]
Who has volunteered to address all of the issues before Sakai 20.0 release?

**Comment by adrianfish** [comment]
Good question - I don't know the answer to that. It was T&L actually.

**Comment by adrianfish** [comment]
It was recorded.

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5124964&bid=16846228)

**Comment by bgarciaentornos** [comment]
EDF will work on the fixes described in the jira

**Pull request closed without merging**
