### PR TITLE
SAK-29459 Responsive view in roster

### PR DESCRIPTION
**Pull request by juanjmerono**
image
image

### CODE REVIEW

**Comment by adrianfish** [comment]
Have you tested the infinite scroll in the wide view?

**Comment by juanjmerono** [comment]
Yes !! Do you remember these jiras https://jira.sakaiproject.org/browse/SAK-29208 and https://jira.sakaiproject.org/browse/SAK-29308?
They fix some infinite scroll issues that I detected and tested with this compact view :)

**Comment by adrianfish** [comment]
Merged. Nice one :)

**Comment by adrianfish** [comment]
Sorry, I should have let you do that so you could delete your branch automatically. It just seems good when somebody else has a look and does the merge.

**Pull request merged**
