### PR TITLE
SAK-31210 Refactored GradesEntityProvider for testability and added tests

### PR DESCRIPTION
**Pull request by cannonpalms**

### CODE REVIEW

**Comment by cannonpalms** [comment]
The build is failing because of some magic with dependency ordering. I'd appreciate some help; I'm not very familiar with the way sakai manages its dependencies. Should mockito be moved from where I put it in pom.xml?

**Comment by steveswinsburg** [comment]
If you are refactoring this, it would be excellent if you could merge it
with the existing gradebook entity provider.
grades-rest was added after the original was added and duplicates some of
the functionality, while providing additional functionality as well.
https://jira.sakaiproject.org/browse/SAK-28175

**Comment by cannonpalms** [comment]
I'll take a look at the merge this morning.

**Comment by cannonpalms** [comment]
@steveswinsburg Is the goal to merge what exists in grades-rest over to to the gradebook entity in edu-services?

**Comment by cannonpalms** [comment]
Laughing. Scratch all the above. I'm going to work up a skeleton and send it your way for approval before I implement.

**Comment by cannonpalms** [comment]
@steveswinsburg I've looked through what is in the existing gradebook entity provider. I think this merge would be better suited for someone with more knowledge on what the requirements are. grades-rest exposes extra data and functionality that I don't feel comfortable trying to implement while maintaining backwards compatibility (I'm not 100% on gradebook's definition of breaking vs. non-breaking change).

**Comment by jonespm** [comment]
While I think we'd like these tests, gradebook it's got a few problems. Currently these tests are failing with
```
Tests run: 16, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.368 sec <<< FAILURE! - in org.sakaiproject.gradebook.entity.GradesEntityProviderTest
ensureEntityViewPathSegmentThrowsIllegalArgumentException(org.sakaiproject.gradebook.entity.GradesEntityProviderTest)  Time elapsed: 0.223 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
```

Also I believe as Steve said, GradesEntityProvider.java should be deprecated and just be rolled into app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradebookEntityProvider.java there's also the GradebookNgEntityProvider.java that I guess has different functionality.

I guess we could take this if it worked but it might just end up being removed if this cleanup was ever done.

**Comment by ncaidin** [comment]
Sakai core team - closing due to lack of activity .

**Pull request closed without merging**
