### PR TITLE
SAK-48335 Basiclti: Rename DataPrivacyLaunchRequest to be LtiDataPrivacyLaunchRequest

### PR DESCRIPTION
**Pull request by zhuoY121**

### CODE REVIEW

**Comment by kunaljaykam** [comment]
I think, There are more files @ zhuoY121 that will need to be renamed. Try `lti_tool_insert.vm`.

**Review by kunaljaykam — CHANGES_REQUESTED** [review]
I think, There are more files @zhuoY121 that will need to be renamed. Try `lti_tool_insert.vm`.

**Comment by mpellicer** [comment]
CLA is completed for @zhuoY121 

image

**Comment by zhuoY121** [comment]
Renamed variables in lti_tool_insert.vm, thank you for the suggestion!

**Review by kunaljaykam — APPROVED** [review]
LGTM! Good job @zhuoY121 :+1: (BasicLTI is Dr. Chuck's tool, therefore I will ask him to take a look at this PR one time.)

**Review by csev — APPROVED** [review]

**Pull request merged**
