### PR TITLE
SAK-49854 Plus: reduce column lengths to reduce composite key length

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by jonespm** [comment]
@csev Looks like if you drop `EMAIL` from the index it would also work without any changes as that's 500 characters. I'm not sure what this is used for any why `SAKAI_USER_ID `and `EMAIL `are both needed and would be different. 

As now it's
`SUBJECT`=500
`TENANT_GUID`=36
`SAKAI_USER_ID`=99
`EMAIL`=500
(500+36+9+500)*4 = 4180, slightly over with 3 bytes and quite over with 4. 

SAKAI_USER has email at 255 which is a good change but does it even need to be here?

**Comment by ottenhoff** [comment]
Here is one composite key you need:
```
 51     Predicate cond = cb.and(
 52         cb.equal(root.get("subject"), subject),
 53         cb.equal(root.get("tenant"), tenant)
 54     );
```

Here is a different composite key you need:

```
 71     Predicate cond = cb.and(
 72         cb.equal(root.get("email"), email),
 73         cb.equal(root.get("tenant"), tenant)
 74     );
 75
```

Here is another composite key you need:

```
 98     Predicate cond = cb.and(
 99         cb.equal(root.get("sakaiUserId"), sakaiUserId),
100         cb.equal(root.get("tenant"), tenant)
101     );
```

Maybe also add `modifiedAt` to this one because you order by it

**Comment by jonespm** [comment]
So by changing these indexes, the change to the size of `SUBJECT` isn't _necessarily_ needed anymore. I think that was the only question that @csev had on the call. 

(Old) SUBJECT + TENANT = 500+36= 536
EMAIL + TENANT = 255+36= 291
USERID + TENANT = 99+36=135

Those are all well within the limits.

**Comment by ottenhoff** [comment]
Yes, but the new sizes are more accurate. No need for 500 chars here

**Review by ern — APPROVED** [review]
The new composite indexes all fit below the limits

**Pull request merged**
