### PR TITLE
LSNBLDR-746: Subpage color in breadcrumb can be hard to read

### PR DESCRIPTION
**Pull request by nicholaswilson100**
on some backgroudns

### CODE REVIEW

**Comment by ern** [comment]
Quick question is this only hard to read because of a color that was chosen for some other aspect of the skin.

Meaning if I were to set the skin to a light color would I not have the same issue? if so then doesn't it make sense that this be configured according the colors chosen in the skin? (If a user choses a poor color combination then thats on them)

**Comment by lardo-de-arnaud** [comment]
I dont think so, for some reason the text is a different colour to every other bit of text that appears in the same navigation bar. There cannot be a good reason for this (can there?)

**Comment by clhedrick** [comment]
It's a different color because the other items are links and the current page title isn't.

Let's look at the colors of the items in the breadcrumbs, left to right:

The site title comes from .Mrphs-siteHierarchy a
The main tool name comes from .Mrphs-hierarchy--toolName
Intermediate subpages if any come from .Mrphs-siteHierarchy a
The current subpage comes from .Mrphs-portalWrapper. 

The current subpage is the same color used by the > separators, which are the only other non-link text in the breadcrumbs. Presumably your skin should choose that color so the separators are visible.

So I think the current color choice is appropriate. I don't recommend using this patch.

**Comment by lardo-de-arnaud** [comment]
it sounds like charles is saying that we are hard coding the colour instead of inheriting.

**Comment by jonespm** [comment]
I agree, I feel like this should be closed as it will cause a problem for white backgrounds or default. I think this color should be coming from the SCSS files that are defined in a skin rather than defined here.

**Comment by fostersdesign** [comment]
The text colour should probably be set on the siteHierarchy element itself at the portal level via Reference.

**Pull request closed without merging**
