### PR TITLE
S2U-21 SAK-49646 T&Q: Fix early timer start with SEB - MASTER

### PR DESCRIPTION
**Pull request by stetsche**
https://sakaiproject.atlassian.net/browse/S2U-21
https://sakaiproject.atlassian.net/browse/SAK-49646

### CODE REVIEW

**Comment by mpellicer** [comment]
Did you test this with and without enabling SEB?

**Comment by jesusmmp** [comment]
I'm going to test this patch! Thanks @stetsche!! :)

**Comment by stetsche** [comment]
@mpellicer I didn't test it without SEB, as I am only touching SEB specific areas of the code, but I will do a quick test.

**Comment by stetsche** [comment]
Just tested using linear and flexible assessments without SEB configured and it seems to work just fine as before.

**Comment by jesusmmp** [comment]
Just tested on our test environment. This works fine and can be merged!
Great job @stetsche!

**Review by jesusmmp — APPROVED** [review]

**Comment by stetsche** [comment]
Awesome, thanks @jesusmmp!

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Thanks for the review and the implementation guys @stetsche @jesusmmp

**Pull request merged**
