### PR TITLE
LSNBLDR-544; temporary fix for RSF-19, new version of xpp3

### PR DESCRIPTION
**Pull request by clhedrick**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Duplicating RSF classes in sakai master just seems like such a bad idea...........

**Comment by clhedrick** [comment]
huh? I'm not sure what the reference to sakai master is. If you mean adding xpp3 to all RSF tools individually, yes, this is a mistake. I wasn't clear it was all tools, but it is. I've just moved it to sakai rsf core. This should cause all RSF tools to inherit it. But I haven't touched master in any of this.

**Comment by clhedrick** [comment]
At this point all the RSF tools should work again. But until RSF-19 is accepted, there are going to be large numbers of errors in the logs. I've done this local fix to mail sender and lessons, but I don't intend to do any more unless it become clear that RSF-19 isn't going to be accepted. In that case I'll have to install the workaround in all the RSF tools individually.

**Comment by ottenhoff** [comment]
> But I haven't touched master in any of this.

I was referencing "master" as the name of our primary git branch.

The duplication of BasicTemplateResolver.java out of the RSF project into lessonbuilder seems like a bad idea. Let's just fix it in the rsf/rsf project.

**Comment by clhedrick** [comment]
Absolutely. Someone with the necessary privs needs to accept RSF-19. I did it locally for lessons and mailsender because without it debugging those tools is nearly impossible. The moment RSF-19 is integrated I'll back out those two hacks.

**Comment by ern** [comment]
This only addresses log messages and not the root cause. I have spoken with Antranig on this and said he would take a look. I posted to the dev list when I did the spring upgrade that people would see these messages.

I wouldn't merge RSF-19 until Antranig has looked at it.

**Comment by ern** [comment]
So Antranig has fixed root issue with this and this PR should probably be reverted.

**Comment by clhedrick** [comment]
I just checked, and both lessons and mail sender are OK with this fix. I'll back out my temporary ones later today.

**Comment by clhedrick** [comment]
No, don't revert this PR or you will break mail sender. I've already said that later today when I'm out of meetings, I'll remove the workarounds from both mail sender and Lessons.

**Pull request merged**
