### PR TITLE
SAK-29731 - StringIndexOutOfBounds when grading submission with a low value (0.01 - 0.09) using two decimals

### PR DESCRIPTION
**Pull request by mcarropellicer**
StringIndexOutOfBounds when grading submission with a low value (0.01 -
0.09) using two decimals

### CODE REVIEW

**Comment by annuelo** [comment]
Hi Miguel,

I've solved this jira too. It works with any number of decimal places.
Here is the code:

int lenght = grade.length();
if (lenght > dec) {
	grade = grade.substring(0, grade.length() - dec) + decSeparator + grade.substring(grade.length() - dec);
}
else {
	String newGrade = "0" + decSeparator;
	for (int i=lenght; i<dec; i++) {
		newGrade = newGrade + "0";
	}
	grade = newGrade + grade;
}

**Comment by mcarropellicer** [comment]
I'm still working on it because i found another problem, thanks @annuelo

**Comment by mcarropellicer** [comment]
The patch works fine but there is still a problem displaying values with comma (Ya sabes, nuestro separador :D).

Displaying dot as separator:
image

Displaying comma as separator:
image

**Comment by mcarropellicer** [comment]
Now seems pretty fine, works for every case. Thanks @annuelo

**Comment by annuelo** [comment]
You're welcome @mcarropellicer :)
I've tested the code in our local instance and it seems fine.

About your last code, only I think this line is necessary:

Integer.parseInt(grade);

It is used to checked the grade value is an integer. If is not then an exception is thrown and and message error is shown.

**Comment by mcarropellicer** [comment]
Thanks @annuelo, true thing, also corrected a typo of your patch (lenght -> length).

**Comment by annuelo** [comment]
Perfect @mcarropellicer ! 
I think it is ready for making the commit.

**Comment by steveswinsburg** [comment]
Can't you just do this with a bigdecimal and decimalformat? Also, please no underscores in variables.

**Comment by mcarropellicer** [comment]
@steveswinsburg decimal_gradePoint was an existing variable.

Also the current logic is written in that way, is not something it ocurred to me

**Comment by steveswinsburg** [comment]
@mcarropellicer that's fine, however it's declared 5 lines above and since touching this area of code, feel free to correct that.
As for the logic, isn't that the basis of this PR? I see all green lines with + at the beginning, meaning new code.

**Comment by mcarropellicer** [comment]
PR updated

**Comment by juanjmerono** [comment]
LGTM

**Comment by bjones86** [comment]
+1, lets merge this in if both @juanjmerono and @steveswinsburg are happy with it

**Comment by bjones86** [comment]
I tested this locally; seems good to go.

**Pull request merged**
