### PR TITLE
SAK-32578 updated OptionsBean.java options.jsp sections.properties

### PR DESCRIPTION
**Pull request by juanjmerono**

### CODE REVIEW

**Comment by ern** [comment]
Putting a confirm button in the notification seems like a poor ui decision. I would rather see a modal that prompts the user if they wish to confirm. And than after confirming the notification would appear.

**Comment by jonespm** [comment]
Yeah, I'm for the modal dialog too just use https://jqueryui.com/dialog/#modal-confirmation

**Comment by joaquinmarques** [comment]
I need close this pull request

**Comment by juanjmerono** [comment]
Closed

**Pull request closed without merging**
