### PR TITLE
SAK-40724 - Legacy translations cleanup

### PR DESCRIPTION
**Pull request by mpellicer**
The es_MX variant only changes 21 translation files, it's very incomplete and will be moved to sakai contrib.

### CODE REVIEW

**Comment by mpellicer** [comment]
Reviewer, take a look here:
https://github.com/sakaicontrib/legacy-language-packs

**Comment by mpellicer** [comment]
I think we're talking about different issues, this PR removes legacy translations which are not updated for ages, and they can always be installed using the contrib repo.

I did the PR because there was a discussion in the sakai-dev list, but I totally accept the decision of the core team. I think this should be merged and the issue you're mentioning, should be in a separate Jira. Otherwise, feel free to close the PR, I'm good with the decision here.

**Comment by mpellicer** [comment]
See https://github.com/sakaicontrib/legacy-language-packs

**Comment by ern** [comment]
Discussed this in the Core Meeting and is approved.

**Comment by mpellicer** [comment]
@ern what do you think about the readme.md file?

**Pull request merged**
