### PR TITLE
SAK-49984 Library use sass math lib when computing contrast and luminance

### PR DESCRIPTION
**Pull request by kunaljaykam**
https://sakaiproject.atlassian.net/browse/SAK-49984

### CODE REVIEW

**Comment by kunaljaykam** [comment]
I have fixed our own sakai SCSS, but there are more issues within Font Awesome 4, which is no longer maintained. Upgrading beyond version 4 will break things, and it doesn’t seem like a good option since we already have Bootstrap Icons in Sakai. What I think we should do is, slowly transition from Font Awesome to Bootstrap Icons, tool by tool. I can look more into, how we can transition from font awesome-4 to bi. please tell me what you think about it.

**Comment by ottenhoff** [comment]
Bootstrap Icons are SVG which looks like a huge change. I would stick with FA

**Comment by ern** [comment]
@ottenhoff pretty sure FA icons are also svg, svg has the plus of resizing so you can use the same icon on any device size.

**Comment by ern** [comment]
because we have our namepsace "si" we should be mapping any "fa" or "bi" icons to "si" in library and our markup should be using "si" only. This also allows us to use multiple icon libs. bootstrap icons probably should be the preferred because of the license and the absence of a pro version but there are still many more icons currently in fa lib than bootstrap. I also think it is wise to upgrade the fa icon lib as long the icons were using are not in the pro version.

**Comment by ottenhoff** [comment]
FA4 used web fonts thus you could do this:

```
    a::before {
      content: "\f0da"; // fa-caret-right
      display: inline-block;
      width: 0.75em; // fixed width for both icons, similar to .fa-fw
      font-family: FontAwesome;
      text-align: center;
    }
```

**Comment by kunaljaykam** [comment]
Alright, I will start migrating slowly to FA6, : https://github.com/kunaljaykam/sakai/tree/FA6-Migration

**Comment by kunaljaykam** [comment]
On the last core call, Dr Chuck suggested we shouldn't upgrade font-awesome anymore instead we should make our icon-picker with the help of bootstrap-icons. Therefore I have decided to drop the idea of upgrading FA and instead I will investigate on how we can have replace FA in Sakai considering that we might not have all icons in the BI library. Until then if this pr is okay, we can merge it @ottenhoff .

**Comment by ottenhoff** [comment]
So if we keep FA4, I think we should import all of it into Sakai and then fix the math() so that we can upgrade to Dart Sass 2.0

**Comment by ottenhoff** [comment]
Any thoughts on importing FA4 into our library source?

**Comment by kunaljaykam** [comment]
I don't think we can disable the warnings. Importing FA4 with the fix is the only option for the problem. but I want to look one more time, If we can do something better. I am stuck on a gradebook bug, I thought I will fix it first then come back to it. So If we have some time. I'd like get into how much less icon bootstrap have compare to FA-4 and if its possible to do it without FA-4, even if  nothing comes out of it. we will get some idea about it for the future.

**Review by ottenhoff — APPROVED** [review]

**Pull request merged**
