### PR TITLE
SAK-47390 rubrics: rubric evaluation not printing for student

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-47390

### CODE REVIEW

**Comment by stetsche** [comment]
First thought you were working on a different issue. But I tested it locally, and it seems to fix all the issues.

**Comment by adrianfish** [comment]
@stetsche Are you saying it doesn't print from the preview, or that the weights just don't show?

**Comment by adrianfish** [comment]
Screenshot 2022-06-01 at 15 32 13

**Comment by stetsche** [comment]
For me it looks like a normal, non weighted rubric. Not showing Weight % and the new point values. Yesterday I compared this branch vs master and my dev branch. Only this one was effected. I was using  `gh pr checkout 10606 -f`.

**Comment by adrianfish** [comment]
Screenshot 2022-06-06 at 11 14 42

**Comment by stetsche** [comment]
If you can't reproduce it, we will have to test it in master after merging I guess?

**Comment by adrianfish** [comment]
Have you tried on the nightly server? It works the same for me on my local, and on nightly. But, I may be missing something.

**Comment by stetsche** [comment]
In the nightly server it is fine. When i checked out the branch of this PR, weighted rubrics appeared as non weighted in the preview.

**Comment by adrianfish** [comment]
Maybe I have something local that fixes this.  A lucky fix :)

**Comment by adrianfish** [comment]
I still can't reproduce this! Let's merge it and let others test it out.

**Pull request merged**
