### PR TITLE
SAK-31692 - Upgrade Sakai to Spring 4.2 (4.2.7 currently available)

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by ern** [comment]
LGTM

**Comment by buckett** [comment]
Build failure looks related.

**Comment by jonespm** [comment]
Thanks Matthew, looks like there's this one test that's still using a deprecated class I missed, I'll update it.

**Comment by jonespm** [comment]
Okay, two tests, but it's all passing locally now, lets see what travis thinks!

**Comment by ottenhoff** [comment]
Right on. Thanks @jonespm

**Pull request merged**
