### PR TITLE
SAK-46343 Update Apache Wicket 9.5.0

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by bjones86** [comment]
@axxter99 this is a major version change, were there no code changes necessary?

**Comment by axxter99** [comment]
@bjones86  Wicket 9.x: JDK 11.0 or newer

**Comment by ern** [comment]
@axxter99 did you do some testing in gradebookng?

**Comment by axxter99** [comment]
Wicket 9.x: OAuth, myconnections, mycalendar, (8.13.0 = 9.5.0)
no term-manager (component calendar :-1:  (8.13.0)
no 6.30.0: profile2, GradebookNG,..

**Review by ern — APPROVED** [review]

**Pull request merged**
