### PR TITLE
NOJIRA -T2 mvn builds

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by csev** [comment]
Hey @ern - does this conflict with the switching to mvnd approach?

**Comment by ottenhoff** [comment]
It's just to show that mvnd isn't much faster than using two threads in mvn!

**Comment by csev** [comment]
:)

**Comment by ern** [comment]
yeah as far as speed goes sure it's not much faster, but it is native code built with graal with a lower memory footprint.

**Comment by ottenhoff** [comment]
copying github actions is an easy way for someone to get up and running. i would argue mvnd is just unnecessary

**Pull request closed without merging**
