### PR TITLE
SAK-29013 enable the ical.opaqueurl.subcribe by default

### PR DESCRIPTION
**Pull request by ottenhoff**
...rl.subscribe by default,

and remove some code from calendar around the old ical.experimental ICS Subscribe functionality

https://jira.sakaiproject.org/browse/SAK-29013

### CODE REVIEW

**Comment by ottenhoff** [comment]
@buckett  can you review these changes?  They are related to SAK-21497 and calendar subscriptions

**Comment by buckett** [comment]
I have one fix to get public subscriptions working. An alternative would be to revert to the behaviour in earlier Sakai versions of just having the public ical only ever export the ical for the current site.

**Comment by buckett** [comment]
Would be good to enable to keep the opaque URL enabling part of the this pull request.

**Comment by ottenhoff** [comment]
Yes, I will re-do this PR to enable opaque and document it

**Pull request closed without merging**
