### PR TITLE
SAK-30171 UI improvements to Page Order page

### PR DESCRIPTION
**Pull request by payten**
Delivers https://jira.sakaiproject.org/browse/SAK-30171

### CODE REVIEW

**Comment by ern** [comment]
LGTM

**Comment by payten** [comment]
Thanks @ern!  I've just checked this against the latest morpheus PR (1585 - yet to be merged) and noticed that I'll need to style things a little differently to match up with the new changes.  It may be worth holding off on merging this and I'll prepare a patch ready for when the latest morpheus changes are in there.

**Comment by payten** [comment]
With the new morpheus changes now in master, I've pushed up an amended branch.  The major difference (**that could use a review**) is my go at generalising the tool icons defined in Morpheus' `_icons.scss`.  The main reason for doing so is to allow these tool icons to be easily used outside of the tool menu and breadcrumb contexts, namely in the tool order listing.  Thanks!

**Comment by SedueRey** [comment]
The changes about font awesome icons are great, thanks, I haven't the time to do it. 

I've been looking at the code and **looks good to me**. +1

**Comment by juanjmerono** [comment]
@payten could you squash it into only one commit?

**Comment by payten** [comment]
:eggplant: squashed! Thanks guys.

**Pull request merged**
