### PR TITLE
SAK-31753 - a[href] background-color overrides some styles

### PR DESCRIPTION
**Pull request by SedueRey**

### CODE REVIEW

**Comment by SedueRey** [comment]
Hi, @payten could you take a look to this PR? I've removed the background-color from a[href] because it was causing some unexpected problems (links with button behaviour) but I would prefer that you tell me if you needed that property for some reason.

**Comment by payten** [comment]
If I recall correctly, I added `$link-background-color` to ensure a button-styled-like-a-link will look like a link.  I think is because ` .button.link, a.btn-link, button.btn-link` needs to `@include sakai_button` and required a meaningful background color variable to make it all sync up.   And this was to aid skinning, whereby a skin may want a link to have a backgound-color and this would then flow through to the button-styled-as-a-link.  

I'm not opposed to removing `$link-background-color`, `$link-hover-background-color` and `$link-active-background-color` if we don't want to allow skins to override this value.  If that's the case I'd suggest we remove the variables completely, including anywhere they are used.

**Comment by SedueRey** [comment]
The problem is the `.sakai_button()` mixin does not override that property because the `[href]` has higher priority. 

In my opinion, we should keep that variables because they are used on some mixins too, just remove that specific declaration.

**Comment by payten** [comment]
Ah, sure thing.  Gosh, that precedence stuff is tricky!  +1 to go for it.

**Comment by SedueRey** [comment]
Thanks!!

**Pull request merged**
