### PR TITLE
LSNBLDR-633: Adding config for lessonbuilder.show.set.owner

### PR DESCRIPTION
**Pull request by nicholaswilson100**
This is adding some config to LSNBLDR-633 so that the feature can be turned on or off.

Default is on.

If this goes back to 11.x, then the property should be set to false and uncommented out.

### CODE REVIEW

**Comment by jonespm** [comment]
This seems okay, I think all of these fixes for the properties should be moved up into the lessonbuilder section in the default.sakai.properties and given consistent names. This could be done afterward I guess.

**Comment by jonespm** [comment]
For instance we've got (all at the bottom of the rather than a few hundred lines earlier in START LESSONBUILDER
lessonbuilder.show.twitter.link
lessonbuilder.show.resource.folder.link
lessonbuilder.show.calendar.link 

And now
lessonbuilder.show.set.owner

I guess the names are okay, just move them all up into lessons section since it conflicts anyway can just do it here.

**Comment by nicholaswilson100** [comment]
I've moved the lessons properties together

**Comment by jonespm** [comment]
Thanks! @nicholaswilson100. I'd meant that this file is intended to be grouped by tool already to make it easier to find properties for tools. Could you move these ALL up to around the section in around line 3990 where all of the other lessons properties are (not just these?) 

image

**Comment by nicholaswilson100** [comment]
Ah ok  - yup I've moved them all together now.

**Comment by jonespm** [comment]
Great, thanks!

**Pull request merged**
