### PR TITLE
When publishing an assessment extended time entry on working copy

### PR DESCRIPTION
**Pull request by jonespm**
removed

### CODE REVIEW

**Comment by jonespm** [comment]
This looks like it was just because the id of the existing entry wasn't set to null, so the code was doing an update here instead of a new save. It should insert a new entry when it's publishing.

**Comment by jonespm** [comment]
Thanks @master-bob for the review more of these to come!

**Comment by master-bob** [comment]
I just realized this commit is lacking the JIRA ticket in the commit message.

**Comment by jonespm** [comment]
Yeah me too, oops! It's SAM-3076, I don't think I can fix this without a force push and even though it seems *safe* for me to do it probably not even worth it. We'll just note it on the jira for the merge.

**Comment by jonespm** [comment]
It looks like jira picked it up anyway just based on the change of title here, it's just not in the github history. I'm not super worried about that.

**Comment by master-bob** [comment]
If so desired, this could be fixed by reverting the commit and then committing it again with an improved commit message.

**Pull request merged**
