### PR TITLE
SAK-49569 Assignments file picker navigation when selecting resource from another site

### PR DESCRIPTION
**Pull request by kunaljaykam**
https://sakaiproject.atlassian.net/browse/SAK-49569

There's still one minor issue. Upon initial load the first nav button seems to be in focus, even though its not active. Probably because its a button.

### CODE REVIEW

**Review by ern — APPROVED** [review]

**Comment by ottenhoff** [comment]
> Upon initial load the first nav button seems to be in focus, even though its not active. Probably because its a button.

Is this the @stetsche commit from "S2U-4 Microsoft integrations working package - MASTER (#12273)"?

$('.nav-item.active').find('a').focus();

**Comment by kunaljaykam** [comment]
> $('.nav-item.active').find('a').focus(); 
No, It helps to focus on the active element. I have switched to `<a>` anyway. It should have been `<a>`. It works fine now.. I am working on minor UI improvements on the tabs. the active tabs shouldn't have a bottom border. 

Thanks.

**Comment by kunaljaykam** [comment]
Screenshot from 2024-02-15 01-06-43
Screenshot from 2024-02-15 01-06-29

**Review by ottenhoff — APPROVED** [review]
Thanks!

**Pull request merged**
