### PR TITLE
SAK-31470 Re-styled the positioning and layout of the topNav bar and associated views

### PR DESCRIPTION
**Pull request by fostersdesign**
There are a number of issues with the alignment and positioning of the items in the top bar. They should be vertically centred across the bar to present balance. I have gone through the topNav bar piece by piece and fixed the positioning, spacing, and sizing to make everything centred, equal, and balanced. 

I also fixed an issue with the colours of the sites across the top to fix accessibility contrast issues and ambiguity of the selected site. 

Here are the before and after screenshots:

Before:
01-gateway-before

After:
02-gateway-after

Before:
03-gatewaymobile-before

After:
04-gatewaymobile-after

Before:
05-topnav-before

After:
06-topnav-after

Before:
07-topnavinsite-before

After:
08-topnavinsite-after

Before:
09-accountmenu-before

After:
10-accountmenu-after

Before:
11-sitesmenu-before

After:
12-sitesmenu-after

Before:
13-selectedsitequicktoolsmenu-before

After:
14-selectedsitequicktoolsmenu-after

Before:
15-othersitequicktoolsmenu-before

After:
16-othersitequicktoolsmenu-after

Before:
17-accountmenuwithprofilemobile-before

After:
18-accountmenuwithprofilemobile-after

Before:
19-toolsmenumobile-before

After:
20-toolsmenumobile-after

Before:
21-sitesmenumobile-before

After:
22-sitesmenumobile-after

Before:
23-mobilenoprofile-before

After:
24-mobilenoprofile-after

Before:
25-accountmenunoprofilemobile-before

After:
26-accountmenunoprofilemobile-after

Before:
27-accountmenunoprofile-before

After:
28-accountmenunoprofile-after

**Please note: the Tools Menu in the mobile view, the All Sites drawer in both views, and the Breadcrumbs in both view are out of scope for this PR and will be fixed too in a future contribution.**

### CODE REVIEW

**Comment by SedueRey** [comment]
One question ... when you change "the" for "instructor", are you changing the name of the user for the last name? Is that a property?

**Comment by SedueRey** [comment]
Did you test your modifications with `top.login=false` for two links

**Comment by fostersdesign** [comment]
Good observation, @SedueRey! For my screenshots, I used two different accounts, which had slightly different full names ("The Instructor" vs "Instructor"). In my PR, I didn't change what gets displayed: in both cases it shows the first names. 

In a future PR, I would like to create properties that will control what names display up there: e.g. first name only, last name only, full name only, username. That was out of scope for this fix, so it'll be future work.

**Comment by fostersdesign** [comment]
Yes, I tested with top.login=false and the two links work. I should attach some screenshots of that.

**Comment by SedueRey** [comment]
Great then :), Thanks

**Comment by fostersdesign** [comment]
Here are two **after** screenshots of the Gateway page with the links instead of the top login:

**top.login=false**
29-toploginfalse-after

**top.login=false and container.login=true**
30-toploginfalse-containerlogintrue-after

**Pull request merged**
