### PR TITLE
SAM-3193: Change attribute of input element to enable update button w…

### PR DESCRIPTION
**Pull request by mateullas**
…hen textbox is clicked to edit pool name

### CODE REVIEW

**Comment by ern** [comment]
If you enter the input box and change the value the onchange event should be triggered. It makes sense to enable the button if the value is changed? However if there is an issue with state and other elements on the page then onfocus is probably more suitable than onclick or even removing the button disable all together (is the disable button logic really needed?)

**Comment by mateullas** [comment]
Hi, Earle. 
The problem here is that with the "onchange" attribute the behavior is the described in the JIRA ticket, you must click outside the textbox to enable "Update" button. This behavior has been reported by our users as annoying (and in some cases as a bug). 
I have tried to change this attribute to "oninput" but in this jsf context fails (there is no "oninput" attribute). For this reason I used "onclick". In this way, when user clicks on textbox to change title, the button is enabled.

**Comment by mateullas** [comment]
I have investigated another option: to use "onkeypress" instead of "onclick". Maybe the behavior is closer to "onchange" because user has to click on a key in order to enable update button. 
What do you think?

**Comment by ern** [comment]
Did you look at onFocus?

**Comment by ern** [comment]
Also does this button disable logic make sense here? I don't see any issue if the user clicks save and hasn't changed anything!

**Comment by mateullas** [comment]
HI, Earle. 
I have tested in local instance using onfocus attribute and it works. 
However, I prefer onkeypress attribute because user has to do something in order to enable the update button. The other fields in this screen contain also the onchange attribute and I think it is better to control that the user modifies something and to avoid saving if nothing has changed.
I can modifify the PR to put all the fields following the same logic (onkeypress, onfocus, what we consider the best option)

Regards

**Comment by mateullas** [comment]
Hi, @ern , should I modify this PR in order that all fields follow the same logic? 
Which attribute must be used: onkeypress, onfocus, another one?

**Pull request closed without merging**
