### PR TITLE
SAK-25514: Refactored Morpheus

### PR DESCRIPTION
**Pull request by alienresident**
## Major Refactoring

* Refactored Sass to use new namespace `.Mrphs-`
* Create variable pattern to work with new namespace — to be documented
* Removed portal.css and now uses just tool.css
* Modified copy_js.sh to copy only `*.min.js`
* Removed unused concatenated .js files
* Changed 'My Workspace' to 'My Account' — needs to be done properly
* Renamed modules to reflect camelCase naming conventions
* Refactored JS for navs
* Moved portal JS to small files

### CODE REVIEW

**Comment by ern** [comment]
There are a lot of commits on this PR including merges from master which shouldn't appear if you've been rebasing and working in a branch.

You will need to refactor this PR, I would also suggest to use squash arranging everything into to more logical commits.

**Comment by alienresident** [comment]
Hi Earle,
I'm a little confused about the workflow. I looked at this and tried to follow along.
https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup
Notably 6b.
Should I rebase and resubmit?

**Comment by buckett** [comment]
I know this wasn't introduced in this pull request, but it might be nice if the compiling of the CSS was part of the build rather than requiring.

https://github.com/Jasig/sass-maven-plugin

**Comment by buckett** [comment]
Looks to have also removed the extra head stuff that came in with:

https://jira.sakaiproject.org/browse/SAK-29001

might be worth double checking that other stuff that got changed in /portal and /reference hasn't got lost in merges.

**Comment by ern** [comment]
Hi Mark,

The PR is coming from your master which is a sign that your not in a branch.

When making changes in git (using the github model) you want to be making changes in a branch and not master.

Typically master is how your fork receives changes from the upstream project. So committing changes to your master is only going to cause problems.

As a contributor always work in a branch and never commit changes to master (this is the github way).

OK so what to do now! Given the number of commits I would just grab a patch of all the changes by creating new branch(s) and sync it with upstream master (not your local master), get a diff between your local master and the newly created branch, then apply your diff to the new branch and then submit a new PR from that branch.

I think this approach will be faster than trying to sort through all the commits.

If that all goes well then its time to fix your master.

Sync your master in your fork to upstream master and then never make commits to master. If you make changes in master (I do this from time to time) then just stash them create your branch and pop/apply the changes that were stashed.

**Comment by ern** [comment]
I realize some of this is maybe out of your comfort zone, if thats the case I can do this for you just let me know?

**Comment by bjones86** [comment]
I think it would benefit a lot of people if instead of doing this for Mark, you could walk him (us) through the commands you would use to accomplish this. This would also be a prime candidate for addition to https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup

**Comment by ern** [comment]
If Mark needs I will provide some more instruction including commands to achieve what I explained above.

**Comment by alienresident** [comment]
Hi Earle,

I was working in a branch in my fork but I merged that branch into my master and did the pull request from there. I'll try to force my master to be back on the sakai master. I think I can figure out the steps to rebase my changes in my branch. I'll be in touch if I'm stuck.

**Comment by bjones86** [comment]
My comment was not to intended to solely create more work for you, Earle, and I appologize if that's how it came off. My intention was rather, to assist new-comers to Git/Github. I know that Mark is not the only one who may be struggling or not quite understanding the new Github workflow, or how to accomplish these more complex tasks wihtout assistance. Myself included.

I'm simply trying to create an effort by those in the community who already possess high-level Git-fu to diseminate their knowledge to the rest of the community. If we were to document these processes and commands somewhere (like the Confluence page), it would be a much easier transition for people coming from the SVN world. Instead of having these one-off suggestions and comments buried in PR threads, documenting them somewhere would avoid these issues coming up again in the future.

**Pull request closed without merging**
