### PR TITLE
SAM-2315 use the jquery-ui date/time picker in samigo. 

### PR DESCRIPTION
**Pull request by ottenhoff**
This is a large change  and removes a lot of legacy code around the custom Samigo datepicker.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
On first load of the settings page for a quiz I see a datepicker at the bottom left of the browser.
Also the 'it is available', 'It is Due' should probably be on separate lines?

screen shot 2015-03-02 at 11 33 35 pm

**Comment by ottenhoff** [comment]
Yeah, I'm not sure why the calendar loads at the bottom. My guess is that it's because the extra height provided to the iframe so the accordion works.

> Also the 'it is available', 'It is Due' should probably be on separate lines?

This is how it was designed by the Stanford team. I'm happy to work on a re-design, but this is the way it was originally designed.

**Comment by steveswinsburg** [comment]
OK yeah I wasnt sure if the 'is it available' was a result of the new
datepicker or not. Leave that.

So should that datepicker be sitting down there? Or hidden completely until
needed?

**Comment by buckett** [comment]
While we may want to change how Samigo works it would seem to be good to get this in and then open other Jira to change behaviours.

**Comment by ern** [comment]
I agree with bucket lets get this in and open new JIRA's for any issues that are related.

**Pull request merged**
