### PR TITLE
SAK-29437 - Update mathjax url to avoid https

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by bjones86** [comment]
+1

**Comment by jonespm** [comment]
I have this on the nightly experimental as the URL and it's working. It sounds like the recommendation now is to always use the SSL version if it's available since that will work with the http page too. So maybe just change this. Doesn't really matter a ton, just means 2 copies might get cached.

http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by bjones86** [comment]
Sounds good to me, thanks Matt

**Comment by steveswinsburg** [comment]
Cool so before this goes in will this be edited to the https version?

**Comment by jonespm** [comment]
Yeah, is updated

**Pull request merged**
