### PR TITLE
SAK-43711 (V2): SWITCH: Mailarchive: Use permissions widget

### PR DESCRIPTION
**Pull request by frasese**
* Moved properties files from tool to api.
* Merged permissions.properties files into mailarchive.properties.
* Adapted to permissions webcomponent.
* Update PermissionsEntitiyProvider to filter by SEARCH + "."

### CODE REVIEW

**Comment by frasese** [comment]
This tool has a special problem related with permissions names. They are called mail.XXX ("mail.read", "mail.new" and "mail.delete.any"). The problem is, when the webcomponent retrieves the permissions data from the direct REST url (PermissionsEntitiyProvider), it checks for everything that starts with "mail". So, not only mail.XXX (mailarchive's permissions), but also mailtool.XXX (mailsender's permissions) are returned.

So we have two different solutions here.

1.- Set the webcomponent tool-key as "mail." (https://github.com/sakaiproject/sakai/pull/8255)
This will retrive the correct permissions data from direct but will generate the permissions table with id="mail.-permissions-table". Then, we need to adapt the javascript selector in the savePermissions method to locate this id.

2.- Change PermissionsEntitiyProvider to look for SEARCH + "." (THIS ONE).
I think this is a more elegant solution as it return the "expected result". But ,I don't know if it will affect other tools that trust the old behaviour.

Both PRs are exclusive, choose one or other.

**Comment by adrianfish** [comment]
Have you searched for other tools that use the direct endpoint? I suspect that there aren't many, but you could get an idea. I'd rather go with this solution and fix the other tools. I don't like the idea of hacking the selector in the component when we can just fix the endpoint.

**Comment by frasese** [comment]
I also prefer to fix the endpoint. And no, there are no more uses of that endpoint.

**Comment by frasese** [comment]
Finally, in "messages" PR (https://github.com/sakaiproject/sakai/pull/8265) we have needed to add the hacking selector option, because the tool id includes a dot (msg.permissions).
So, it's up to you to use this option or the first one (https://github.com/sakaiproject/sakai/pull/8255) **Caution with conflicts**, because both PRs apply the same change.
Anyway, I consider this option stills being good.

**Comment by frasese** [comment]
This PR is the good one. The other one was closed in favour of this.

**Comment by adrianfish** [comment]
Go for it, then :)

**Pull request merged**
