### PR TITLE
SAK-29578 updated Turkish translations

### PR DESCRIPTION
**Pull request by eemirtekin**
Sakai Turkish translations files updated via Transifex

### CODE REVIEW

**Comment by bjones86** [comment]
Looks good, thanks @eemirtekin. I'll merge this one in tomorrow unless anyone has comments, etc.

**Comment by ottenhoff** [comment]
Looks good to me

**Comment by eemirtekin** [comment]
Hi @bjones86 and @ottenhoff;

I could not find my translated Tuskish files in svn repo https://source.sakaiproject.org/svn/sakai/tags/sakai-10.5/
Is there anything else I have to do.

Thanks

**Comment by bjones86** [comment]
@eemirtekin this hasn't been merged into the 10.x branch because the merge flag on the JIRA ticket wasn't set.

When creating a JIRA ticket, if you wish for the feature to be backported to the 10.x branch. You need to set the appropriate flag on the ticket to let the branch managers know that this is on the list to be merged into the maintenance branch.

Since the 10.5 tag has been finalized, this won't be making it into 10.5. We can set the merge flag now, but you'll have to use a copy of the 10.x branch, or wait for the 10.6 tag to be cut.

**Comment by eemirtekin** [comment]
@bjones86 thanks for your help.

**Pull request merged**
