### PR TITLE
SAK-40809 Add Turkish tool name and description which not included in Transifex for BBB and News

### PR DESCRIPTION
**Pull request by eemirtekin**

### CODE REVIEW

**Comment by eemirtekin** [comment]
Hi @mpellicer,

Will this PR and #6163 merged with 19.x?
Should I send again for 19.x?

Thanks in advance.

**Comment by mpellicer** [comment]
Hi @eemirtekin, you should set the "Sakai 19 Status" to "Please Merge" in the Jira, I don't know if exists yet but will exist for sure.

Regards

**Comment by mpellicer** [comment]
Hi @eemirtekin, you should set the "Sakai 19 Status" to "Please Merge" in the Jira, I don't know if exists yet but will exist for sure.

Regards

**Comment by mpellicer** [comment]
Hi @eemirtekin, you should set the "Sakai 19 Status" to "Please Merge" in the Jira, I don't know if exists yet but will exist for sure.

Regards

**Pull request merged**
