### PR TITLE
SAK-40055 Make the collapse tool button easier to hit

### PR DESCRIPTION
**Pull request by fostersdesign**
See screenshots in [https://jira.sakaiproject.org/browse/SAK-40055](https://jira.sakaiproject.org/browse/SAK-40055).

The collapse tool button in the lower left corner of the interface (that collapses the side tool menu when clicked) has a smaller hit area than advertised.

Although the cursor changes to the pointer (click finger pose), users have to click a particular part of the area which the button contains.

My fix makes the button take up the full area of that collapse button area, so it is all clickable.

I also reduced the need for JavaScript to run to control the positioning and display of this button by controlling it all with CSS (less code, yey!).

### CODE REVIEW

**Comment by ottenhoff** [comment]
Thanks Shawn. Can you show a screenshot of what focus looks like when in Firefox? This was an issue with our latest a11y review.

**Comment by fostersdesign** [comment]
Yes, I noticed the lack of focus in Firefox too, Sam, in regard to this interface component. I was able to reproduce it (the lack of focus) prior to my fix, so I decided it was out of the scope of this fix/PR. 

I would like to investigate the focus (and discuss it with those who have been working on it) to have a better understanding of the needs and how those can be balanced with aesthetics.

**Comment by fostersdesign** [comment]
Actually, I take that back... I just retested it now and get this:


focusinfirefox

**Comment by ottenhoff** [comment]
Okay focus looks good to me ... and once collapsed and reloaded, still visible focus?

**Comment by fostersdesign** [comment]
After collapsing and refreshing the page:

focusinfirefoxaftercollapseandreload

**Comment by ottenhoff** [comment]
LGTM ... does this PR remove the "floating" part of this functionality?

**Comment by fostersdesign** [comment]
I wouldn't say that focus "looks good". I think the changes made in SAK-38356 make focus throughout the system look like Windows controls from the '90s. I'd be happy to discuss this with you at Open Apereo next week.

**Comment by ottenhoff** [comment]
Subtle focus continues to cause issues during our a11y reviews. A clear and pronounced focus ring is key for our default skin.

**Comment by fostersdesign** [comment]
Okay. Thanks, Sam. We can discuss the focus elsewhere. 

Thank you for looking at this PR. Do you have any concerns with it?

**Comment by fostersdesign** [comment]
Thanks!

**Pull request merged**
