### PR TITLE
SAK-31669 Correctly log when removing permissions.

### PR DESCRIPTION
**Pull request by buckett**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Not sure if this is the right place to do it, but the defaults for SitePerms tool are bad ..... they should pause less and should have a *much* higher max run time (86400 instead of 3600)

**Comment by buckett** [comment]
There doesn't seem to be a max run time, there's a max time to wait for a job to complete before you're allowed to start another, but the thread doesn't appear to limit itself.
Dropping the pause time down to 100ms seems sensible, or were you thinking further?

Really this should be a quartz job and then you get cross cluster coordination and lockout of jobs while the old one is running as well as the ability to stop a running job half way through cleanly.

**Comment by ottenhoff** [comment]
100ms is fine with me.

Here is the max run time: site.adminperms.maxrun.secs=3600

**Comment by buckett** [comment]
Ah, I missed the call to `isLockedForUpdates()` in the loop.

**Pull request merged**
