### PR TITLE
SAK-49597 Kernel allowAccessSite should consider if user is role swapped

### PR DESCRIPTION
**Pull request by kunaljaykam**
https://sakaiproject.atlassian.net/browse/SAK-49597

### CODE REVIEW

**Comment by adrianfish** [comment]
You've used the wrong SAK number in the commit log

**Review by adrianfish — APPROVED** [review]
Thanks Kunal

**Comment by adrianfish** [comment]
I've approved it, but you should update that SAK number in the commit message

**Comment by kunaljaykam** [comment]
Thank you :+1:

**Comment by adrianfish** [comment]
@kunaljaykam You're welcome :)

**Pull request merged**
