### PR TITLE
SAK-48219 trinity Dark mode Highlight color could use more contrast

### PR DESCRIPTION
**Pull request by austin48**

### CODE REVIEW

**Comment by austin48** [comment]
https://sakaiproject.atlassian.net/browse/SAK-48219

SAK-48219-1
SAK-48219-2

**Comment by austin48** [comment]
here is the proposed change

SAK-48219-change

**Review by adrianfish — APPROVED** [review]
Lovely, thanks Austin.

**Review by kunaljaykam — APPROVED** [review]
Thanks, @austin48

**Pull request merged**
