### PR TITLE
SAK-29247 Previous method code but accessing by gbItemId

### PR DESCRIPTION
**Pull request by juanarcadio**
The code of method getAssignmentScoreString(final String gradebookUid, final String assignmentName, final String studentUid), but accessing by gbItemId.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
How did you get multiple gradebook items in the gradebook with the same name? There is a check for this in the impl already when creating:

if (assignmentNameExists(session, asn.getName(), asn.getGradebook()))
                {
                    throw new ConflictingAssignmentNameException("You cannot save multiple assignments in a gradebook with the same name");
                }

**Comment by jonespm** [comment]
I believe external tools can do it through the API. We has some issues like 
https://jira.sakaiproject.org/browse/SAK-27494

There might be other ways to do it. Basically the problem there is because there is a column to indicate if the gradebook item is removed. And if you remove the item you can re-use the name, so there's no constraints. Since you could have a constraint on (gradebook_id, name) but not for both allowing removed and not removed that all becomes a problem. You'd have had to have had two tables I guess in the database design?

**Comment by juanarcadio** [comment]
That is possible with gradebook2. I don't know if this check could be skipped in gradebook importing grade items from assignment tool or tests&quizzes tool.

**Comment by steveswinsburg** [comment]
Yes this is definitely poor database design. There definitely should be a unique constraint on these columns. That would have prevented SAK-27494.
Difficult to add now but with a few modifications to the columns it might be doable. 

Interested to know if there are other ways this can be bypassed?

**Comment by juanarcadio** [comment]
I tried to create gradebook items with duplicated name in a nightly server: importing from excel file, publishing from samigo, publishing from assignments tool,... and I couldn't do it. But you can do it using external tools through the API, for example with Gradebook2 you can easily create different assignments with the same name.

Then, If the gbItemId is unique and assignmentName should be unique but it can actually be duplicated by external tools (i.e.: we have 146 items duplicated) I believe that this patch makes sense, doesn't it?
The code of getAssignmentScoreString that retrieves scores from a gbItemId should query by gbItemId instead of querying by an assignmentName obtained from the gbItemId.

This patch is already working in our local instance of sakai. Any thoughts about it?

Thanks.

**Comment by juanjmerono** [comment]
We've got this in production for two weeks without any issue.

**Pull request merged**
