### PR TITLE
SAK-29127 Fix portal video chat on Morpheus

### PR DESCRIPTION
**Pull request by sinmsinm**
Lot of changes done to fix portal video chat on Morpheus. Now it can works on neo and morpheus either. In the future, we can suppress neoskin support to simplify things and improve SASS style.
 
videochat-morpheus

### CODE REVIEW

**Comment by ottenhoff** [comment]
Great! Thanks for the hard work here.  Thoughts on squashing all of this work down to one commit?

**Comment by sinmsinm** [comment]
If you want I can try on monday.

**Comment by csev** [comment]
I am ready to merge this as soon as the commits are squashed.

**Comment by sinmsinm** [comment]
I close this PR. Hi did another branch with the correct JIRA number and just one commit.

**Pull request closed without merging**
