### PR TITLE
SAK-29595 Change gradebook comment_text to a 500 char string instead of a clob.

### PR DESCRIPTION
**Pull request by steveswinsburg**
The comment text field in the gradebook comment is currently a materialized_clob. This needs to be cut down to a reasonable limit of a few hundred chars since all grades and comments are fetched in bulk.

Change the hibernate field size.
Add length validation to the persistence method
Add conversion

### CODE REVIEW

**Comment by juanjmerono** [comment]
I've got many rows with this field greater than 500 chars, so I can't do this conversion without losing data. Is it possible to retrieve a fragment of this data (adding a new calculated field) to compose the bulk in order to keep the field with the original size, but allowing a faster bulk operation?

**Comment by steveswinsburg** [comment]
IMO this is a performance bug and should never have been implemented as such a large field. Why would anyone want to add more than a few notes like 'good work' or 'you could have done better' so this field? It's not for massive amounts of assignment feedback. 

What is the maximum length of the field that you have? I don't intend on reworking the gradebook to keep this field at this length.

**Comment by sinmsinm** [comment]
Wow, looking to my DB I have around 900 comments bigger that 500.  Longest is 18520, and from those that are bigger than 500 it's average length is 961. I don't know what teachers exactly explain but it must be detailed :dart:

**Comment by juanjmerono** [comment]
I'm talking about more than 2k comments with more than 500 chars. The longest one has more than 6k characters, but only 11 have more than 4k characters. I agree that it was an error, but sadly now we have to deal with it, trying not to lose all these extra feedback if possible :cry: 

It's hard to try to convince users that upgrades are always positive if they lose data on them.

It seems that without doing the database conversion everything works (with poor performance in some cases). I won't be able to modify comments with more than 500 characters (due to code restriction), but it will let me see the original big comment. After some time I will be able to do the database conversion. I will lose data too..., but only "old data" that should not compromise current user's work. I think it is worth mentioning this possibility beside the conversion script.

**Comment by ottenhoff** [comment]
```
mysql> select count(*) FROM GB_COMMENT_T WHERE LENGTH(COMMENT_TEXT) > 500;
+----------+
| count(*) |
+----------+
|    18846 |
+----------+
1 row in set (1.13 sec)
```

**Comment by steveswinsburg** [comment]
May need to take it to the list. We can increase the limit from 500 to
something a bit higher, though I'm tempted to have a big note in the
upgrade docs and if people want the data, export the gradebook to preserve
it.
Obviously I don't want people losing data, but I think this is a bug we
need to address.

**Comment by steveswinsburg** [comment]
The other alternative is to not limit the DB column, but provide the
application code to limit it.I would be agreeable to that, however we
should also note somewhere that this is a known issue and could cause
performance problems if that column has a lot of data in it.

On Mon, Jun 29, 2015 at 10:51 PM, Steve Swinsburg <steve.swinsburg@gmail.com

**Comment by ottenhoff** [comment]
We're not currently aware of any performance problems around this column. How can we attempt to replicate?

**Comment by steveswinsburg** [comment]
In a site with a large  number of students and assignments (300 and 20
perhaps), add extremely long comments to all of the grade entries, fill the
column with its maximum amount (n) of data since that is possible now (can
be done direct in the gb _ comment table ). A fetch on that will pull back
300 x 20 x n bytes of data.

sent from my mobile device

**Comment by ottenhoff** [comment]
What if we limit the new GradebookNG UI to only allow 500 chars? And then allow legacy sites to choose to truncate or leave their existing comments alone?

Also I believe Assignments and Samigo both send their comments over to GB in Sakai 10+

**Comment by steveswinsburg** [comment]
Yeah I'm happy with that. I'll back this out and make the change in GBNG
only.

There is potentially still an issue if someone looks at an old gradebook
that had massive amounts of comment data. But perhaps that can be a known
issue.

**Pull request closed without merging**
