### PR TITLE
LSNBLDR-542: New Lessons component: Add Resources Folder

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
I'm taking over Neelam's PR here (https://github.com/sakaiproject/sakai/pull/1412) as she is no longer working on it.

**Comment by nicholaswilson100** [comment]
I'm adding a fix for when selecting a Resources Folder listing to add, one sees the standard Sakai / WL footer halfway down the page on top (or underneath) of the "select folder" <div>

**Comment by clhedrick** [comment]
OK, it works now. I didn't see anything in the code to object to. But is there some reason you didn't implement the normal require and don't release until prequisites options? We do it for resources, so it seems a bit odd not to do it for these. That might require you to go through /access/lessonbuilder rather than /access/content, and might require some changes in the code, to check whether what the user is trying to load is included in the item.

I can see that require would be hard. Do you require them to view every item in the folder? If so, how do you keep track of it? But don't release unless prerequisites have been met is currently done even for tools where require makes no sense such as inline video. So is group release, which your backend code supports but not your UI.

Also, people got after me when I didn't make the UI sensitive to underlying access issues. That is, when you add a file that is hidden or released to only a group, the author's UI has a note showing that, and the item doesn't show for students who can't use it. (Currently a folder that you can't see shows as extra vertical white space, although someone changed the CSS markup to show individual items it would become obvious that it's an empty item.) I see that this is more complex because there can be multiple subfolders with different restrictions. Probably all you can do is tie access to the main directory. I'd suggest mimicking the UI for linking to items. 

I'm trying to make sure that new features behave consistently with old ones.

**Comment by bjones86** [comment]
Needs rebasing...

**Comment by ncaidin** [comment]
Any additional work planned to get this consistent with other areas of Lessons per Chuck Hedrick's comments?

**Comment by lardo-de-arnaud** [comment]
We are happy to do the "pre-requistes" code. This was an oversight. 

I dont think "require" makes much sense in this context so we werent planning to do this.

I dont understand the last long para so I'm going to have a play before responding.

Were hoping to get this into 12 so it will be a high priority for the next week or two

**Comment by buckett** [comment]
Is the "pre-requistes" done as I don't see any check for it here?

I think @clhedrick is saying when we display the folder listing we should make it clear if an item has additional restrictions on it (hidden or group limited) so that an author is aware then although they see the file when a student is looking at the UI they may not see that item.

**Comment by lardo-de-arnaud** [comment]
Nick and I spoke about this and my view was that we should replicate what the "/access" view and regular view of Resources does. ie, when a "maintainer" views the listing they see hidden folders as greyed out. I figured this is a sign that the folder is hidden and is consistent with the rest of Sakai. Because of this, it doesnt need to be explicitly stated that "this folder is hidden". 

I hope I've understood correctly.

**Comment by nicholaswilson100** [comment]
Please read the Jira carefully if you're commenting on this PR as the requirements tend to change.

**Comment by lardo-de-arnaud** [comment]
Nick's just reminded me that there's a whole hep of comments on the Jira pertaining to comment by Charles and others on the original pull request.

See: https://jira.sakaiproject.org/browse/LSNBLDR-542 - comments made on 7th Feb and onwards. 

It's a bit awkward having two places to comment!

**Comment by nicholaswilson100** [comment]
Actually most of the Jira comments I've made pertain to comments made in the Jira not the PR.

**Comment by lardo-de-arnaud** [comment]
Nick, as far as I can see, Charles made 4 main comments on the PR. I've read the jira and cant see these points covered. Can you either confirm that you've addressed them

1/ The code doesnt implement the normal require - this is not practical though so can be ignored 

2/ doesn't implement "release until prequisites" options

3/ doesn't implement "group release"

4/ leaves white space when a folder that you cant see

**Comment by nicholaswilson100** [comment]
I've addressed all the comments.

**Comment by nicholaswilson100** [comment]
I've done 1,2 but not 3 and 4

**Comment by nicholaswilson100** [comment]
@adamm: 4 you said to leave as it was presentational

**Comment by lardo-de-arnaud** [comment]
Right so I have discovered that there are still two outstanding issues that Charles raised that havent been addressed

3/ doesn't implement "group release" in the UI

4/ leaves white space when a folder that you cant see

If the PR can be merged we'll address these 2 as bug fixes in the next couple of days.

**Comment by nicholaswilson100** [comment]
I think I've addressed all the comments in this PR that need addressing.

**Comment by nicholaswilson100** [comment]
@adamm: I'm not sure 4 is definitely an issue.  I didn't see it on my machine.

**Comment by adrianfish** [comment]
I've merged this. It needs checking over though. The alignment needs adjusting and there needs to be an icon to make it look like the other items, imho. If there are any other ticks that Chuck spots, they should be looked at before the final bug freeze.

**Comment by adrianfish** [comment]
I've just reverted it. As @bjones86 said, you need to rebase this onto the current tip. Library is now a top level project, for a start. I shouldn't have merged this - my aplologies for the history muddying.

**Comment by nicholaswilson100** [comment]
Thanks Adrian.  How come you were able to merge something that wasn't rebased on the tip?

**Comment by nicholaswilson100** [comment]
I thought github prevented or ought to prevent this

**Comment by buckett** [comment]
Github prevents conflicts but all this issue did was add files to a folder so there was no conflict with a file that was moved.

**Comment by lardo-de-arnaud** [comment]
nick is onto this, hopefully it'll be ready to merge again soon.

**Comment by nicholaswilson100** [comment]
Since this PR was closed, I've rebased this and created a new PR here: https://github.com/sakaiproject/sakai/pull/4085.

@adrianfish : How does it look to you?

**Pull request merged**
