### PR TITLE
SAK-44487 Rename Site Info --> Tool Order - "Tool Order/Visibility"

### PR DESCRIPTION
**Pull request by victorfv2**
https://jira.sakaiproject.org/browse/SAK-44487

### CODE REVIEW

**Comment by victorfv2** [comment]
@mpellicer

**Comment by victorfv2** [comment]
@josecebe

**Review by fostersdesign — COMMENTED** [review]
I'm not a fan of making the tabs longer with more text, especially Site Info with its many, many tabs. Ideally, we'd merge Tool Order's functionality into the Manage Tools page for a single tab, but that seems out-of-scope for this fix.

**Comment by mpellicer** [comment]
Closing as this requires many discussions and unassigning @victorfv2

**Pull request closed without merging**
