### PR TITLE
SAK-29601 Roster large screen view doesn't have any column headers

### PR DESCRIPTION
**Pull request by juanjmerono**

### CODE REVIEW

**Comment by juanjmerono** [comment]
You don't have to trust me, you can see the screenshot added in jira, or this one :)
image

**Comment by adrianfish** [comment]
Cuidado! Have you done the headers for Site Visits and Last visit time?
I've just added that functionality.

**Comment by juanjmerono** [comment]
Good catch Adrian !! I'm afraid no !! I've added the roster.showVisits=true property but I'm not seeing any extra info. Can you show me how to test this new columns properly?

**Comment by adrianfish** [comment]
You have to rebuild sitestats to get the new api, and there is also a new
permission that you need to set, roster.viewVisits (I think).

**Comment by buckett** [comment]
Should that permission be set in default authz templates?

Should there be a migration script for 11 to add the permissions to some
existing roles?

-- 
  Matthew Buckett

**Comment by juanjmerono** [comment]
I've added the SiteStats tool to the site, and granted the permission "roster.viewsitevisits" to instructor role. Then I've connected as student and after that as instructor and then the roster doesn't show the list and the log show me this error:
```
Caused by: java.lang.NullPointerException
	at org.sakaiproject.roster.tool.entityprovider.RosterSiteEntityProvider.getMembership(RosterSiteEntityProvider.java:191)
	... 42 more
```
Looking at the line:
https://github.com/sakaiproject/sakai/blob/master/roster2/src/java/org/sakaiproject/roster/tool/entityprovider/RosterSiteEntityProvider.java#L191

It seems like if there are users in the list without any visit lastvisit returns null, make sense?

**Comment by adrianfish** [comment]
You're right. I couldn't get hibernate to create a non null column for that
value, for some reason. I'll raise a ticket and fix that. I'll also do what
Matthew suggests - get the default perms for maintain updated so they can
see the visits.

**Comment by juanjmerono** [comment]
Thanks Adrian, I've tested with the new column headers and it works as expected !!

**Pull request merged**
