### PR TITLE
SAK-30278 move to webjars for jquery, jquery-ui, jquery-migrate,dropzone, ckeditor, pnotify, blockUI

### PR DESCRIPTION
**Pull request by ottenhoff**
This sure makes updating JS dependencies a lot cleaner ..........

This is not fully tested, but I wanted to get it out there for review and comments before going too far down this road.

CC: @buckett

### CODE REVIEW

**Comment by buckett** [comment]
Look sensible to me. I don't know much about the CKEditor plugins as they have been shuffled about (and upgraded?). In a quick test it all seems to work for me.

**Comment by buckett** [comment]
You can see a simple rewrite in: https://github.com/sakaiproject/sakai/compare/master...buckett:SAK-29063?expand=1

**Comment by ottenhoff** [comment]
Very cool. Thanks for the rewrite pointer. I can add another PR for rewrites ..... 

Any comments before this gets merged?

**Comment by buckett** [comment]
LGTM.

**Comment by steveswinsburg** [comment]
Looks like drag and drop might be broken:
`document.querySelector(...) is null`

**Comment by ottenhoff** [comment]
Drag and drop in Resources? I can't replicate any issues on my local or on trunk-mysql nightly.

**Comment by ern** [comment]
Hi Steve,
Yeah I am aware of that issue in dropbox.

On my list https://jira.sakaiproject.org/browse/SAK-30341 <https://jira.sakaiproject.org/browse/SAK-30341>

**Pull request merged**
