### PR TITLE
LSNBLDR-815: Fixed display of unordered lists in rich-text blocks

### PR DESCRIPTION
**Pull request by hornersa**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Reverses #4458

**Comment by hornersa** [comment]
I think we might be able to achieve a fix for both LSNBLDR-769 and -815 if we qualify the ul class in the two instances of the selector ".split ul" in Simplepagetool.css, such that the selector is revised to ".split ul.mainList".

**Comment by hornersa** [comment]
I've updated my LSNBLDR-815 branch to accommodate the display of unordered lists across two columns, and it does so by changing the ".split ul" selector to ".split ul.mainList". Furthermore, I've added padding and margin to the bottom of unordered lists in Lessons; otherwise, paragraphs following those lists would not have enough whitespace separating the two.

For what it's worth, the list-style-type such for the unordered list displayed on the Lessons page does not match the display of the same list in CKEditor. This seems to be due to the nesting of user-contributed lists within the ul.mainList predefined by the Lessons tool. Because the setting of list-style-type is deferred to the browser, there doesn't seem to be an elegant way to establish true WYSIWYG with respect to these lists in Lessons. I'm wondering if rewriting the Lessons page HTML to use div elements instead of ul and li for representing page items would be a better approach long-term. (Maybe a Sakai 13 project?)

**Comment by hornersa** [comment]
Is there a compelling reason to keep the ul.mainList and li elements as ul and li instead of using div? Using div for page items seems like we can make the styling rich-text blocks in Lessons more consistent with other Sakai tools.

With some cursory experimentation, I'm observing that this swap could happen more easily than I previously expected. I've update my LSNBLDR-815 branch to reflect this change, though I wouldn't be surprised if I overlooked something.

**Comment by hornersa** [comment]
My latest commit repairs the add and delete item actions associated with each item and fixes the add button at the bottom of a section/column. All the repairs needed in this commit are in show-page.js.

**Comment by hornersa** [comment]
Apparently there were a bunch of revisions in show-page.js that also needed to be made for each of the kinds of items to edit (via the pencil icon). I've since tested an edit of each kind of item (as listed in the "add content" drop down), and my code revisions now committed to this branch seem to handle the behavior of each kind of edit correctly. Sorry for the overlooking that.

**Comment by hornersa** [comment]
Earle and Sam, thanks for tracking and reviewing this PR.

**Pull request merged**
