### PR TITLE
SAK-40515 Revert "SAK-40381: Lessons - Add Resources Folder with a sites with UTF-8 characters is shown wrong (#5843)"

### PR DESCRIPTION
**Pull request by ottenhoff**
This reverts commit 999fd9d16dbc51d911c4574239e15714da4e9e3d.

CC: @jesusmmp @mpellicer

### CODE REVIEW

**Comment by mpellicer** [comment]
HI @ottenhoff, I've tested this in one of my instances:
Before:
image

After reverting:
image

**Comment by mpellicer** [comment]
Unfortunately, after reverting the patch, if the folder name contains utf-8 characters it doesn't work:
a

b

**Comment by ottenhoff** [comment]
Yes, this reverts because I believe SAK-40515 is worse than SAK-40381.

I'd like to see the original developer propose a better fix. If that's not possible, I can work on a better solution to SAK-40381 next week.

**Comment by mpellicer** [comment]
Totally agree, I'm gonna approve this and it affects 12.x.

**Pull request merged**
