### PR TITLE
SAK-32569 - Stealth gradebook for Sakai 12

### PR DESCRIPTION
**Pull request by jonespm**
(stealth)

### CODE REVIEW

**Comment by jonespm** [comment]
@ern suggested that rather than removing the categories here we add this to a default stealthTools@org.sakaiproject.tool.api.ActiveToolManager in kernel.properties. It looks like that used to have a default set but hasn't since 10.0 in SAK-21170. Any opinion on that one?

**Comment by jonespm** [comment]
Advantage of the default stealthProperty is that it's a little easier to change, but if people are stealthing things locally they need to know to update this for 12 (if they want to get rid of gradebook). The categories *used* to be hard to alter but not so bad anymore after KNL-1031 (but not always an obvious property to change).

**Comment by ern** [comment]
Yeah I prefer stealthTools since its easy to change a property where most won't know to update the tool registration.

**Comment by buckett** [comment]
I generally prefer that we don't have default properties as people upgrading may have set the value of a property and then don't see changes on upgrade. We for example already have `stealthTools@org.sakaiproject.tool.api.ActiveToolManager` set so wouldn't see this change.

**Comment by jonespm** [comment]
Yeah, there's already a lot of properties set in kernel.properties. I think any way we stealthed/disabled that currently exists or might be developed it would be a documentation issue for how to re-nable it. (if someone wanted) stealthTools has been in Sakai since the beginning so at least that should be somewhat"well known"

**Pull request merged**
