### PR TITLE
SAK-40585 remove lots of unnecessary and maybe conflicting caching headers

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
I fear that your desire for the perfect solution here is too far of a reach.

**Comment by ern** [comment]
I agree with you, but it doesn't mean it shouldn't be stated!!!

I agree with the cleanup in the PR,  I am sure many of the headers are not needed...
Also this doesn't address adding duplicate headers by portal? Is that a separate PR?

**Comment by ottenhoff** [comment]
It does address duplicate cache- control added by the portal

**Comment by mpellicer** [comment]
Looks like new commits introduced merge conflicts :(

**Comment by ern** [comment]
Closing per Core Team call 10/09/2018

**Pull request closed without merging**
