### PR TITLE
[SAK-29391] Updated resource upload instructions

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Please wait for grammar changes.........

**Comment by ottenhoff** [comment]
Notes: I don't recommend discussing WebDAV in this context. It's too complicated.

I'm also not sure this is the right place to tell the instructor about their copyright responsibilities..... but I could be convinced otherwise.


Files can be uploaded individually or in ZIP archives. Expand ZIPs after uploading via the file''s Action menu. To remove files before completing the upload, click X next to them. Click <strong>Upload Files Now</strong> when ready to complete the upload. Note that you cannot upload more than {0} MB of material at once.

**Comment by lardo-de-arnaud** [comment]
The reason we added the copyright notice to the drag and drop upload page was so that we, as owners of the VLE/LMS service could not be accused of not informing users of their responsibilities. 

There's a notice on the "upload files" pages (where you can upload single or multiple files) so therefore it should also be on the drag and drop upload page (where you can upload single or multiple files).

Both pages perform the same function so if "warning text" appears in one place, it should also appear in the other. I hope this is a convincing argument.

I have no disagreement about skipping the webDAV text.

I'm also happy with the proposed changes to the "ZIP text"

**Comment by ottenhoff** [comment]
> There's a notice on the "upload files" pages (where you can upload single or 
> multiple files) so therefore it should also be on the drag and drop upload page 
> (where you can upload single or multiple files).

Okay, I agree with you.

> Both pages perform the same function so if "warning text" appears in one place, 
> it should also appear in the other. I hope this is a convincing argument.

Agreed

> I'm also happy with the proposed changes to the "ZIP text"

Okay, cool, @adrianfish can you update this PR and then we can merge

**Comment by adrianfish** [comment]
Will do. Tonight, or this afternoon in US time.

**Pull request merged**
