### PR TITLE
Another round of NYU morpheus changes

### PR DESCRIPTION
**Pull request by payten**
This PR delivers the following JIRAs:
- https://jira.sakaiproject.org/browse/SAK-32443
- https://jira.sakaiproject.org/browse/SAK-32414
- https://jira.sakaiproject.org/browse/SAK-32430
- https://jira.sakaiproject.org/browse/SAK-32431
- https://jira.sakaiproject.org/browse/SAK-32420
- https://jira.sakaiproject.org/browse/SAK-32433
- https://jira.sakaiproject.org/browse/SAK-32418

### CODE REVIEW

**Comment by ottenhoff** [comment]
@payten any chance you can resolve these conflicts in syllabus real quickly so we can merge?

**Comment by payten** [comment]
Yep, sure thing @ottenhoff.  I just had a quick go but was unable to test the merge locally as viewing existing and adding new items seems to be broken in Syllabus? This problem seems to be happening on nightly too: https://trunk-mysql.nightly.sakaiproject.org/portal/site/ec659311-5d34-410a-acc0-8aedd3871dd4/tool/64e72248-847f-4e9a-a3d5-c72e93362570.  I'll be able to look into in more depth on Tuesday (long weekend here in Australia 🏖 ).

**Comment by jonespm** [comment]
Yeah, there were 3 changes in the last few days against syllabus. I'd guess one of those is causing this problem. I can look this bug at least on Monday so you can fix this up for Tuesday. Regular weekend here.

**Comment by payten** [comment]
Hi @jonespm.  Thanks to @marktriggs for doing some long weekend sleuthing, syllabus is back on track!  I've rebased the branch and bits seem to be happy.

**Pull request merged**
