### PR TITLE
SAK-31199 Add versions to plugins to make Maven happy

### PR DESCRIPTION
**Pull request by steveswinsburg**

### CODE REVIEW

**Comment by ern** [comment]
You can change the versions in the pluginManangement section.

**Comment by steveswinsburg** [comment]
The versions are in there - problem persists.

**Comment by jonespm** [comment]
Yeah, but they do differ from what's in the pluginManagement section wrt version and I'm not seeing this problem on nightly. It seems like from these issues that it was fixed in newer versions of Maven?

**Comment by ern** [comment]
Steve have you read this (from http://maven.apache.org/plugins/maven-site-plugin/maven-3.html#Version_Resolution)
When used with Maven 3, a report plugin version can be empty (like build plugins).

The following order/strategy will be used to find/resolve a version:

search the same groupId/artifactId in the build.plugins section
search the same groupId/artifactId in the build.pluginManagement.plugins section
resolve with current repositories (can include automatic SNAPSHOT resolution)
Notice that Maven 3.0.x reports a misleading warning in case of empty report plugin version: see MNG-5477, fixed in Maven 3.1.0.

**Comment by steveswinsburg** [comment]
I think the computer I was on was 3.0.5. I am on 3.2.3 and the problem doesn't exist. Will close.

**Pull request closed without merging**
