### PR TITLE
SAK-50642 resources Ensure group reference for permissions is valid

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-50642

### CODE REVIEW

**Comment by adrianfish** [comment]
this doesn't work on nested folders. In realms, only one /content/group/SITE_ID realm is ever created, no matter how many nested folders you create. I thought permissions used to be handled by the permissions helper, ie: using standard realm references. So, how did we handle nested folder permissions? Did they always inherit the top level permissions?

**Comment by ottenhoff** [comment]
> I thought permissions used to be handled by the permissions helper, ie: using standard realm references. So, how did we handle nested folder permissions? Did they always inherit the top level permissions?

In Sakai 22, permissions helper will create a new realm for the folder e.g., /content/group/SITE_ID/Folder Name/

Did you take a look at my PR for this issue? I added you as a reviewer last night

**Comment by adrianfish** [comment]
@ottenhoff Sorry, I think there've been some crossed wires here. Earle asked me to take a look at the SAK last night so I thought you'd hit the buffers on it.

**Comment by adrianfish** [comment]
So the permissions helper used to auto create these realms, on the fly? That I did not know. So your PR is adding that auto provisioning back in?

**Comment by ottenhoff** [comment]
Yeah, here is 22.x code:

https://github.com/sakaiproject/sakai/blob/a50900ee2e38ee8a7933307c79985bdc64b56320/admin-tools/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java#L279

**Pull request closed without merging**
