### PR TITLE
SAK-29598 - Add more templates to CK Editor

### PR DESCRIPTION
**Pull request by mcarropellicer**
Add more templates to CK Editor

### CODE REVIEW

**Comment by ern** [comment]
When the ckeditor is updated it could potentially lose these changes it would be better if this was added and loaded from `<source>/reference/library/src/webapp/editor/ckextraplugins`

**Comment by mcarropellicer** [comment]
New version of the pull request, overwrites the default configuration with a custom one.

With this implementation, we will not lose the new templates if we upgrade the CK Editor.

**Comment by ottenhoff** [comment]
I see changes made to autosave_saveDetectionSelectors in ckeditor.launch.js. Are those changes relevant to this PR?

**Comment by mcarropellicer** [comment]
Hi @ottenhoff , the only change there is that i needed to add a comma at the end of the line to separate the configuration values.

Miguel

**Comment by ottenhoff** [comment]
Okay, I see. Thanks.

Can you set the ckextraplugins directory as a variable so it can be re-used?

CKEDITOR.basePath.substr(0, CKEDITOR.basePath.indexOf("ckeditor/"))+"ckextraplugins/

**Comment by mcarropellicer** [comment]
Thanks @ottenhoff, neater code available.

**Pull request merged**
