### PR TITLE
SAK-23873 - Problem with site manage quoting

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by buckett** [comment]
Works for me locally.

What's really bad here is that there's nothing in the logs and there's no way to do a tool reset because there's no portal code displayed.

**Comment by ottenhoff** [comment]
Nice find. LGTM

**Comment by ottenhoff** [comment]
It looks to me like portal buffers code and prob scans for presence of HTML head tags.... so the HTML head tag in JS in site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm causes confusion?

**Comment by buckett** [comment]
Merged to get site-info back working again.

**Comment by jonespm** [comment]
Thanks, rebuilding trunk now.

**Pull request merged**
