### PR TITLE
KNL-1343 upgrade spring dependencies from 3.2.3.RELEASE to 3.2.13.RELEASE

### PR DESCRIPTION
**Pull request by ottenhoff**
http://docs.spring.io/spring/docs/3.2.x/changelog.txt

### CODE REVIEW

**Comment by ottenhoff** [comment]
@ern this Spring upgrade seem okay to you?

**Comment by jonespm** [comment]
Travis is failing on [ERROR] Failed to execute goal on project sakai-login-tool: Could not resolve dependencies for project org.sakaiproject.login:sakai-login-tool:war:11-SNAPSHOT: The following artifacts could not be resolved: org.springframework.security:spring-security-core:jar:3.2.13.RELEASE.

I don't see this artifact after 3.2.7? http://projects.spring.io/spring-security/

I guess this will need a separate version in the master from sakai.spring.version.

**Comment by ottenhoff** [comment]
Thanks @jonespm . I modified, rebased, and pushed the new commit.

**Comment by ern** [comment]
looks good

**Pull request merged**
