### PR TITLE
KNL-1582 ContentService: Date, Instant => NullPointerException

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by axxter99** [comment]
@buckett ?

**Comment by axxter99** [comment]
#5045

**Comment by axxter99** [comment]
#5045

**Comment by jonespm** [comment]
Feels like we should be [using more Optional](http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html) nowadays than returning null's but this seems fine to me.

**Pull request merged**
