### PR TITLE
SAK-46687 Show a confirmation window when saving a submission as draft

### PR DESCRIPTION
**Pull request by josecebe**

### CODE REVIEW

**Comment by josecebe** [comment]
This will be the result:

SAK-46687

**Comment by ottenhoff** [comment]
This seems well-coded, but I'm -1 on the feature right now. Too many clicks is a primary criticism we receive. This feature adds more clicks to perform an existing action.

**Comment by bjones86** [comment]
I agree with Sam here. Can it just be an instruction message on the page?

**Comment by mpellicer** [comment]
@vacercon Any comments on this? Is an instruction message enough? I'm with @bjones86 and @ottenhoff about the extra clicks.

**Comment by vacercon** [comment]
The draft is only seen by the teacher after the assignment is completed. Therefore it is not an error. A similar behavior occurs with the assessment in progress.
Therefore we have changed our mind and no change is necessary.

**Pull request closed without merging**
