### PR TITLE
S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - Master

### PR DESCRIPTION
**Pull request by JuanDavid102**

### CODE REVIEW

**Comment by mpellicer** [comment]
This is missing many commits right?

**Comment by JuanDavid102** [comment]
I squash all of them into one

**Comment by mpellicer** [comment]
> I squash all of them into one

I don't see these commits:
https://github.com/sakaiproject/sakai/commit/71c1550963dc38cfe8ee8615d1c0696003df360e
https://github.com/sakaiproject/sakai/commit/b4b10021c69d7e24675e751d952c02d30aaf2471

**Review by mpellicer — CHANGES_REQUESTED** [review]
I don't see some commits applied, I don't see this one either.

https://github.com/sakaiproject/sakai/commit/d9358f4901eabf41882a9adc1c8f28ca68840143

**Comment by JuanDavid102** [comment]
I think that is because some commits after change that again

**Comment by mpellicer** [comment]
And this one
https://github.com/sakaiproject/sakai/commit/a97705d179b3ce363998f6472b2fd3cc1afab5f0

**Comment by JuanDavid102** [comment]
Now it should have all the changes of the commits related to s2u-39

**Comment by mpellicer** [comment]
Are you sure of all of this? Remember that this jira got many reviews and corrective PRs, I just want to grab all the hard work we done!

**Comment by mpellicer** [comment]
This is missing the conversion scripts PR, we have to copy the work done here
https://github.com/sakaiproject/sakai-reference/tree/master/docs/conversion/s2u_features

to the sakai_24 scripts.

**Comment by JuanDavid102** [comment]
The sakai-reference is: https://github.com/sakaiproject/sakai-reference/pull/226

**Review by mpellicer — APPROVED** [review]
Thank you very much!

**Pull request merged**
