### PR TITLE
SAK-29542 - Accessibility issues with Sitestats design

### PR DESCRIPTION
**Pull request by mcarropellicer**
Accessibility issues with Sitestats design

### CODE REVIEW

**Comment by SedueRey** [comment]
Sorry, but **no.**

We can't do it that way to apply the background-color to a tool. If we change the background-color to #F8F8F8 we ABSOLUTELY LOSE all customize options. 

If any member of community tries to change background color to another, #F8F8F8 would always be shown.

I've take a quick look to tool and it would be fixed adding "portletBody" class to a tool container (I've done the same in Samigo with same problem in https://github.com/sakaiproject/sakai/pull/670 )

**Comment by buckett** [comment]
@SedueRey In the longer term do you think it's worth having a better CSS class to use for instances like this, rather than having people use a "portal" CSS class?

**Comment by mcarropellicer** [comment]
Thanks for the feedback Eduardo! 

If you prefer i can work on it applying the same solution to Samigo... anyways the tool now is much better than the current :D

**Comment by SedueRey** [comment]
@buckett yes, sure, I think we should have proper class names for this, something like "tool-container" or something like that. Anyway, since we haven't iframes anymore, tools are *inside* portal so using a "portal" class is not wrong. We can add CSS classes to make them more *developer-friendly*

@mcarropellicer ok, if you need anything just tell me.

**Comment by mcarropellicer** [comment]
Thanks @SedueRey, changes done.

I've tested the tool and looks fine again!

**Comment by SedueRey** [comment]
Thanks Miguel, but you changed a lot of lines due to spaces or tabs rather than changing only the lines to add the new divs.

On the other hand, you can get the same result adding the css class to the existing div and avoid adding extra divs to the code.

**Comment by SedueRey** [comment]
I've added on Samigo an extra div because on inner div samigo puts the background color user had picked, it was the only way to get default sakai tool color outside samigo's chosen color by user.

**Comment by mcarropellicer** [comment]
So many lines because i've fixed the indentation.

Will generate a new patch with the suggestions.

**Comment by juanjmerono** [comment]
I guess you already know them, but some tips about PR were included on  https://github.com/sakaiproject/sakai/blob/master/CONTRIBUTING.md#pull-requests

Thank you so much Miguel !!

**Comment by mcarropellicer** [comment]
Cleaner patch.

I think some pages require some extra DIVs, that's why i've added them.

Regards

**Comment by mcarropellicer** [comment]
Thank you @juanjmerono

**Pull request merged**
