### PR TITLE
KNL-1566 CREATE TABLE SAKAI_USER ( ...CREATEDON DateStamp

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by axxter99** [comment]
@buckett ?

**Comment by steveswinsburg** [comment]
Since the data type is changing I think we will want a conversion script as well

**Comment by axxter99** [comment]
ALTER TABLE SAKAI_USER 
CHANGE
  MODIFIEDON  MODIFIEDON  DATETIME NOT NULL;
?

**Comment by axxter99** [comment]
https://github.com/sakaiproject/sakai-reference/pull/9

**Pull request merged**
