### PR TITLE
LSNBLDR-864 Remove use of synoptic announcements days from the past f…

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**
…rom the announcements entity broker code.

### CODE REVIEW

**Comment by jonespm** [comment]
It looks like everything in the 
` 		if(synopticTc != null){		
`
Should be removed. Leaving some stuff in here as a special case for synoptic doesn't seem like a good idea since it could partially work and partially break. Does synoptic tool call this? The best case might be to add more methods and have this getAnnouncements call take these values (numberOfAnnouncements numberOfDaysInThePast) as method parameters.

**Comment by jonespm** [comment]
As the easiest instead of using a tool detection

` 			synopticTc = site.getToolForCommonId("sakai.synoptic.announcement");		
`
Maybe just have a new parameter on the method like "useSynopticConfig" (default to false). Then you'll get your values you want without removing this code. A lot of this code should probably be refactored down to the service.

**Comment by steveswinsburg** [comment]
The Announcements tool has two parameters, number of announcements and number of days in the past. This provider was added with both of those features so that people using the provider endpoint could get at that same flexibility and behaviour. It's also now technically API.

The original ticket LSNBLDR-864 mentions the Lesson Builder widget. By all means don't use that param if not desired, or set it to something really high in the web service call so its effectively ignored. But the days in the past value does (at least originally) match the synoptic tool behaviour.

If the 'days in the past' is going away from the synoptic tool then by all means remove it from the provider code.

**Comment by ern** [comment]
Closing due to inactivity to address comments.

**Pull request closed without merging**
