### PR TITLE
SAK-33521 - Import grades doesn't work with locales that use comma as decimal separator

### PR DESCRIPTION
**Pull request by mpellicer**
Import grades doesn't work with locales that use comma as decimal separator

### CODE REVIEW

**Comment by ottenhoff** [comment]
Is there a junit test we can add here so we don't ruin non-USA importing again?

**Comment by mpellicer** [comment]
To be honest, the application and all the tests are done using the point as decimal separator, this will require more changes in the tool and the tests, this is a more complex piece of work.

IMHO, the optimal solution is the ability to choose the CSV separator in the UI and detect the separator in the backend based on the user's locale. I'll ask some Spanish institutions if they are really interested in having this. We can leave this PR as is, the gradebookService requires the user's separator to store the value.

**Comment by ottenhoff** [comment]
@payten should this be merged?

**Comment by payten** [comment]
I'm a little confused at the use of `FormatHelper.formatGradeForDisplay` in this context; this helper method was intended for converting values from the root locale to the user's locale for display in the UI.  Does that mean that the imported spreadsheet is expected to be using the root locale and '.' as a decimal; this would convert the value to the user's locale and the gradebook service would then be happy?

Or is the importer sneakily converting values to the root locale? @steveswinsburg would know!

If the grade values in the spreadsheet had ',' decimals, I think `FormatHelper.formatGradeFromUserLocale` would be suitable to clean up the value for the service.  That's how the UI currently prepares grades for the service.

**Comment by sinmsinm** [comment]
I've tested the PR at sakai-trunk.atica.um.es. I've executed the test plan and all works as described. It works.

**Comment by payten** [comment]
Yep, I can see it works when the CSV import has grades entered in the root locale ('.' for decimals).  I was assuming that users would enter the grades in the CSV as they would in the UI -- in their preferred locale.  With this patch, if my sakai user locale is Spanish and my CSV import file is the same, then an imported grade with value `9,5` would be converted to `95`, `9,32` becomes `932` and `1.000,52` becomes `1.00`.  That said, if my assumption is wrong then this patch will do the job!

**Comment by mpellicer** [comment]
Hi @payten, 
I agree with you, now the CSV will be exported using the correct locale separator and the decimal separator.

English: Comma for values and dot for decimals.
Spanish: Semicolon for values and comma for separators.

The import process will work in the same way. Some members of the Spanish group will test it in our nightly instance sakai-trunk.atica.um.es

Regards, Miguel

**Comment by mpellicer** [comment]
Some tests are failing, I'm repairing them.

**Comment by mpellicer** [comment]
Tests fixed!

**Comment by mpellicer** [comment]
I'm sorry @ottenhoff , I've tested using both locales and worked fine for me.

Let me re-test again.

**Comment by mpellicer** [comment]
I've found a stupid bug in the separator comparison, fixed it and rebased the patch.

Tested in en_US and es_ES, works fine for both formats using different separators for decimals and CSV files.

**Comment by ottenhoff** [comment]
Sorry to ask for more here, but can you add one test to TestImportGradesHelper.java so we make sure that semi-colon importing does not get broken in the future?

**Comment by mpellicer** [comment]
@ottenhoff no worries! I agree it's much better to have tests here.

PR updated with some tests and regular expression update.

**Comment by steveswinsburg** [comment]
Apologies, I've only just seen my tag from Payten. I'm in this area now so
I'll test it out and let you know if there is anything funky.

**Pull request merged**
