### PR TITLE
SAK-44324 only match specific old samigo function patterns instead of strToLowering all

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by profmikegreene** [comment]
W H A T A B E A S T.

Do you sleep?

**Comment by ottenhoff** [comment]
nothing beats math function debugging!

**Comment by jesusmmp** [comment]
Great @ottenhoff. I was working on a patch too. I've got some suggested changes.
Let me test this on my local instance.

**Comment by jesusmmp** [comment]
1. Update mathparser to last version - 4.4.2

https://github.com/sakaiproject/sakai/blob/master/master/pom.xml#L1994

2. Adding URLs with more information:

https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp#L213
https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp#L213

https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp#L303
https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp#L304

<li><h:outputText value="#{authorMessages.calc_question_functions}" /> <a target="_blank" href="http://mathparser.org/">http://mathparser.org/</a></li>
<li><h:outputText value="#{authorMessages.calc_question_constants}" /> <a target="_blank" href="http://mathparser.org/mxparser-tutorial/built-in-constants/">http://mathparser.org/mxparser-tutorial/built-in-constants/</a></li>

3. Properties

https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties#L123

calc_question_functions=You can use many math functions including: sin, cos, tan, asin, acos, atan, abs, exp, sgn, sqrt, log10, and ln. More information:
calc_question_constants=There are built-in constants like pi(3.14...), e(2.718...), or [phi](1.618..). Use them in your formula expression. More constants here:

4. Delete methods:
 - getfirstChar()
 - getToken()

Boths now are useless.

https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java#L215
https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java#L232

I think there are some methods into getToken that could be removed too.

5. Unescape

I think this should be something like:

String formulaStr = StringEscapeUtils.unescapeHtml4(GradingService.cleanFormula(cqcb.getText()));

https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java#L463

**Comment by ottenhoff** [comment]
1) Agree
2,3) URLs: I'm worried about the permanence of these URLs. Maybe we just add to help docs instead? 
4) Thanks. Done.
5) This feels like it should be a different JIRA. Do you have some examples that you've seen where HTML escaping causes issues?

**Comment by jesusmmp** [comment]
- 3. URLS. I don't know if is better here or on the help docs. But this information should be accesible to instructors.
- 5. If you dont' unescape all these functions don't work:

if({alea}>3, 5, 2)     [[ if({alea}>3, 5, 2) ]]
if({alea}<=3, 5, 2)    [[ if({alea}<=3, 5, 2) ]]
if({alea}<3, 5, 2)   [[ if({alea}<=3, 5, 2) ]]
if({alea}=3 && {alea2}=1, 5, 2)   [[ if({alea}<=3, 5, 2) ]]

Now, it arrives:   expr=if{alea}&gt;>3, 5, 2

e = new Expression(expr);
double d = e.calculate();

and this return NaN because e.calculate() fails.

Please test it. Thanks.

**Comment by ottenhoff** [comment]
IS this only when using the CKEditor? I don't know how to test it. Feel free to edit my PR to add a unit test .....

**Comment by jesusmmp** [comment]
@ottenhoff, I've add more things to your PR. Here: https://github.com/sakaiproject/sakai/pull/8626.

**Pull request closed without merging**
