### PR TITLE
SAK-45744 My Calendar: update Apache Wicket 8.12.0

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by mpellicer** [comment]
Nice @axxter99 !

**Comment by mpellicer** [comment]
Do you think is a good opportunity to use a common version of Wicket 9.x?

**Comment by axxter99** [comment]
@mpellicer wicket 9:
`Java version
This Wicket version requires at least the following Java version: JDK 11.0 or newer.`

**Comment by mpellicer** [comment]
Sounds perfect, thanks!

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
