### PR TITLE
SAK-32087 new UI for users to see which courses they're enrolled in

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-32087

Student's (typically, although it could happen to any type of user) often times don't know if they are enrolled in a section or course site properly or if the instructor just hasn't published it yet. This has lead to a lot of support calls in the past at our institution.

It would be highly beneficial to have a place where students can see what enrollments they have, and whether or not the enrollments are tied to existing Sakai sites. The sites will only appear to the user if the site is either published, or the user has the 'site.visit.unp' (visit unpublished sites) permission. If a given section is tied to multiple sites, each site will be listed in the last column, comma separated (provided that each site pass the previously mentioned stipulations). The site titles are rendered as links for ease of access.

The most logical place to insert this new UI is in the 'Membership' tool, which appears in every user's 'Home' space (formerly My Workspace).

We have been running this feature at Western in our production environment since late August, 2015.

This feature introduces the following sakai.property:

`membership.enrolments.blurb`

This sakai.property controls whether or not extra information is to appear before the instruction text at the top of the page (first paragraph in the screenshot). The property defaults to an empty string, so that institutions can decide if they want to provide extra information regarding their SIS integration process (or anything else), or not.

This feature supports sorting on all columns of the table, case insensitive searching/filtering, and a caching scheme (with a time to live of 5 minutes per user).

### CODE REVIEW

**Comment by bjones86** [comment]
Screenshots on the JIRA. Let me know if anyone would like to see more/different screenshots.

**Comment by ottenhoff** [comment]
This looks like a nice feature. Can you use the American spelling "Enrollment" in the default property files and then "Enrolment" in en_GB and en_CA?

If you want a background on the two spellings: http://grammarist.com/spelling/enrol-enroll/

**Comment by bjones86** [comment]
Yes, completely agreed.

**Comment by fostersdesign** [comment]
@ottenhoff, I wasn't aware that there was a en_CA language in Sakai?

**Comment by ottenhoff** [comment]
You're right, there isn't, but it's a valid Java locale so if you thought en_CA was distinct enough you could begin creating distinct property files.

**Comment by fostersdesign** [comment]
We've had requests from our local institution community members for a Canadian language option. Is there a defined process for adding a new language? Maybe I'll take this conversation offline with you.

**Comment by ottenhoff** [comment]
I'm not aware of the process. Neal or sakai-dev should be able to help. For just a few translations, I would do it by hand. For large-scale translations, I would use Transifex.

**Comment by fostersdesign** [comment]
We'd have to add something other than just translations to Sakai so that the language option shows up in User and Site Preferences, right?

**Comment by ottenhoff** [comment]
Yeah it looks like SakaiLocales.java needs a tiny edit for the user to choose the new locale

**Comment by fostersdesign** [comment]
Okay. Thanks, @ottenhoff. I'll ask Neal whether there is a formal community process to follow for adding new languages.

**Comment by bjones86** [comment]
@ottenhoff I've changed default to be 'enrollment'; en_CA and en_GB are 'enrolment'.

I'll do the work of adding en_CA as a choice for the end user in a future PR.

**Comment by bjones86** [comment]
I'm planning to merge this in by the end of the day provided there are no other comments/suggestions/etc.

**Pull request merged**
