### PR TITLE
SAK-50319 Dashboard image and text need explicit flex options

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Review by adrianfish — APPROVED** [review]
Looks fine to me, although if we're betting on bootstrap for the future it might be better using bootstrap's breakpoint and flex classes. That margin of 10px could definitely be set using a flex breakpoint. If we move to using boostrap's approach, like using mb-2 to set the bottom margin, then we will be able to theme so easily by just setting what those numbers mean in our sass build. We could define mb-2 to mean 12px or anything. That is the approach bootstrap recommend.

**Comment by ottenhoff** [comment]
Ahh I didn't even intend to bring back the margin stuff. I only care about the flex direction as that is the important one ... what was the intention of deleting the flex direction? I understand why you deleted it from the container for small devices

**Comment by adrianfish** [comment]
Not actually sure what my intention was there. It may have just been a bit of idiocy.

**Comment by ottenhoff** [comment]
okay i deleted the margin direction

**Pull request merged**
