### PR TITLE
SAK-30675 Chat - Table header formatted incorrectly

### PR DESCRIPTION
**Pull request by alejandrogj**
This also resolves SAK-30677 Chat - Padding between Start/End dates
needs to be increased

### CODE REVIEW

**Comment by SedueRey** [comment]
Hi, 
Great work indeed. Just to make it perfect, could you vertical-align the date picker icons? Thanks

**Comment by juanjmerono** [comment]
Also, could you add some padding on inputs like "Show the last[10]messages"?

**Comment by alejandrogj** [comment]
Fixed!

**Comment by SedueRey** [comment]
You're _on fire_. Looks Great!

**Pull request merged**
