### PR TITLE
LSNBLDR-609; also need to fix UI for long names

### PR DESCRIPTION
**Pull request by clhedrick**

### CODE REVIEW

**Comment by jonespm** [comment]
I believe SimplePageItemImpl also has a MAXNAME restriction to 100? (If this is applicable to the same field)

**Comment by clhedrick** [comment]
It does. However testing showed no issue. I’ll have to figure out why it worked.

On Apr 19, 2016, at 2:19 PM, Code Hugger (Matthew Jones) <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe SimplePageItemImpl also has a MAXNAME restriction to 100? (If this is applicable to the same field)

**Comment by clhedrick** [comment]
Ah. It truncates in the middle, so my tests didn’t show an issue.

The next question is what I want to happen. I maintain that huge names are a UI issue. They ran into a problem converting from Melete. If they put stuff directly into the database with a conversion tool it will work. However the next time I change it it will get abbreviated. It’s not obvious that this is incorrect behavior. The reason for the truncation is that names are sometime set to things that might get long, e.g. URLs. I didn’t think it made sense to retain that length in the UI.

On Apr 19, 2016, at 2:19 PM, Code Hugger (Matthew Jones) <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe SimplePageItemImpl also has a MAXNAME restriction to 100? (If this is applicable to the same field)

**Comment by clhedrick** [comment]
I’m going to query the person who reported it through the Jira.

On Apr 19, 2016, at 2:19 PM, Code Hugger (Matthew Jones) <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe SimplePageItemImpl also has a MAXNAME restriction to 100? (If this is applicable to the same field)

**Comment by clhedrick** [comment]
After further thought, I’m going to finish this jira allowing users to set 255 char names.

I will add a separate Jira to make sure that names I create automatically are always reasonable length. There are 3 different places I generate names, with different code to try and control length. I’ll do it in one place, with a somewhat smarter approach.

The only case where there should be an issue is if users type a long name themselves, and it doesn’t have spaces in it. I will probably check in a CSS fix so that Safari and Chrome will split long lines without spaces. This CSS does not work on Firefox or Edge. I spent several hours trying to find CSS that would work with Firefox and Edge, but failed. I could come close, but it had undesirable side effects.

On Apr 19, 2016, at 2:19 PM, Code Hugger (Matthew Jones) <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe SimplePageItemImpl also has a MAXNAME restriction to 100? (If this is applicable to the same field)

**Pull request merged**
