### PR TITLE
SAK-33534 Missing key inserting a non-number value in Categories & We…

### PR DESCRIPTION
**Pull request by josecebe**
…ighting

### CODE REVIEW

**Comment by josecebe** [comment]
Work in progress

**Comment by josecebe** [comment]
Sometimes the key can contains the component prefix and it should be removed.
Now I have two questions:
	- On each "loadStringResource()", "loader.containsKey(key)" is called before the "loadString(locale, key)" one. Is this a good way to check it? I have seen in SiteStatsApplication.java the same logic.
	- Can the "key.replace(component.getId() + ".", "")" create new issues?

**Comment by jonespm** [comment]
I merged #5129 to 11.x.

Were you still waiting on some feedback from @payten about those questions here?

**Comment by payten** [comment]
The comma-change looks good.

I can't speak to the `loadStringResource` query -- is this a weird Wicket thing? Or specific to GradebookNG?  If unique to GradebookNG, my feeling is that keys shouldn't include the component id and we should fix where that's occurring.

**Comment by josecebe** [comment]
I'm not sure about why is this occurring. But the issue is occurring when `GradebookNgStringResourceLoader` overrides IStringResourceLoader `loadStringResource` methods.

I have tested deleting `GradebookNgStringResourceLoader` and there is no issue. But this file seems to be necessary for https://jira.sakaiproject.org/browse/SAK-33038

**Comment by payten** [comment]
Thanks @josecebe, I looked a little deeper and the strange key seems to be generated by the `ConversionException` which is provided a resource key:
```
```

**Comment by steveswinsburg** [comment]
Sorry I just saw this. Adding the key that wicket suggests is the way to fix it. Wicket looks at certain component hierarchies for keys and complains if it can't find them.

For example:
````
12-Feb-2018 22:17:52.583 WARN [http-nio-8080-exec-131] org.sakaiproject.util.ResourceLoader.getString bundle 'org.sakaiproject.gradebookng.GradebookNgApplication'  missing key: 'minPercent.IConverter.Double'  from: org.sakaiproject.gradebookng.framework.GradebookNgStringResourceLoader.loadString(GradebookNgStringResourceLoader.java:46)
````

**Comment by josecebe** [comment]
Hi @steveswinsburg & @payten , I've just updated the pull request and it's ready to be merged.

**Pull request merged**
