### PR TITLE
SAK-27955 Swap out Apache James for SubethaSMTP

### PR DESCRIPTION
**Pull request by buckett**
This is a version of the inbound email processing which uses SubethaSMTP instead of Apache JAMES. It's much more lightweight, has tests and supports early rejection (at RCPT time).

### CODE REVIEW

**Comment by ottenhoff** [comment]
Okay a definite +1 for the idea and effort here.

I looked through the code briefly and it makes sense. +1 to getting this in now and making sure we test during QA process

**Comment by ottenhoff** [comment]
Ready for merge?

**Comment by csev** [comment]
I think that if Matthew thinks this is good - it should be merged and soon.

**Comment by jonespm** [comment]
Is this going to also remove the mailarchive-james folder? It seems like that's no longer used after this. Separate jira?

**Comment by jonespm** [comment]
Would probably also be *nice* if the commits were rebased

**Comment by buckett** [comment]
@jonespm I was going to leave the old implementation in so that it's easy to switch out if there are problems.

I'm squashed it down into one commit.

**Pull request merged**
