### PR TITLE
SAK-49396 Forums: cannot be cast to class org.sakaiproject.api.app.me…

### PR DESCRIPTION
**Pull request by mpellicer**
…ssageforums.DiscussionTopic

### CODE REVIEW

**Comment by ottenhoff** [comment]
I've definitely seen this exception before. What's the key fix here? I don't see it.

**Comment by mpellicer** [comment]
> I've definitely seen this exception before. What's the key fix here? I don't see it.

Unfortunatelly I don't know the culprit, this repairs the consequence but not the root cause and that's bad because the user report is super confusing :( They don't know how to reproduce it but the forums stopped working in that site, all of them.

The logic to see if has previous or next items is a bit weird and repetitive, the logic to get the previous and next items do the same iterations. There are 4 methods (hasNext, hasPrevious, getNext, getPrevious), one has a try-catch block, the other three don't and this PR adds some try-catch.

**Comment by ern** [comment]
The issue is related to how msgcntr works directly with the hibernate entities which can still be in their proxied state.
class org.sakaiproject.component.app.messageforums.dao.hibernate.TopicImpl$HibernateProxy$Ty3yjfw9
cannot be cast to class org.sakaiproject.api.app.messageforums.DiscussionTopic (org.sakaiproject.component.app.messageforums.dao.hibernate.TopicImpl$HibernateProxy$Ty3yjfw9 and org.sakaiproject.api.app.messageforums.DiscussionTopic

The HibernateProxy instances must first be unproxied before it can be cast to the DiscussionTopic. The use of proxies by Hibernate allows for it to be efficient by not fetching the data unless it is actually accessed (using the proxy), this also means there is more than one way to fix this.

**Comment by mpellicer** [comment]
Thanks for the explanation @ern, this is hard to reproduce but I still have the data so probably can work on this later today.

**Comment by mpellicer** [comment]
Done, I reproduced the issue again and the fix works fine as the other does.

**Review by ern — APPROVED** [review]

**Pull request merged**
