### PR TITLE
NOJIRA mvn license:check

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by axxter99** [comment]
https://github.com/sakaiproject/sakai/pull/11827

**Review by ern — APPROVED** [review]

**Comment by ern** [comment]
Dave I actually liked the license check to be separate from the other tasks, because then it is visible what failed the build.

**Comment by axxter99** [comment]
@ern 
87f5f68
`- name: Check wih license
      	env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: mvn --show-version --batch-mode license:check `
Run failed:
`Invalid workflow file: .github/workflows/maven.yml#L41
You have an error in your yaml syntax on line 41`

**Comment by ern** [comment]
OK so just to be sure that is the message you get when license check fails?

**Review by ottenhoff — APPROVED** [review]

**Pull request merged**
