### PR TITLE
SAK-46183 - Hibernate: Revert configuration introduced in SAK-45997 as it's breaking forums.

### PR DESCRIPTION
**Pull request by mpellicer**
https://jira.sakaiproject.org/browse/SAK-46183

### CODE REVIEW

**Review by bjones86 — CHANGES_REQUESTED** [review]
I personally don't like this fix. This was added intentionally to fix an issue where Oracle and MySQL treat nulls differently. My preferred solution to this would be to fix the query that's breaking in Forums.

If that can't be done, and this absolutely has to be reverted, then the original commit from SAK-45997 should be reintroduced to avoid the original issue: https://github.com/sakaiproject/sakai/commit/0485b48f5370d2ac924b37906e42d66232f78229

I changed it to the global pattern so that we wouldn't have to do this pattern for all Hibernate queries where this could be an issue.

**Comment by mpellicer** [comment]
No problem to discuss this Jira @bjones86, I don't know how many tools are affected by this change but something is wrong with Forums!

**Comment by ottenhoff** [comment]
Yeah Forums is not looking good. @mpellicer do you know what query is prompting the issue in Forums?

**Comment by ottenhoff** [comment]
@mpellicer any ideas on what is provoking this NPE ?

**Comment by mpellicer** [comment]
> @mpellicer any ideas on what is provoking this NPE ?

The change introduced in the Hibernate configuration is adding some 'order by' clauses which produce a MySQL and Oracle syntax errors, they are detailed in the Jira:
where topicimpl0_.ID=? order by case when case when attachment2_.CREATED is null then 1 else 0 end, attachment2_.CREATED desc is null then 1 else 0 end, case when attachment2_.CREATED is null then 1 else 0 end, attachment2_.CREATED desc

While I agree with @bjones86 that Forums queries should be fixed, I don't know the side effects of this configuration in other parts of Sakai.

**Comment by ottenhoff** [comment]
Ok so let's revert and apply 0485b48f5370d2ac924b37906e42d66232f78229 in the same PR

**Comment by bgarciaentornos** [comment]
It is also causing issues on Sitestats -> https://jira.sakaiproject.org/browse/SAK-46215

**Comment by ottenhoff** [comment]
Please see #9812

**Pull request closed without merging**
