### PR TITLE
KNL-1456 Don’t flush the cache when loading.

### PR DESCRIPTION
**Pull request by buckett**
When searching for sites the cache of fully loaded sites is replaced with sites that are partially loaded. This is because we’re searching for all the sites in the DB and replacing the values in the cache with them.

### CODE REVIEW

**Comment by buckett** [comment]
This isn't well tested but I was wondering what other people think of it.

**Comment by ern** [comment]
Hi Mathew,

I like the approach of considering whats in the cache and only loading those that aren't cached.

One thing I would probably add to your the filter is ignoring those items in the cache that are not opaque or not lazily fetched. This would hopefully eliminate any issues with lazily loaded <Site>Objects .

**Comment by buckett** [comment]
If nothing is in the cache this call results a list of Site objects that are all partially loaded (pages and groups aren't loaded).
If we exclude items in the cache that are fully loaded we're going to end up getting more from the DB and then we come back to the question of should we put them in the cache, to which I'd say no.

**Comment by ern** [comment]
Yep agree that partially load items shouldn't be cached.

**Comment by ottenhoff** [comment]
ready for merge?

**Comment by buckett** [comment]
I think there's still room for improvement so that we cache both partially and fully loaded Sites but think that this was just a bug in the original implementation that is reasonably safe to add.

**Comment by ern** [comment]
Agree that is probably a future optimization. This change is better than whats currently there.

**Pull request merged**
