### PR TITLE
SAK-32728 RemoteHostFilter should allow access to certain endpoints

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by adrianfish** [comment]
I've broken the remote host test you introduced. I'm looking at it. Getting forbiddens on the i18n requests.

Failed tests:
  RemoteHostFilterTest.testAllowRequestURI:102 expected:<200> but was:<403>
  RemoteHostFilterTest.testExplicitAllowRequest:124 expected:<200> but was:<403>

**Comment by ern** [comment]
In test class, you will need to update the Mock's that call serverConfigurationService.getString() in method configureFilter().

**Comment by ern** [comment]
Also the method getRegExPatterns might be a little specific maybe makes sense to not include that in SCS?

**Comment by jonespm** [comment]
Failed tests: 
  RemoteHostFilterTest.testAllowRequestURI:102 expected:<200> but was:<403>
  RemoteHostFilterTest.testExplicitAllowRequest:124 expected:<200> but was:<403>

**Comment by ern** [comment]
Yeah they worked previously!

**Comment by adrianfish** [comment]
@ern Sorry I'm patchy on this. I'm trying to fit it in on vacation. Like you say, the mock SCS needs setting up with the getPatternList method. I'm not sure about whether the regex method should be in SCS. Might it not be a repeated pattern in the future, to have a list of regexes?

**Pull request merged**
