### PR TITLE
SAK-45091: Some tools don't respect user notification preferences

### PR DESCRIPTION
**Pull request by jesusmmp**
This should be combined with CLOG-211 to solve notification clog problems.

### CODE REVIEW

**Review by ern — COMMENTED** [review]
@jesusmmp could you add a unit test for this method?

**Comment by jesusmmp** [comment]
> @jesusmmp could you add a unit test for this method?

Ok, I'll try adding asap.

**Comment by jesusmmp** [comment]
> @jesusmmp could you add a unit test for this method?

@ern Unit test done!

**Comment by danielmerino** [comment]
@ern are you OK with the test? We would like to get this merged. Thanks!

**Review by juanjmerono — APPROVED** [review]

**Pull request merged**
