### PR TITLE
KNL-1336 Allow no new sessions on a node.

### PR DESCRIPTION
**Pull request by buckett**
This allows a node to be marked as accepting no new sessions. This means it will continue to handle existing sessions but new requests will get redirected to the same URL without it’s existing cookie and the load balancer should try sending the request to a different node.

### CODE REVIEW

**Comment by ottenhoff** [comment]
This is interesting. My two questions:

1) Does it make any sense to modify the user's cookie with a valid node set instead of just deleting it and hoping the load-balancer will be smart?  I know some load-balancers will use a LRU algorithm which means the node going down may be the least-used node.

2) Does it make sense to use an ENUM on the database STATUS column?

**Comment by buckett** [comment]
In our local deployment the load balancer monitors the nodes and sends new sessions to the one that has the least load (but excludes ones in shutdown). Because of this we're always going to prefer having the new node decision made by the load balancer but I can see that in other cases this might be useful.

I didn't use an ENUM as it means you have to keep the DB schema and Java in sync if people add more statuses. I don't have strong feelings either way about this.

**Comment by ottenhoff** [comment]
Okay ready to merge?

**Comment by buckett** [comment]
I've updated the branch so that we use an ENUM.
I've also updated the RequestFilter so that you can ask it to redirect to another active node in the cluster instead of just removing the cookie. This is controlled by the config value `cluster.redirect.random.node` which defaults to true, meaning it will pick another node that is still active.

The filtering of nodes could be nicer in Java 8.

**Pull request merged**
