### PR TITLE
SAK-29501 Build broken due to SAK-29467 SAM-2576

### PR DESCRIPTION
**Pull request by juanjmerono**

### CODE REVIEW

**Comment by buckett** [comment]
It was in #636 that this got broken

**Comment by juanjmerono** [comment]
Yes I've added the link to the specific line in jira.
https://github.com/sakaiproject/sakai/pull/636/files#diff-b170e5c32bc9ecbc933ea27d66039fdaR84

**Comment by buckett** [comment]
Was there a reason for removing the version as master/pom.xml sets the resources plugin at 2.6 so this will downgrade it I think.

**Comment by juanjmerono** [comment]
I think there is no reason to use 2.7 here so downgrade should be fine :smile:

**Comment by buckett** [comment]
Magic, nice.

**Comment by ern** [comment]
Joda time is used in a bunch of places and it would be nice to keep these multiproject dependencies managed from one location.

**Comment by ern** [comment]
Sorry I didn't catch the erroneous update to maven-resources-plugin!

**Pull request merged**
