### PR TITLE
SAK-41117 - Email Archive: @deprecated Time => instant

### PR DESCRIPTION
**Pull request by axxter99**
@deprecated Time => instant
Lombok @Setter
commons-lang => commons-lang3

### CODE REVIEW

**Comment by mpellicer** [comment]
The changes look good to me, thanks for the work @axxter99

**Comment by adrianfish** [comment]
@mpellicer Hey Miguel, could you take another quick look at this? David's added a commit after your initial review, I think.

**Comment by axxter99** [comment]
ping @mpellicer @ern ?

**Comment by mpellicer** [comment]
Thanks @axxter99 , would you mind resolving the conflicts?

**Comment by axxter99** [comment]
@mpellicer conflicts OK

**Comment by mpellicer** [comment]
I'm sorry @axxter99, it still appears a merge conflict :(

**Pull request merged**
