### PR TITLE
SAK-30808 - Update Delegated Access to Wicket 6

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
So I've tested this quite a bit but I'm stuck pretty badly on this. The worst part is that it seems like newer versions of wicket (1.5) are doing this stateful thing where it's adding a new number to every page, where the old wicket (1.4) didn't do that.

http://stackoverflow.com/questions/8602489/delete-version-number-in-url
http://stackoverflow.com/questions/11537696/wicket-appending-weird-number

That's causing a direct break on the DropDownChoice hierarchyLevel drop boxes. There's an ajax listener there that updates the next box, but previously there was javascript on the html onchange event that would do a 
```
<select wicket:id="hierarchyLevel" onchange=" this.form.submit();"/>
```

And that seemed to work and cause the navigatorBottom to update. Now if that's left in there all of the drop down fields are cleared and the page number in the URL is incremented. I've tried a few ideas on these pages and others such as StatelessPage to get this to stop, but to no change. I think having the user fill in the drop downs and hit submit is better than *nothing* but it would be nice to have this functionality back. Maybe this is something super easy.

I didn't notice any other huge breaks with this.

**Comment by steveswinsburg** [comment]
@jonespm, have a look at GradebookNG. You'll need a page mount and one pass render. See GradebookNgApplication.java

The version number isn't the problem though, you can easily update fields based on a select box. There is code in the gbng panels/Settings* that does this.

**Comment by jonespm** [comment]
Hmm, I did a rebase and a few small updates and this looks to be working fine now. I can't find anything else wrong. I think this is good to merge.

**Comment by axxter99** [comment]
Wicket 6.22.0 -> 6.26.0

**Comment by jonespm** [comment]
Thanks @axxter99 updated poms

**Comment by axxter99** [comment]
profile2, sitestats #3938

**Pull request merged**
