### PR TITLE
SAK-40432 avoid missing items charCodeAt error

### PR DESCRIPTION
**Pull request by ottenhoff**
Not sure on approach here either ....

### CODE REVIEW

**Comment by payten** [comment]
Hi @ottenhoff, this bug might be due to something more sinister happening to the serialised grades JSON blob.  Do you have any tips on reproducing the bug? Thanks.

**Comment by ottenhoff** [comment]
No, I wasn't able to replicate. I did debug a bit on a prod instance and found that the one missing value was the very last value in a medium-sized class with 15 or so gradebook items. The last student was missing values for the very final item.

**Comment by payten** [comment]
No probs, we'll try and replicate here.  Do have the prod instance's latest commit? We'll make sure we're on the same code.

**Comment by marktriggs** [comment]
Hey @ottenhoff,

If you run this snippet in the browser console, it should dump out the packed scores plus the rowCount and columnCount values:

```
(function (text) { var start = text.indexOf('packed:'); var end = text.indexOf("\n", start); return text.substring(start, end) }($('script').text()))
```

I think that should be free of any identifying information.  If you're willing/able, could you mail me the output to mark.triggs@nyu.edu?

Thanks!
Mark

**Comment by marktriggs** [comment]
By the way, I just submitted PR #5869: if you're testing by adding larger grades, *don't* add 16384 :)

**Comment by ottenhoff** [comment]
Okay, I'm closing this one in favor of a @marktriggs solution

**Pull request closed without merging**
