### PR TITLE
SAK-32055 Site page session storage can now be controlled by property.

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by ern** [comment]
Hi Adrian, while this change is trivial it does have a significant effect of disabling what page the user was last on in a site. Trying to understand why someone would want this?

**Comment by adrianfish** [comment]
@ern If you are trying to build some community stuff in the site's homepage it may well be important to make sure it isn't hidden by always returning people to specific tools other than the home. Noodle/Pepperdine asked for this as not enough folk were engaging on the commons tool in the home page - they did some behavioural testing and identified that this was why. I thought it may as well go into master, still keeping the default behaviour. It's maybe an edge case, but the code is so light I thought it worth inclusion.

**Comment by ern** [comment]
FYI I think hidden is exaggeration here :), however I understand that they want people to return to the sites default page vs the page the user was last on. I had only asked as this feature has been around for a very long time.

**Comment by adrianfish** [comment]
No worries with you asking - I hope I didn't come across as shirty, definitely not my intention :) Both behaviours are good behaviours.

**Pull request merged**
