### PR TITLE
SAK-30396 Duplicate Site button covered by Link and Help buttons

### PR DESCRIPTION
**Pull request by nrg12**

### CODE REVIEW

**Comment by ern** [comment]
Need to provide a better title in your commit message!
Could you imagine if every commit said "Fixed Bug"!

Also looks like your github workflow is off try rebasing instead of merge.

FYI, dont close this PR just fix and force push!

**Comment by ern** [comment]
Not seeing this person in the list at http://licensing.apereo.org/

Please check the contributing readme.

**Comment by ncaidin** [comment]
All good - Nicholas Raymond Groszewski is on the list. Would be cool if we could publish github ids...

**Comment by ottenhoff** [comment]
/CC @juanjmerono any thoughts on this modification?

**Comment by SedueRey** [comment]
I need to test this, `.navIntraTool` is used all along Sakai, in almost every tool so I don't know if this change should be to a new class _ad hoc_ to this "duplicate site"

**Comment by juanjmerono** [comment]
@SedueRey you're always aware !! Thanks !!

**Comment by SedueRey** [comment]
This was fixed already modifying the link and edit buttons, https://youtu.be/WjhlucjQ6Ak (there's a moment where the two buttons dissapear in this testing, I'm going to check if it's a bug or a resize strange behaviour and create a JIRA if necessary)

**Pull request closed without merging**
