### PR TITLE
SAK-42841 - New recovered assessments tab should have a unique identi…

### PR DESCRIPTION
**Pull request by jonespm**
…fier

### CODE REVIEW

**Comment by mpellicer** [comment]
The PR is totally fine @jonespm, thank you, however, I don't think showing the IDs to instructors is good from the UX perspective, is something internal and too technical....

I'm going to approve it and let others decide.

**Comment by jonespm** [comment]
Yeah, I'm happy for the core team to talk about it, or for it even to be merged and reverted. I'm kind of against adding properties for things like this though. I was thinking it could just display if there was duplicate titles but that'd be a little more work and then the UI would be inconsistent depending on if there were or were not duplicate titles.

**Comment by fostersdesign** [comment]
I had the same concern, @mpellicer. On SAK-42841, Tiffany mentions that "other tabs in Tests & Quizzes" refer to it as "Assessment ID". I'm not sure where she is referring to.

**Comment by ottenhoff** [comment]
Samigo -> User Activity Report has a column for Assessment ID

**Comment by fostersdesign** [comment]
I agree with Tiffany that they should use the same language to refer to these ids.

**Comment by jonespm** [comment]
Okay I reworked this PR to have the same order as the user activity report and also re-use the text from user activity report.

image

**Pull request merged**
