### PR TITLE
SAK-46978 Resources: Secure access pop-up repeats text

### PR DESCRIPTION
**Pull request by V100X**
Jira: [SAK-46978](https://sakaiproject.atlassian.net/browse/SAK-46978)

Info text will show once, without a title.

Users using SR will hear: 
_more info - button - For example, temporary access to students taking assessments with images included on them._

### CODE REVIEW

**Comment by V100X** [comment]
I tried to replace the anchor, but other elements were not working as intended.
Also, I'm not sure if "button" role is the best option, since using keyboard you just need to press tab to focus ton he icon, no extra action is required to get the message.

**Comment by ottenhoff** [comment]
Does this anchor do anything when clicked? 

If not, I would argue that it shouldn't have role=button and shouldn't be an anchor either

**Comment by V100X** [comment]
I feel the same.
The way it's implemented right now has conflicts with elements different than _anchor_ and role="button".
I'll take a simpler approach.

**Comment by V100X** [comment]
Now it behaves like in Site info / Site information. But it can be focused with keyboard.

**Review by ottenhoff — APPROVED** [review]

**Pull request merged**
