### PR TITLE
SAK-47955 ORACLE Not possible to recover resources from Trash

### PR DESCRIPTION
**Pull request by jesusmmp**
https://sakaiproject.atlassian.net/browse/SAK-47955

@ottenhoff @ern This is the second regression from https://sakaiproject.atlassian.net/browse/SAK-46281
Maybe there is some other regression but I don't know it right now.

Similar solution: https://github.com/sakaiproject/sakai/pull/10869

### CODE REVIEW

**Comment by jesusmmp** [comment]
I'm thinking... 
Should I duplicate the methods in this classes: MultiSingleStorageSqlOracle and SingleStorageSqlOracle.java instead of changing the default classes?

**Comment by jesusmmp** [comment]
Changed!

**Review by mpellicer — CHANGES_REQUESTED** [review]
Could we use String.format instead?

**Comment by jesusmmp** [comment]
> Could we use String.format instead?

Changed!

**Review by mpellicer — APPROVED** [review]
Thanks @jesusmmp ! Cleaner and nicer

**Pull request merged**
