### PR TITLE
SAK-30162 Possible duplicate use of oracle sequence in sitestats

### PR DESCRIPTION
**Pull request by juanjmerono**

### CODE REVIEW

**Comment by juanjmerono** [comment]
@adrianfish Please review and merge this. I think your intention in *SAK-29546* was use a different sequence number in *SST_PRESENCE_TOTALS* table than the used in *SST_PRESENCES*. Oracle creates and uses the sequence declared in the hbm file, so in this cases is sharing the same sequence for both tables. With this fix I'm adding a new sequence (only for oracle), and using a new name in hbm for *SST_PRESENCE_TOTALS* table. Is it right?

**Comment by steveswinsburg** [comment]
FYI it's perfectly fine for multiple tables to share a sequence, if that was the intention.

**Comment by juanjmerono** [comment]
I think this wasn't on purpose because the behavior in mysql is use different sequences (both are autoincrement fields, but independently). Maybe someone wants to share the sequence here but I think it was unintentional due to a "copy&paste" issue, that's why I asked to @adrianfish to take a look.

**Comment by buckett** [comment]
Looks sensible to me. In MySQL the table is just declared as having an `AUTO_INCREMENT` primary key and this gives it a sequence without an explicit name. So thats why under MySQL the tables don't share a sequence.

**Pull request merged**
