### PR TITLE
Styling / Checkbox Updates for Import Selection Screen

### PR DESCRIPTION
**Pull request by steveswinsburg**
Delivers  #3274.

Updated a significant amount of the processing logic to make this more robust. Added a bunch of helper methods and split out bits of logic so it is easier to follow.

Added a new `GbStyleableWebMarkupContainer` that is able to emit its own styles based on a set of styles added to it. We use this pattern elsewhere so we may be able to encapsulate that as well at some stage.

Updated the zebra striping to be in pairs.

A bunch of other fixes 💛

### CODE REVIEW

**Comment by ottenhoff** [comment]
@payten should this be merged into 11.x?

**Comment by payten** [comment]
I believe so, @ottenhoff.  I'd be worried that if we skipped porting some these commits, future critical changes would be harder to back-port.

**Comment by ottenhoff** [comment]
I tried to do a bunch of 11.x GBNG merges but failed. There are huge differences between master and 11.x that are going to require expertise to reconcile.

**Comment by ottenhoff** [comment]
I need help reconciling these changes with the 11.x branch .....

**Comment by payten** [comment]
Hm yeah, it looks like there were some commits missing, and on top of it all, the order of commits is important.  @steveswinsburg, I think we might need your help and intimate knowledge of these later commits!

**Pull request merged**
