### PR TITLE
SAK-29660 - Refresh tool in the LHS page menu

### PR DESCRIPTION
**Pull request by mcarropellicer**
When in the tool, allow user to click on the "tool name" in the LHS page
menu - this would have the same effect as clicking on the reset buttons

### CODE REVIEW

**Comment by buckett** [comment]
I think you need to also drop the aria attribute as it's no longer disabled.

Also shouldn't it be the reset URL, rather than just the normal page URL? As if you're in a tool such as Site Info that remembers state you need to use the reset URL to get it back to front page.

**Comment by mcarropellicer** [comment]
@buckett indeed!

Let me work on it

**Comment by mcarropellicer** [comment]
@buckett New version of the PR provided, i think fits all cases.

Tested on the current trunk.

**Comment by ottenhoff** [comment]
What does LHS mean?

**Comment by csev** [comment]
"Left Hand Side"

**Comment by csev** [comment]
I think this is ready to merge.   We discussed it on the Morpheus call - thumbs up.

**Pull request merged**
