### PR TITLE
SAK-34373 Samigo answer is correct but score is 0

### PR DESCRIPTION
**Pull request by austin48**

### CODE REVIEW

**Comment by austin48** [comment]
I committed this patch on behalf of edtell.com

**Comment by ottenhoff** [comment]
If you're committing on behalf of another organization, you would need their permission to contribute the code.... They would need to fill out the relevant CLA

**Comment by austin48** [comment]
contributing the code for them was discussed in https://jira.sakaiproject.org/browse/SAK-34373

sorry, I'm not familiar with the CLA process.  How do I get started with that?

Or feel free to reject this PR.  - Thanks!

**Comment by ottenhoff** [comment]
https://www.apereo.org/licensing

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/DataInconsistencyException.java  1
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java  2
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakai/sakai/pullRequest?prid=4602449&bid=15445378)

**Comment by bjones86** [comment]
Also, since you're contributing on behalf of someone it would be nice to give them credit for their work:

`git commit --author="Dave Hearn <dhearn@edtell.com>" -m "SAK-34373...."`

**Comment by austin48** [comment]
Unfortunately the folks at edtell.com are not able to submit a CLA.  So where do we go from here?  How can we get this patch in?

**Comment by ottenhoff** [comment]
You can use their patch as inspiration, but you should write your own, original patch without any copying/pasting from the original.

**Pull request closed without merging**
