### PR TITLE
Sam 1263(3)

### PR DESCRIPTION
**Pull request by gillmanjc**
New updated PR for SAM-1263

### CODE REVIEW

**Comment by ern** [comment]
Hi Jaco,

Would you mind squashing these into a single commit, it looks like there should be only one.

**Comment by steveswinsburg** [comment]
This is looking much better Jaco, good work. The image now displays at the front and I can set the bounding areas and save without the error I was getting in #954.

However the main issue as you pointed out over email is that if the image is resized, the coordinates no longer match. This happens both when the instructor creates the original image, and then views the created assessment, and when the student resizes the image. In the screenshot, as an instructor I had drawn a box around the B letter exactly, but now when previewing it it is a bit smaller. I think the size display is different between both views. This should be consistent for the instructor.

Likewise for student, if I made the image bigger or smaller when taking the quiz, I wouldn't be able to get the correct area.

We also need to be able to save the coordinates in a better way, perhaps by storing the original image height and width that the instructor viewed the image at, and then performing a calculation on the % size when the student views it? WDYT?

The good news is that the other issue you mentioned of adding multiple hot spot question types to an assessment seems to be working ok, at least for me on Firefox. What were the issues you found?

Another minor issue I found is that clicking into the textbox to enter a description does not clear the text 'Enter item description' and you need to manually clear it, or the words get mixed up with the placeholder text. Can you add that as HTML5 placeholder text on the text field, instead of the current approach?


screen shot 2015-10-12 at 9 00 17 pm

**Comment by ottenhoff** [comment]
Hi Steve,

> 1. Browser resize will cause issues when a user works on different screen sizes
> than what the author used when adding the HotSpot question type with it answer coordinates. 

I don't remember ever coming across this issue in our testing. I agree it's a blocker-level issue.

> 2. I tried to add multiple HotSpot Q types per Assessment and this causes some more issues.
> Seems like the patch contribution only catered for one HotSpot Q type per Assessment.

I don't remember this limitation, but I haven't tested this code in 2+ years.

**Comment by steveswinsburg** [comment]
Any chance we can fix this by using a relative calculation combined with percentages:
http://stackoverflow.com/questions/7844399/responsive-image-map

This should fix the browser resize issue.

**Comment by ern** [comment]
Jaco many of these commits should form one logical commit can you please use rebase and squash your commits on this PR (there is no need to open a new PR).

See https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

Once you have rebased you force push to your branch and this PR is updated.

**Comment by ern** [comment]
Also when you are making changes to this branch it can be easier to just use --amend which updates the previous commit.

git add xxxxxx
git commit --amend

**Comment by steveswinsburg** [comment]
Closing this is as it was superceded by https://github.com/sakaiproject/sakai/pull/1448.

**Pull request closed without merging**
