### PR TITLE
S2U-42 SAK-49259 Card Game: Skip users with no photo

### PR DESCRIPTION
**Pull request by stetsche**
This addresses [SAK-49259](https://sakaiproject.atlassian.net/browse/SAK-49259) for [S2U-42](https://sakaiproject.atlassian.net/browse/S2U-42)

[SAK-49259]: https://sakaiproject.atlassian.net/browse/SAK-49259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[S2U-42]: https://sakaiproject.atlassian.net/browse/S2U-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by stetsche** [comment]
Closing, as this commit is already merged with #11920

**Comment by mpellicer** [comment]
So is SAK-49259 incorporated in SAK-49260 ? Resolve the Jiras with the right status please.

**Comment by stetsche** [comment]
I think they should be resolved with the PR merged to master, right?

**Comment by mpellicer** [comment]
Exactly, when we merge into 22.x it also resolves the Jira, we must make a Master PR for both. Let's do some testing before that.

**Pull request closed without merging**
