### PR TITLE
SAK-28977 add jackson libs to shared

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Do the deployed jackson JARs in BLTI need to be removed?

**Comment by ern** [comment]
I think it would be a good idea if other parts of the code could use the same library (now declared in master), but other classloaders aka webapp its not mandatory. 

Possibly if your using some spring api that relies on jackson and declared your own version of jackson you may need to do something extra.

Libraries like elasticsearch include jackson underneath their package name so no worries there.

**Comment by ottenhoff** [comment]
> I think it would be a good idea if other parts of the code could use the same 
> library (now declared in master), but other classloaders aka webapp its not mandatory.

But if you move a JAR to shared/lib, your JAR deployed in your webapp is no longer used, correct?  So shouldn't BLTI be modified to not deploy Jackson?

**Comment by ern** [comment]
See https://tomcat.apache.org/tomcat-7.0-doc/class-loader-howto.html

When a request to load a class from the web application's WebappX class loader is processed, this class loader will look in the local repositories first, instead of delegating before looking.

However, all that being said I still think it prudent to use the libs in shared first before loading your own... Will open a separate issue for that in JIRA.

**Comment by ern** [comment]
https://jira.sakaiproject.org/browse/SAK-28979

**Pull request merged**
