### PR TITLE
SAM-2586 Add Side Panel to Track Question Progress

### PR DESCRIPTION
**Pull request by master-bob**
Adds a side panel in tests, which are a single question per page, which shows test takers their progress in the test. Shows test takers what question they are on, all the other questions, which questions are answered, which questions are unanswered, and which questions are marked for review. Also allows test takers to navigate using the panel.

See PR #712 .

### CODE REVIEW

**Comment by steveswinsburg** [comment]
I commented on the original PR for this.

"The styling of the panel looks a bit odd, also those look like clickable radio buttons. Maybe need some UX input? Cool feature though."

Have you had UX input into this yet? The screenshots look the same. IIRC you posted on list saying you would get a UX review.

**Comment by ottenhoff** [comment]
I agree this is a cool feature. And I agree with Steve, let's make the styling more standard and get this in ... I'm happy to merge it in now and then work on styling. Are there any jquery UI components that make sense here?

**Comment by master-bob** [comment]
A UX survey has been sent out, final responses due by the 14th. Wilma is leading this.

**Comment by jonespm** [comment]
Okay, looks like the UX survey was overall positive. I'm going to merge this and will open a few related issues based on the feedback on that ticket, rather than leave this hanging out here.

**Comment by raulsv** [comment]
Hi!

Why is this feature only done for a single question per page?

We believe that it might be useful to add this feature also to assessments that have more than one question per page.

Our instructors believe that it might be useful to always show the track questions progress side panel. Regards, Raúl

**Comment by master-bob** [comment]
Hi @raulsv,

In order to encourage use of one question per page (which we recommend as it allows for less potential of lost work - i.e. if something goes wrong a student would lose at most one question of work), we only developed this feature for a single question per page.

**Pull request merged**
