### PR TITLE
SAK-31539 fix context-sensitive help links

### PR DESCRIPTION
**Pull request by ottenhoff**
Main changes are in the sakai_toc.xml towards bottom of diffs

### CODE REVIEW

**Comment by jonespm** [comment]
This seems like it would get overwritten by the help export right? We closed a similar issue on #3814

**Comment by ottenhoff** [comment]
This code was generated by the help export!

**Comment by jonespm** [comment]
Okay, was this a refresh of the help files too? We've had this requested. The PR is too big so I can't tell. 
https://jira.sakaiproject.org/browse/SAK-32368

I think this was fixed (introduced in #1170) but overwritten during the last refresh. :/ Thanks!

**Comment by ottenhoff** [comment]
Help files have not been updated

**Pull request merged**
