### PR TITLE
KNL-1554 Refactor of time service to aid deprecation

### PR DESCRIPTION
**Pull request by buckett**
This splits out a new API called UserTimeService which is just responsible for getting the user’s timezone at the moment. This allows the main TimeService to be deprecated and any place that uses TimeService to just get the user’s timezone can switch to using UserTimeService.

This also makes the current TimeService more testable as it doesn’t actually need the whole kernel to be running, just mock instances of 2 helpers that can be easily mocked with Mockito (or similar).

This also makes the classes more focused (Single Responsibility Principal).

### CODE REVIEW

**Comment by ottenhoff** [comment]
This makes good sense to me. @ern ?

**Comment by axxter99** [comment]
public interface TimeRange ...
@deprecated ?

**Comment by ern** [comment]
@buckett what do you think about Horowitz's comment with respect to TimeRange?
Maybe bringing over the TimeRange as there is no similar concept in Java 8 time. It looks like the rest of the BasicTimeService will not be needed. This could definitely go in a new PR.

**Comment by buckett** [comment]
Yeah, at the moment I think we still still need to keep TimeRange and there isn't an obvious replacement.

**Comment by ern** [comment]
Yeah I am not advocating for its removal but rather its separation from the old service since its something we actually do need!

**Pull request merged**
