### PR TITLE
SAK-41553 Adding "To:" field in new folders created in Private Messages

### PR DESCRIPTION
**Pull request by danielmerino**

### CODE REVIEW

**Comment by mpellicer** [comment]
@danielmerino I've introduced a change in #6722 for sorting messages in folders, I'm gonna approve and merge this but I'd like you to test the sorting functionality in the sent and the custom folders. Makes sense?

**Comment by danielmerino** [comment]
@mpellicer Thanks, I will verify both PRs ASAP.

**Comment by mpellicer** [comment]
The feature I introduced in #6722 looks broken in custom folders.
image

**Comment by mpellicer** [comment]
@danielmerino See #6738

**Pull request merged**
