### PR TITLE
SAK-31672 - Term select box not working on site browser

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by buckett** [comment]
LGTM

**Comment by bjones86** [comment]
Gotta love jQuery stating they're always backwards compatible, and then removing super common stuff like `attr()`...

**Comment by jonespm** [comment]
Yeah right, it completely just doesn't work anymore. I know I've fixed a few more of these attr->prop ones.

**Comment by ern** [comment]
Same been running into the same issue with attr not working  and putting in prop.

**Comment by bjones86** [comment]
Yep, me too. So annoying, thanks jQuery...

**Pull request merged**
