### PR TITLE
SAK-30601 - Upgraded basic LTI dashboard

### PR DESCRIPTION
**Pull request by mpellicer**
Upgraded basic LTI dashboard

SAK-30601 : v0.1

- Replaced "attribution" column (Department) search field by a selector
- Some modifications based on comments from pull request

SAK-30601 : v0.2

- added search for URL and created_add columns*
- added sort by URL*
- modified LTI URL link (tool_url)
- solved some little bugs

* Now Foorm search supports 'and' and 'or' separators, and 'null' and
'date' values

Signed-off-by: Miguel Carro Pellicer <mcarro@entornosdeformacion.com>

### CODE REVIEW

**Comment by buckett** [comment]
There is some original discussion about this on a ticket that was for merge to 11.x #2071

**Comment by mcarropellicer** [comment]
@buckett So do you suggest to wait until the discussion gets concluded? Thanks Matthew!

**Comment by buckett** [comment]
This doesn't currently merge.

**Comment by mpellicer** [comment]
@buckett Rebased.

Travis failed for other reason.

**Comment by buckett** [comment]
Do you have any general concerns about making this sort of change to the LTI admin tool @csev 

I kicked of another build and it passed this time.

**Comment by csev** [comment]
This looks like a great fix - several of these things have been on my "to do list" for a while.  Is there a server where I can play with it?  Or is there a git command I can cherry pick it into my own dev instance to play with it?

**Comment by bjones86** [comment]
@csev, yes we have instructions for this @ https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup. Look for the 'Reviewing Pull Requests' section.

**Pull request merged**
