### PR TITLE
SAK-45116 Create a new Meetings tool in Sakai

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-45116

### CODE REVIEW

**Comment by bjones86** [comment]
Just curious, does this retain the git history from the old repo?

**Comment by adrianfish** [comment]
@bjones86 No, no git history. I did it that way initially, but then thought that plenty of schools would want to back port it into their older instances. So, all those commits would then need merging back into their branches. Really messy. This way it's one commit. I'd rather have kept the commits as I would have been ahead of Payten in the insights, never mind :)

**Comment by adrianfish** [comment]
The bbb-tool won't be removed from sakaicontrib, this is a reworking of that code. If anybody still wants to work on bib-tool, they're fine to do so. You can actually run bbd-tool and this new code in the same Sakai without issue. Different tables, different bundles, the works.

**Comment by bjones86** [comment]
Sounds good, thanks for clarifying.

**Pull request closed without merging**
