### PR TITLE
SAK-31932 - External Tool's Installed Tools page does not display external tools'…

### PR DESCRIPTION
**Pull request by hunt-son**
… site ids

### CODE REVIEW

**Comment by master-bob** [comment]
Is there a JIRA for this?

**Comment by hunt-son** [comment]
SAK-31932

**Comment by master-bob** [comment]
Edit the commit message to include the JIRA (and edit the PR to also include the JIRA). This is necessary so that they are automatically linked within JIRA (which is very useful after the fact).

**Comment by hunt-son** [comment]
did it work? I pushed with an amended commit message, and changed the title of the PR

**Comment by master-bob** [comment]
Yes it worked. Thanks.

**Comment by csev** [comment]
OK - I am going to merge this.

**Pull request merged**
