### PR TITLE
KNL-1489: Update antisamy library

### PR DESCRIPTION
**Pull request by juanjmerono**

### CODE REVIEW

**Comment by jonespm** [comment]
So antisamy dev seemed to mostly stop in 2013 when Google Code went away. Though looking at it there are two releases since then. One from Atlassian and one from who appears to be the original author in github. https://github.com/nahsra/antisamy (This one just had a release a few days ago and is the one updated on this ticket)

I can't tell if the issue you mention on the jira is incorporated into this version?

**Comment by jonespm** [comment]
There also looks like 50 tests in error after this change? Maybe it needs a little more work still? I'll re-run travis.

**Comment by juanjmerono** [comment]
I thought antisamy 1.5.5 was released in 2016 (https://mvnrepository.com/artifact/org.owasp.antisamy/antisamy/1.5.5). I didn't run tests but I was testing and I didn't found side effects (maybe not testing deep enough). Also it seems that 1.5.5 artifact in maven repo is not the official version  (https://github.com/nahsra/antisamy).

Test failures seems to be related, it seems not so easy to update this library, sorry.

**Comment by jonespm** [comment]
Yeah well (Dec 22, 2016) :) So technically it was 2016. I think this is worthwhile to revisit but might not be entirely ready to go yet.

**Comment by jonespm** [comment]
Well the "official" version went away in 2013 when Google Code went away. Since then there's been many people that have forked it onto github. Though this appears to be semi-official. Really OWASP has been quiet about this project because of the Java HTML Sanitizer. https://github.com/owasp/java-html-sanitizer

However the problem with that library (for us) is you have to define all of the rules in code (rather than external file like XML like we're doing) and it doesn't sanitize CSS.

**Comment by juanjmerono** [comment]
I see, it's a pity. Thanks for your comments !!

**Comment by jonespm** [comment]
It looks like all that's needed to get the tests to pass is updating xercesImpl in master. It might still be worth pushing forward with this. This is needed because nekohtml uses a newer version of xerces. 

Though rwiki, announcement, and site-manage are also using this dependency.

```
diff --git a/master/pom.xml b/master/pom.xml
index 4b1645e..517bc01 100644
--- a/master/pom.xml
+++ b/master/pom.xml
@@ -117,7 +117,7 @@
     <sakai.tika.version>1.12</sakai.tika.version>
     <sakai.tomcat.version>8.0.32</sakai.tomcat.version>
     <sakai.velocity.version>1.6.4</sakai.velocity.version>
-    <sakai.xerces.impl.version>2.6.2</sakai.xerces.impl.version>
+    <sakai.xerces.impl.version>2.11.0</sakai.xerces.impl.version>
     <sakai.xerces.api.version>2.6.2</sakai.xerces.api.version>
     <sakai.log4j.version>1.2.17</sakai.log4j.version>
     <sakai.slf4j.version>1.7.21</sakai.slf4j.version>
@@ -348,13 +348,13 @@
       <dependency>
         <groupId>xalan</groupId>
         <artifactId>xalan</artifactId>
-        <version>2.6.0</version>
+        <version>2.7.2</version>
         <scope>provided</scope>
       </dependency>
       <dependency>
         <groupId>xerces</groupId>
         <artifactId>xercesImpl</artifactId>
-        <version>2.6.2</version>
+        <version>${sakai.xerces.impl.version}</version>
         <scope>provided</scope>
       </dependency>
       <!-- common/lib -->
@@ -375,7 +375,7 @@
       <dependency>
         <groupId>xerces</groupId>
         <artifactId>xmlParserAPIs</artifactId>
-        <version>2.6.2</version>
+        <version>${sakai.xerces.api.version}</version>
       </dependency>
       <!-- block these versions if the user really wants them they will have to be specific -->
       <dependency>
```

**Comment by jonespm** [comment]
@juanjmerono I updated the changes I suggested right to your branch. I think they'll pass the tests now, but I'm not 100% sure if we want to update to this version *yet* until it gets a few more updates.

**Comment by jonespm** [comment]
Okay, tests passed, I'd like to check this out locally though.

**Comment by ottenhoff** [comment]
LGTM

**Pull request merged**
