### PR TITLE
 SAK-50378 LTI - Remove Tool Features / Rationalize DB Fields

### PR DESCRIPTION
**Pull request by csev**
This is a re-submission with the branch caught up to master after @zhuoY121 changes were merged.

### CODE REVIEW

**Review by zhuoY121 — APPROVED** [review]

**Comment by csev** [comment]
Hey @ern the merge went smoother than I expected - git is pretty smooth.   @zhuoY121 reviewed this and ran his tests against - I think it is ready for review.

**Comment by hornersa** [comment]
@csev - Note that it may be a (long) while before I can review this particular jira. (Lots of demands on my plate currently with the start of the school year, keeping an eye on runtime related issues with new Sakai 23 deployment, etc.) FYI.

**Comment by csev** [comment]
No problem @hornersa - This will get a lot of eyes.  There will of course be little things which we fix.  The longer you wait the smoother it all should be.  I tested what I thing is your use case and it works.

**Comment by bgarciaentornos** [comment]
Hi, is there a database conversion script required? We're getting error with existing 25 local instances and I'm not sure if it's related to fields that were 25-only and scripts won't be needed or if that's pending at the moment. Thanks!
image

**Pull request merged**
