### PR TITLE
SAK-31651 - Sticky header

### PR DESCRIPTION
**Pull request by fgeraci**
Might be a nice/useful addition, hello @bjones86, thoughts?

[JIRA - SAK-31651](https://jira.sakaiproject.org/browse/SAK-31651)

[Video Demo](https://goo.gl/Pjoa7A)

### CODE REVIEW

**Comment by bjones86** [comment]
I'm undecided, I think I'll defer to the UI gurus on this one.

**Comment by fgeraci** [comment]
@SedueRey @jmarianolujan hello folks, any thoughts on this UI feature? I am still undecided on whether to add it or not to our production roll out next month.

Thanks.

**Comment by SedueRey** [comment]
Sorry, I was on my holidays and I didn't read it the email. I like it, a lot. Just one concern ... what if one user has a lot of sites? (3 or 4 rows)

I think that, if this is an issue we can fix it later and figure out with UX group the best way to approach it

+1, of course

**Comment by fgeraci** [comment]
Hello Eduardo. I did the adjustments and will update the PR soon. It
handles many favorites resizing, scrolling if there is not enough room,
etc... We just roll out and got tied up woth that. This particular feature
has positive feedback.

Thanks.

**Comment by SedueRey** [comment]
Hi, I need to say that I love this feature :) 

Thanks to you

**Comment by fgeraci** [comment]
Hello @SedueRey , I updated a bit the code, which handles resizing, going back and forth form media, several sites, etc. You can see a video demo [here](http://goo.gl/Ktdl3k)
Due to the fact that a user can have as many favorites as they'd like, I decided to hide then when shrunk, since this can be easily accessed from the "sites" modal.

**Comment by SedueRey** [comment]
I like it! :) :+1:

**Comment by ern** [comment]
Yeah 👍

**Comment by jonespm** [comment]
This sounds like a feature people liked, are you able to resolve the conflict so we can merge this? How does it look in the mobile view?

**Comment by fgeraci** [comment]
sakai.rutgers.edu

Ill look into this after Jan.

**Comment by jonespm** [comment]
I see, so mobile looks unchanged now, I guess that's better than it being it not working. ;) Okay I'm good with merging this after the conflict is resolved unless you were going to update it for mobile too. Thanks!

**Comment by buckett** [comment]
PR was updated so ok to merge?

**Pull request merged**
