### PR TITLE
SAK-33330 - Signup new meeting validation error resets the dates

### PR DESCRIPTION
**Pull request by mpellicer**
Signup new meeting validation error resets the dates

### CODE REVIEW

**Comment by jonespm** [comment]
Thanks for looking at this Miguel. Does this also fix the case where they leave the location blank? I just see fixes for the title in here.

**Comment by mpellicer** [comment]
@jonespm I've tested it and yes, leaving it blank you don't lose the date, it's validated in the bean side.

I will test again in Nightly once merged.

**Comment by jonespm** [comment]
Thanks sure, it will be tested as this needs to be back to 12.

**Comment by mpellicer** [comment]
@jonespm I've verified the problem has been resolved, however i found another problem because the pull contains a small error on variable binding, i'll resolve it fast.

**Comment by mpellicer** [comment]
@jonespm The another problem is a blocker bug, resolved in this another PR #4787

I'm really sorry for the mistake 👎

**Pull request merged**
