### PR TITLE
SAK-14556 Add Ability to Equally weight Items in Category

### PR DESCRIPTION
**Pull request by master-bob**
Jira Ticket: https://jira.sakaiproject.org/browse/SAK-14556

This is a port from 2.9.3. I left it as two separate commits to easily show the backend (edu-services/gradebook-service) changes vs the front end changes (gradebook).

### CODE REVIEW

**Comment by ottenhoff** [comment]
@steveswinsburg thoughts on how to handle this considering impending GB changes?  Are you okay with the backend changes here?

**Comment by steveswinsburg** [comment]
I was discussing this with Jeff the other day. Backend changes look OK so
long as they are ignored if the settings aren't there. We won't be
supporting this in gbng just yet. But let me confirm first, we found this
feature confusing.

sent from my mobile device

**Comment by master-bob** [comment]
Currently the gradebook assumes all points are equivalent within a category. When enabled this feature would make it so all items within a category are equivalent.

Consider the following scenario. 
* Homework Category
  * Homework 1 (HW1) - 10 points possible
  * Homework 2 (HW2) - 200 points possible

Student Ted has the following scores:
* HW1 - 2 points earned
* HW2 - 200 points 

As it stands, a point earned in HW1 is equivalent to a point earned in HW2 and contributes equally to the overall category score. A point in HW1 is worth 10% (1/10 * 100) of the HW1 grade, but worth ~0.48% (1/210 * 100) of the overall category score. A point in HW2 is worth 0.5% ( 1/200 * 100) of the HW2 score, but worth 0.48% ( 1/210 * 100) of the overall category score.

He will earn an overall score of 96.19% [ (2+200) / (10+200) * 100 ].

Now, let's say the feature is enabled. Same scenario.

In this case a point earned in HW1 is NOT equivalent to a point earned in HW2. A point in HW1 is worth 10% of the HW1 score, and worth 5% [ (1 / 10) / 2 * 100 ] of the overall category score. A point in HW2 is worth 0.5% of the HW2 score, and worth 0.25% [ (1 /200) / 2 * 100 ] of the overall category score.

In this case, with the feature enabled, Ted will earn an overall score of 60% [ ( (2/10) + (200/200) ) / 2 * 100 ].


I hope that helps clear up any confusion.

**Comment by steveswinsburg** [comment]
Thanks for the info. I wonder though, since you can already set a weighting
percentage on categories, if people wanted to have separate weightings
within categories, couldn't they just make more categories?

Seems like a complex situation where a grade weighting is a percentage of
another percentage, and can be worked around.

There will be no UI for this in gradebookNG, so committing this in this
form may be premature.

Do we have any indication of the support in the community for this?

sent from my mobile device

**Comment by jeffpasch** [comment]
Great to see folks interested in the new Gradebook. 

I follow the example above, but I agree with Steve about the added level of complexity here. Jim M. from ANI (at the time) was part of the Gradebook enhancements project. We discussed this feature in GB2. He brought up the complexity here as well and noted that he received many questions from users on this, trying to figure out how a given item impacted the final grade.

It would be interesting to see what % of faculty use this. Maybe some queries on instances using GB2? It seems much more common that an instructor makes a quiz worth 50 points because they want it to have a greater impact on a student's grade than a quiz worth 10 points. So I'd vote for more user research  and ultimately user testing. It's worked well for us in developing the new Gradebook.

**Comment by jmarianolujan** [comment]
Hi everyone! For those of us using GB2, it makes sense to have this functionality in the new gradebookNG. It does not hurt. Users might be able to reproduce that way of grading by using existing functionality like creating multiple categories, adapting the points so that they weight equal... but I understand that this improvement, which is already in GB2, will give users a simple way to set equal weighted items within a category.

Thanks for the work!

**Comment by steveswinsburg** [comment]
This functionality won't be in GradebookNG. Whilst it might be in the backend (if this PR goes in), we won't be supporting it in the front end of GradebookNG. One of the goals of GradebookNG is for better usability, and whilst I understand the example given above, I think it is confusing and goes against the goals we had in mind - see Jeff's comment above re: feedback from users.

The fact that two assignments with different point values can actually be made to be worth the same is the crux of the issue. There are two workarounds to achieve the same goal: Make them equal points or make separate weighted categories. Both have pros and cons, but until we get some more community desire for this feature, and a PR for the front end, I'm going to close.

I appreciate the work involved in back porting this, good work :+1: we can always resurrect this one when the time comes.

**Comment by master-bob** [comment]
I understand that GradebookNG will be replacing GB1 in Sakai11. I just wanted to remind everyone that this PR is for merging into GB1. This is not a PR to merge into GradebookNG.

**Comment by steveswinsburg** [comment]
Correct, however they both use the same backend, and this adds a UI to the
front end of gradebook 1 which is then not present in gbng.
As above, it is questionable whether this should be in gb1 at all.

sent from my mobile device

**Pull request closed without merging**
