### PR TITLE
SAK-50605 Overview do not overwrite existing description with null

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by austin48** [comment]
This doesn't work in the case where you **want** to blank out the overview description (so that the overview display falls back to the site title).

I think the bigger question is why does the overview page get written to when you update a "web content" tool.

As a workaround we're planning to use the patch I attached in the JIRA until a better solution is found

**Comment by ottenhoff** [comment]
> This doesn't work in the case where you want to blank out the overview description (so that the overview display falls back to the site title).

Seems like a pretty odd use case! If you blank out the description, why would a normal user expect the site title to now be filled in?!

> I think the bigger question is why does the overview page get written to when you update a "web content" tool.

I assume because multiple tools use this idea of a "web portlet". It's all a very old concept in the Sakai codebase.

> As a workaround we're planning to use the patch I attached in the JIRA until a better solution is found

Your patch doesn't work for the community because we are multi-language

**Comment by austin48** [comment]
> > This doesn't work in the case where you want to blank out the overview description (so that the overview display falls back to the site title).
> 
> Seems like a pretty odd use case! If you blank out the description, why would a normal user expect the site title to now be filled in?!
> 

I suppose a normal user wouldn't expect it to default back to the title (although that is the default behavior, right?), but what if did want it to be blank? 

> > I think the bigger question is why does the overview page get written to when you update a "web content" tool.
> 
> I assume because multiple tools use this idea of a "web portlet". It's all a very old concept in the Sakai codebase.
> 
> > As a workaround we're planning to use the patch I attached in the JIRA until a better solution is found
> 
> Your patch doesn't work for the community because we are multi-language

good catch I didn't think of that.  could something else be used like the tool id, or tool registration, or tool property sakai.iframe.site.title

**Comment by ottenhoff** [comment]
> I suppose a normal user wouldn't expect it to default back to the title (although that is the default behavior, right?), but what if they did want it to be blank?

I agree. I updated the code.

**Pull request merged**
