### PR TITLE
SAK-29904 - Add maria and mysql versions into the master properties

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by ottenhoff** [comment]
LGTM

**Comment by buckett** [comment]
I think properties like these make sense for large projects like spring where there are multiple artifacts and you want them to all be in sync, but is there the same requirement for the JDBC connectors.

I'm not objecting to it, I just don't see the reason for it.

**Comment by jonespm** [comment]
@buckett The only reason I did this is because I feel we'll be updating this version often and want to keep it up-to-date (every few months). And it's easiest to have every version updated in the master pom rather than random pom in kernel (that really only we know about and others would have to search for)

**Comment by buckett** [comment]
I see, I prefer using `<dependencyManagement>` for stuff like this so that if someone else doesn't have to explicitly use our property but can just leave out the version.

**Comment by jonespm** [comment]
Yeah, I can put this into dependency management in master and get rid of the version too.

**Comment by jonespm** [comment]
Changed up commit to remove versions out of kernel and into master dependencymanagement.

**Pull request merged**
