### PR TITLE
SAK-30770 - Add extra enforcer rule for circular dependencies

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by buckett** [comment]
I've kicked off the build again because I think this would be good to have, but the travis build looked to take much longer ~25 minutes compared to the normal ~20. If it's going to add 25% to existing build times I'm not sure we should enable this by default.

**Comment by jonespm** [comment]
Maybe, Travis is really slow though. 25% extra time to my local build would only be like a minute and there have been a few builds on Travis in the past that have his >25 minutes. I'll rebuild it again and see what it says for an average.

**Comment by jonespm** [comment]
FYI: A build locally for me (skipping test) with a populated repository is
Without this: Total time: 02:18 min
With this: Total time: 02:24 min

So 6 seconds locally.

**Comment by buckett** [comment]
Thanks. Good to have this in.

**Pull request merged**
