### PR TITLE
SAK-33441 SakaiScript's addNewToolToAllWorkspaces() may not set the tool order correctly

### PR DESCRIPTION
**Pull request by austin48**
Fix for SAK-33441 addNewToolToAllWorkspaces() tool order and SAK-33428 ArrayIndexOutOfBounds

### CODE REVIEW

**Comment by ern** [comment]
Austin the name on this commit is not very informative you can do better!

**Comment by jonespm** [comment]
In kernel BaseSitePage, it looks like it already does most of this logic here (and it's safe from overwriting this variable)

Can't you just call setPosition(position) without the check? It's weird because in the method it's reversed logic from what's here . . . 

(BaseSitePage)
```
	public void setPosition(int pos)
	{
		if (m_site == null) return;
		List<SitePage> pageList = m_site.getPages();
		//KNL-250 if the position is greater than the number of pages make it last to avoid an exception
		if (pos > pageList.size()) {
			pos = pageList.size() +1;
		}
		((ResourceVector) pageList).moveTo(this, pos);
```
	
This webservice
```
                if (newPosition >= numPages) {
                    newPosition = numPages - 1;
                 }		                  
  		   
               sitePageEdit.setPosition(newPosition);
```

It seems like you should be able to pass a position into setPosition and it will work.

**Comment by austin48** [comment]
this pull request contains two fixes:

**SAK-33428 ArrayIndexOutOfBounds** which was failing despite the logic in sitePageEdit.setPosition() because it would fail when the position was equal to the number of pages.  So the fix I added was to check if the position is >= the number of pages and if so set the position to one less than the size.  I suppose you can add that check to sitePageEdit.setPosition() but I hadn't thought of that.  Plus, the original comment says "//deal with this here and just set to the number of pages - 1 so its at the bottom."

**SAK-33441 addNewToolToAllWorkspaces() tool order**  This one fixes a problem where the original code was overwritting the parameter that is passed into the function, so the positon would not be where you intended and would eventually always end up at 0

**Comment by jonespm** [comment]
Yeah, I think all of this code here is just so old in webservices (it was added back in 2009) that is just never got cleaned up. There's also 3 instances in SakaiScript of this pattern (deal with this here)that's broken, not just this one. 
In addNewPageToSiteWithPosition, addToolAndPageToSite and addNewToolToAllWorkspaces

I think we should just remove it all and fix it in setPosition. I can test it out if you don't have time for a fix to kernel.

**Comment by austin48** [comment]
You're right, it is weird that the logic is opporisite in BaseSitePage vs. in the webservice.  it's setting the position to size + 1 vs size  - 1.   perhaps if you changed the code in BaseSitePage to

`if (pos >= pageList.size()) {
    pos = pageList.size() - 1;
}`

maybe that's why the original code in the webservice was setting the position there because it was buggy in BaseSitePage?  (although it still makes me nervous to change core code if the fix in the webservice is working)

**Comment by austin48** [comment]
> I think we should just remove it all and fix it in setPosition. I can test it out if you don't have time for a fix to kernel.

If you don't mind, thanks.

**Comment by jonespm** [comment]
Yeah, well the ideal is if we changed this we'd add a new unit test test like the one in 
kernel-impl/src/test/java/org/sakaiproject/site/impl/BaseSitePageTitleTest.java

to verify there was no exception and the position was set correctly. That's ultimately the best fix. Thanks for the suggestions.

**Comment by jonespm** [comment]
I'm going to close this as it's incomplete and I'll fix it in kernel

**Comment by jonespm** [comment]
I finally got around to adding this as a kernel fix and PR on #5175

**Pull request closed without merging**
