### PR TITLE
SAK-46620 Assignments > Grades are in 14 digits precision in the export_grades_bulk_download excel file

### PR DESCRIPTION
**Pull request by mameawadiop**
https://sakaiproject.atlassian.net/browse/SAK-46620

### CODE REVIEW

**Comment by ottenhoff** [comment]
I dont understand how this solves the root issue. It's still using floating-point numbers!

Don't we need to do some rounding and formatting?

**Comment by mameawadiop** [comment]
The grade is already saved as a double with 2 digits precision.
With the method org.apache.poi.ss.usermodel.Cell.setCellValue(double value) the use of float is not necessary.

**Comment by ottenhoff** [comment]
Ahhhh, I see. thanks.

**Review by adrianfish — APPROVED** [review]
Thanks for the PR :)

**Pull request merged**
