### PR TITLE
SAK-50500 LTI rename basiclti to lti

### PR DESCRIPTION
**Pull request by csev**
This is two commits to make sure that git does not get confused w.r.t. the renames and text changes in a single commit.  **So don't **squash** these when merging to give us the best chance of tracking chances across the name changes.**

You might find it easier to review the two commits separately.  The second commit is all file *changes* - they first commit is merely renames in order to give us the best chance at history carryover.

This branch is running on dev1.sakaicloud.com is you want to test it on an actual system - this is the partner test server so clean up after yourself and don't break any one else's test setups.

This is aimed at Sakai 25.0.  We will not merge this into master until we have done some testing on the branch.   The target for merging this is 24-Sep-2024.

### CODE REVIEW

**Comment by jonespm** [comment]
I checked this out and it looks like it runs as expected. There are still a lot of "BASICLTI" references in the code which we might cleanup on a separate issue after this is merged rather than trying to fix it all here. Of these I think only 1 needs to be updated, but that's easy. 2 would be nice to have. 3 sounds like a large project. 

1) On the README.md it refers to documents like these, but it looks like these were all renamed
```
20:* [Sakai API Documentation Including API Extensions](docs/sakai_basiclti_api.md)
22:* [Configuring the Sakai External Tools Portlet](docs/sakai_basiclti_portlet.md)
24:* [Configuring the Sakai LTI Provider](docs/sakai_basiclti_provider)
26:* [Documentation for Vendors of Sakai Tools](docs/sakai_basiclti_vendor.md)
```

2) All of the variables in lti/lti-common/src/java/org/sakaiproject/lti/util/SakaiLTIUtil.java are still `BASICLTI_`

3) The tool_id is still sakai.basiclti. To rename this would require changing a **lot** of things
  * All the names in the config/localization bundles
  * All the value\ in the sitestats Events
  * Likely a database conversion 
  * A check in portal
  * The value in the help documentation which is in screensteps
  * Webservices in Sakai Script
  * Icons in the library
  * Some code in lessons would need to change to reference this like

(This might be a separate issue)
* The values in CC are called "cartridge_basiclti" link and under an imsbasiclti name space. Some of these might not need to change but some of them are wrong and maybe a different issue. It looks like in[ CC 1.3 they also dropped the "basic"](https://www.imsglobal.org/cc/ccv1p3/imscc_Overview-v1p3.html#toc-2) but it's in the for older cartridges.

Lessons has 
```
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/Ns.java
226:    resourceTypes.put("imsbasiclti_xmlv1p3", BLTI);
```
But that should be `imslticc_v1p3` for 1.3 and NS there doesn't exist. I'm not sure where else that is being used and maybe the export needs to be updated to this version? I don't remember if Sakai 100% supports IMS CC 1.3 or not, but looks like there was some support.

**Review by jonespm — APPROVED** [review]
I'll approve this as it looks like it works as it is. These changes I suggested could be done here or in another issue/pr.

**Comment by csev** [comment]
@jonespm Thanks for the review.  I will definitely do 1 and 2.  Issue 3 is very much on purpose and would be another much later JIRA - I wanted to avoid any DB conversion on this JIRA.   I don't want to fix 4 in this JIRA - lets make it another JIRA - the switch in IMS world makes things a little trickier and needs to be thought of as not just a "rename" in our code.

**Comment by ern** [comment]
this should not be merged until #12843 has been merged

**Comment by csev** [comment]
So @ern I agree to delay until after until #12843 has been merged - it is way easier to redo this (because I have scripts) than to redo that PR.  Any sense of an ETA?

**Review by ern — APPROVED** [review]

**Pull request merged**
