### PR TITLE
SAK-32722 Moved client i18n utils to use SakaiI18n webservice

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by adrianfish** [comment]
This one needs merging before #4569 and #4570. I'll refactor those two to use this new method.

**Comment by buckett** [comment]
Does this mean all deployments have to have web-services enabled?

**Comment by ern** [comment]
The Sakai18n webservice doesn't require a session.

**Comment by ern** [comment]
May need to adjust the RemoteHostFilter to always allow Sakail18n webservice (as @buckett pointed out)

**Comment by buckett** [comment]
I'm not sure that having Sakai18n in webservices is the right place. At the moment it's focused on serverside admin stuff and I think it might be cleanest to leave it that way.

**Comment by ern** [comment]
Maybe a good idea to bring this up at next core meeting?

**Comment by adrianfish** [comment]
If you need webservices allowed to get this to work, even without a session, then this is a no goer. The connection manager uses it and would be busted. Trouble is, I can't make the call on Tuesday as I'm off on holiday. Can I amend this PR with a change to RemoteHostFilter?

**Comment by adrianfish** [comment]
Maybe the i18n service should be an entity provider?

**Comment by ern** [comment]
I have a new PR to address this that updates the RemoteHostFilter.

**Comment by adrianfish** [comment]
I'm not seeing the PR. What number is it?

**Comment by ern** [comment]
I haven't submitted it just yet!

**Comment by adrianfish** [comment]
Ha! Just checking. Thought I might be missing something.

**Comment by ern** [comment]
See pull #4636

**Comment by jonespm** [comment]
I'd thought in the past about having an i18n endpoint in /direct 

I feel like if you're going to put it into webservices here (which is fine) maybe we should have both unsecured and secured webservices? Was that the idea behind #4636 just with a code rather than just creating actually two separate webapps? (like sakai-ws, sakai-ws-public).

**Comment by ern** [comment]
Yes that's the idea.

**Comment by ottenhoff** [comment]
Okay #4636 was merged. How are we proceeding on this one? @buckett and @ern?

**Pull request merged**
