### PR TITLE
SAK-29520 : Upgrade copy site

### PR DESCRIPTION
**Pull request by buckett**
Tools affected :
- Announcements
- Assignments
- Calendar
- Forums
- Syllabus
- Polls
- Wiki
- Kernel*
- Site-manage*

### CODE REVIEW

**Comment by buckett** [comment]
I need todo some more work on this as it doesn't make sense as is.

**Comment by ern** [comment]
I think this cleanup makes a lot of sense.
Have you tested this from web service calls like SakaiScript.copyContent()?

**Comment by jonespm** [comment]
This has some conflicts, but I believe that the assignment code currently isn't implemented for the new backend.

**Comment by ern** [comment]
This is a PR from a year ago closing please reopen if it gets updated.

**Pull request closed without merging**
