### PR TITLE
SAK-49848 Assignments remove Progress Bar from student view

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Can discuss on core call.

I believe T&L discussed briefly this week.

**Comment by bgarciaentornos** [comment]
In case it is finally removed, you'd also have to delete the actual macro part where it's rendered

**Comment by jesusmmp** [comment]
I think the progress bar helps than bothers.

**Comment by ottenhoff** [comment]
> I think the progress bar helps than bothers.

I don't mind it, but it's broken. Who is going to fix it? 

If no one wants to fix it, I think removing it is the obvious choice as it is just a graphical addition.

**Comment by bgarciaentornos** [comment]
As I said in the jira, we don't have a preference but hiding it via property would be the less agressive and more usual solution for similar cases

**Comment by ottenhoff** [comment]
This code has been the source of many bugs in the past and in the present. We support way too many paths and way too many ways to do things. 

I have no idea who thought of the feature and am not assigning blame. It's just a bad feature, bad implementation, bad code. Let's move on and focus on fixing bugs.

**Comment by ern** [comment]
LGTM I didn't see any other pieces to remove

**Review by ern — APPROVED** [review]

**Pull request merged**
