### PR TITLE
SAK-32651 - Passing certification suite

### PR DESCRIPTION
**Pull request by csev**

### CODE REVIEW

**Comment by csev** [comment]
@ottenhoff what should I do instead of e.printStackTrace() ?

**Comment by ottenhoff** [comment]
> @ottenhoff what should I do instead of e.printStackTrace() ?

log.error or log.warn

**Comment by csev** [comment]
Looks like we made it!

**Comment by csev** [comment]
Thanks for all your help - we passed the cert suite with Sakai 19.

**Pull request merged**
