### PR TITLE
SAK-29019 remove sakai.properties and email template for join notificati...

### PR DESCRIPTION
**Pull request by bjones86**
SAK-24423 introduced some new settings for joinable sites. One of the original features was an email notification when someone joins your site.

However, this option was rejected and ripped out of the code in KNL-1202.

Unfortunately a few things were missed, like the sakai.properties to enable the setting, the XML email template and the code to load the template.

These should be removed; no need to keep dead code/messages/files around.

### CODE REVIEW

**Comment by bjones86** [comment]
Yarg... I'm not sure why sitesetupgeneric_zh_CN.properties is showing as 806 additions, 807 deletions. All I did was delete the offending line like I did with the other message files.

I notice when I did the commit, it said 'rewrite' for the file.

Any suggestions?

**Comment by ottenhoff** [comment]
That file was updated today 2015-01-23 13:52 by Gao Jun.

I would do a fetch from upstream and do a rebase

**Comment by bjones86** [comment]
Ya, I got that update already though. Made sure to fetch upstream before I created this branch.

**Comment by bjones86** [comment]
I was able to make the changes to the zn_CH.properties file getting the massive diff, but now I'm having trouble syncing the branch because it's so far behind upstream and I'm getting massive diffs on tons of files....

So out of frustration I'm just going to close this one and open a new one.

**Pull request closed without merging**
