### PR TITLE
LSNBLDR-514 Added title to read event

### PR DESCRIPTION
**Pull request by adrianfish**
The page id and title are separated by hash (#)

### CODE REVIEW

**Comment by ottenhoff** [comment]
The only defacto standard I see in SAKAI_EVENT is comma-separated values. For example, a Samigo ref:

publishedAssessmentId=15072, assessmentGradingId=1631785

**Comment by ottenhoff** [comment]
Also are we guaranteed this entire REF will fit in less than 255 chars?

**Comment by clhedrick** [comment]
I have no objections from a lessons point of view. However if I were doing the stats integration, I wouldn't do it this way. First, titles can change, so you could have the same page showing up twice. Furthermore, sometimes it uses item.getName and sometimes page.getTitle. item.getName is from the link on the page that points to it, where page.getTitle is the title at the top of the page. These may not be the same, and ini fact that same page can be pointed to from several places, each of which could have different names in the link.

It would be an improvement to always fetch the page and use page.getTitle. At that point the only danger is if the title changes. I'd consider getting the title at display time and depend upon caching.

**Comment by clhedrick** [comment]
The ref will fit in 255 chars. It's an ID number and a title, which can't be more than 100 characters.

**Comment by buckett** [comment]
This is linked to #1254

**Comment by adrianfish** [comment]
The consensus here seems to be that the sitestats mod should pull the page title from the entity properties, that way we don't end up with a stale title. I'm just a bit obsessed about not hitting the database unless absolutely necessary, hence my approach. Let's just drop this PR and resolve the JIRA as won't fix. I'll amend the sitestats code in the linked PR to lookup the page title in entity properties.

**Comment by adrianfish** [comment]
Negating my previous comment: entities aren't returned by lessonbuilder, so, as Chuck suggested, using the LB apis at display time is the way I'll do it.

**Pull request closed without merging**
