### PR TITLE
SAK-41886 Gradebook Classic is not listed in tools to import in Site …

### PR DESCRIPTION
**Pull request by austin48**
…Info -> Import from site... if both Gradebook Classic and GradebookNG are selected to be copied, Only transfer entities for NG

### CODE REVIEW

**Comment by austin48** [comment]
Sorry, I'm not sure if this was the correct way to do it, but this is a separate PR from
https://github.com/sakaiproject/sakai/pull/7014
because _this_ one is for merging into master

**Comment by steveswinsburg** [comment]
IIRC, GradebookNG handles this internally and will not import entries that already exist (ie have been imported from the old Gradebook Classic). I don't think the logic should be in SiteManageServiceImpl.

**Comment by austin48** [comment]
@steveswinsburg
_GradebookNG handles this internally and will not import entries that already exist_

I mentioned that in https://jira.sakaiproject.org/browse/SAK-41886?focusedCommentId=243232&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-243232

however, it sounded like @ern wanted me to add the extra logic:  https://jira.sakaiproject.org/browse/SAK-41886?focusedCommentId=243348&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-243348

Please let me know if I should keep or remove the 2nd commit (SiteManageServiceImpl) from this PR

**Comment by austin48** [comment]
@steveswinsburg said in https://jira.sakaiproject.org/browse/SAK-41886

> ok yep the code in gradebook classic is where it should be. If both Gradebook Classic and GBNG importers are both aware of a gradebook existing already and being able to handle that (checking for existing items etc) then this should be fine. Site manage shouldn't need to be involved here which is where the contention is.

so I'm closing this PR since it's not needed

**Pull request closed without merging**
