### PR TITLE
SAK-39955 - Job scheduler migration job is not available in Sakai 12

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
WIP label as I haven't validated this yet with old data and the table doesn't exist at all in Sakai 12 with auto.ddl. I'm going to try to run through a conversion tomorrow.

**Comment by jonespm** [comment]
Testing this today, this isn't working yet, will have a fix in the morning.

**Comment by jonespm** [comment]
Okay tested, this is working now as expected.

**Comment by buckett** [comment]
Sorry, it was working, although we never rolled this out in production. It was however converting things in test.

**Pull request merged**
