### PR TITLE
SAK-29127 : Fix portal video chat for Morpheus

### PR DESCRIPTION
**Pull request by sinmsinm**
This branch has correct  JIRA number and just one commit with all the changes.
@csev This is the one that should be merged.

### CODE REVIEW

**Comment by csev** [comment]
Reviewing - Figured out a cool checkout command to get  a PR into a branch in your local repo for testing.

git fetch upstream pull/326/head:SAK-29127

**Comment by csev** [comment]
Tested.   Did not work on Chrome - worked on FF.  But I am going to merge this and let you tweakt it in trunk.  
sak-29127-cool

**Comment by csev** [comment]
Drat.  This would not automatically merge because it modified a deleted file.  So I hand merged it into master.   But then I got credit instead of sinsim.  Drat.

**Comment by csev** [comment]
Alex - sorry I got credit for your wonderful commit.

**Comment by jonespm** [comment]
@csev Since it was the last thing committed, it the author could be amended, but I got credit for the wonderful hand merge! Can't win them all? ;)

**Comment by csev** [comment]
I have no need for merge credit.   As long as @sinmsinm gets the original commmit credit.   Hey @sinmsinm make sure ot test on nightly - as of 3AM last night this should be on noghtly as well as all of the PDA / Neo removal.

**Comment by sinmsinm** [comment]
Tested on nigthly. Works on both. Details in JIRA.

**Pull request closed without merging**
