### PR TITLE
SAK-29147 Added this institution as copyright holder

### PR DESCRIPTION
**Pull request by adrianfish**
In the resources tool.

### CODE REVIEW

**Comment by ottenhoff** [comment]
What is stored in the database?  Is it the numerical id? If yes, this will change all existing copyright statements >= 5

**Comment by steveswinsburg** [comment]
Yes, adding this to the end rather than the middle would be good, though this highlights an issue with this particular setting and the way it is implemented, especially with the last one being the one requiring the 'below' text. People might have already added their own and then this number would conflict, ideally it would be a string ID rather than a sequential number. 

I think we would need SQL to accompany this to shift all of the numbers up, but it still not safe to run due to local customisations.

**Comment by adrianfish** [comment]
Thanks for the comments. Do you think the general idea of adding a 'this institution' copyright statement is valid? If so, I'll stick it on the end and any schools running local mods will have to update, which shouldn't be a terrible bind.

**Comment by buckett** [comment]
The type should be stored in the DB. The type is a short string that
identifies the statement.

On 11 March 2015 at 22:09, Adrian Fish <notifications@github.com> wrote:

> Thanks for the comments. Do you think the general idea of adding a 'this
> institution' copyright statement is valid? If so, I'll stick it on the end
> and any schools running local mods will have to update, which shouldn't be
> a terrible bind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sakaiproject/sakai/pull/275#issuecomment-78383501>.
>



-- 
  Matthew Buckett

**Comment by adrianfish** [comment]
@buckett Are you talking about the BINARY_ENTITY column in CONTENT_RESOURCE? I can't find any other reference to the copyright.

**Comment by buckett** [comment]
I think in the copyright is stored in the DB as a resource property. All I was meaning was that the value of the resource property isn't an integer or the license text, but a short identifying string that refers to a license.

**Comment by ottenhoff** [comment]
Immediate regression here: the Use Copyright Below is now broken ..... 

https://trunk-mysql.nightly.sakaiproject.org/portal/site/32ac8f3d-43cf-4f80-b0a9-42aa42f26ee2/tool/1a46a948-7dbe-41f4-ad15-77911fca6f5a?panel=Main

**Comment by adrianfish** [comment]
Revert it, please. I can't until tomorrow. Sorry about that.

**Pull request merged**
