### PR TITLE
Grep and check for bad unicode characters

### PR DESCRIPTION
**Pull request by ottenhoff**
The problem is that one bad translation will blow up Spring init

See https://sakaiproject.atlassian.net/browse/SAK-47085

### CODE REVIEW

**Comment by csev** [comment]
Cool

**Review by mpellicer — APPROVED** [review]
Awesome! All the translations come from a Transifex export in diff format, but the PR is created by a human so this could happen in any language, thanks Sam.

**Review by jesusmmp — APPROVED** [review]

**Comment by mpellicer** [comment]
> Agreed, any rogue character will break the translations and cause secondary effects that are very difficult to debug

@stetsche be honest, how many hours it took to understand and fix #11003  ?

**Comment by mpellicer** [comment]
I've raised https://github.com/sakaiproject/sakai/pull/11006 for testing.

**Comment by stetsche** [comment]
@mpellicer I asked you not to ask! :laughing: 10h...
@ottenhoff Nice test!

**Comment by ottenhoff** [comment]
Yes sorry about the 10h. I prob wasted 6h on it a few months ago. It was _very_ difficult to find the origin.

**Comment by stetsche** [comment]
No problem, that's not your fault! I agree it's pretty tricky to spot

**Pull request merged**
