### PR TITLE
SAK-44696 setup Github Actions for CI to replace Travis-CI

### PR DESCRIPTION
**Pull request by ottenhoff**
@ern any ideas on these build errors:

`java.lang.AssertionError: expected null, but was:<Fri Nov 20 02:42:11 UTC 2020>
	at org.sakaiproject.sitestats.test.StatsUpdateManagerTest.testSitePresencesDifferentUsers(StatsUpdateManagerTest.java:489)

Error:  Failures: 
Error:    StatsUpdateManagerTest.testSitePresencesDifferentUsers:489 expected null, but was:<Fri Nov 20 02:42:11 UTC 2020>
Error:    StatsUpdateManagerTest.testSitePresencesExistingPresence:568 expected null, but was:<Fri Nov 20 02:42:09 UTC 2020>
Error:    StatsUpdateManagerTest.testSitePresencesExistingPresenceWithNoDuration:600 expected null, but was:<Fri Nov 20 02:42:08 UTC 2020>
Error:    StatsUpdateManagerTest.testSitePresencesTwoSitesSameUsers:515 expected null, but was:<Fri Nov 20 02:42:07 UTC 2020>
Error:  Tests run: 37, Failures: 4, Errors: 0, Skipped: 4`

### CODE REVIEW

**Comment by ern** [comment]
StatsUpdateManagerTest.testSitePresencesDifferentUsers:489 expected null, but was:<Fri Nov 20 02:42:11 UTC 2020>
the test expected a null LastVisitStartTime but instead returned a date

In the past these tests could fail because of the test data not being cleared after each test.

**Comment by ottenhoff** [comment]
How to run a single test inside a CI environment? 

Can you just have the DB instantiated for each test instead of re-using it among the many tests?

**Comment by ottenhoff** [comment]
I'm trying out the DirtiesContext annotation

**Comment by ottenhoff** [comment]
Closing because can't get the StatsUpdateManagerTest tests working with Github Actions

**Comment by ottenhoff** [comment]
Now using their older Ubuntu 16.04 and now it seems to build ok

**Comment by mpellicer** [comment]
Nice!

**Comment by ottenhoff** [comment]
is removing travis.yml appropriate ?

**Pull request merged**
