### PR TITLE
SAM-2486 - All submissions not available when assessment set for average

### PR DESCRIPTION
**Pull request by jonespm**
grade on submissions

### CODE REVIEW

**Comment by ottenhoff** [comment]
+1 looks good

**Comment by jonespm** [comment]
Yeah, surprising that this was missing, works clicking the drop down back and forth. Wasn't sure how much more could be tested. It looks like in the case of anonymous == true it did do something with this. I'll look and see how that looks before committing this.

**Comment by jonespm** [comment]
Wow, with anonymous eq true, selecting "All Submissions" really results in a messed up display. I don't know if this is new or was a problem before with the other types (like highest score) 
anonymous true

**Comment by jonespm** [comment]
Nope that's not a new bug, still looks like it fixes the problem.

**Pull request merged**
