### PR TITLE
SAK-29518 updated Japanese translations

### PR DESCRIPTION
**Pull request by bkirschn**
Japanese translation update from Hosei University. Encoding validated, files checked to make sure that only localized Japanese properties files are included, and Sakai started and each tool verified to not crash (and displays Japanese characters).

### CODE REVIEW

**Comment by ern** [comment]
+1
Is there a different author (from Hosei University) you would like to set on the commit?

**Comment by bkirschn** [comment]
I was contacted by Yuji Tokiwa, though I'm not sure who else should share the credit (see also JIRA ticket).

**Comment by ern** [comment]
Here is his github account https://github.com/tokiwa

You can change the author with:
git commit --amend --author "Yuji Tokiwa <yuji.tokiwa.dc@hosei.ac.jp>"

**Comment by bkirschn** [comment]
Given license agreements, I think I should remain the author, with credit given in the JIRA - but thanks - I didn't know you could do that in github :-)

**Comment by buckett** [comment]
This pull request re-created folders that don't have anything in them. We now have osp folders again.

**Pull request merged**
