### PR TITLE
KNL-1405 SAKAI_SESSION’s TIMESTAMPS creation can fail.

### PR DESCRIPTION
**Pull request by buckett**
On MySQL under some configurations SAKAI_SESSION table creation can fail because you can’t have multiple columns with a default timestamp. Making the columns null means it works across all configurations and the Java code sets the timestamp.

### CODE REVIEW

**Comment by buckett** [comment]
This is mainly for people using 5.7 which on a standard deployment from Oracle will see this error.

**Comment by ottenhoff** [comment]
+1

**Comment by jonespm** [comment]
Do the Oracle scripts need alteration? Have those been tested?

**Comment by buckett** [comment]
From discussions as SakaiCamp the Oracle scripts should default to allowing null and looking at the documentation I can't see any reference to Oracle defaulting to the current timestamp.

https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements001.htm#i54330

I changed them both so it's clearer they are in sync and someone looking down the road sees that we intend to have both vendor DBs the same, although the NULL shouldn't be necessary.

The oracle upgrade script shouldn't do anything but it should be harmless if we're correct.

**Comment by ottenhoff** [comment]
So the default is to allow null values thus the addition of NULL is unnecessary .... and it seems like some versions of MySQL don't accept this new "NULL" and reject the syntax ..... anyone else running into issues here?

**Comment by bjones86** [comment]
I'm running 5.7 locally for several instances, they were all happy after this modification.

**Pull request merged**
