### PR TITLE
SAM-2892 - Adding only front end only count character functionality in samigo

### PR DESCRIPTION
**Pull request by fgeraci**
[JIRA - SAM-2892](https://jira.sakaiproject.org/browse/SAM-2892)

Somewhat convoluted but due to the fixed size of the elements, there are no more than a few look ups in constant time. Also, this approach is necessary to self-contain each search (bottom up) within each div, for each part and question, in case there are many per page.

### CODE REVIEW

**Comment by jonespm** [comment]
Does this still result in the problem as described in SAM-2698 with timed assessments? I can understand the desire for having it count for plain text but this other issue sounded worse.

**Comment by jonespm** [comment]
Also these should be merged against master first rather than 11.x

**Comment by fgeraci** [comment]
Hello @jonespm , yes, it solves SAM-2698 for the "Count .." button no longer submits the form to the back end when pressed producing the erratic timer behavior. In short, that happened due to the fact the original button was a JSF commandButton which is of type submit, hence on every press, it was sending the form back to the listener. This is now a fully front end function.

I will move the commit to master and create the pull request. Thanks for letting me know.

**Comment by jonespm** [comment]
Sounds good, yeah all of these commits you made should have a base against master first. Then after they're verified by the QA team we cherry-pick them to the 11.x branch. You might have to close and re-create your PR's to change the base.

We only have separate ones with an 11.x base if the issue only affects 11.x or if the change is significantly different between master and 11.x (because of framework or other changes)

**Comment by fgeraci** [comment]
@jonespm , great to know! I was using 11.x since at the U (Rutgers) we are working on 11.x rather than master. Thank you for letting me know.

I will close these tomorrow and re-open them in master.

**Comment by fgeraci** [comment]
Closing PR, will create new PR against master.

**Pull request closed without merging**
