### PR TITLE
SAK-30646 Fix download links in Site Export

### PR DESCRIPTION
**Pull request by buckett**
The download links were POST requests, this switches them to GETs and drops the broken jQuery. Also added some handling of errors.

### CODE REVIEW

**Comment by buckett** [comment]
This switches it from a POST to a GET, I don't think this has any implications as we still do the admin check, but am I missing something as to why it was originally done as a POST?

**Comment by jonespm** [comment]
I don't entirely remember or see the history of it. Does it encode file names with special characters (spaces) correctly when passing them as parameters? I feel like having them as a hidden field would take care of that and not sure about edge cases otherwise. There would probably be security implications if it wasn't admin only but like you said this is already just for admins.

**Comment by buckett** [comment]
Only should contain site IDs so shouldn't need encoding. The old code didn't deal with it.

**Comment by ottenhoff** [comment]
OK LGTM. Thanks

**Comment by jonespm** [comment]
Yea "shouldn't need encoding" but too many places use spaces in their site ids still. Not sure if it worked or not for downloading, though looked really like the only thing broken with the other form was it had an an old version of jQuery still being used.

**Comment by buckett** [comment]
Fixed the escaping of site IDs, also did titles while I was there and switched to <small>
Making the form simpler just means it's less likely to break in the future.

**Comment by jonespm** [comment]
Okay, seems good to me

**Comment by buckett** [comment]
Build issue looks unrelated so kicking off again.

**Pull request merged**
