### PR TITLE
SAK-31466 - Following menu if tools do not overflow view port and auto adjustable width tabs

### PR DESCRIPTION
**Pull request by fgeraci**
[Video Demo](https://goo.gl/JtZP1S)

[JIRA](https://jira.sakaiproject.org/browse/SAK-31466)

### CODE REVIEW

**Comment by fgeraci** [comment]
@jmarianolujan Mariano, adjusts based on your testing.

**Comment by SedueRey** [comment]
It's a great work, it looks nice and useful but if you can share this behaviour changes on Slack channel it would be great in order to avoid some bugs if more people can watch modifications.

**Comment by fgeraci** [comment]
Hey Eduardo. Thanks, sure. Is there a Slack ch.? What's the domain?

**Comment by SedueRey** [comment]
You can find us on https://apereo.slack.com/archives/sakaimorpheusdev

**Pull request merged**
