### PR TITLE
SAK-43017 Update maven repo URLs to use https

### PR DESCRIPTION
**Pull request by dnhutchins**

### CODE REVIEW

**Comment by jonespm** [comment]
Looks like http://repo.spring.io in master/pom.xml is also https only now

**Comment by jonespm** [comment]
I'd probably also change nexus.opencast.org to https too while we're doing these.

**Comment by dnhutchins** [comment]
Ohhh yeah, didn't notice, my local cache was working. Added those.

**Comment by jonespm** [comment]
Yeah, I noticed that when I build deploy with a clean repo. I'm building everything now, I'll merge this after it completes but it looks good! Thanks. I'd like to move stuff off of sonatype and put source.sakairproject.org in S3 under https also next but this fix should be the only immediate one needed now. 

I also usually build with a full cache so don't notice when most artifacts aren't available.

**Pull request merged**
