### PR TITLE
NO-JIRA Move SCORM contrib tool to core Sakai

### PR DESCRIPTION
**Pull request by davidpbauer**
This merges the scorm contrib tool's latest version into Sakai while maintaining commit history. Additionally, I've included the "scormplayer" module in the base pom, updated the pom versions to 25-SNAPSHOT, and fixed tests.

Other local to UD work we could contribute after this is merged:
1. Import/duplicate scorm content
2. Link to scorm package in lessons, including making it required/pre-req.
3. "Upload new version" feature in the tool (this has some limitations but allows for simple typo fixing, etc.)

Locally: build and deploy successful, tests pass, startup is clean in fresh Sakai instance, basic tool testing works as expected.

### CODE REVIEW

**Comment by ern** [comment]
@davidpbauer thx for doing the work, I'll check it out and take a quick look.

**Comment by csev** [comment]
Thanks Dave.

**Comment by ottenhoff** [comment]
Merge commit or Rebase?

If we do rebase, then I would vote for prefixing every commit with "SCORM"

If Merge, I'm fine with it as is

**Comment by davidpbauer** [comment]
I don't have a preference either way

**Comment by bjones86** [comment]
Please preserve all commit authorship. Not only for Western's work, but for Edia's and everyone else who has contributed to this tool over the years.

**Comment by ern** [comment]
I've redone this import and have rewritten all the history so that the files are prefixed correctly. I also added a prefix "SCORM".
I am going to close this as I will simply push to repo once it is completely done.

**Comment by csev** [comment]
Awesome!

**Comment by jesusmmp** [comment]
Scripts are missing on sakai-reference!

**Pull request closed without merging**
