### PR TITLE
SAM-3253 fix a few NPEs in this observable helper method

### PR DESCRIPTION
**Pull request by ottenhoff**
I'm seeing NPEs in 11.x and 12.x logs related to this method.... I'm not sure what's going on in this method but lots of NPE opportunity in it

### CODE REVIEW

**Comment by master-bob** [comment]
Looks like that will fix the NPE you are seeing. But it may cause email
notifications to fail for that assessment submission. Depending on how
SamigoETSProviderImpl.notify handles an empty map.

I don't think the issue is here, but rather before.

When an assessment is submitted (for any of the three cases), an event is
generated with Metadata as a string from a hash map. The SamigoObserver
then watches for the specific events. When they match, the event resource
is converted back to a map and an email is sent saying it was submitted.

**Comment by ottenhoff** [comment]
Thanks @master-bob, can you propose what PR or JIRA broke this functionality and is causing these NPEs?

**Comment by jonespm** [comment]
This could be fixed by https://jira.sakaiproject.org/browse/SAM-3244 yesterday on #4757  Have you rebased?

That's what's mentioned there.
"We can't just NPE-proof SamigoObserver.stringToHashMap() because it then will just blow up in SamigoETSProviderImpl when it goes to retrieve values in the HashMap it expects to be there."

**Comment by ottenhoff** [comment]
Thanks. Looks relevant.

**Pull request closed without merging**
