### PR TITLE
SAK-49160 - WS throws NPE when user is disabled via changeSiteMemberS…

### PR DESCRIPTION
**Pull request by danielmerino**
…tatus

### CODE REVIEW

**Comment by danielmerino** [comment]
The line was added in https://github.com/sakaiproject/sakai/pull/11032/files by @josecebe . Maybe he is on holidays right know, @mpellicer ?

Looking other lines added in that patch, I think that this line was added unintentionally.

**Comment by mpellicer** [comment]
> The line was added in https://github.com/sakaiproject/sakai/pull/11032/files by @josecebe . Maybe he is on holidays right know, @mpellicer ?
> 
> Looking other lines added in that patch, I think that this line was added unintentionally.

He left the company in February, we're happy to support this issue. I remember it from UPV. So it only happens when a user is disabled? Does this mean the WS has a security issue?

**Comment by danielmerino** [comment]
I don't think it's a security issue.

Several changes of SAK-48096 patch consist in two lines: the first builds a list of strings in userAuditList variable and the second adds the list with userAuditRegistration.

When these changes are included in changeSiteMemberStatus there are a third line, the one I think is useless.

siteService.getSite(siteid).getUserRole(user.getId()).getId();

User's role is retrieved but it's not used at all. And it throws an NPE when the user is disabled.

My change just remove this line and we have tested that the method still works.

**Review by ottenhoff — APPROVED** [review]
Thanks for looking into the history here. Removing the line looks good to me.

**Comment by mpellicer** [comment]
Thanks for the investigation and the good work Dani @danielmerino !

**Pull request merged**
