### PR TITLE
SAK-32437 Roster Improvements

### PR DESCRIPTION
**Pull request by master-bob**
The following roster improvements where made:
* The roster is separated by roles in all views and they are organized
by most permissions to least permissions. If two roles have the same
number of permissions, they are organized alphabetically. Each section
shows the number of people in that role, as well as the number shown and
the total.
* Add in the ability to show an inferior 12 hour clock to the roster
tool. Fortunately this ability is by default off and must be foolishly
enabled via the sakai.property 'roster.12HrClock'. VIVA 24 TIME!
* Improve the time and date format by converting it to a "bundle".
* All the tabs are different views of the tool. As the export button is
an action, it does not make sense to have it as a tab. As such, it has
been moved to a button.
* Added the header to float if the role table is larger than the
window height.
* Ensured all the columns widths are aligned.
* Fix striping
* Highlight the row you are hovering over
* Add the roster.12HrClock as a sakai.property
* * Made the date format a bundle

See [JIRA](https://jira.sakaiproject.org/browse/SAK-32437) for screenshots.

### CODE REVIEW

**Comment by master-bob** [comment]
@adrianfish, could you take a look when you have a chance?

**Comment by adrianfish** [comment]
I've just done a stack of stuff in ...

https://github.com/sakaiproject/sakai/pull/4216

... that may well clash with what you've done here. Can you review my PR and rebase yours accordingly? I've not touched permissions, although I was tempted, so that will be okay.

**Comment by master-bob** [comment]
Shouldn't I then wait until #4216 is merged, and then just rebase mine on master?

**Comment by adrianfish** [comment]
Yes, but it you can review #4216, then I can just get it in :)

Just a sanity check for crappy code, or pull the commit locally and do a bit of testing. If you could, that'd be great.

**Comment by master-bob** [comment]
Rebased on master. I fixed the conflicts, but I think there is a change I need to make with the .scss, which I will investigate tomorrow.

**Comment by adrianfish** [comment]
@master-bob Hi Leonardo. I've found some serious problems with this and they may be down to the fact that you've had to rebase onto my changes and broke some stuff along the way. In which case, sorry about that, bad timing :( I like the hover and the block shading you've added, I also like the export button top right. The permissions page layout looks a lot neater.

Problems:
1. Infinite scroll is now broken, though. If you divide the users up into blocks of roles I don't know how you'll be able to load the individual blocks on scroll - that's why I just had the whole lot scrolling as one and had the filter drop down for focusing on roles.
2. Profile popup on photo click is now broken. Not sure why, but it just doesn't work anymore.
3. Small one - the export button needs ligning up with the filter drop downs.
4. The save button doesn't work on the permissions page.

So, there are some showstoppers here. When I test roster I turn on the demo data and run the quartz job to setup sites and users and then I blackbox test like crazy. One thing I saw in the console when trying to save permissions was this:
ReferenceError: showOfficialPictures is not defined.
I got rid of that variable in 9b72aea691eab317e72b2b30a11822b2ba19b821 (profile popup) and that implies to me that you've created a hybrid.

I suggest you rework this because there's some good stuff in it  - get rid of the blocking of roles but keep the nice block shading. Fix the profile popup. Move the export button down a bit and just test it tons with all the demo data turned on, in a site with plenty of users, ~200's good. I would literally just get the diff up for this and just copy and paste the changes into a new pull of master, one by one. If you pick it across and then try and clean up afterwards you'll just be making more work for yourself. Sorry for creating more work, really.

**Comment by master-bob** [comment]
I fixed the showOfficialPictures leftovers, which I believe caused the issues 1, 2, & 4.
I fixed the positioning of the export button.

I tested this in a site with 91 members.

The only reason we made this PR to begin with is due to the separation of user roles into their own tables. In our opinion, it is a waste of screen real estate to have the role repeated for each user.

The separation of roles works in the following manner:
- Get the permissions for the site
- Sort all the roles in the site, by number of permissions
- For the role with the most permissions, get the members in that role, and [keep track of the page retrieved](https://github.com/master-bob/sakai/blob/38d198221cf1933c72a57c8faaf96923c1bba56f/roster2/src/webapp/js/roster.js#L503)
- Render the members ([attaching the members to the appropriate table](https://github.com/master-bob/sakai/blob/38d198221cf1933c72a57c8faaf96923c1bba56f/roster2/src/webapp/js/roster.js#L752))

**Comment by adrianfish** [comment]
@master-bob When you say 'Sort all the roles in the site, by number of permissions', do you mean members rather than permissions?

**Comment by master-bob** [comment]
Nope.

It was the only way I could think of which would ensure that you would always get "Teachers", "Teaching Assistants", and then "Students" (in that order). Though it does make the assumption that Teachers have the most permissions, followed by TAs, and finally followed by students. Sorting roles alphabetically would not work for Sites with different role names (in Spanish: Professor & Estudiantes for Teachers & Students).

**Comment by adrianfish** [comment]
@master-bob 

A few more issues:

1. The popup table header is not lined up properly after you start to scroll.
2. The rendered counter looks indistinct. The rendered count is a cool idea, but it needs more visual distinction from the background. It looks broken.
3. The groups ellipsis shows through the moving table header.
4. The role filter doesn't do anything now. Change the role and the view remains the same. The role filter should go in this scenario.
5. Search doesn't work anymore. Nothing happens after you type and find.
6. The groups filter doesn't work

I don't see how the grouping actually improves over just having a dropdown filter as currently, TBH. I'm not convinced, I have to say. One thing that jumps out at me is that Instructors seem to come topmost, whereas the likely use is to view an print/export student rosters for use by instructors. I'm looping @ottenhoff, @jonespm and @steveswinsburg in on this to see what they think.

screen shot 2017-04-18 at 17 02 20


screen shot 2017-04-18 at 16 58 51
screen shot 2017-04-18 at 17 05 53

**Comment by master-bob** [comment]
I'm doing local work now, so I'm not sure when I'll be able to come back to this.

Regarding Instructors top most, students are the largest user group of Sakai. As such it makes sense, from a student's perspective, to have the most important people first in the roster.

**Comment by ottenhoff** [comment]
Conflicts on this PR so closing it for now ... feel free to re-open when conflicts resolved

**Pull request closed without merging**
