### PR TITLE
SAK-44008 Help link for MathJax is not directed to the correct page

### PR DESCRIPTION
**Pull request by MRutea**

### CODE REVIEW

**Review by bjones86 — CHANGES_REQUESTED** [review]
I don't understand how this changes anything. It seems like the code is the exact same, but moved between 2 classes.

Additionally, I think the original class is the correct location for this code.

**Comment by MRutea** [comment]
Hi, 
Yes. There is an important change.
If the site is null, because it is being created, this is never set:
**context.put (CONTEXT_MATHJAX_HELP_URL, HELP_URL);**

So that value must be set regardless of whether site is null or not.
For this reason should be placed in SiteAction.java, before checking if site==null.

Thank you for your comments.

**Comment by bjones86** [comment]
Ah, I see, that makes more sense. Rather than moving the member variables between classes, can you just make them public in the `MathJaxEnabler`? That class is meant to house everything related to MathJax.

**Comment by MRutea** [comment]
Thanks, Brian.
Understood.
Very good point.
I make the appropriate changes to leave everything related to MathJax in MaxJaxEnabler.

**Review by bjones86 — APPROVED** [review]

**Pull request merged**
