### PR TITLE
SAK-49389 Discussions with Rubrics include bootstrap so the rubric grading bits work

### PR DESCRIPTION
**Pull request by maurercw**

### CODE REVIEW

**Review by bgarciaentornos — APPROVED** [review]

**Comment by stetsche** [comment]
I think in this case bootstrap is not available, perhaps due to an iframe? I think this is probably the best approach to include bootstrap JS and the vanilla bootstrap CSS is something be probably never want to load. So I would be in favor of keeping this PR as it is and cleaning up the CSS reference in headscripts separately.

**Comment by ern** [comment]
@maurercw Can you update the bootstrap include in headscripts to correctly not include the vanilla css as the tool.css already takes care of this.

**Review by ern — CHANGES_REQUESTED** [review]
see last comment

**Comment by maurercw** [comment]
Requested changes have been made

**Review by stetsche — APPROVED** [review]

**Review by ern — APPROVED** [review]

**Comment by ottenhoff** [comment]
Are we merging this?

**Pull request merged**
