### PR TITLE
LSNBLDR-496: Lesson builder - Header UI Update

### PR DESCRIPTION
**Pull request by doodelicious**
https://jira.sakaiproject.org/browse/LSNBLDR-496

screenshot 2015-04-30 09 50 03

Requested work to modify header to match screenshot above.

Before:
screenshot 2015-04-30 10 38 24

After:
screenshot 2015-04-30 10 55 32

Work done:
* Significant mark-up changes done to remove inline styling (header piece only), streamline classes for extendible styling, general code clean-up, etc.
* Added button styles and classes
* Added new icons for buttons
* Converted jQuery/Javascript dropdowns to CSS dropdowns
  * Removed summary text from dropdown items
* Moved styling from inline and Simplepagetool.css into a new CSS file titled lesson-builder.css (porting pieces from Simplepagetool.css). The file lesson-builder.css is built on LESS architecture (not added to the pull request currently). This skinning architecture modularizes aspects of the lesson builder UI, including:
  * Layout styles (buttons, header, general layout, mobile considerations)
  * Modules (alerts, cluetip, dropdowns, toolbar)
  * Theme (changes to theme, including colors and styles)
  * Vendor styles (currently mixins but can be built out to include UI frameworks such as Bootstrap)

This architecture can be written in LESS or SCSS. However, this project is not set up to compile either LESS or SCSS so the only thing added for the time being is the compiled CSS file.

Until the lesson builder UI rebuild is complete, both Simplepagetool.css and lesson-builder.css will need to exist in the head.

### CODE REVIEW

**Comment by doodelicious** [comment]
*Corrected issue with direct URL link not working (changed back from ID to class)
*Corrected dropdowns base on client feedback, including adding import/export CC to dropdown; added more header styling to CSS

**Comment by doodelicious** [comment]
Added accessibility to the dropdown menus using keyboard tab.

**Comment by buckett** [comment]
Is there a SAK issue associated with this? Normally this is referenced in the branch name and the commits.

**Comment by doodelicious** [comment]
Hi @buckett,

I'm checking with Apereo, as they are the ones who authorized the changes. I'll get back to you when I hear from them.

Cheers,
Jodie.

**Comment by clhedrick** [comment]
I’m waiting for whoever is doing it to say they’re finished. At that time there’s a bunch of stuff I need to do. Unless a lot has changed recently, it’s not internationalized, and is missing standard header elements. I committed to doing this stuff, but I’d rather start once they’ve done everything they can. I’ll create a Jira if there isn’t one.

**Comment by doodelicious** [comment]
Hi @buckett,

I've completed a Jira ticket for this PR, you can find it here:

https://jira.sakaiproject.org/browse/LSNBLDR-496

Feel free to reach out to me if you have any questions or concerns.

Cheers,
Jodie.

**Comment by ottenhoff** [comment]
Hi Jodie,

Can you modify your git commits to reference LSNBLDR-496?  When the commits are referenced with the relevant JIRA, someone using git blame will be able to learn more about the work done.

**Comment by doodelicious** [comment]
Hello @ottenhoff,

Absolutely. I will get that done today and you will see the commit updates. Thanks for the heads up!

Cheers,
Jodie.

**Comment by doodelicious** [comment]
Hello @ottenhoff,

Because the commit history is already written, I opted to create a new branch (LSNBLDR-496) with modified commits that now have the JIRA ID added. Sorry for the double work, but I was concerned with rewriting commit history and having it affect others who have pulled this PR down locally.

Let me know if you have any questions or any additional guidance.

Cheers,
Jodie.

**Comment by clhedrick** [comment]
This PR shouldn't be merged. There are lots of issues with the code. I'll be doing separate PR's containing fixed versions.

**Pull request closed without merging**
