### PR TITLE
SAK-44615 Rubrics are broken in 20.x if you compile it in Windows

### PR DESCRIPTION
**Pull request by MRutea**

### CODE REVIEW

**Comment by ottenhoff** [comment]
What about master/trunk?

**Comment by jesusmmp** [comment]
Thanks @MRutea ! 

@ottenhoff This is only for 20.x. 
21 and 22 is applied here. https://jira.sakaiproject.org/browse/SAK-44319

**Comment by ottenhoff** [comment]
Okay is there a reason for the special commit here? Or can SAK-44319 just be merged by the branch manager?

**Comment by ern** [comment]
SAK-44319 was merged and should solve this.

**Pull request closed without merging**
