### PR TITLE
L10n 11.x update translations

### PR DESCRIPTION
**Pull request by dooremont**
New translations Swedish,Turkish,Russian,French, French Canada....

### CODE REVIEW

**Comment by ern** [comment]
We would like the to have the i18n group review this ( knock konck @Gao-Jun )

**Comment by dooremont** [comment]
Ok how to contact i18n group ?

**Comment by ern** [comment]
@dooremont also need a JIRA issue on your commit message, please see what everyone else's commits look like!

**Comment by ern** [comment]
Please see my comment in PR #4555

**Pull request closed without merging**
