### PR TITLE
SAK-29192 Fix for chat tool messages.

### PR DESCRIPTION
**Pull request by willkara**
So this was a fun one!

Turns out that the chat tool doesn't use the appendMessage js function anymore due to everything being down through the head scripts script.

The reason it WASN'T working was because we were trying to set a global variable ( **updateUrl** ) and then use it in a function that was already defined.

For that to work in JavaScript, you need to define the global variable and THEN the logic, you can't define logic for a global variable and THEN define it.

What I did was to just pass the url and time parameters through the methods so headscripts can use/see it.

### CODE REVIEW

**Comment by willkara** [comment]
Will definitely require some more looking into due to JS changes and the timer still being a little wonky, maybe someone with more JS experience can confirm for me?

**Comment by ern** [comment]
Hi Will,

Thanks for working on this... When you pulled in changes from upstream you didn't rebase which is why those merge commits show up.

In order to fix this you will need to do an interactive rebase (git rebase -i HEAD~5)
where you will need to drop commits 2dca0ec, a9f8acd, 6c94576
squash your 2 commits ed961e5, 6448c06
after that you will end up with just one commit on this branch.

You then need to perform one more rebase to bring any changes from master into your branch (git rebase master) then you can push (with force) your new branch.

To prevent this in the future once you have commit's on your branch use rebase, which essentially removes your commits and then updates your branch with master and then reapplies your commit's on top.

**Comment by willkara** [comment]
Ooops. Thanks for the headsup! I'll be sure to watch out for the merge/rebase confusion for the future.

**Comment by willkara** [comment]
@ern , Having a little trouble fixing the git workflow for this one. I'll just update this ticket when it's figured out. May email you for some assistance.

**Pull request closed without merging**
