### PR TITLE
SAM-1408 bug fix commit

### PR DESCRIPTION
**Pull request by gillmanjc**
Updated SimpleDateFormat pattern

### CODE REVIEW

**Comment by gillmanjc** [comment]
Hi Steve
I have made this very small change and have done some proper testing for the 3 issues mentioned... I will do some more testing, but this seems to have done the trick. Please have a look at my findings and let me know what you think. I will list them below and comment accordingly:
Testing has found a number of issues. Tester's comment and my reply below:
•	The begin assessment for student always says that there is no due date, even though there is one. (Student beginning to take an assessment).
This need to be fixed. Seems relatively simple?
 I have tested with 2 new Assessments, having 2 student users, both now see due dates. See images below:
image
image
image

•	An assessment that overall is available to all students, does not respect group settings to take the assessment available at a later time. In other words, as a student I can take an assessment if the overall assessment available date has passed (and before the due date), even though the group I am in has a later available date, and I shouldn't be able to take it yet.
This need to be fixed. Sounds like an issue in determining the opening/closing dates when the group setting is applied. Flows on the the below issue.
For this issue, I have done the following testing, here is a screen print of the Assessment Settings:

image

So it is released to the entire Site, and is active at the moment. I did however set a Group entry, with a test user, and as you can see in the settings, this group’s duedate, available date etc is after the Assessment’s dates. Tested and the group user does not have access to this assessment. So the group user aren’t able to take the test yet although other users that is not in this group is allowed.
•	An assessment that overall is not available to students, does not respect group settings to take the assessment at an earlier time. The group members have to wait until the assessment is available to everyone. In other words, if the overall assessment available date has not passed, so most should not be able to start the assessment, but the group I am in has an available date that has passed (earlier than the overall available date), Samigo won't let me start the assessment.

image

For this issue I created an Assessment that is not yet available to users in the entire site (see Assessment settings above). I then created a group setting before this Assessment’s available dates, and tested with a user in that group.
The user in the group has access to the Assessment as per settings, before Actual Assessments available date for entire site.

image
image

**Comment by steveswinsburg** [comment]
Hi Jaco, thanks very much for that. Could you please paste this into the Jira ticket and I'll merge this and get another round of testing to hopefully close this one out?

**Comment by gillmanjc** [comment]
Sure, I will do Steve!

**Comment by ottenhoff** [comment]
Any ideas why such an odd date/time format was used here instead of ISO-8601 ?

`SimpleDateFormat("MM/dd/yyyy hh:mm:ss"`

**Pull request merged**
