### PR TITLE
SAK-48106 UserAuditLogs is not saving consistently the userId and sometimes is using userEid

### PR DESCRIPTION
**Pull request by josecebe**
This could need a conversion script for old values, I'm currently working on it. But wIthout the conversion script it would still working as it's working now.

### CODE REVIEW

**Comment by ern** [comment]
LGTM ty @josecebe

**Review by ern — APPROVED** [review]

**Review by mpellicer — CHANGES_REQUESTED** [review]
@josecebe Are we going to provide a conversion script for old cases?

**Comment by josecebe** [comment]
> @josecebe Are we going to provide a conversion script for old cases?

Yes, but I'm still working on it. I will let you know here when it's done.

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Thanks for the scripts, amazing!

**Pull request merged**
