### PR TITLE
SAK-26180 Add submissions time and lateness to assignment export.

### PR DESCRIPTION
**Pull request by buckett**
This adds a submission time and lateness to the assignment export.

It also cleans up the exporter so that the code is a little cleaner, it's extracted out into a simple class, this greatly simplifies the code in BaseAssignmentService.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Is it possible to squash these 4 commits into 1?

**Comment by buckett** [comment]
I can do, the commits were there to make it clearer how the work went. The first one doesn't actually change any functionality and just cleans up the code (extracting it into another class). Shall I just sqaush the last 3 down?

Especially as this isn't a bugfix that will get backported, isn't it better to have good blame annotations against each line?

**Comment by ottenhoff** [comment]
Sure, I see your point.  I'm all for having the best annotations possible if these are distinct tasks you are tackling.

**Comment by buckett** [comment]
Squashed last 3 commits.

**Pull request merged**
