### PR TITLE
KNL-1124 Switch to use Mockito.

### PR DESCRIPTION
**Pull request by buckett**
Switch the external calendaring service to just use Mockito instead of sakai-mock.

### CODE REVIEW

**Comment by buckett** [comment]
This doesn't fix KNL-1124, but is a step in the right direction.

**Comment by ottenhoff** [comment]
Nice +1

**Comment by buckett** [comment]
And fix the entitybroker one as well.

**Comment by buckett** [comment]
Went a bit further. sitestats didn't need much work to remove it's dependency on sakai-mock. With all the dependencies on sakai-mock I just deleted it, in the future Mockito (or alternative) is a better solution.

**Comment by ottenhoff** [comment]
Big +1 for 155 additions and 3,591 deletions

Ready to #resolve KNL-1124?

**Pull request merged**
