### PR TITLE
SAK-32036: make RHS iframe column thinner

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by fostersdesign** [comment]
On a 15" screen, this change breaks the columns for me:

brokencolumns

**Comment by buckett** [comment]
@nicholaswilson100 Do you think you're change introduced this?

**Comment by nicholaswilson100** [comment]
Possibly.  It's be good for this to be (independently) tested (so we can find out what someone else thinks and also to see how many pages might look like this)?

**Comment by juanjmerono** [comment]
I've found another issue related with this change:
https://jira.sakaiproject.org/browse/SAK-32161

**Pull request merged**
