### PR TITLE
SAK-44066 Remove courier from portal presence

### PR DESCRIPTION
**Pull request by smarquard**
This removes the functional use of /courier/ URLs from the portal presence tool,
eliminating end-user requests to /courier/... which serve no purpose, because
requesting the presence list itself also serves to establish the user's presence in a site,
and the morpheus js refreshes the presence anyway.

Complete cleanup left for SAK-39977, including removal of scheduleUpdate() from headscripts.js
which is referenced from some other places too (JSF widgets).

Should be mergeable back to 20.x

### CODE REVIEW

**Comment by smarquard** [comment]
Note sure if this will break the display.users.present.iframe=true configuration (or if that even works still?)

# SAK-19129 Use the old method of displaying presence in an iframe with courier
# DEFAULT: false
# display.users.present.iframe=true

**Comment by ern** [comment]
Yeah fine by me! Can we be more complete about this ad remove the other parts as well so we don't leave in dead code?

**Comment by smarquard** [comment]
Happy to expand this, @ern. By "the other parts" do you mean references to courier in presence, or the whole of courier as in SAK-39977? This is a good optimization for 20.x so don't want to do something that would make it not mergeable to 20.x.

**Comment by ern** [comment]
OK yeah I was referring to what SAK-39977 is for sorry!

**Comment by smarquard** [comment]
PR #8451 for SAK-33977 which is a bit of a rabbit hole.

**Comment by smarquard** [comment]
This is good to merge AFAIK. This code has been running at UCT in production on 20.x for a while.

**Pull request merged**
