### PR TITLE
use rubygems.org for gem artifacts

### PR DESCRIPTION
**Pull request by mkristian**
this will remove the remaining problems in #1669 

CLA will come once you decided to pull in this patch

### CODE REVIEW

**Comment by mkristian** [comment]
ok - travis would need to use mvn-3.3.x

let's see how to achieve this

**Comment by buckett** [comment]
Don't worry too much, in the longer run we are wondering about switching to a native maven scss compiler.

**Comment by buckett** [comment]
The way to have this work, it to have a maven profile in library that activates the local maven extension is the maven version is greater than 3.3.1 and otherwise uses torquebox proxy. But I'm not sure the complexity is worth it.

**Comment by mkristian** [comment]
with jruby itself we use: https://github.com/jruby/jruby/tree/master/.mvn/wrapper and https://github.com/jruby/jruby/blob/master/mvnw
and tell travis to use those ```mvnw```

**Comment by mkristian** [comment]
but it also needs to enforce maven-3.3.x somewhere.

**Comment by jonespm** [comment]
Switched to using libsass for compilation https://jira.sakaiproject.org/browse/SAK-30439 so this is no longer applicable. Thanks!

**Pull request closed without merging**
