### PR TITLE
SAK-42662 - Prevent double click issues

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
@jesusmmp I re-did this one, it's working better for me now.

**Comment by jesusmmp** [comment]
> @jesusmmp I re-did this one, it's working better for me now.

Thanks. Please don't merge yet. We are testing it.

**Comment by mpellicer** [comment]
@jesusmmp any thoughts on this?

**Comment by jesusmmp** [comment]
@mpellicer It's OK. Tested and it works!
Yesterday, I was working with @adrianmticarum to change this method to avoid the 'while' bucle.

But... a lot of work...

**Comment by mpellicer** [comment]
Discussed with @jesusmmp , they'd like to implement improvements in a separate Jira, they are fine merging this PR that mitigates the problem.

**Comment by jonespm** [comment]
Yeah, I thought the same. I was like hmm, this looks like it works to fix the issue. It's not the *best* because if someone goes too fast on the clicks it's going to lose some of their actions but the client side spinner should prevent that from happening (or anyone even seeing this) anyway.

**Pull request merged**
