### PR TITLE
KNL-1379 Increased SESSION_USER_AGENT size from 255 to 300 

### PR DESCRIPTION
**Pull request by sinmsinm**
...to prevent errors on requests from some browser that send bigger user-agent header

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Since it's a varchar I would prefer if this was bumped right up to 1000 or more so it doesn't need to be changed ever again.

**Comment by ottenhoff** [comment]
How important is it that we save the entire user agent? 

For MySQL:

Data Type :
VARCHAR(M), VARBINARY(M)

Storage Required:
L + 1 bytes if column values require 0 – 255 bytes, L + 2 bytes if values may require more than 255 bytes

**Comment by jonespm** [comment]
I don't think there is a reason to increase this size, I already see code in here (addSession) that's really old to limit this. So I'm not sure how you're hitting this error.

			String userAgent = (session.getUserAgent() != null && session.getUserAgent().length() > 255) ? 
				session.getUserAgent().substring(0, 255) : session.getUserAgent()

**Comment by sinmsinm** [comment]
Yeah, I see now. It's strange because the dbwrite that exploded is the same that is protected by code Matt described. Ok, I'll try to get a test to reproduce and see how it could be trying to write 256 instead 255 characters. 
I feel I should close the PR and do it again when done. Should I close or do you prefer I keep it open to track all this conversation?

**Comment by sinmsinm** [comment]
Ok, I've found it the bug. The agent sent was larger than 255 so it cut to 255 chars, but VARCHAR2 is 255 bytes. If you look at the user agent string below you'll see that there is a "ñ" that are 2 bytes, so it tried to store 256 bytes and exception. So, when I extended the size it worked for me but I was really no solving the problem. What do you think I should try? Try to cut to 255 bytes instead 255 chars? Change the oracle scripts to VARCHAR2(255 CHAR) instead of byte ? 

---
Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H321 [FBAN/FBIOS;FBAV/38.0.0.6.79;FBBV/14316658;FBDV/iPhone6,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/8.4.1;FBSS/2; FBCR/OrangeEspaña;FBID/phone;FBLC/es_ES;F
----

**Comment by ottenhoff** [comment]
I would recommend the easiest path: change the substring to 255 bytes instead of chars

**Comment by buckett** [comment]
Need to be careful the last byte isn't a 2 byte character and gets cut in
half.

On 4 September 2015 at 13:56, Sam Ottenhoff <notifications@github.com>
wrote:

> I would recommend the easiest path: change the substring to 255 bytes
> instead of chars
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sakaiproject/sakai/pull/1043#issuecomment-137728909>.
>



-- 
  Matthew Buckett

**Comment by sinmsinm** [comment]
IMO the easiest and safest way is declare the column as VARCHAR2 (255
CHAR). It would reserve the space necessary to fit utf8 chars. MySql
scripts don't have to be changed.  The issue only affects oracle. Do you
agree?

El Dv, 4 Set., 2015 15.06 Matthew Buckett <notifications@github.com> va
escriure:

**Comment by jonespm** [comment]
Yeah, I'm okay with just changing the Oracle type rather than expanding the size of the field or changing mysql.

**Comment by jonespm** [comment]
Left a comment back on the jira related to NLS_LENGTH_SEMANTICS. Seems like a conversion is needed but not sure if we want to change every Oracle script to explicitly specify CHAR.

**Comment by steveswinsburg** [comment]
Since it's a varchar I would prefer if this was bumped right up to 1000 or more so it doesn't need to be changed ever again. (repeating message).

Varchars are varying length and won't use any extra space in the database even if the user agent is 1 byte and the column is declared as 1000. Seems like this should just be increased to a large enough number then we can move on and never have to address this ever again.

**Comment by juanjmerono** [comment]
The concern here is about the Sakai OOTB scripts that could create fields as VARCHAR2( XX BYTE) instead of VARCHAR2(XX CHAR) no matter how long the field is... Is pretty easy to alter your existing fields but not so easy to check what fields are created as BYTE and change the proper script on each case to ensure that the field is created as CHAR.

**Comment by steveswinsburg** [comment]
It's probably only a 30 minute job to look through each table IN Sakai and find varchar columns that are byte instead of char, collect them, determine if they are candidates for modification, modify their Hibernate mapping or the SQL script that creates them, and update the conversion scripts. That said, that would be a separate issue, **this** ticket is around one specific field, which can be fixed in a one liner, AND increased in size so it never has to be modified again and will not chop any characters in half.

**Comment by juanjmerono** [comment]
I agree, let's fix this one with the db script to change all columns from BYTE to CHAR. I've created a new jira to fix OOTB Sakai scripts https://jira.sakaiproject.org/browse/KNL-1380

**Pull request merged**
