### PR TITLE
SAK-29397 remove standalone gradebook app as well as other modules previously marked for removal

### PR DESCRIPTION
**Pull request by steveswinsburg**
There is currently an unused standalone app inside the gradebook source that is unused, however requires updating whenever APIs change etc.

This should be removed.

Also, the other bits that are marked with the remove-10 build profile.

### CODE REVIEW

**Comment by jonespm** [comment]
I looked at doing this awhile back but held off because removing this looked like it removed a bunch of unit tests for gradebook. Is this something we want to do without relocating them? I think this would be okay if the new UI got in place and these weren't used at all anymore but it looked like many of these were testing the service and just were never moved. A subtask back of SAK-29101.

**Comment by steveswinsburg** [comment]
You are right, it does remove a bunch of tests. Unknown if they work or what. The code has been out of the build for a while. Happy for someone to volunteer to move them, but I won't be updating an out of date module when I change the API in the coming days.

**Comment by steveswinsburg** [comment]
p.s. new UI will be in trunk in the coming weeks. Though I will be refactoring the API this week. Chicken and egg ;)

**Comment by ottenhoff** [comment]
The samigo and gradebook standalone versions have caused me to lose countless hours of work while searching in the wrong places.  This is welcome cleanup.

**Comment by steveswinsburg** [comment]
Is this ok to be merged?

**Pull request merged**
