### PR TITLE
Revert "SAK-29251 Default for Turnitin assignment 'save' option should n...

### PR DESCRIPTION
**Pull request by baholladay**
Reverts sakaiproject/sakai#401

### CODE REVIEW

**Comment by buckett** [comment]
If the intention was just to revert the the changes in 401 you should have just reverted the commit in: 
https://github.com/steveswinsburg/sakai/commit/b9ba6a71caed917e60231a22041d7a6f262b3d19 you've reverted the fix Steve in https://github.com/steveswinsburg/sakai/commit/0be642e5f1410cce17acee3f5e9043282a4a157b which fixed the build on SAK-29248.

Having pull requests mean other people can have a quick scan over what's in the request to check it looks ok, if you merge the pull request straight away it is pretty pointless doing the pull request to start with.

Do you have any suggestions as to how the code in #401 could have been written so it works with the Vericite integration?

**Comment by baholladay** [comment]
I didn't realize that there was more than one jira in that PR. That seems wrong to have multiple jira's for a single PR. My intention was to only revert https://jira.sakaiproject.org/browse/SAK-29251

>Do you have any suggestions as to how the code in #401 could have been written so it works with the Vericite integration?

Don't throw any errors unless it's the turnitin service. Quickly looking at the patch, I'd think it'd simply be wrapping a if(turnitin){} check around:

addAlert(state, rb.getString("review.submit.papers.repository.notset"));

**Comment by baholladay** [comment]
I've created a PR https://github.com/sakaiproject/sakai/pull/428 for the accidental revert of https://github.com/steveswinsburg/sakai/commit/0be642e5f1410cce17acee3f5e9043282a4a157b

**Comment by buckett** [comment]
Cleaning up the branch again.

**Pull request merged**
