### PR TITLE
SAK-43745 An invalid IconURL will create additional whitespace

### PR DESCRIPTION
**Pull request by MRutea**
https://jira.sakaiproject.org/browse/SAK-43745

### CODE REVIEW

**Review by bjones86 — APPROVED** [review]

**Comment by bjones86** [comment]
How does this work with the resource shortener in Resources?

Resources > Edit Details > Short URL

I fear this validation will not work for Sakai provided short urls because they will not end in one of the image file type extensions.

**Comment by mpellicer** [comment]
> How does this work with the resource shortener in Resources?
> 
> Resources > Edit Details > Short URL
> 
> I fear this validation will not work for Sakai provided short urls because they will not end in one of the image file type extensions.

I don't think this will work for shortened URLs to be honest, I kinda don't like this implementation.

**Comment by mpellicer** [comment]
@bjones86 I did not like the previous approach, I implemented a different approach in the client side, and restricting images to the same Sakai domain for security purposes.

What do you think?

**Comment by fostersdesign** [comment]
@mpellicer, I've been querying for "invalid" site icons on our local Sakai instance for the last year, since they break JSF tools, like Forums, by displaying a 404. 

While doing that clean-up, I've noticed that there are a number of legitimate images that are hosted outside of Sakai. Sites I've seen used are Wordpress, my university's public sites, Wikimedia, Google drive, Facebook, other wikis like Wikia, Twitter, Flickr, images from Google Image searches, and news sites. With the copyright considerations aside, these all work to display the image properly. 

In most of these cases, I don't see a security issue with using these; however, I do see the potential security issue that the site icon feature allows. 

If we restrict it to images that are stored within the Sakai instance, then I think the feature should be changed to be a resource picker to only select images uploaded to the Resources of the site rather than a URL text field. 

Thoughts?

**Pull request closed without merging**
