### PR TITLE
SAK-29398 Remove all modules marked as 'remove-10'

### PR DESCRIPTION
**Pull request by steveswinsburg**
See https://jira.sakaiproject.org/browse/SAK-29398

There are a number of modules within Sakai that are included in the remove-10 profile. They are not built and are redundant bits of code that often require maintaining if APIs change etc.

These should be deleted.

eg:
````
[steveborg:~/dev/sakai/src/sakai]$ grep -r "remove-10" *
edu-services/cm-service/pom.xml:            <id>remove-10</id>
jobscheduler/pom.xml:		<id>remove-10</id>
portal/pom.xml:            <id>remove-10</id>
profile2/pom.xml:        <id>remove-10</id>
providers/pom.xml:          <id>remove-10</id>
shortenedurl/pom.xml:            <id>remove-10</id>

<profiles>
      <profile>
          <id>remove-10</id>
          <modules>
              <module>jldap-integration-test</module>
              <module>cm-authz-integration-test</module>
          </modules>
      </profile>
  </profiles>
````

### CODE REVIEW

**Comment by jonespm** [comment]
All of these were marked as such back in SAK-26295 because they were either sample projects or they had tests that were broken that nobody had time to fix. The ideal was that someone would go and determine if the code was useful or if the tests were useful and fixable. I still don't think that removing all of this code without doing some kind of review on it is the best plan.

For instance there was a nice (looking) JLDAP test, some unit tests for quartz, sample source code in the cm-service for doing course synchronization. 

I'd be -1 on this. Perhaps some of these things (like the CM sample code) should be in reference or somewhere else instead of in the edu-services directory, but most of this stuff still does work, we just didn't want it to build as part of the "standard" profile.

**Comment by steveswinsburg** [comment]
Nice idea, but if no one is going to do the work, it is out of date useless code. Even moving it to reference means it can get out of date and is no use to anyone. This sort of stuff is best placed on a 'how to' page, not as dumped code that is unmaintained.

**Comment by ottenhoff** [comment]
Yeah, I mean the reality is that no one is going to fix these. I think the amount of old code we've left in edu-services, gradebook, and samigo has only slowed down developers.

**Comment by jonespm** [comment]
Well I think some of this was still working, or if not just had a minor problem. I also don't know where to put this sample utility code. 

Does it belong in there with the tool, in some other directory in sakai or some other repository? There's a lot of nice random utility code out there for Sakai and it seems like it would be all better if it was organized in github than scattered all over the net (in gist, blogs, confluence, svn contrib). I agree with removing *or* fixing most of this though and I think it should be a blocker for 11 but once it's removed it's not coming likely coming back.

**Comment by steveswinsburg** [comment]
Is this ok to be merged? I agree with Sam, no one is going to fix this and this is holding people up. I also agree with you Matt, there is a lot of code scattered everywhere, including in my own blog. In a perfect world that would all be centralised and always up to date. But it's not so IMO lets just get this in and move on. May be harsh and I realise we are removing code snippets but they are maintenance issue and in the wise worlds of an internet sensation "ain't nobody got time for that!"

**Comment by jonespm** [comment]
I just hate when unit tests are removed because nobody has time to fix them, I think that ends up costing us much more time long term. But go ahead and remove these if they're holding something up. I know they existed and hopefully I'll (or someone else) will have a chance to get these working again. Most of the GB ones on #540 seem like they should have been moved into the edu-service and I didn't know why these specific ones didn't work anymore.

**Pull request merged**
