### PR TITLE
SAK-43088 Samigo set cascading with orphan removal for Item's

### PR DESCRIPTION
**Pull request by ern**
This PR also reverted the following recent fixes as the root of this
issue was traced back to SAK-42116

Reverts SAK-43107 SAK-43123 SAK-42901 SAK-42853 SAK-42858 SAK-42116

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 15
           

Complexity decreasing per file
==============================
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java  -6
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java  -4
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5019865&bid=16548049)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 15
           

Complexity decreasing per file
==============================
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java  -7
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java  -4
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5019865&bid=16548049)

**Comment by ottenhoff** [comment]
My testing so far looks good. I have tested unpublished, published, q pool questions... all appear to be correct while editing

**Comment by ern** [comment]
Yeah my testing has been good as well, will have one more update to the PR just beautifying the lines changed.

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 18
           

Complexity decreasing per file
==============================
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java  -7
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java  -6
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5019865&bid=16548049)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 18
           

Complexity decreasing per file
==============================
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java  -4
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java  -7
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5019865&bid=16548049)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 10
           

Complexity decreasing per file
==============================
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java  -7
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java  -6
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5019865&bid=16548049)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 5
           

Complexity decreasing per file
==============================
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java  -4
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java  -6
+ samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5019865&bid=16548049)

**Pull request merged**
