### PR TITLE
SAK-32101 Assignments service refactor

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by csev** [comment]
Wow - A lot of code :)

**Comment by smarquard** [comment]
A long-overdue refactor. Props to Longsight for taking this on and committing to seeing it through for Sakai 12.

**Comment by danielmerino** [comment]
Thanks a lot, Earle, for such an impressive work!

**Comment by csev** [comment]
I say merge soon and then lets test and fix.  Thanks for all this.

**Comment by ern** [comment]
Just did a rebase to fix a few merge conflicts.

**Comment by shojikajita** [comment]
We found that ACCESS column is causing ORA-00904 when auto.ddl = true in our environment.
We could use hibernate.globally_quoted_identifiers=true but it generates more errors in mvn test.

Please see the patch at https://github.com/shojikajita/sakai/commit/5289abf9c9fb67edd7c72d4febf9f8f0b350acdf

**Comment by buckett** [comment]
The list of Oracle reserved words is at: http://docs.oracle.com/cd/B19306_01/server.102/b14200/ap_keywd.htm

**Comment by shojikajita** [comment]
We also found that the name length for PEER_ASSESSMENT_STUDENT_VIEW_REVIEW column causes "ORA-00972: identifier is too long".  The length for Oracle 12c should be 30 at most: https://www.databasestar.com/ora-00972/

**Comment by shojikajita** [comment]
Reported as https://jira.sakaiproject.org/browse/SAK-33505 and https://jira.sakaiproject.org/browse/SAK-33506

**Pull request merged**
