### PR TITLE
12.x GBNG proposed merges

### PR DESCRIPTION
**Pull request by ottenhoff**
Please review but do not merge.... 

These are proposed cherry-picks into 12.x now that 12.0 is tagged.

### CODE REVIEW

**Comment by jonespm** [comment]
We'll also probably want to rebase and merge this one rather than squash

**Comment by ottenhoff** [comment]
We may be blocked from merging until this Blocker is resolved:

  https://jira.sakaiproject.org/browse/SAK-34012

I think we're going to need @steveswinsburg help to identify where the issue may have come from.

**Comment by ottenhoff** [comment]
I added two more commits from SAK-34012 .... I think this is ready to go .... if someone wants to bring it down to test locally, that would be appreciated.

**Comment by bjones86** [comment]
I can probably take this out for a quick spin this afternoon. Anything in particular I should be focusing on?

**Comment by ottenhoff** [comment]
I would spend most time testing on Settings page as an instructor ... make sure you can change the scheme, grade type, etc. I think it's looking pretty good

**Comment by bjones86** [comment]
Will do! I'll spend a bit of time on the Import/Export as well, since I did some work on those pieces that are included here.

**Comment by bjones86** [comment]
My testing has gone well:

* all aspects of Settings page are now working
* grade entry/validation on spreadsheet is working
* charts are working
* import front-end validations and performance improvements are working

The only thing I've found that's not working, is importing in locales that use comma as the decimal separator. This is a problem introduced by the work I contributed to add all the front-end validation. We have a fix for this locally, I just haven't gotten around to submitting a PR for it. I'm hoping to get around to that early next week.

**Comment by bjones86** [comment]
@ottenhoff, I submitted the PR I was referring to in my earlier comment, so you'll likely want to cherry-pick it into this branch once it's merged (#5442)

**Comment by ottenhoff** [comment]
Okay, 12.x-merges branch updated with #5442

**Comment by jonespm** [comment]
Okay I merged and updated the fix version of all these issues.

**Pull request merged**
