### PR TITLE
SAK-47669 - Rubric should only be locked if the association is active

### PR DESCRIPTION
**Pull request by maurercw**

### CODE REVIEW

**Comment by adrianfish** [comment]
I don't know if this is right. If an instructor accidentally switches an association to another rubric and wants to switch back, what happens when the original rubric has been deleted? That original rubric may even have evaluations associated with it. The reason the active flag was put in was to handle that case and help prevent student evaluations being lost. So, if this needs to happen, you should probably check that you can't deleted a rubric with evaluations. That way at least any student evaluations are protected.

**Comment by adrianfish** [comment]
@maurercw No probs! I just know a lot about rubrics, for my sins. It seems to me that if we want to unlock a rubric that isn't part of an active association, then we just need to make sure it hasn't got any evaluations against the inactive tool associations. Then we unlock it and it can be deleted or whatever. But, we then need to make sure that when the rubrics is deleted all the inactive associations are removed too.

**Comment by maurercw** [comment]
@adrianfish Finally coming back to this!  So, because everything is separate, how is a Rubric supposed to know if there are any evaluations?  It seems like the objects are related, but have no direct linkage.  So I can't go from Rubric -> ToolItemRubricAssociation -> Evaluation.  But since the locked status is really part of the Rubric, I can't make a service call to find the evaluations.

**Comment by ern** [comment]
Closing this as this is likely not the appropriate fix.

**Pull request closed without merging**
