### PR TITLE
SAK-44248 use blockUI to prevent user from mashing Question Progress links

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Review by bjones86 — DISMISSED** [review]
Cool, thanks for using the spinner!

**Comment by fostersdesign** [comment]
Thanks, @ottenhoff. 

In testing this fix, it achieved the multi-click prevention. However, an unexpected side effect happens if you right click on the links in the question panel now: the right click also triggers the BlockUI. But since the page isn't refreshing, the "Please wait" message stays on the page. The only way to interact with Sakai is to refresh the page, which the browser then asks to resend the last request, which then triggers the Data Discrepancy message page again. 

Any thoughts on how to address this?

**Comment by ottenhoff** [comment]
Maybe try changing the onmouseup currently in the questionProgress:

../samigo/samigo-app/src/webapp/jsf/delivery/questionProgress.jspf
61:             <h:commandLink title="#{question.strippedText} (#{question.pointsDisplayString}#{question.roundedMaxPoints} #{deliveryMessages.pt})" action="#{delivery.gotoQuestion}" rendered="#{delivery.navigation eq '2'}" onmouseup="questionProgress.disableLink(this); serializeImagePoints();">

**Comment by plukasew** [comment]
You could trying using addEventListener to attach a handler with access to the MouseEvent, and then check MouseEvent.button to see if it was a primary click or not.

**Comment by ottenhoff** [comment]
> hmm, I'm not sure if there is a good alternative link event handler that could still capture the primary click and ignore the

I just changed onmouseup to onclick ..... am i missing something obvious?

**Comment by ottenhoff** [comment]
@bjones86 how do you want to proceed here? onclick seems to work fine in my testing

**Comment by fostersdesign** [comment]
@ottenhoff For our local fix, we were trying to stick to the JS file because it was easier to live deploy the change. The onclick might work. I'm trying to test it but have had an issue with my test environment that I need to work out first. I'll try to let you know early next week.

**Review by fostersdesign — APPROVED** [review]
I think this works on Sakai master. (It is hard to test for sure on localhost because of how fast the pages load.) The onclick triggers the BlockUI page for the Question Progress now though.

I struggled to get it to work on older versions of Sakai because JSF did something weird merging this new onclick with the form's existing onclick, but the newer version of JSF in master seemed to be able to handle it.

**Pull request merged**
