### PR TITLE
SAK-45326 add puppeteer to resolve chrome dependency issues

### PR DESCRIPTION
**Pull request by profmikegreene**
https://jira.sakaiproject.org/browse/SAK-45326

Dependencies list from
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

### CODE REVIEW

**Comment by profmikegreene** [comment]
would love @adrianfish to verify these changes don't conflict with his testing strategy and any docker experts to make sure i haven't done a bad thing... @dnhutchins or @jonespm have any concerns with the changes here? I've not worked with entrypoints much, but since we're not using a custom dockerfile, I didn't know how else to install these dependencies.

**Comment by jonespm** [comment]
I saw this which looks like it does the same things. We also mentioned switching the maven Docker file used to work around this, but one of these solutions might be better. 

https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

**Comment by profmikegreene** [comment]
Switching the docker image for maven to `image: markhobson/maven-chrome:jdk-8` is working for me and would be the only change needed, no Puppeteer dependency required. Just updating the karma config like that link demo'd didn't work for me as the maven docker image was still missing the chrome dependency.

If we change our maven image, we can split out the puppeteer discussion from getting docker to with with just karmajs. I am a big fan of puppeteer but I haven't worked with Karma, so I don't know how much overlap there is between the two, more research to come!

**Comment by profmikegreene** [comment]
There's also images like this which I may switch to locally anyway https://hub.docker.com/r/atlassianlabs/docker-node-jdk-chrome-firefox but I recommend us giving at least a thought to since we're doing so much front end now. A maven image with node installed directly would allow us to run npm commands directly and not only go through maven to run them.

**Comment by ern** [comment]
This is causing an issue on nightlies so I added #9163 which is more focused on solving chrome headless issue without the docker issues.

**Comment by jonespm** [comment]
With the Docker `maven-3-jdk-8-slim` or `maven:3-jdk-8` this still isn't building with the latest fix. I think we'll still need something for Docker builds.

maven:3-jdk-8
```
[INFO] 11 04 2021 19:41:39.454:INFO [karma-server]: Karma v6.3.2 server started at http://localhost:9876/
[INFO] 11 04 2021 19:41:39.456:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
[INFO] 11 04 2021 19:41:39.463:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 11 04 2021 19:41:39.503:ERROR [launcher]: Cannot start ChromeHeadless
[INFO]  /usr/src/app/webcomponents/tool/src/main/frontend/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
```

I tried with `markhobson/maven-chrome:jdk-8` and it gives a different error
```
[INFO] 11 04 2021 20:12:40.965:INFO [karma-server]: Karma v6.3.2 server started at http://localhost:9876/
[INFO] 11 04 2021 20:12:40.967:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
[INFO] 11 04 2021 20:12:40.974:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 11 04 2021 20:12:41.303:ERROR [launcher]: Cannot start ChromeHeadless
[INFO]  [0411/201241.026780:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

I found a fix for this though which was to add `--cap-add=SYS_ADMIN` to the start which was from https://github.com/puppeteer/puppeteer/issues/3451#issuecomment-523961368. This worked!


I didn't try `atlassianlabs/docker-node-jdk-chrome-firefox` but it's over a year old and looks to include really old dependencies.

**Comment by jonespm** [comment]
It looks like this runs fine as "docker run" but not supported in "docker build", which is what the instructions for the Docker *in* Sakai suggest. I'm not sure if that's going to work anymore without skipping tests or re-doing how the build is done. 

I a[pplied the fix to the builder](https://github.com/sakaicontrib/docker-sakai-builder/commit/967776794ee515151b6d53b2069d3742644b981d) I use and it does work fine there.

**Comment by ern** [comment]
Been thinking about moving the headless tests into a different maven profile, what do people think about that?

**Comment by profmikegreene** [comment]
I have no opinion on the maven profile and agree that docker image from atlassian is a bit old, i ended up switching back to the markhobson one for my local machine but ideally, our builder iamge would also include node since web-components already uses it and I'd love to add node to library as well. Unless i'm missing something with how our maven-node plugin works, I can't run node or npm commands directly in the builder, only the ones predefined in the POM.

Perhaps we should publish our own images? Is hosting a docker image repo something the nightlies could do so we can avoid docker hub and github container repo costs?

**Comment by ern** [comment]
Were going to be removing this soon so going to close this.

**Pull request closed without merging**
