### PR TITLE
SAK-33107 add the ability to scale point grades

### PR DESCRIPTION
**Pull request by steveswinsburg**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Why does this PR introduce so many whitespace changes?

**Comment by steveswinsburg** [comment]
It's the codestyle settings I use. I've been meaning to send it around to
all Devs as it allows us to get things consistent and find a bunch of
actual code issues that the bots would pickup before committing

**Comment by ottenhoff** [comment]
It's been our practice for years now not to accept changes that modify whitespace without making a functional change

**Comment by steveswinsburg** [comment]
It either happens here or in another PR. Every file I touch is being cleaned up automatically. Unless I disable the cleanup on save which I don't particularly want to do as it fixes a whole heap of other issues. I'll see if I can disable just the whitespace corrections.

**Comment by ern** [comment]
Steve I understand your concerns but for the purposes of this PR could we remove the white spacing changes and let that play out on the email list?

**Comment by ern** [comment]
@steveswinsburg can you fix the conflicts here waiting on this for the branch?

**Comment by ern** [comment]
This was discussed in the Core Meeting
see https://etherpad.nightly.sakaiproject.org/p/core-2018-10-16
and a consensus was reached that it doesn't make sense to accept a PR with large amounts of non functional changes.

**Comment by steveswinsburg** [comment]
I am in the middle of updating. Please do not close my PRs without consulting me first.

**Comment by steveswinsburg** [comment]
I have backed out the whitespaces changes in GradebookServiceHibernateImpl. That should not have gone in and I missed it in the original diff. I have adjusted my codestyle preferences to only do the formatting on modified code from now on. Hopefully we can get consensus on a codestyle at some stage.

**Comment by ottenhoff** [comment]
The 10 people on community core call unanimously decided to close this issue. What's with merging your own PR without community consensus?

**Pull request merged**
