### PR TITLE
SAK-31538 - Removing conversion scripts from Sakai 11, adding readme

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by juanjmerono** [comment]
I'm wondering how could this affect the future cherry-picks, I mean if you add a change in Sakai that requires one change in the conversion script, you would send a PR with changes in code and also in conversion script files. Then when someone needs to cherry-pick the commit it will fail because the conversion script is missing in 11.x branch, I know it's easy to solve the conflict but the final commit in 11.x branch won't match the original one and that will cause that "git cherry" command return a false positive showing that the original commit is still missing in 11.x even you already cherry pick it (solving the conflict)

Also when you have to create the future branch from master you must remove this folder again from the new created branch. I think the best option is remove the conversion scripts from all branches and move to another repo (with only master branch), although developers have to clone two repos and send two different PR's in case of database and code changes, I guess jira could show both PR's.

**Comment by juanjmerono** [comment]
Anyway, the commit message has a typo SAI instead of SAK :)

**Comment by buckett** [comment]
Locally our workflow is often to fix something on our local 11 fork, test it, then cherry-pick the commit onto a new branch based off the sakai master branch to feed the change back to the community, if the upgrade scripts aren't there it means we would need a different workflow for these sort of changes.

**Comment by jonespm** [comment]
What Earle and I were talking about on the core team meeting and a little after is after 11.0 is released, moving this entire reference directory (conversion script and all) out to it's own separate repository. Then it could be compiled and deploy independently. 

However if we did that right now, I don't think we'd get the release out today and it wouldn't be able to build without released artifacts. I really just wanted *this* space empty for the 11.0 release, and I feel like even for 11.1 we can get this out of here and maybe have it linked up there as a subtree.  I think it's okay if you'd rather close this and clean it all up in a few weeks. Just whoever gets 11.0 might also pick up out of date conversions and not know it.

**Comment by jonespm** [comment]
Well yeah, that's the eventual dream, but it will still have the same problems of needing to keep these directories correct and in sync. Yeah, I don't know if a subtree would make it any better, at unless maybe it was *only* the conversions that were in there. And yeah, I think if we just had a README there that said "please see master for the most up-to-date conversions" people wouldn't notice the readme. :(. I guess I can just do that though if you think it will make merging better until we figure out a better plan for this.

**Comment by steveswinsburg** [comment]
What's the rationale for changing this? What is the problem with having
these files in here?

sent from my mobile

**Comment by jonespm** [comment]
@steveswinsburg We've found in the past trying to keep documentation branches in sync will eventually lead to them being out of sync. And at time of release the scripts are never tested enough, there will for sure be something missing or incorrect. A ton of jiras right near the end of the release were just fixing up these scripts.

There are also conversions in the 11 branch script that weren't in master discovered this week so that just adds more work to a release manage. And the tags will never be updated, so anyone using those will probably have conversion scripts that are outdated.

The source I'd trust is the documentation page and that has direct links (also to the version in trunk since 2.9.3) but not everyone reads that. 

It's more of a problem I think of tags and lack of people testing these (especially Oracle). In any case I've closed this and just put a README there that likely nobody will ever read.

**Comment by steveswinsburg** [comment]
This folder of scripts has worked for the past decade. Without an automatic upgrader, I don't see how moving this stuff somewhere less visible will achieve much.

Its trivial to run Liquibase against a clean install vs upgraded install. Perhaps this needs to be in the tester's toolkit.

**Pull request closed without merging**
