### PR TITLE
SAK-29834 Student view has complete instructions for assignment submi…

### PR DESCRIPTION
**Pull request by ouit0408**
…ssion.

Edited the 'assignment.properties' file to include the complete message.

### CODE REVIEW

**Comment by ern** [comment]
I don't recognize this contributor do you have a Apereo/Sakai CLA submitted?

**Comment by ouit0408** [comment]
Yes I have submitted the Apereo/Sakai CLA.

**Comment by ottenhoff** [comment]
How about:

Don't forget to submit! A successful submission will provide a confirmation id.

**Comment by lardo-de-arnaud** [comment]
To summarise: the proposal is to change the current message 

  "Don't forget to submit." 

to

   "Don't forget to submit, make sure you get a submission confirmation on screen." 

Sam suggests

    "Don't forget to submit! A successful submission will provide a confirmation id."

I don't agree with Sam's comment because by explicitly mentioning it there's an implication that the confirmation ID is in some way important. The student may then think that maybe it should be copied. 

The student will get an email confirmation containing the ID if they successfully submit so there is no need for them to separately note down the complex ID. Based on all this, may I suggest:

   "Don't forget to submit your work. Confirmation will be displayed on screen and a receipt emailed to you."

**Comment by buckett** [comment]
Ok, how can we move this on?

**Comment by lardo-de-arnaud** [comment]
@ottenhoff 

Is this acceptable 

"Don't forget to submit your work. Confirmation will be displayed on screen and a receipt emailed to you." 

It would be good to move this along.

**Comment by ottenhoff** [comment]
Don't forget to submit your work! A confirmation message will be displayed after submission.

**Pull request merged**
