### PR TITLE
LSNBLDR-646 Remove unnecessary index

### PR DESCRIPTION
**Pull request by ottenhoff**
The index on lesson_builder_q_responses(questionId, userId) makes the index on just questionId unnessary

### CODE REVIEW

**Comment by juanjmerono** [comment]
You forget to add the jira ticket to this PR, isn't it?

**Comment by clhedrick** [comment]
fine with me. I'd prefer a jira entry if possible.

**Comment by clhedrick** [comment]
Do we want the 10.x and 11 conversion scripts to remove the extra index?

**Comment by ottenhoff** [comment]
Please learn about the squash commit option during merging.... This PR merge brought in 7 very ugly commits into master instead of one nice and clean commit .......

**Comment by bjones86** [comment]
Can we possibly revert this and re-merge it with a squash?

**Comment by ottenhoff** [comment]
Git revert will add in a revert commit plus a merge of the revert .... and then a new squash commit .... so it will add another 3 commits total .....

**Comment by bjones86** [comment]
Ahhh thumbs down then.

**Comment by clhedrick** [comment]
When I went to integrate this into 10.x, I noticed that there are some files it missed, so there's going to be yet another PR. Obviously I should have looked more carefully before accepting.

**Comment by clhedrick** [comment]
Also, it drops the wrong index in Oracle. I need to take time, look carefully, and clean this all up.

**Pull request merged**
