### PR TITLE
SAK-32416 - Replace jQuery datepicker icon to use font-awesome

### PR DESCRIPTION
**Pull request by mpellicer**
Replace jQuery datepicker icon to use font-awesome

### CODE REVIEW

**Comment by ottenhoff** [comment]
CC: @mclare 

How should we handle accessibility here? What if we add an aria-label to the fontawesome icon to say "Datepicker field"? Or should we be more verbose?

**Comment by mpellicer** [comment]
@ottenhoff True! Thanks Sam.

**Comment by mclare** [comment]
Doing a little research.  To confirm, we're considering replacing the silk icon image /library/image/silk/calendar.png with font awesome implementation?

The accessibility concern is more about the field than the picker (though jQuery's picker handles keyboard nav well and zooms well).  When I've talked with users with visual disabilities before they've been less interested in the picker and more interested in a simple, standardized text field to type a date into.  Instructions/assurances about that field and format might be the way to go.

**Comment by mclare** [comment]
Based on Hans Hillen of TPG's example here https://hanshillen.github.io/jqtest/#goto_datepicker the following ARIA labels for the form input would help:

- aria-haspopup   **should** be true,
- aria-owns also could be set, but requires the id of the jQuery item and that would need to be available/accurate or risk making things worse.

The label is another issue.
My _static_ inspection of the Calendar tool in nightly Master currently suggests that the <label> tag does not encapsulate the input tag, nor is their a aria-labelledby property. Two options there:

1. The input gets the current label properly associated with it through one of the 3 means (maybe there's more than 3?)
2. It stays as-is, and aria-label="Please enter a date from the pop calendar or directly in the following format year/month/day"

**Pull request merged**
