### PR TITLE
SAK-31886 : Sites Nav misplaced (Mrphs-sitesNav__menuitem)

### PR DESCRIPTION
**Pull request by SedueRey**
I've tried to respect all ARIA roles for the dropdown item, I think "separator" is appropiate but I'm open to any comment.

@mclare, what do you think?

### CODE REVIEW

**Comment by ottenhoff** [comment]
@mclare any comment? We need to get a fix into master so other UI changes can proceed ....

**Comment by mclare** [comment]
In Master SAK-31886 issue is resolved for most site titles, but I'm still seeing symptom, SAK-31886, which breaks that instance for all.  So I assume I've got to apply this patch to a local copy of master to review, and that's testing my git/vagrant skills at the moment.  Will report back.

**Comment by ottenhoff** [comment]
No, we're just asking if his fix is acceptable from an a11y perspective. Look at the Files changed tab in Github and you can see he uses the aria-role "separator" on one of the two spans.

**Comment by mclare** [comment]
Syntactically, the initial role of menuitem and addition of separator look approriate for Sakai, and match their intent in the spec.
https://www.w3.org/TR/wai-aria/roles#menuitem
https://www.w3.org/TR/wai-aria/roles#separator

**Pull request merged**
