### PR TITLE
SAK-30924 Drag and Drop upload has'Overwrite existing files' function…

### PR DESCRIPTION
**Pull request by ouit0408**
…ality.

Added overwrite boolean for 'doDragDropUpload' method which checks if user
wants to overwrite files.

### CODE REVIEW

**Comment by ottenhoff** [comment]
I commented on the JIRA.

This seems like unnecessary clutter to me .... we could add 20 checkboxes on this page .... not sure why this is important enough to deserve a checkbox.

**Comment by lardo-de-arnaud** [comment]
didnt we establish that we DID want this feature (on a separate mail list conversation). This was because the default behaviour is to NOT overwrite existing files which is counter intuitive.

**Comment by lardo-de-arnaud** [comment]
so could this be merged then? 

Everybody's in agreement that it's desirable arent they. 

I'd even go so far to say the current behaviour is a bug (but that's just me all over isnt it?)

**Comment by lardo-de-arnaud** [comment]
so is this going to be merged. All parties seem to think it's a good idea

**Comment by lardo-de-arnaud** [comment]
actually, we need to include https://jira.sakaiproject.org/browse/SAK-31794 in this PR. I'll get Nick to update this PR

**Comment by lardo-de-arnaud** [comment]
This PR is now ready to merge, can somebody do it?

**Comment by ern** [comment]
Check to see if old file can be moved to trash.

**Comment by lardo-de-arnaud** [comment]
the idea is that the display of the option is behind a property, the default value of the property would be "dont display the option in the UI".

People would like a pop up list of files that will be overwritten with "continue" & "cancel" buttons AND / OR people would also like the overwritten file to be moved to Trash. 

If the above is done the there's no need to protect via a property

NB: the same should be done with "upload new version" in Resources > Actions as well (maybe on a separate Jira)

this is also loosely related to https://jira.sakaiproject.org/browse/SAK-31947 (WL-2521 @ Oxford0

**Comment by lardo-de-arnaud** [comment]
@ern We've just had a discussion here and noted that when you do an "Upload New Version" via Resources > Action menu, the file isnt moved to Trash, so why should it be done here. The improvement is a non trivial fix. I am very happy for this to me merged (pretty much) as is and will create a new Jira to say that both "Upload New Versions" should move the original file to Trash.

**Comment by lardo-de-arnaud** [comment]
given my above comments, can this be merged and a new Jira created to say when a file is overwritten either in resources > upload new version  OR drag and drop upload the previous copy should be moved to Trash?

I agree this extra feature is a great improvement but is separate from the issue being covered here.

**Comment by bjones86** [comment]
Needs rebasing...

**Comment by fostersdesign** [comment]
I would recommend a property to enable the visibility of the checkbox and another property to set the default status of the checkbox (checked or not checked)

**Comment by jonespm** [comment]
I feel like if this got added there's also no point for the "Upload New Version" feature anymore, so that could be removed to simplify the workflow. Upload new version just is the same as upload.

I'd also feel like refactoring all of this into kernel "addResource" with a parameter for "boolean overwrite" makes more sense than all this code duplication is a better idea.

**Comment by lardo-de-arnaud** [comment]
Shawn: we'll do the requested properties.

Matt: I tend to agree that upload new version should be the default, however, in the case of "single file upload" (Resources > Actions > Upload new version" it may make sense to have a confirmation check "Are you sure you wish to overwrite this file". It is fairly easy to accidentally select "Upload New Version" alongside the wrong file. The idea of making 'overwrite' the default action is totally separate issue though - I think it needs a Jira of its own.

**Comment by buckett** [comment]
Rebased branch and opened PR #3975

**Pull request closed without merging**
