### PR TITLE
SAK-43104 Samigo allow user with permission assesment.grade.any to grade

### PR DESCRIPTION
**Pull request by ottenhoff**
…

### CODE REVIEW

**Comment by ottenhoff** [comment]
> Wish Samigo would use permissions vs the Role checks.

yeah do you know any of the history here? when were these realm permissions added (and then never used)?

**Comment by ern** [comment]
They're currently not in the code base, I would use the ones in SamigoConstants

**Review by ern — CHANGES_REQUESTED** [review]
They're currently not in the code base, I would use the ones in SamigoConstants

**Comment by ottenhoff** [comment]
okay switched to constants

**Review by ern — APPROVED** [review]

**Pull request merged**
