### PR TITLE
S2U-35 Lessons: View items based on grade - MASTER

### PR DESCRIPTION
**Pull request by stetsche**
Conversion scripts: https://github.com/sakaiproject/sakai-reference/pull/235

https://sakaiproject.atlassian.net/browse/S2U-35

### CODE REVIEW

**Comment by mpellicer** [comment]
Could you rebase this after #12241  ? Thanks!

**Review by mpellicer — CHANGES_REQUESTED** [review]
Needs rebase

**Comment by mpellicer** [comment]
Needs rebase again ?

**Comment by stetsche** [comment]
As the build here failed when installing npm,  I built it again locally and it ran fine. I'll just rebase again to fix the small conflict with S2U-4 on the master pom.

**Comment by stetsche** [comment]
Rebased again. `master` is building, should be good to go.

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
