### PR TITLE
SAK-39962 Add jquery tablesorter webjar

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by ern** [comment]
I set WIP until maven central contains the version 2.27.7

**Comment by ottenhoff** [comment]
http://central.maven.org/maven2/org/webjars/tablesorter/2.30.3/

**Comment by jonespm** [comment]
Did you test the tools that used the 2.0.3 table sorter to make sure they still worked without client side error? (Looks like polls and msgcntr)

**Comment by ern** [comment]
Yeah when I remove the WIP I will have tested this in all the locations that loaded the JS

**Comment by jonespm** [comment]
@ern Okay, add me back as a reviewer if you need after you remove the label. I probably won't notice otherwise.

**Comment by ern** [comment]
- refactored all the locations in sakai to use the same version of the plugin.
- BasicLTI tool had the most issues, Dr Chuck please review if i removed to much!
- Removed js in tools using these libs
- Removed the static files from library
- Updated headscript includeWebJarLibrary to handle css

```
<script type="text/javascript">includeWebjarLibrary('jquery.tablesorter');</script>
```

**Comment by csev** [comment]
Make sure to keep the scrolling working - some schools have *tons* of LTI links.

**Pull request merged**
