### PR TITLE
SAK-30364 Fix the permission issue in SubethaSMTP.

### PR DESCRIPTION
**Pull request by buckett**
We already have a Session class imported so it needs to be fully qualified. We also add some checking to make sure the object is correctly initialised.

### CODE REVIEW

**Comment by jonespm** [comment]
Do you know if this would cause a problem or not if the postmaster user didn't exist in Sakai (like if someone decided to delete it?). I'm thinking it might just still fail the unlock check, just with the user postmaster instead of null. In the original code it has 

```
                User postmaster = null;
                try
                }
                   postmaster = userDirectoryService.getUser(POSTMASTER);
		}
		catch (UserNotDefinedException e)
		{
			M_log.warn("service(): no postmaster, incoming mail will not be processed until a postmaster user (id="+POSTMASTER+") exists in this Sakai instance");
			mail.setState(Mail.GHOST);
			return;
                 }
```

Maybe this was just as a double check?

**Comment by buckett** [comment]
I think you're correct, I've implemented the previous behaviour of swallowing any messages when there isn't a postmaster user and writing a message to the logs.

Thanks.

**Comment by buckett** [comment]
And updated the tests to cover the case where there isn't permission.

**Comment by jonespm** [comment]
Tested locally, LGTM, thanks!

**Pull request merged**
