### PR TITLE
LSNBLDR-527 Added confirmation screen when deleting a Lessons page co…

### PR DESCRIPTION
**Pull request by ouit0408**
…mponent

Have added a separate delete-confirm.js for all the confirmation messages
before actually removing items from Lessons tool.

### CODE REVIEW

**Comment by buckett** [comment]
This one has merge conflicts.

**Comment by ouit0408** [comment]
This functionality has been implemented in the sakai trunk, do we need to merge this?

**Comment by buckett** [comment]
No, what's the difference in implementation?

**Comment by ouit0408** [comment]
There is not much difference in implementation of the delete confirmation thus closing this pull request.

**Pull request closed without merging**
