### PR TITLE
SAK-28971; direct URLs not mapped in site duplicate

### PR DESCRIPTION
**Pull request by clhedrick**
This should work as long as the site doesn't change the URL shortener to bitly. Implementing it there requires expertise with bitly.

### CODE REVIEW

**Comment by clhedrick** [comment]
I think this is OK. I didn't check it in myself because it involves two modules that I'm not a maintainer for.

**Comment by clhedrick** [comment]
wrong request

**Comment by clhedrick** [comment]
it looks to me like I closed the wrong request. As far as I know this is still valid. We're going into production with it tomorrow.

**Comment by clhedrick** [comment]
Ah. I see why I closed it. This got two different patches. It should only be one

**Comment by clhedrick** [comment]
Wrong. I checked the actual changes, and this agrees with the original commit. As noted, the fix is going into production at Rutgers. It's been tested pretty carefully.

**Comment by ottenhoff** [comment]
Hi Chuck,

I recommend creating a branch per issue you work on. The problem with submitting a PR from master is that any additional commits you make to your master will be reflected in the PR.

**Comment by bjones86** [comment]
The whole process is documented pretty well @ https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup

It will walk you through the process of creating branches, squashing commits, etc

**Comment by clhedrick** [comment]
please hold review of this until I redo the PR from a branch. It's accumulated additional diffs that are unnecessary.

**Comment by clhedrick** [comment]
I'm going to issue a new pull request for this

**Pull request closed without merging**
