### PR TITLE
SAK-44860 Incorrect word usage in Date Manager confirmation message.

### PR DESCRIPTION
**Pull request by MRutea**
https://jira.sakaiproject.org/browse/SAK-44860

### CODE REVIEW

**Comment by ottenhoff** [comment]
This is a good change. Thank you.

**Review by fostersdesign — COMMENTED** [review]
Thanks for making this change, @MRutea. 

The English lines don't need to be in those non-English language translation files. You can remove those lines from those files.

**Review by mpellicer — CHANGES_REQUESTED** [review]
Looks good to me thanks Marcelino, just remove the lines from the non-english files (_ar, _fr_FR and de_DE).

**Comment by MRutea** [comment]
Thank you for your comments.
Changes made.

**Comment by mpellicer** [comment]
Lines are not removed yet.

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
