### PR TITLE
SAK-30365 jquery-i18n-properties causes Ajax deprecation warning in C…

### PR DESCRIPTION
**Pull request by adrianfish**
…hrome

Added version 1.2.1

### CODE REVIEW

**Comment by juanjmerono** [comment]
Is this reference still needed or must be changed also?
https://github.com/sakaiproject/sakai/blob/master/roster2/src/webapp/WEB-INF/bootstrap.jsp#L86

**Comment by adrianfish** [comment]
@juanjmerono That can stay. We'll still keep the old version alongside. I've got a ticket in for modifying roster2 to do everything async and I'll switch to 1.2.1 in that.

https://jira.sakaiproject.org/browse/SAK-30366

**Comment by ottenhoff** [comment]
Here is how to use webjars:

  https://github.com/ottenhoff/sakai/commit/0ef707f6ac2e11914925fe47809111c3d47477d4

org.webjars.bower will build your new 1.2.1 version automatically and will have it deployed to Maven Central in the next 4 hours.

**Comment by juanjmerono** [comment]
Is the webjars change going to be merged into 11.x? Because this jira SAK-30365 has "11 status" but this SAK-30278 not :disappointed:

**Comment by adrianfish** [comment]
It needs merging into 11.x and 10.x, otherwise we're going to keep getting the deprecated warnings.

**Comment by adrianfish** [comment]
@juanjmerono  Can you merge this, please? This commit can then be picked back into 11.x and 10.x. The webjars stuff looks like it's going to be a 12.x thing, so the webjars src change can be applied to 12.x only.

**Comment by ottenhoff** [comment]
If you are targeting 10.x, I don't recommend using webjars

If you are targeting 11.x only, then I think webjars are a good idea.

**Comment by adrianfish** [comment]
Okay, I'll add 1.2.1 as a webjar dependency but leave 1.0.9 in place for
backwards compatibility. I'll put something out on the list asking who's
using it. We'll deprecate 1.0.9 in other words. 1.2.1 is fully backwards
compatible, so people should be able to move onto that.

We'll have to patch 10.x so I'll take Juanjo's advice on that one. I kind
of wish roster2 was a contrib still, so I could pick stuff around.

**Pull request closed without merging**
