### PR TITLE
KNL-1575 Session cluster cookie fix

### PR DESCRIPTION
**Pull request by jayee**

### CODE REVIEW

**Comment by ottenhoff** [comment]
@buckett can you approve or comment?

**Comment by jayee** [comment]
We have multiple nodes in the cluster and we have:

```
memory.cluster.enabled=true
memory.cluster.server.urls.count=1
memory.cluster.names.1=org.sakaiproject.tool.impl.RebuildBreakdownService.cache
```
The suffix of the cookie value is the serverId, I have seen.

I have to investigate this a bit more, but I think you're right.
Although "following link" -> login -> redirect to link did not work before my change. And the code comments on the old if-statement was really odd.

**Comment by buckett** [comment]
Closing this one for now, please re-open if you still feel this change, or a version of it is still needed.

**Comment by jayee** [comment]
Follow up after more investigation:
It is tomcat inserting its own JSESSIONID cookie, when coming back from ADFS login. As the name is the same as the sakai session cookie, sakai tries to interpret it as a sakai session id and fails.

Is there are reason sakai is using the same name as tomcat for its session cookie?

I can change tomcats session cookie name in a global context.xml, or
change sakai cookie name (not preferable I think), or
in findCookie add something like
```
// If no suffix on cookie value, throw away
if (suffix != null && !cookie.getValue().contains(DOT)) {
   validCookie = false;
}
```

**Pull request closed without merging**
