### PR TITLE
SAK-29176 - Allow samigo to be linked to existing, non-externally maintained gradebook items

### PR DESCRIPTION
**Pull request by fgeraci**
... when published, and record grades, if submissions were available in test.

[SAK-29176](https://jira.sakaiproject.org/browse/SAK-29176)

### CODE REVIEW

**Comment by steveswinsburg** [comment]
This is in conflict, can you please merge the latest master in to the branch.

**Comment by fgeraci** [comment]
@steveswinsburg I just did. Thanks.

**Comment by ern** [comment]
Instead of merging it should've been a rebase can you please update this PR with a rebase.

**Comment by ottenhoff** [comment]
The merger can always use the new Github squash functionality to get a nice and clean commit without having to worry about the ugly commits in a PR:

   https://github.com/blog/2141-squash-your-commits

**Comment by ern** [comment]
In this case the merge commit 95c74e2 shouldn't be part of the commit, which is why the user needs to rebase.

**Comment by ottenhoff** [comment]
So just squash it for them in the Github GUI when doing a Merge pull request .....

**Comment by ern** [comment]
Since the merge commit has no effect here, I think Sam is right.

**Comment by fgeraci** [comment]
@ern , something doesn't seem right, i can't squash the commits as Sam suggests since it is during the merge pull requests.... anyhow.

**Comment by fgeraci** [comment]
@ern @steveswinsburg this one got messy. I will update it and re create the pull request.

**Pull request closed without merging**
