### PR TITLE
SAK-48471: Fix NPE in PortletIframe line 1360

### PR DESCRIPTION
**Pull request by zhuoY121**

### CODE REVIEW

**Review by csev — APPROVED** [review]
Looks good to me.

**Comment by csev** [comment]
Hey @ern - This build keeps failing - I think somehow it is because of the revert has not been "noticed" by this branch.

**Comment by ern** [comment]
Hi Zhuo looks like you will need to rebase your branch

**Comment by zhuoY121** [comment]
> Hi Zhuo looks like you will need to rebase your branch

Hi Earle, thanks for the suggestion!

**Pull request merged**
