### PR TITLE
SAK-31081 - Statistics does not use updated tool/info icons

### PR DESCRIPTION
**Pull request by SedueRey**
image

I've updated the branch, my mistake

### CODE REVIEW

**Comment by alejandrogj** [comment]
LGTM

**Comment by juanjmerono** [comment]
It is worth to add some font awesome icon to replace bullet_feed.png removed from nested items?

**Comment by SedueRey** [comment]
Does it have sense? I mean, it's not a tool

**Comment by juanjmerono** [comment]
Just add a screenshot to see how it looks like, maybe is not needed.

**Comment by SedueRey** [comment]
It's not ok, I made a mistake ... I'm going to updated this PR, don't merge yet, please

**Pull request merged**
