### PR TITLE
SAK-48539 T&Q: Unable to select groups

### PR DESCRIPTION
**Pull request by kunaljaykam**
https://sakaiproject.atlassian.net/browse/SAK-48539

Screenshot from 2023-02-27 16-32-50

### CODE REVIEW

**Comment by mpellicer** [comment]
LOL, I was waiting for this because I can't test https://sakaiproject.atlassian.net/browse/SAK-48424, thanks @kunaljaykam !

**Comment by mpellicer** [comment]
Can you paste some screenshots about the group picker for me? Thanks!

**Review by mpellicer — APPROVED** [review]
Nice work Kunal thanks!

**Comment by kunaljaykam** [comment]
Thank you :)

**Comment by mpellicer** [comment]
Nah, you're welcome, doing a great job!

**Pull request merged**
