### PR TITLE
SAK-45694 Delete jsf/

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by bjones86** [comment]
wow, are there no more dependencies on this?

**Comment by maurercw** [comment]
I'm pretty sure that some jsf2 things point back at deployed artifacts in jsf-resource.  Might want to double check that before killing it off.  jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/Configuration.properties has a property where stuff can be found, and it's still set to jsf-resource.

**Comment by jonespm** [comment]
Good catch @maurercw, that does look used still. We could delete everything else and just leave that directory there, or move it somewhere else. It looks like it packages everything in there as a .war file.

**Comment by ern** [comment]
This PR was discussed at the Core Call on 6/29/2020 and we believe it to make sense to keep the jsf 1 bits in for a release cycle to give contrib tools or other jsf1 tools that institutions may have a chance to migrate.

**Pull request closed without merging**
