### PR TITLE
SAK-32303 Allow stopping of some jobs

### PR DESCRIPTION
**Pull request by buckett**
Don't allow concurrent execution of the AuthzGroupProviderSync job as it doesn't make sense. Locally we've back an issue where multiple copies of this job were running concurrently and killing system performance. Also allow jobs to be stopped from the administration interface for some of the long running jobs.

We need to switch to spring injected jobs to allow stopping as you need a different instance of the jobs for each run to be able to cancel the correct one.

### CODE REVIEW

**Comment by buckett** [comment]
If we have a site with a provided membership and nobody logs into Sakai who is a member of that site the membership won't get re-updated from the provider.

If someone then sends an email to that site or an automated announcement happens it will be sent to all the members of the site.

We run this job to ensure that every site is updated at least once a day from the provider.

**Comment by buckett** [comment]
I think this needs to have bean aliases so that the old jobs continue to work.

**Comment by buckett** [comment]
Actually it's more complicated, because all the old jobs had the same job class we need to look inside the actual job data and because this is a blob in the DB (yey) we can't just do this with SQL migration. Doing it at the startup of the job schedules seems sensible.

**Comment by ern** [comment]
I would probably just provide some migration where the old jobs are removed and then you add this to the release notes that if your using these jobs you need to recreate them.

**Comment by buckett** [comment]
Ok, written some migration code, just need to test so don't merge yet.

**Comment by buckett** [comment]
Yep, and the migration works in my local testing.

**Pull request merged**
