### PR TITLE
SAK-48077 GradebookNG scrollbars are not visible on hover in Chrome browsers (22.x)

### PR DESCRIPTION
**Pull request by austin48**

### CODE REVIEW

**Comment by ern** [comment]
@austin48 is there a screenshot you could share?

**Comment by austin48** [comment]
video added to the jira

https://sakaiproject.atlassian.net/browse/SAK-48077

**Comment by ern** [comment]
@austin48 can you resolve the conflicts and is this still an issue?

**Comment by austin48** [comment]
it looks like this is no longer an issue on 22.x.  An additional fix, SAK-47974 was merged into 22.x

https://github.com/sakaiproject/sakai/commit/4a80f9fb84ee3baa10cb4e858b76bb07aba007f5

that JIRA was also committed to master in https://github.com/sakaiproject/sakai/pull/11416

I'll go ahead and close the PR

**Pull request closed without merging**
