### PR TITLE
KNL-1433 setting default site quota to 1GB. 

### PR DESCRIPTION
**Pull request by ottenhoff**
This is the long-term behavior of Sakai that was changed in Sakai 10.6.

/CC: @bjones86 can you review the one functionality change here the *fileSizeKB* conditional

### CODE REVIEW

**Comment by bjones86** [comment]
Yep, looks good to me. Thanks @ottenhoff!

**Comment by ern** [comment]
The setting in spring will take precedence over these...

**Comment by ottenhoff** [comment]
How do you figure?

**Comment by bjones86** [comment]
I'm not sure as to the why, but in my testing I found that the setting in the XML file in kernel, which is the one I think @ern is referring to, always took precedence if you didn't set a value explicitly in sakai.properies. This was part of the original bug where the (old) default of unlimited wasn't being enforced.

https://github.com/bjones86/sakai/blob/fb22a185b729eda84ae8b76e367ec3c42b2e3ff2/rights/rights-impl/pack/src/webapp/WEB-INF/components.xml

https://github.com/bjones86/sakai/blob/fb22a185b729eda84ae8b76e367ec3c42b2e3ff2/kernel/kernel-component/src/main/webapp/WEB-INF/content-components.xml

**Comment by bjones86** [comment]
I just tested this again. With default/no sakai.properties, 0 still ends up as the default:

"This site is currently using (0 KB ) of its Unlimited quota."

The setting in the XML file really does need to be updated to reflect the defaults set in the Java code/advertised in sakai.properties.

**Comment by ern** [comment]
should've just removed the property from the bean.

**Comment by bjones86** [comment]
Yep, either option would work. I wasn't sure if there was a valid reason for it being in there when I did my original PR, so I just updated the value.

**Comment by jonespm** [comment]
Yeah, well if you do that it breaks for anyone that has this property defined. Really that's the trade off. It's being set because this bean property is calling setSiteQuota after the object is created, which takes the highest precedence. You either have to set the property to match in the bean, or remove the property from the .xml which would cause it to not work at all anymore.

**Comment by jonespm** [comment]
@bjones86 The biggest valid reason for it remaining there is backward compatibility with people who have that property in their properties file. If we just removed it it would cause the startup to crash per https://jira.sakaiproject.org/browse/KNL-791

**Comment by bjones86** [comment]
Ahh, gotcha. Makes sense then. Thanks for the info @jonespm! Looks like we just need to update the value in the XML file to reflect the default and it should be good to go.

**Comment by jonespm** [comment]
Yeah, we could change the setter to issue warnings, or maybe even consult another SCS property. There's a lot of options. But it didn't seem like removing the setters or the beans was really a good idea unless we could protect spring from running the setters through some type of reflection pattern on that other ticket.

**Comment by bjones86** [comment]
Hmm ya, seems to me like that would be a lot more work for very little gain.

**Comment by jonespm** [comment]
It looks like if you remove the value completely from the XML, the property can still be set via sakai.properties. It's just when the setter is removed it causes a problem. So I'd just remove these properties from the components XML.

**Comment by bjones86** [comment]
Sounds like a plan to me.

**Pull request merged**
