### PR TITLE
SAK-32673 : Create forum/topic not working with open+close dates

### PR DESCRIPTION
**Pull request by frasese**
Please read the JIRA [SAK-32673](https://jira.sakaiproject.org/browse/SAK-32673) for more info.
Here is one posible solution for Spring/Hibernate problem.

The logic problem will be solved in this other JIRA [SAK-31935](https://jira.sakaiproject.org/browse/SAK-31935)

### CODE REVIEW

**Comment by buckett** [comment]
Is this because the transaction manager isn't connected correctly? Does making the transaction annotation on the `ContextMappingDAO` to:

    @Transactional(transactionManager = "org.sakaiproject.springframework.orm.hibernate.GlobalTransactionManager")

work?

**Comment by frasese** [comment]
Hi @buckett,
no, I've tested it and manually pointing the annotation to the transaction manager does not work. Also, this is supposed to be done in the components.xml with <tx:annotation-driven transaction-manager="org.sakaiproject.springframework.orm.hibernate.GlobalTransactionManager"/>

**Comment by buckett** [comment]
`<tx:annotation-driven transaction-manager="org.sakaiproject.springframework.orm.hibernate.GlobalTransactionManager"/>` is already there.

**Comment by frasese** [comment]
Yes, that's what I tried to say. The transaction manager is already set in the components.xml, so @Transactional annotation should get the correct one.
The question is, why does not it seem to be working? Especialy with nested transactions (consequence of multiple and consecutive calls to "createDelayedInvocation")

**Comment by ern** [comment]
Anytime there is a need flush manually its usually a sign of a different issue, typically with the transaction manager. Usually the only time flush would need to be called manually is when your doing lots of updates and you periodically would call flush.

**Pull request merged**
