### PR TITLE
SAK-29579 - Associate portal icon for Feedback tool

### PR DESCRIPTION
**Pull request by mcarropellicer**
Associate portal icon for Feedback tool

### CODE REVIEW

**Comment by buckett** [comment]
Doesn't that confuse it with the help tool especially on a mobile device when you can't see the names?

**Comment by mcarropellicer** [comment]
As i mentioned in the Jira, there are other options:

I've added the same icon as help but there are so many icons that can fit this tool.
Personally i like some of them:
fa-envelope
fa-envelope-o
fa-send
fa-comments
fa-question
fa-send-o

If you want i can use another and rebase the PR, thanks for the feedback @buckett

**Comment by mcarropellicer** [comment]
@buckett changed to fa-paper-plane-o

**Comment by mcarropellicer** [comment]
Thanks @csev

**Pull request merged**
