### PR TITLE
SAK-40284 Admin-tool: Time -> Date

### PR DESCRIPTION
**Pull request by axxter99**
CreatedTime => CreatedDate
 ModifiedTime => ModifiedDate
 Site Admin cover =api

### CODE REVIEW

**Comment by ern** [comment]
Would it make sense to include these time helper methods into the UserTimeService as it seems this might be needed by other tools?

**Comment by axxter99** [comment]
@ern : UserTimeService.dateFormatLong(Date date, Locale locale)
UserTimeService.dateTimeFormatLong(Date date, Locale locale)
?

**Comment by bjones86** [comment]
@axxter99, yes I think that is what @ern is suggesting.

**Comment by bjones86** [comment]
@axxter99 looks like there's a small compile error here:

```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/travis/build/sakaiproject/sakai/calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java:[311,49] <anonymous org.sakaiproject.calendar.impl.DbCalendarServiceSerializationTest$3> is not abstract and does not override abstract method dateTimeFormatLong(java.util.Date,java.util.Locale) in org.sakaiproject.time.api.UserTimeService
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project sakai-calendar-impl: Compilation failure
[ERROR] /home/travis/build/sakaiproject/sakai/calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java:[311,49] <anonymous org.sakaiproject.calendar.impl.DbCalendarServiceSerializationTest$3> is not abstract and does not override abstract method dateTimeFormatLong(java.util.Date,java.util.Locale) in org.sakaiproject.time.api.UserTimeService
```

**Pull request merged**
