### PR TITLE
SAK-14142 Allow Velocity tools to work when webapps aren't expanded.

### PR DESCRIPTION
**Pull request by buckett**
Although this isn't recommended in the Tomcat 8 deployment guide I don't see any harm in supporting running without unpacking the webapps.

This also cleans up some of the use of velocity to use the velocity tools JAR, rather than using copy of the file.

### CODE REVIEW

**Comment by ottenhoff** [comment]
I don't completely understand this change, but I trust Matthew. @ern any concerns?

**Comment by buckett** [comment]
You can ask Tomcat not to unpack WARs when it deploys them, but some of the code in Sakai assumed that the WARs were always unpacked and so would attempt to load the files directly off disk, this would fail. In all those cases there is an alternative way to get at the contents of the file.

**Comment by jonespm** [comment]
I personally don't have any opinion on this, mostly because I generally use the sakai:deploy-exploded goal anyway and won't have war files. I also like being able to modify vm files in-place and have them exploded. Will this still work in that case if there are no war files?

**Comment by buckett** [comment]
@jonespm Good point, just cleaned out my webapps directory and sakai:deploy-exploded to check and it all seems to work fine (startup and tools).

However I don't think live reloading on VM used to work as they are all set to be cached forever (0).

**Comment by buckett** [comment]
Ah, no 0 means check every time. https://velocity.apache.org/engine/releases/velocity-1.5/developer-guide.html#resourceloaders

**Comment by buckett** [comment]
And editing in webapp works fine.

**Comment by jonespm** [comment]
Thanks for checking, I'm fine with it if it still works with exploded wars too

**Comment by ern** [comment]
Yeah I am with Matt I use the deploy-exlpoded goal as well but maybe someone out there wants to use this!

**Comment by buckett** [comment]
Cheers for looks over it.

**Pull request merged**
