### PR TITLE
SAK-32491 Library: Redesigned and standardized the design and states of Sakai buttons; introduced primary and secondary action buttons

### PR DESCRIPTION
**Pull request by fostersdesign**
https://jira.sakaiproject.org/browse/SAK-32491

My PR standardizes how buttons look and act in Sakai:
- it simplifies the button design code and variables; 
- it specifies consistent states, including hover, action, focus, and disabled; 
- it introduces primary and secondary action buttons
- it fixes cases of primary and secondary action buttons throughout the tools
- it fixes issues with the font that caused issues with button and icon alignment
- it cleans up extra tool-specific styles that are no longer necessary or that previously made the interface inconsistent

See https://jira.sakaiproject.org/browse/SAK-32491 for some before and after screenshots.

### CODE REVIEW

**Comment by SedueRey** [comment]
Looks GREAT to me

**Comment by SedueRey** [comment]
I think this change improves UX for all tools, focusing user to main action button.

**Comment by fostersdesign** [comment]
Thanks, @SedueRey !

**Comment by mpellicer** [comment]
I reviewed the PR, and I agree with @SedueRey , it's a huge improvement in Sakai.

I've reviewed the Codacy complains and all of them are false positives, especially in JSP files.

@fostersdesign I'd like to approve and merge the PR but I'd like to have your support if there is any accessibility problem or bug caused by this merge, are you ok with this?

Thank you so much for this amazing contribution.

**Comment by fostersdesign** [comment]
While developing, I was very conscious of colour contrast (particularly with the disabled state) and of the focus. I don't foresee this causing any new accessibility concerns.

**Comment by mpellicer** [comment]
Amazing @fostersdesign ! Let's merge it and do some QA, this contribution looks terrifying to me!

**Comment by fostersdesign** [comment]
Awesome, @mpellicer! Thanks!

**Pull request merged**
