### PR TITLE
SAK-29974: Nested citation lists with drag and drop

### PR DESCRIPTION
**Pull request by nicholaswilson100**
This is a new feature for Citation lists where you can create a section with a heading (and a section within that section, up to 3 levels) and drag and drop your citations into those sections, thereby building up a nested citation list (see screenshots in the Jira for examples).

You can drag and drop nested sections containing citations around and add a description to each section.The reading list title and an editable introduction is also displayed at the top of the nested citation list. The resulting nested list is then shown as such in the student view.

Most of the saving to the db is done via Ajax so that, for example, when you click 'Add Section', an Ajax request calls a method (usually in CitationActionHepler.java) which persists a CitationCollectionOrder representing a 'HEADING1' section.

Looking at the database side of things, the way that we decided to represent nested sections was in CITATION_COLLECTION_ORDER. We are adding 2 new columns (SECTION_TYPE - which is of type ENUM and can have values 'HEADING1', 'HEADING2', 'HEADING3', 'CITATION' - and VALUE which has the title of the section). The LOCATION column is used to store the nested structure.

For example, we might have this in the db:

COLLECTION_ID | CITATION_ID | LOCATION | SECTION_TYPE | VALUE

xxx | | 1 | 'HEADING1' | 'Economics'

xxx | | 2 | 'HEADING2' | 'UK Banks'

xxx | | 3 | 'HEADING3' | 'Natwest'

xxx | aaa | 4 | 'CITATION' |

xxx | bbb | 5 | 'CITATION' |

This would represent an h1 section with an h2 section in that and an h3 section in that and then 2 citations in that h3.

### CODE REVIEW

**Comment by ern** [comment]
Hi Nick,

So this looks pretty good the only thing I would recommend is to use the jquery version from reference. 
https://github.com/sakaiproject/sakai/tree/master/reference/library/src/webapp/js/jquery

The idea is that if there are js libs you are using typically we want those centrally located so that they are not spread out all across sakai. Feel free to add any missing js libs you may need to reference.

The js that is specific to the tool is in the right location.

Thanks for adding the conversion scripts.

If you could just fix the js libs i think this is ready to go, nice job ;)

**Comment by nicholaswilson100** [comment]
Hi Earle,

Good shout, makes sense. Will do.   

Thanks for looking at it,
Nick

**Comment by nicholaswilson100** [comment]
Hi Earle,

I've removed the jquery that was in citations (and the minified version) and referenced the one that's in reference.

I've also added in 3 images that I forgot to commit before: a placeholder image for a book and 2 white arrows for when you expand/collapse a reading list.

Best,
Nick

**Comment by ern** [comment]
Nick I think it makes sense to move the js jquery.sortable lib to this location https://github.com/sakaiproject/sakai/tree/master/reference/library/src/webapp/js/jquery/sortable

**Comment by nicholaswilson100** [comment]
Agreed

**Comment by nicholaswilson100** [comment]
I've moved the jquery sortable lib to reference

**Pull request merged**
