### PR TITLE
SAK-38320 add scope to matrix table

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by fostersdesign** [comment]
Sorry if I missed it: where in the changed code does the "td"s get changed to "th"s (as mentioned in SAK-38320)?

**Comment by ottenhoff** [comment]
tds are not changed to th in this PR

**Comment by fostersdesign** [comment]
The description in the JIRA references changing tds to ths. I thought that was the purpose of the ticket.

**Comment by ottenhoff** [comment]
I believe scope was the real intent

**Pull request merged**
