### PR TITLE
SAK-33833: GBNG new sakai.property to control visibility of 'Grade Entry' panel in 'Settings' UI

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-33833

We had an institutional requirement to hide the 'Grade Entry' panel in GBNG's 'Settings' UI from non-admin users. We found that users were flipping these settings without realizing the consequences, which resulted in a lot of support calls.

We implemented this behaviour behind a new sakai.property (gradebook.settings.gradeEntry.hideFromNonAdmins) which defaults to false to preserve OOTB functionality.

For those who wish to hide this setting from end users, but still be able to make the changes with an admin account, simply set the property to true.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
I don't really like settings that have to be turned off to actually enable something. There are a few of these floating around and they are confusing (disable user is a classic one). Also, as its a sakai property, it's all or nothing, it's not just for non admins, so perhaps `gradebook.settings.gradeEntry.visible = true/false` is better

**Comment by bjones86** [comment]
I implemented it this way to preserve the original functionality OOTB. Are you suggesting that you would prefer to have the default changed from `false` to `true`? Or is your comment directed at the name of the sakai.property?

**Comment by steveswinsburg** [comment]
Yeah something like gradebook.settings.gradeEntry.showToNonAdmins with a default of true.

**Comment by bjones86** [comment]
No problem, thanks for clarifying.

**Comment by bjones86** [comment]
Updated the PR based on previous comments.

**Comment by bjones86** [comment]
@steveswinsburg any further comments on this?

**Pull request merged**
