### PR TITLE
SAK-32282 NYU submenu styles and shading

### PR DESCRIPTION
**Pull request by ottenhoff**
This isn't the entire NYU skin.

This is a start at bringing over some of their elements: specifically the sub-tool menu and the shading on the boxes

### CODE REVIEW

**Comment by adrianfish** [comment]
I'm gonna try it now ...

**Comment by adrianfish** [comment]
There's a missing corner on the bottom left of the tool nav:

screen shot 2017-03-06 at 18 52 33

**Comment by adrianfish** [comment]
More weirdness in the profile tool. The tool menu is pressed up against the tool list.

screen shot 2017-03-06 at 19 01 02

**Comment by ottenhoff** [comment]
Not sure what you mean by a missing corner. I can't replicate your screenshot locally.

**Comment by adrianfish** [comment]
@ottenhoff That's odd. I can just see a missing pixel or two bottom left of the tool menu.

**Comment by ottenhoff** [comment]
Okay if you can fix it please feel free to modify my branch

**Comment by adrianfish** [comment]
I've sorted the pixel thing.

**Comment by adrianfish** [comment]
Lessons looks bad ...

screen shot 2017-03-06 at 19 29 30

**Comment by adrianfish** [comment]
Multi col pages look odd. They are jammed against the top nav.

screen shot 2017-03-06 at 19 30 51

**Comment by ottenhoff** [comment]
yup feel free to throw some padding in now or if/when we destroy the breadcrumbs

**Comment by adrianfish** [comment]
So, we're going to fix this stuff up after feature freeze? I'll stop being a pedant, if so.

**Comment by ottenhoff** [comment]
well everything going to have to be fixed eventually.... feel free to throw in a commit now or I will eventually get to it later.....

**Comment by ottenhoff** [comment]
Okay two more commits. I took care of the padding and also slightly modified footer per NYU skin:

image

**Comment by adrianfish** [comment]
Looking a lot better now, nice one. I'm not sure about the different bordering if on a multi tool page though. Don't you reckon it'd be nicer if the borders and shading were consistent.

**Comment by ottenhoff** [comment]
> Looking a lot better now, nice one. I'm not sure about the different bordering if on a multi tool page though. Don't you reckon it'd be nicer if the borders and shading were consistent?

What is inconsistent?

**Comment by adrianfish** [comment]
Multi tool page:
screen shot 2017-03-06 at 20 57 13

Single tool page:
screen shot 2017-03-06 at 20 57 21

**Comment by adrianfish** [comment]
I reckon the multi tool and single tool pages should have the same title styling and border.

**Comment by ottenhoff** [comment]
> I reckon the multi tool and single tool pages should have the same title styling and border.

I disagree. On a multi-tool page, I think NYU uses shading and borders to create distinction between the tools. On a single-tool page, there is no need for this separation. If you want to get more input, please create a sakai-dev thread and try to get some more people chiming in .... I'm happy to proceed with genereal consensus

**Comment by adrianfish** [comment]
Okay,  that's cool. I can understand that.

**Comment by lardo-de-arnaud** [comment]
really good stuff Sam. I say plough ahead and tidy things up later. I think the look is so important and the current "11" style is a rod with which to beat sakai with.

**Comment by ottenhoff** [comment]
Okay @jeffpasch and @csev how to proceed here? I have another PR after this one with color changes. This PR is changing shading and left menu and footer.

**Comment by jeffpasch** [comment]
@ottenhoff Fine by us to get these merged. As for the next PR with color changes, the sooner it gets in the better, since our dev will base their work on what you commit.

**Pull request merged**
