### PR TITLE
SAK-43609: Samigo improved wording: adding instructions about using radians in calculated questions

### PR DESCRIPTION
**Pull request by Fangcong-Yin**
https://jira.sakaiproject.org/browse/SAK-43609

Add instructions about using radians in calculated questions in Test & Quizzes: "For trigonometric functions (SIN, COS, TAN, ASIN, ACOS, ATAN), radians are used for angles."

### CODE REVIEW

**Comment by fostersdesign** [comment]
Thanks for submitting this change, @Fangcong-Yin. 

I just left a comment on the Jira issue about whether this fix solves the original issue with the students not knowing to use radians. We'll see what Sam responds with.

**Comment by fostersdesign** [comment]
As this is @Fangcong-Yin's first contribution, I've confirmed we have a CLA on file already. Thanks!

**Comment by bjones86** [comment]
More changes are expected here, according to the comments on the JIRA ticket.

**Comment by ern** [comment]
Closing as this is stale now, reopen if it's updated

**Pull request closed without merging**
