### PR TITLE
SAK-45457 Lessons embedded announcements displays messages scheduled …

### PR DESCRIPTION
**Pull request by austin48**
…to open in the future

### CODE REVIEW

**Comment by smarquard** [comment]
Also affects /direct/ endpoint, SAK-45483

**Comment by austin48** [comment]
@smarquard, sorry about this regression.  is there anything else needed in this PR for SAK-45457 or SAK-45483?

**Review by smarquard — APPROVED** [review]
Tested this change on a 20.x dev system, and it fixes the issue both for Lessons embed and for /direct/announcement/ results.

**Comment by smarquard** [comment]
I didn't test specifically in Lessons any issues around sorting or display order, just that future-dated announcements no longer showed up there for students.

**Comment by austin48** [comment]
Thanks!

**Comment by mpellicer** [comment]
Thank you so much for the hard work @austin48 @smarquard and @axxter99.

**Pull request merged**
