### PR TITLE
SAK-41000 show correct hours value on assignments reminder mail

### PR DESCRIPTION
**Pull request by bgarciaentornos**

### CODE REVIEW

**Comment by mpellicer** [comment]
@bgarciaentornos using String.format instead

**Comment by bgarciaentornos** [comment]
It could also be >24 hours shown in 'xx days and yy hours' and < 24 hours
shown as 'yy hours'.

**Comment by bjones86** [comment]
SAK-41000 is a duplicate, I think this should be filed under SAK-40753

**Comment by bjones86** [comment]
I'm mistaken; disregard my above comment.

**Comment by bgarciaentornos** [comment]
Have just updated the code using String.format and also showing the result in hours, days or days+hours. Although it will probably need to change once it all gets localized.

**Comment by mpellicer** [comment]
Creepy, but it's fine since this should be re-done to localize it correctly.

**Pull request merged**
