### PR TITLE
SAK-32769 Improve scalability and performance of the GradebookNG table

### PR DESCRIPTION
**Pull request by payten**
Delivers https://jira.sakaiproject.org/browse/SAK-32769 and also has patches for SAK-32751 and extends upon SAK-32737 to better handle locales in parsing and formatting locale specific input (periods vs commas).

In short, the new approach replaces the Wicket `DataTable` with a progressive rendering HTML table provided by a JavaScript library handsontable (https://handsontable.com/). Instead of delivering all of the HTML on the initial request (which was taking quite a while to serve from the backend, render in the browser and then parse with JavaScript) we now deliver a compressed JSON blob in the HTML which we decompress in the Javascript and deliver to the handsontable plugin.

There are many changes in `GradebookPage.java`.  We’ve dropped the `DataTable` and all the associated renderers, panels and comparators.  This is replaced with a new custom component `GbGradeTable.java` which is passed a detachable model `GbGradeTableData.java`.  The `GbGradeTable` component provides the basic panel for the new HTML table (an empty div) plus a bunch of TrimPath JavaScript templates which are used when rendering the new table cells, popovers and actions.  `GbGradeTableData.java` takes the `GradebookNgBusinessService` and the current session’s settings and gathers up all the data required for the table. Previously this data gathering was done here and there, in the page and various panels and sometimes multiple times.  This moves it into a single spot.  

The `GbGradeTable`’s model is the `GbGradeTableData`.  It pulls out the data from the model and passes to `GbGradebookData.java`, which is a JSON serialisable object.  The GbGradeTable
serializes `GbGradebookData` in its `renderHead` to a JSON string now accessible to the JavaScript.  To keep the size of this JSON from blowing out, the scores are being compressed and packed as base64 into 3 bytes.  The JavaScript then unpacks these values back into decimals before passing to the Handsontable plugin.

We’ve dropped the old `gradebook-grades.js`, which had all the weird and wonderful custom JavaScript we wrote to work with the Wicket `DataTable`.  Much of the behaviours are now handled by the plugin which simplifies the JavaScript drastically.  The new file `gradebook-gbgrade-table.js` provides all the JavaScript to drive the handsontable plugin.  Similarly, there’s a new CSS
file targeting the new table, `gradebook-gbgrade-table.css`.

Many of the interactions with the table are still Wicket events/callbacks.  As we’ve dropped many of the panels that once defined these callbacks, we’ve introduced a new set of
`Action`’s which are bound to the new table component.  We can trigger these callbacks from the JavaScript and retain much of the previous Wicket-backend behaviours. These actions are defined under the namespace `org.sakaiproject.gradebookng.tool.actions` and redefine many of the callbacks defined in the actions of the Wicket panels we have replaced.

Some interactions with the table are now handled by the handsontable plugin.  This includes things like sorting of column data which is all client-side now and a textual search for filtering all the of the students in the site.

NYU has been running this version of the table in production from the beginning of the Summer term.

### CODE REVIEW

**Comment by fostersdesign** [comment]
How does client-side sorting and filtering work if the data isn't loaded on the page yet because of the progressive load?

**Comment by payten** [comment]
Hi @fostersdesign, the new table supports progressive render and is single load.  We deliver the entire Gradebook dataset as a JSON blob and this is consumed by the handsontable plugin.   "Progressive render" means that only a subset of the HTML table is rendered at any one time; as you scroll the table horizontally or vertically, the HTML cell number remains the same, but the data is moved through the table to give the impression the table is massive.

As all the data is available to the handsontable plugin / JavaScript, sorting and filtering across the entire dataset is possible.

**Comment by ottenhoff** [comment]
Can this entire PR be squashed when merged?

**Comment by jonespm** [comment]
Yeah we were hoping to do that, we also hoped to have a short ~30 minute overview of this patch sometime in the late afternoon (eastern time) before squashing this patch down. NYU was setting that up.

**Comment by ottenhoff** [comment]
Sorry @payten , I think a recent PR merge I did is causing the branch conflicts here. Any idea how difficult these merge resolutions is going to be?

**Comment by payten** [comment]
Ah yep, our integration server just spat it! Just looking into it now.  It looks like a change was made to introduce an optional fixed column in the table - a student number?  It doesn't look trivial, but will report back.

**Comment by ottenhoff** [comment]
Yeah, that's the one. I'm happy to take a look tomorrow or look at backing out if it's untenable

**Comment by payten** [comment]
Hi @ottenhoff, we've had a go at porting the changes for SAK-32608.  They came across ok after some JavaScript wrangling to make adding fixed columns easier.

We also patched a bug whereby the `CandidataeDetailProvider` was required for the `GradebookNgBusinessService` even when `useInstitutionalNumericID=false`.

**Comment by ottenhoff** [comment]
Thanks payten. I have tested locally and this is working for me without any console or Tomcat errors.

**Comment by jonespm** [comment]
Okay, I'm good with merging this, it's okay to squash this all down right with the github? Or did you want to squash it a little to preserve some authorship? Seems like a lot of commits.

**Pull request merged**
