### PR TITLE
SAK-47531 GRADEBOOKNG A lot of errors GradeSummaryTablePanel.populateItem Failed to configure rubric button for submission: org.sakaiproject.exception.IdUnusedException

### PR DESCRIPTION
**Pull request by jesusmmp**
https://sakaiproject.atlassian.net/browse/SAK-47531

It's only the
if (assignment.getExternalAppName().equals(assignmentService.getToolId())) {

and indentation

On 22 should be merged with
if (assignment.getExternalAppName().equals(assignmentService.getToolTitle())) {

### CODE REVIEW

**Comment by jesusmmp** [comment]
> Looks ok to me. So, you're just making sure that the external assignment is from the Assignments tool?

Yes! :)

**Review by juanjmerono — APPROVED** [review]

**Comment by mpellicer** [comment]
I'm worried about this for 22.x:

`On 22 should be merged with
if (assignment.getExternalAppName().equals(assignmentService.getToolTitle())) {`

Maybe better to do a PR for 22.x only?

**Comment by jesusmmp** [comment]
The PR for 22.x can be avoided if this one is merged to 22.x firstly
https://sakaiproject.atlassian.net/browse/SAK-47291

Here the method was changed.
https://github.com/sakaiproject/sakai/pull/10540/files#diff-03c897ffacdb01e30bc8e44e8975028af725482fcdc3216141a4b4641ae04ca1R766

Please do what you think is best. @ottenhoff @mpellicer

**Comment by ottenhoff** [comment]
I attempted to merge SAK-47291 but failed. It requires at least 7 manual merges

**Pull request merged**
