### PR TITLE
SAK-29368 - New icons for sakai tools

### PR DESCRIPTION
**Pull request by SedueRey**
I've also created a little repo with all sources (SVG) of the icons I've drawn with Inkscape and a PHP script to export in all colors.

[Icons for Morpheus](https://github.com/SedueRey/morpheus-icons)

If you think this source should stay inside sakai repo (at least, the SVG) I can add it to repo and refresh the PR.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Hi all,

There is one major problem here: the icons are licensed as GPL v2 and that license is incompatible with Sakai's more liberal license: ECL 2.0.

**Comment by SedueRey** [comment]
Well, I'm not quite good on licenses so I've add GPL thinking it should be enough. I'm going to update to same license Sakai has.

There's no problem on change it, actually, I've made icons for Sakai :)

**Comment by ottenhoff** [comment]
Okay, thanks. Here is the preferred Sakai license:

http://opensource.org/licenses/ECL-2.0

**Comment by SedueRey** [comment]
I have updated it :)

As I said, I'm not well versed in licenses

**Pull request merged**
