### PR TITLE
SAK-49559 grader. Removed annotation buttons from pdfjs

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-49559

### CODE REVIEW

**Review by mpellicer — CHANGES_REQUESTED** [review]
This is not clear to me. Does this PR remove the annotation controls for everybody?

In understand that could be confusing, but on the bright side, many instructors want this and are uploading PDFs with corrections, not sure if this is removing all of that by default.

**Comment by adrianfish** [comment]
Not for everybody, just in the grader

**Comment by mpellicer** [comment]
I put a comment in the Jira to discuss this, not sure about this implementation.

**Comment by ern** [comment]
+1 as we were getting questions about this in grader since the annotations are never saved, would be a good feature!

**Comment by mpellicer** [comment]
@vacercon Do you have thoughts about this? I believe we can ask Fulgencio about the feature, it has controversy in it's current status.

**Comment by ern** [comment]
Maybe it makes sense to add some instructions for the user, so that it is clear that it will not save the annotations and is only available to download?

**Pull request closed without merging**
