### PR TITLE
SAK-30835 Added multi user retrieval

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by adrianfish** [comment]
@manuelal Hola Manuel, could you do a quick review of this. It extends the get-users search to multiple user ids, limited to 5 results. I also turn the scroll off when doing the user search.

**Comment by juanjmerono** [comment]
I've tested the Use Case 3 mentioned in the jira. If you type something that is not found and click "Find" button you get an error in the js console and the animation stays forever.

image

**Comment by adrianfish** [comment]
@juanjmerono Okay, thanks. I'll sort it out.

**Comment by adrianfish** [comment]
@juanjmerono Okay, sorted. You get the no_participants message if no user is found.

**Pull request merged**
