### PR TITLE
SAK-41248: Lessons > set Settings tooltip to 'Settings'

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-41248

When you hover over the Settings gear icon in Lessons, the tooltip says:

> Edit page title, release, or style -- opens new dialog

Without a proper label/tooltip indicating that the button opens the Settings dialog, there is nothing in the Lessons UI that gives users any indication of where to find the Settings dialog. This is especially confusing for users who see the following message when the page has been hidden via the Settings dialog:

> *Note:* This page is currently hidden from standard users. You can change this in the Settings window.

This PR suggests changing the tooltip to the following:

> Settings -- opens new dialog

The " -- opens new dialog" bit was added previously via #6123 (SAK-38421) for accessibility reasons, and as such I'm assuming it must remain.

### CODE REVIEW

**Comment by ottenhoff** [comment]
How about combining? E.g., Settings -- edit page title, release, or style in a new dialog window

**Comment by bjones86** [comment]
I'd be happy with that, I just need to run it by the interested parties first. Thanks for the suggestion, @ottenhoff!

**Comment by bjones86** [comment]
@ottenhoff, your suggestion has been implemented; thanks!

**Comment by bjones86** [comment]
Thanks, @adrianfish!

**Pull request merged**
