### PR TITLE
SAK-31677 Allow admins to add themselves to sites.

### PR DESCRIPTION
**Pull request by buckett**
This changes it so we don't check for role downgrades when adding people to a site (simplify the code), but we just don't allow the external users box to add people who are already a member of the site (internal users box already has this).

There is a Jira trail that looks like this might have been how it worked in the past but it looks to have got lost along the way.

### CODE REVIEW

**Comment by ansorgej** [comment]
I haven't had time to actually test this, but do these changes still prevent, say, an "Instructor" type role from changing themselves to a "Student" type role in Site Info?  That would be bad because they would lose the permissions to themselves back to an Instructor.  I thought that's what the "checkCurrentUserRoleChange()" method was trying to prevent.

I agree that the check doesn't need to be performed when adding a user to the site, but it should still be done when a user changes their own role in a site.

**Comment by buckett** [comment]
I don't believe so as role downgrades are done through `SiteAction.java`, whereas new users are added with `SiteAddParticipantHandler.java` which this PR changes.

Currently there is nothing to stop an Instructor downgrading themselves to a TA using Site Info as I've just done this on http://nightly2.sakaiproject.org

I do remember there being protection from the last maintainer removing themselves from the site however.

**Comment by buckett** [comment]
Going to merge shortly.

**Comment by ansorgej** [comment]
You're completely correct.  In Sakai 10 there is no protection from an Instructor/Maintain type user changing themselves to a Student/access type (and subsequently being unable to switch back).  I guess I thought there was based on this behavior in SiteAddParticipantHandler.  Which makes me wonder what these checks in were intended to accomplish in the first place.  

Anyway, thanks for merging.

**Pull request merged**
