### PR TITLE
SAK-32132 : Content-review : Urkund Implementation

### PR DESCRIPTION
**Pull request by frasese**
Upgrade for Assignments tool and Base content-review needed for : https://jira.sakaiproject.org/browse/SAK-32132 (11x) and used with https://github.com/sakaicontrib/urkund-antiplagiarism

### CODE REVIEW

**Comment by ottenhoff** [comment]
Please let branch maintainers do the merging

**Comment by frasese** [comment]
Sure, I just wanted to make things easier to everybody

**Comment by mpellicer** [comment]
To be honest this change is not dangerous because it's disabled by default and saves time of the maintainers... i suggest to reopen it 👍 

Thanks @ottenhoff

**Comment by ottenhoff** [comment]
Let's focus on the master PR right now. It will get into master as soon as the changes are made.

**Pull request merged**
