### PR TITLE
SAK-50010 rubrics Update comment textarea on switching criterion

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-50010

### CODE REVIEW

**Comment by hornersa** [comment]
@adrianfish - For some regressions I've identified while testing this PR, refer to my comments in the other PR for this jira: https://github.com/sakaiproject/sakai/pull/12690.

**Comment by adrianfish** [comment]
@hornersa Fixed, hopefully ...

**Comment by hornersa** [comment]
@adrianfish - I'll see if I can squeeze in testing your new commit today, though may not be until early next week.

**Comment by adrianfish** [comment]
@hornersa Either of those would be just fine. Thanks for testing it out.

**Review by hornersa — APPROVED** [review]
I was able to test this and the issues I cited before are resolved. That said, is the removal of the close 'X' button at the top-right of Grader occurring with this commit? If so, is that intentional? Again, if so, we'd likely want to at least highlight this change in the test plan if not also solicit other opinions re the removal of that control.

**Comment by adrianfish** [comment]
I see the close button still. The contrast is not great, but it's there.
Screenshot 2024-07-15 at 10 53 53

**Comment by adrianfish** [comment]
@hornersa I can't work out why you're not seeing the close button, but it definitely was not intentional. I can see it after a rebuild of portal, library and webcomponents, so it seems ok on master.

**Comment by hornersa** [comment]
@adrianfish - While trying to switch back to the branch I used to test and rebuild, I'm having problems rebuilding the code. Since returning to work last week, I've been frequently experiencing an w/ the webcomponent in master/trunk code (specifically any code recently branched from master) that manifests as npm and/or eslint errors but w/o a consistent signature. Do you recall any recent changes to pom files or npm or eslint that might be causing this fragility (or fixing it)? 

Fwiw, my latest set of errors (which changes) are:

```
[INFO] npm ERR! code 1
[INFO] npm ERR! path /home/shorner/sakai/ootb-sakai/webcomponents/tool/src/main/frontend/node_modules/nx
[INFO] npm ERR! command failed
[INFO] npm ERR! command sh -c node ./bin/post-install
[INFO] npm ERR! node:util:251
[INFO] npm ERR!     throw new ERR_INVALID_ARG_TYPE('superCtor.prototype',
[INFO] npm ERR!     ^
[INFO] npm ERR! 
[INFO] npm ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
[INFO] npm ERR!     at new NodeError (node:internal/errors:405:5)
[INFO] npm ERR!     at inherits (node:util:251:11)
[INFO] npm ERR!     at Object.<anonymous> (/home/shorner/sakai/ootb-sakai/webcomponents/tool/src/main/frontend/node_modules/readable-stream/lib/_stream_passthrough.js:30:20)
[INFO] npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[INFO] npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[INFO] npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
[INFO] npm ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
[INFO] npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
[INFO] npm ERR!     at require (node:internal/modules/cjs/helpers:119:18)
[INFO] npm ERR!     at Object.<anonymous> (/home/shorner/sakai/ootb-sakai/webcomponents/tool/src/main/frontend/node_modules/readable-stream/readable.js:13:25) {
[INFO] npm ERR!   code: 'ERR_INVALID_ARG_TYPE'
[INFO] npm ERR! }
[INFO] npm ERR! 
[INFO] npm ERR! Node.js v18.18.0
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/shorner/.npm/_logs/2024-07-15T16_22_03_167Z-debug-0.log
```

**Comment by hornersa** [comment]
Fwiw, even my reverting back to master and applying this patch now yields a different set of errors for webcomponents:

```
[INFO] 150 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO] 
[INFO] 56 vulnerabilities (1 low, 20 moderate, 29 high, 6 critical)
[INFO] 
[INFO] To address issues that do not require attention, run:
[INFO]   npm audit fix
[INFO] 
[INFO] To address all issues (including breaking changes), run:
[INFO]   npm audit fix --force
[INFO] 
[INFO] Run `npm audit` for details.
[INFO] 
[INFO] --- frontend-maven-plugin:1.15.0:npm (lint) @ webcomponents ---
[INFO] Running 'npm run lint' in /home/shorner/sakai/ootb-sakai/webcomponents/tool/src/main/frontend
[INFO] 
[INFO] > sakai-ui@1.0.0 lint
[INFO] > eslint "packages/**/src/*.js" --max-warnings=0
[INFO] 
[INFO] 
[INFO] --- frontend-maven-plugin:1.15.0:npm (analyze) @ webcomponents ---
[INFO] Running 'npm run analyze' in /home/shorner/sakai/ootb-sakai/webcomponents/tool/src/main/frontend
[INFO] 
[INFO] > sakai-ui@1.0.0 analyze
[INFO] > lit-analyzer --strict --quiet --rules.no-complex-attribute-binding=warning --rules.no-incompatible-type-binding=off "packages/**/src/*.js"
[INFO] 
[INFO] Analyzing 118 files...
[INFO] 
[INFO]   ✓ Found 0 problems in 118 files
[INFO] 
[INFO] --- frontend-maven-plugin:1.15.0:npm (bundle) @ webcomponents ---
[INFO] Running 'npm run bundle' in /home/shorner/sakai/ootb-sakai/webcomponents/tool/src/main/frontend
[INFO] 
[INFO] > sakai-ui@1.0.0 bundle
[INFO] > esbuild "bundle-entry-points/*.js" --preserve-symlinks --bundle --splitting --format=esm --outdir=bundles --minify
[INFO] 
[INFO] ✘ [ERROR] Unexpected end of file in JSON
[INFO] 
[INFO]     node_modules/@sakai-ui/sakai-submission-messager/node_modules/lit-element/package.json:1:0:
[INFO]       1 │ 
[INFO]         ╵ ^
```

**Comment by adrianfish** [comment]
Maybe SAK-50230

**Comment by hornersa** [comment]
@adrianfish Thanks. Having circumvented the issues I mentioned before (by cloning another git repo and applying this patch), I confirm your observation that the close button for Grader is present.

**Comment by adrianfish** [comment]
@hornersa Thanks Sean. Could you approve this then, if you're happy with the testing.

**Review by hornersa — APPROVED** [review]

**Pull request merged**
