### PR TITLE
SAK-40908 - Update _lessonbuilder.scss

### PR DESCRIPTION
**Pull request by lgekeler**
nexprev typo , should be nextprev as everywhere else

### CODE REVIEW

**Comment by mpellicer** [comment]
@lgekeler you also need to sign the ICLA, you only need to do this step once in a lifetime:
https://www.apereo.org/licensing/agreements/icla

To be listed here:
http://licensing.apereo.org/completed-clas

**Comment by csev** [comment]
I don’t know - but for me the simple approach is delete it, make a JIRA and redo it against master.  Once you get your JIRA made, you can indicate which versions this needs to be back-ported to.

/Chuck

P.S. So cool!

**Comment by lgekeler** [comment]
Okay. I will close this one. With CLA in hand, am I able to submit a pull against Master?

**Comment by fostersdesign** [comment]
@lgekeler - just an FYI: if I understand the issue as described in SAK-40908, you'll have to change more than just the selector of the rule for this class. 

Changing the style selector will not change the element's class in the tool. You'll need to change the class in the markup for all instances of those navigation buttons in Lessons. You'll also want to ensure that class isn't being used by any other markup, JavaScript, RSF, or styles elsewhere in the tool.

Let us know if you need assistance making these additional changes and we'll try to help.

**Comment by fostersdesign** [comment]
We'll also have to advertise this change because it will break all institutions' custom stylesheets who are targeting ".nexprev" currently.

**Comment by fostersdesign** [comment]
Good catch though. Thanks for fixing it for us!

**Pull request closed without merging**
