### PR TITLE
SAK-43389 Assignments - fixes for progress bar and confirmation page

### PR DESCRIPTION
**Pull request by bgarciaentornos**
This is a work in progress, waiting for comments on https://jira.sakaiproject.org/browse/SAK-43389 for feedback about the changes and texts.

### CODE REVIEW

**Comment by ottenhoff** [comment]
I am getting an NPE on assignment.getContentReview().I don't understand why.

`caused by: java.lang.NullPointerException
    at org.sakaiproject.assignment.tool.AssignmentAction.build_student_confirm_submission_context(AssignmentAction.java:2045)
    at org.sakaiproject.assignment.tool.AssignmentAction.buildMainPanelContext(AssignmentAction.java:1241)`

**Comment by bgarciaentornos** [comment]
> I am getting an NPE on assignment.getContentReview().I don't understand why.
> 
> `caused by: java.lang.NullPointerException at org.sakaiproject.assignment.tool.AssignmentAction.build_student_confirm_submission_context(AssignmentAction.java:2045) at org.sakaiproject.assignment.tool.AssignmentAction.buildMainPanelContext(AssignmentAction.java:1241)`

That's interesting because I'd say it could be a previously existing bug and it will probably appear on the preview screen too (this feature was originally kinda duplicated from the preview methods). Is it easily reproduceable? Maybe new jira? Solution is just moving that bit of code upwards, but I'd like to know more about the qa/preview case first.

**Comment by ottenhoff** [comment]
I can reproduce easily on my localhost when creating and taking an assignment (no need to use Turnitin settings) .... @ern any ideas?

**Comment by bgarciaentornos** [comment]
On preview screen too?

**Comment by ottenhoff** [comment]
Okay @ern solved the getContentReview NPE. 

I am testing locally and getting a new error now after clicking Proceed: "Alert: Can not find the assignment 'null'."

**Comment by ern** [comment]
fixed the "Alert: Can not find the assignment 'null'."

**Pull request merged**
