### PR TITLE
SAK-34093 - Ensure links that spawn dialogs indicate the fact

### PR DESCRIPTION
**Pull request by SedueRey**
I've tested with aXe thanks to @ottenhoff and now it doesn't give any a11y issue on "Edit" link (now button)

### CODE REVIEW

**Comment by ottenhoff** [comment]
One more thing: should we add aria-expanded="true" when the dialog is opened and then remove it when closed?

**Comment by SedueRey** [comment]
It's not mandatory on the w3c documentation but I think it would be a great idea

**Comment by SedueRey** [comment]
I've updated PR but I have a doubt. I didn't find if it's mandatory to close dialog on pressing "escape" key or it would be just a common practice.

**Comment by ottenhoff** [comment]
Yeah, I don't think it's mandatory to close with the Escape key.

@hanshillen do you have advice? Does a small dialog need to be close-able with the Escape key?

**Comment by hanshillen** [comment]
If a dialog is dismissable without further input from the user, then yes I would expect it to be closable with Esc and have focus move back to the original link in that event. Same with other dialogs, dropdowns, flyouts, edit modes, etc. Esc lets you cancel out of those.

**Comment by SedueRey** [comment]
Perfect, I'll update pr with that

**Comment by SedueRey** [comment]
I've tested on local in Chrome and Firefox and, by now, it closes with Esc key without code changes (sorry, I didn't tested that, I assume it wouldn' work in that way)

**Comment by SedueRey** [comment]
May someone remove the WIP tag ? Thanks

**Pull request merged**
