### PR TITLE
SAK-31739 Improve the look of subsite buttons in mobile view.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**

### CODE REVIEW

**Comment by buckett** [comment]
Wrong reference on commit comment.

**Comment by lardo-de-arnaud** [comment]
can this be reviewed and merged?

**Comment by lardo-de-arnaud** [comment]
anybody able to look at this. Eduardo's now left so he aint going to do it!

**Comment by ottenhoff** [comment]
LGTM

**Comment by buckett** [comment]
@ottenhoff Thanks.

**Pull request merged**
