### PR TITLE
SAK-46986 Tasks: remove tasks for removed site users

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-46986

### CODE REVIEW

**Comment by adrianfish** [comment]
@mpellicer. This is not future, it's a blocker. Did you not see Andrea's email?

**Comment by mpellicer** [comment]
@adrianfish No but I followed the same rule you applied to the other ticket about the 22 release, you're introducing new database objects so for me you're implementing something which was unimplemented in the first commits, could you at least apply the same rules to your work and our work when you decide to block something?

**Comment by adrianfish** [comment]
@mpellicer This is*obviously* different as it fixes a glaring bug in tasks. There's no way dashboards will be taken out of experimental if we don't fix blockers like this. I didn't make it a blocker, Andrea did.

**Comment by adrianfish** [comment]
@mpellicer This will be merged back to 22. Roberto's change won't be. If you merged Roberto's fix and I fixed a a bug that needed to go back to 22, there would be a risk of taking back unrelated changes (ie: stuff from Roberto's fix). That's why Roberto's should wait until the majority of blocker bugs are fixed for 22.

**Comment by adrianfish** [comment]
@ern Could you take a particular look at the transactionTemplate pieces of this? Just make sure I'm not doing anything stupid?

**Comment by adrianfish** [comment]
@mpellicer Are you saying I'm biased here? That I apply different rules of acceptability to your PRs based on who you are? This is not true, in fact I spent around 8 hours reviewing Roberto's PR as I have an interest in the work being solid and maintainable. Roberto's work is a feature - it has UI changes - and the feature freeze was in September iirc. The only way I blocked that change is by just saying that it should be held up until 22 is out so there's less chance of accidentally merging feature code with blocker fixes. I feel totally justified in that. Please raise this grievance on the PMC list so we can discuss it.

**Comment by mpellicer** [comment]
@adrianfish Do you mean database and UI changes like here? Even the PR is marked as a feature request.

https://github.com/sakaiproject/sakai/commit/00dcc6312f91109003aa152927ae282ceb57dbec

And you don't need to remember me when is the freeze date because I didn't want to merge #10286 in 22.x, it's an Apereo project targeting 23, but seems that it's gonna be another project blocked for further discussion.

**Review by ern — APPROVED** [review]

**Pull request merged**
