### PR TITLE
SAK-30833: Odd Button in Discussions

### PR DESCRIPTION
**Pull request by ramonchu2k**

### CODE REVIEW

**Comment by ramonchu2k** [comment]
The solution is for jsf 1.0

**Comment by ottenhoff** [comment]
So is the problem that "ForumTool.selectedTopic.isMovePostings" is not working?

**Comment by ramonchu2k** [comment]
No, it's working but it's not in the right place. The problem was that the test only affected the text of the button, not the button itself.

**Comment by ottenhoff** [comment]
Okay, how about a minimal change to just add rendered to a panelGroup surrounding the relevant content?

**Comment by ramonchu2k** [comment]
I though so, but just a panelGroup generates a span tag instead div tag so I'd be changing the html structure, and a panelGroup with layout=block, which generates a div tag, is not allowed for this jsf version. I tried using c:if but it brought me problems with this jsf version as well.

**Comment by ottenhoff** [comment]
One extra span tag would be much preferred over the additions in that top of this change.

**Comment by ramonchu2k** [comment]
I've made it as you said. I hope it looks good to you.

**Pull request merged**
