### PR TITLE
SAM-3129 "period or comma" is confusing to USA students

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ern** [comment]
I think that comment is eluding to that 8,263 is not the same as 8263.0

**Comment by jonespm** [comment]
Well a comma can't be used as a decimal point marker in US. Whether or not it's possible to use a comma as a thousands separator (it mentions spaces are allowed) is another question.

**Comment by ern** [comment]
Yeah I agree but I know in samigo there are some regex that do swap commas for periods so I was just pointing out that maybe that comment was eluding to that!

**Comment by jonespm** [comment]
Yeah, I think there is but this is just for the English language. The comma/period swap would be for other languages. (Who would update to appropriate text to not reference periods!)

**Pull request merged**
