### PR TITLE
SAK-47315 rubrics. Reload page when reordering criteria

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-47315

This is the dirtiest of hacks and I am not proud of it. But ... until I work out a decent way of not annoying lit by moving stuff around underneath it, it will do the job.

### CODE REVIEW

**Review by ottenhoff — APPROVED** [review]

**Comment by stetsche** [comment]
I see that you are not happy with this hack and I don't want to block this fix for the release, if this is going to be addressed later. Anyway, I see two alternatives to this fix that might be unnoticed by the user:
1. Update the data that is used to render the criterions by sorting it based on `sortedIds`.
2. Fetch the sorted criterions again from the backend.

I would think lit would just update the dom then, based on the new order and things should work. If the confusion of lit goes deeper though, could you clarify more or less what is happening please?

**Comment by stetsche** [comment]
That's interesting, sounds pretty tricky... Let's hope lit 3 will do the job :)

**Comment by adrianfish** [comment]
I'll test it out in the bundling pr

**Comment by adrianfish** [comment]
I suggest we merge this horrible hack in the meantime though. I hope the community can forgive me for such a sin.

**Review by stetsche — APPROVED** [review]

**Pull request merged**
