### PR TITLE
SAK-29514 - Support accessibility in Velocity menus

### PR DESCRIPTION
**Pull request by mcarropellicer**
SAK-29514 - Support accessibility in Velocity menus

### CODE REVIEW

**Comment by juanjmerono** [comment]
I think is better to create a single constructor with all the available parameters and define the others calling to the main one. Something like:
```java
	public MenuEntry(String title, String accessibilityLabel, String icon, boolean enabled, int checked, String action, String form)
	{
		m_title = title;
		m_icon = icon;
		m_enabled = enabled;
		m_checked = checked;
		m_action = action;
		m_form = form;
		m_accessibilitylabel = title;
	} // MenuEntry
	
	public MenuEntry(String title, String accessibilityLabel, String action)
	{
		this(title,accessibilityLabel,null,null,null,action,null);
	} // MenuEntry

	public MenuEntry(String title, String accessibilityLabel, boolean enabled, String action)
	{
		this(title,accessibilityLabel,null,enabled,null,action,null);
	} // MenuEntry

       ..............
```

**Comment by mcarropellicer** [comment]
Thank you so much for the feedback Juanjo, totally agree with you.

Improved logic, all the constructors will call the main constructor with all arguments, this guarantees the compatibility of the component in all tools.

If the accessibilityLabel is null, will show the title (Just like now).

**Comment by buckett** [comment]
LGTM.
If you have the urge to JavaDoc don't let the lack of existing JavaDoc hold you back. :smile:

**Comment by mcarropellicer** [comment]
:D 

This opens the door to improve the accessibility in the Menu buttons (Velocity tools)

**Pull request merged**
