### PR TITLE
KNL-382 getAuthzGroupsIsAllowed may fail on Oracle with > 1000 groups in...

### PR DESCRIPTION
**Pull request by juanjmerono**
... a site

### CODE REVIEW

**Comment by bjones86** [comment]
+1; the Oracle limit on 1000 elements in an IN clause has bit us before.

**Comment by ottenhoff** [comment]
To be clear: this patch will affect MySQL and Oracle, correct?

But we assume it will have little real effect so it's worth merging?

**Comment by juanjmerono** [comment]
It's only for Oracle, the change is at DbAuthzGroupSqlOracle.java

**Comment by ottenhoff** [comment]
Yes, absolutely. Thanks @juanjmerono

**Pull request merged**
