### PR TITLE
SAK-43199 Move new grader toggle to more prominent place

### PR DESCRIPTION
**Pull request by adrianfish**
Fixed a bug in 2fd7dd2566ecf5ceb3e650dc8f9571e2b9bd228c

### CODE REVIEW

**Comment by jesusmmp** [comment]
LGTM!

**Comment by adrianfish** [comment]
@jesusmmp Thanks Jesus. Could you approve it, too? Thanks for doing so much testing on the new grader. Really really helpful.

**Comment by adrianfish** [comment]
@jesusmmp I bet you don't have write access, do you?

**Comment by jesusmmp** [comment]
@adrianfish I don't have write access... :(

**Pull request merged**
