### PR TITLE
SAK-40999 - Errors sorting announcements with null values in date attributes

### PR DESCRIPTION
**Pull request by adrianmticarum**
Commit to fix this issue

### CODE REVIEW

**Comment by mpellicer** [comment]
Lovely use of switch 😋

**Comment by ern** [comment]
Can you use java 8 time library, Instant vs Date

**Comment by adrianmticarum** [comment]
Requested changes made. Thanks @ern !

**Comment by mpellicer** [comment]
Thanks @adrianmticarum for improving the overall quality of Sakai!

**Pull request merged**
