### PR TITLE
SAK-33341 Fire assignment events after db commit

### PR DESCRIPTION
**Pull request by adrianfish**
Also, switched from add event to revise event for bullhorn alert. Add
is fired when the assignmnent is incomplete. No dates set, for example.

### CODE REVIEW

**Comment by ern** [comment]
Hey Adrian,

It might be best to hold off on this since I've got a PR coming that puts a few events back to the way they were and you wouldn't need to make some of those changes.

**Comment by ern** [comment]
see #4863

**Comment by ottenhoff** [comment]
Is this still needed after #4863 ?

**Comment by adrianfish** [comment]
I'll have to test again.

**Pull request closed without merging**
