### PR TITLE
SAK-29776 improve performance of auto groups by roster

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-29776

Improve the performance by cutting out the CMS and UserDirectoryService calls in favour of using the realm. This reduces code and eliminates the dependency on the CMS.

### CODE REVIEW

**Comment by baholladay** [comment]
has this been tested on provided users?

**Comment by bjones86** [comment]
Yes, we've tested this locally (dev testing). We're also in the midst of doing QA

**Comment by ottenhoff** [comment]
Nice..... if testing passes, merge away

**Comment by bjones86** [comment]
Yep, I'll leave this one open till our internal QA is done.

**Pull request merged**
