### PR TITLE
SAK-46008 HTML files should set user's preferred theme in HTML class names

### PR DESCRIPTION
**Pull request by ottenhoff**
…

### CODE REVIEW

**Comment by adrianfish** [comment]
I'm guessing this PR works because those theme classes are referenced in the sass build already? In the iframe content?

**Comment by ottenhoff** [comment]
> I'm guessing this PR works because those theme classes are referenced in the sass build already? 

Aren't those the classes that make light/dark work? 

> I'm asking as I don't see any updates to css to reference those class additions to the template.

I'm just adding the already-defined classes to the Resources HTML pages that are created by Sakai

**Comment by adrianfish** [comment]
@ottenhoff Just asking out of a desire for due diligence :)

**Review by adrianfish — APPROVED** [review]
Thanks Sam.

**Pull request merged**
