### PR TITLE
SAK-30277 - Update opencast repository URL

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by buckett** [comment]
It's a shame they didn't do redirection for the old repository URLs.

**Comment by jonespm** [comment]
Yeah, we could reply asking if that would be possible even temporarily (might not be), but still this needs to be changed.

I have a local .m2/settings.xml that overrides 3 repositories right now for improved build speed/reliability. Not sure how to get the best word out for that though.

**Comment by buckett** [comment]
I wasn't disagreeing with it being changed.

Does it need to be in more than just the kernel, it's just that then other modules in the build will start using this repository as well which will slow down building.

**Comment by jonespm** [comment]
I believe that maven goes down the repositories in the order they're defined. So it would only end up using this one (last in the list) if it can't find the artifact everywhere else, right? 

But this new nexus.opencast.net is distributed across 4 servers so it should be up there in speed, maybe not as fast as maven central, but it should always be going to maven central first.

I put it in master because I'm putting 3rd party artifacts there that used to be in Berkley, UCDavis and UCT and those servers are often unavailable and maybe disappear at any time. That's when it would need this repository, and there are a few outside of kernel that fall into there.

**Comment by ern** [comment]
LGTM

**Comment by buckett** [comment]
Would be good to have your settings.xml more public.
I wasn't aware we used repositories from Berkley, UCDavis and UCT.

**Pull request merged**
