### PR TITLE
SAK-43350 Added peer review icon and info to Grader

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-43350

### CODE REVIEW

**Comment by jesusmmp** [comment]
@adrianfish, do we need to add **onclick="$('#peerReviewInfo').show();"** as on the other grader?

**Comment by adrianfish** [comment]
That's not implemented, the dialog. I'll have to add that. I know nothing about peer review in assignments!

**Comment by adrianfish** [comment]
I get it. It's for mobile users.

**Comment by adrianfish** [comment]
I've updated the PR. I've added a boostrap popover with the peer info.

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5160726&bid=16945175)

**Comment by jesusmmp** [comment]
@adrianfish Let me test this on my local instance.

**Pull request merged**
