### PR TITLE
SAK-31332 - Update jquery ui in rsf tool to webjars version

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by bjones86** [comment]
LGTM

**Comment by buckett** [comment]
The upgrade from 1.10 to 1.11 has the following upgrade note: https://jqueryui.com/upgrade-guide/1.11/

**Comment by jonespm** [comment]
I'm not seeing any issues with it. I am seeing an issue with jquery being at a newer version. I think I saw this problem in 10.x too that I'm also testing out.

**Comment by jonespm** [comment]
I'm just going to merge this, I don't see any errors in the console and the only tools that use this date picker (evaluation and polls) seem to MUCH better with this reference than without it.

**Comment by jonespm** [comment]
As an aside, I'm working on https://jira.sakaiproject.org/browse/SAK-31306 for at least 11.1 so hopefully this will never be a problem again

**Pull request merged**
