### PR TITLE
S2U-20 Tests & Quizzes: random questions from multiple pools - MASTER

### PR DESCRIPTION
**Pull request by stetsche**
https://sakaiproject.atlassian.net/browse/S2U-20

### CODE REVIEW

**Comment by stetsche** [comment]
I will rebase this PR when https://github.com/sakaiproject/sakai/pull/12280 is merged.

**Comment by stetsche** [comment]
Rebased, EU translations pending.

**Comment by mpellicer** [comment]
moooore conflicts

**Review by mpellicer — CHANGES_REQUESTED** [review]
EU translations missing.

**Comment by mpellicer** [comment]
Please resolve these conflicts for me @stetsche , thanks!

**Comment by stetsche** [comment]
@mpellicer, rebased!

**Comment by mpellicer** [comment]
Thanks Markus @stetsche !

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
