### PR TITLE
SAK-29208 In very big resolutions roster infinite scroll does not work

### PR DESCRIPTION
**Pull request by juanjmerono**
Detect if scroll is not visible but there are more pages to load.

### CODE REVIEW

**Comment by ottenhoff** [comment]
@adrianfish does this look okay to you?

**Comment by ottenhoff** [comment]
@adrianfish? Is anyone running this in production?

**Comment by juanjmerono** [comment]
I also asked @adrianfish to review this patch in jira (no answer). Nobody is running this in production, I did it for trunk to prevent misfunction in big resolutions or compressed views (due to custom changes in css). With the new roster infinite scrolling you must see a scrollbar to go to the next page, but what happend if your resolution allows you to see all the content of the first page?

This fix detects if there are more pages and you don't see the scrollbar, and in that case ask for the next page until you see the scrollbar or no more pages available. It works and I think makes sense.

**Comment by adrianfish** [comment]
I'll take a look. When you ask if it's running in production, @ottenhoff , do you mean this patch, or the infinite scroll version of roster generally?

**Comment by juanjmerono** [comment]
Changes done !!
Thanks for your review @adrianfish !!

**Comment by adrianfish** [comment]
Nice job. I should have let you merge it so you could close your branch automatically.

**Pull request merged**
