### PR TITLE
SAM-3071 - Samigo auto submit script should backfill setting to exist…

### PR DESCRIPTION
**Pull request by jonespm**
…ing assessments

### CODE REVIEW

**Comment by jonespm** [comment]
I'm not sure the Oracle syntax for this. Does INSERT INTO SELECT work the same way? In MySQL you need a temporary table because you can't select from the same table you're inserting into.

**Comment by jonespm** [comment]
S2U said they'd look at it for Oracle

**Comment by juanjmerono** [comment]
Hi @jonespm the sintax in Oracle should be:
```
CREATE GLOBAL TEMPORARY TABLE UPDATE_SAM_AUTO_IDS ON COMMIT PRESERVE ROWS AS (SELECT ID FROM SAM_ASSESSMENTBASE_T WHERE ID NOT IN (SELECT ASSESSMENTID FROM SAM_ASSESSMETADATA_T WHERE label = 'automaticSubmission_isInstructorEditable'));
INSERT INTO SAM_ASSESSMETADATA_T (ASSESSMENTMETADATAID, ASSESSMENTID, LABEL, ENTRY) SELECT sam_assessMetaData_id_s.nextVal, ID, 'automaticSubmission_isInstructorEditable', 'true' FROM UPDATE_SAM_AUTO_IDS;
TRUNCATE TABLE UPDATE_SAM_AUTO_IDS;
DROP TABLE UPDATE_SAM_AUTO_IDS;
```

**Comment by jonespm** [comment]
Thanks @juanjmerono added that

**Pull request merged**
