### PR TITLE
SAK-32330 - Grouping of several Lesson tool instances in Site Info is…

### PR DESCRIPTION
**Pull request by jonespm**
… gone

Restoring Section 5 CSS rules

### CODE REVIEW

**Comment by jonespm** [comment]
This does fix the problem mentioned and problem some other formatting problems. I'm not sure why these were removed besides them not being the best practice for formatting. But they're just used so much.

image

**Comment by buckett** [comment]
As we've not had these for a while we may have workarounds for other fixes.
If we add them back should we mark them as deprecated (do we consider them deprecated?) in the CSS to indicate that for new code people should avoid using them?

I haven't looked through all the uses but I'd imaging using `<ul>...</ul>` would make more sense in other cases as well, but not sure if they would work in all of them.

**Comment by ern** [comment]
!important is just bad form and typically just cause other issues elsewhere.

**Comment by jonespm** [comment]
Yeah, I can remove the !important and see if this still works out.

**Comment by jonespm** [comment]
I removed the !important from the css rules. It still fixes the problem here.

**Pull request merged**
