### PR TITLE
LSNBLDR-596; fix Samigo edit assessments in iframe

### PR DESCRIPTION
**Pull request by clhedrick**

### CODE REVIEW

**Comment by clhedrick** [comment]
I've assigned this to csev. The patch works. But it might be better to put it in the same place that generates the other jquery includes, since it makes no sense to include jquery ui without the css.

**Comment by ottenhoff** [comment]
Agree: if we are going to load jquery-ui JS, we should load the CSS also

**Comment by ern** [comment]
+1 for both comments load where jquery ui is loaded.

**Comment by ottenhoff** [comment]
I saw a similar PR get committed today.... is this one still relevant?

**Comment by jonespm** [comment]
Not sure, with #2124 this probably wasn't needed anymore. Worst case is it will load it twice from the cache in Samigo.

**Pull request merged**
