### PR TITLE
SAK-44561 Error parsing the date/time PA SYSTEM Create Banner

### PR DESCRIPTION
**Pull request by MRutea**
SAK-44561 Error parsing the date/time PA SYSTEM Create Banner

### CODE REVIEW

**Comment by adrianfish** [comment]
@MRutea You have a conflict on this one. Can't be too bad :)

**Comment by MRutea** [comment]
@adrianfish 
Hi, Adrian.
As always, thank very much for your comments!
Amended.

**Comment by bjones86** [comment]
@mateullas, a small conflict remains here.

**Comment by MRutea** [comment]
@bjones86 
Thank you, Brian.
I'v resolved the conflict.

**Review by ern — APPROVED** [review]

**Pull request merged**
