### PR TITLE
SAK-33442 Added Commons tool description

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by ottenhoff** [comment]
I think we should avoid referring to Facebook here.

The Commons tool allows short, update posts with previews and unthreaded replies.

**Comment by adrianfish** [comment]
Why not mention Facebook? The thing works a bit like Facebook, so it seems a good description, to me. Is there a legal issue?

**Comment by ottenhoff** [comment]
I believe it's more instructive to describe how the tool functions instead of saying that it functions like XX commercial tool. But if others find that "Facebook" is the most accurate description of the tool, then sure, it's fine with me.

**Comment by buckett** [comment]
For me part of the issue with mentioning Facebook is that Facebook does lots of things and different people see it differently and focus on particular areas. So if commons tool doesn't do the thing they use Facebook for it's confusing.

**Comment by jonespm** [comment]
Yeah, I think replacing Facebook with "social networking style" would work here.

**Comment by jonespm** [comment]
Made these commits directly to this PR

**Pull request merged**
