### PR TITLE
SAK-29603 : Remove roles from forums permissions

### PR DESCRIPTION
**Pull request by frasese**

### CODE REVIEW

**Comment by jonespm** [comment]
This patch is causing a compilation error because this method isn't in the AuthzGroupService cover. If you need to use this it really should be switched over to use the spring injection. 

I'm also not sure what the problem with this is.. 

[ERROR] /home/travis/build/sakaiproject/sakai/msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java:[6936,48] cannot find symbol
  symbol:   method isRoleAssignable(java.lang.String)
  location: class org.sakaiproject.authz.cover.AuthzGroupService

**Comment by buckett** [comment]
This requires #693 first as it uses a method added in that pull request.

**Comment by buckett** [comment]
I think issue is that when in the Forum tool is allows you to map Sakai roles (access/student/etc) to Forums permissions levels. However because forums doesn't use the Sakai SecurityService todo it's permission checks .anon/.auth don't actually work. This change just prevents the non-working roles from showing up in the UI so it doesn't confuse people.

**Comment by jonespm** [comment]
Okay, fixed the problem with the cover in #1716

**Pull request merged**
