### PR TITLE
 SAK-39967 Turnitin Core API Sakai integration: 12.x merge

### PR DESCRIPTION
**Pull request by baholladay**

### CODE REVIEW

**Comment by jonespm** [comment]
Did you notice this issue @baholladay https://jira.sakaiproject.org/browse/SAK-40199

**Comment by baholladay** [comment]
Nope, didn't get the email b/c it was sending it to my no longer available longsight email... I'll look at it, thanks!

**Comment by baholladay** [comment]
I've created a PR for that jira: https://github.com/sakaiproject/sakai/pull/5726

**Comment by ern** [comment]
Did we attempt to merge the original PR for this?

**Comment by baholladay** [comment]
Closing since a PR is not needed for a 12.x merge. I have updated the Sakai JIRA 12.x status to "please merge" for SAK-39967 and SAK-40199. Don't forget the Sakai-Reference 12.x merge as well (no specific jira for it)

**Pull request closed without merging**
