### PR TITLE
SAK-30355 use bootstrap callouts from bootstrap documentation

### PR DESCRIPTION
**Pull request by ottenhoff**
I like the callouts in the bootstrap documentation:

  http://cpratt.co/twitter-bootstrap-callout-css-styles/

They seem like an improvement on our current "instruction" callouts.....

I am submitting this for comment and review. I am new to bootstrap, sass, and morpheus....

image

CC: @SedueRey @juanjmerono

### CODE REVIEW

**Comment by SedueRey** [comment]
Great mixing! 

We can use it later to define the three states, success, info and warning. 

Great!

**Comment by SedueRey** [comment]
Could you put yourself a JIRA to mark it to 11.x version? Also, nobody else will work on this :)

**Comment by juanjmerono** [comment]
Yes, please create a jira and add "11 status" field to merge, to ensure this is included in 11.x, and also name the PR or commit with the jira.

**Comment by ottenhoff** [comment]
Thanks for the comments. I have a JIRA and I will re-do this PR.

What are the appropriate colors for three states, success, info and warning?

**Comment by juanjmerono** [comment]
I guess green, blue and yellow :smile: , any opinion on this @SedueRey ?

**Comment by ottenhoff** [comment]
Yes, I agree. Are these the correct colors?

```
$okcolor:                    #dff0d8 !default;                                                                                                                                                       
$errorcolor:                 #f2dede !default;                                                                                                                                                       
$warncolor:                  #fcf8e3 !default;       
```

**Comment by SedueRey** [comment]
Yes, those colors and the blue you have added for .info would be great :)

The okcolor is green hehehe

**Comment by ottenhoff** [comment]
Okay new PR with a proper branch and JIRA is here : #1170

**Pull request closed without merging**
