### PR TITLE
SAK-30828 Normalize sakai logging

### PR DESCRIPTION
**Pull request by ern**
- remove commons-logging (jcl)
- add logging to those projects where it was removed
- convert System.out to log messages in many projects
- add jcl-over-slf4j lib
- update many dependencies to inherit from master
- update logging for tests
- add lombok to global dependency (@Slf4j)

### CODE REVIEW

**Comment by bjones86** [comment]
Amazing!!!! Thanks @ern

**Comment by ottenhoff** [comment]
Wow!!!

**Comment by ottenhoff** [comment]
still in progress? or ready for merge?

**Comment by ern** [comment]
Yeah I have 2 more commits coming on this..

**Comment by adrianfish** [comment]
do we need to add lombok-extern to the master pom, too? Isn't that where the Slf4j annotation comes from?

**Pull request merged**
