### PR TITLE
S2U-17 Add dialog label for modal

### PR DESCRIPTION
**Pull request by stetsche**
Also removing unused variable.

https://sakaiproject.atlassian.net/browse/S2U-17

### CODE REVIEW

**Review by jesusmmp — APPROVED** [review]

**Comment by stetsche** [comment]
I will also add missing licence headers here.

**Review by mpellicer — CHANGES_REQUESTED** [review]
Please add the license headers

**Comment by stetsche** [comment]
@mpellicer Missing license headers added, also squashed into the master version.

**Review by mpellicer — APPROVED** [review]
Nicee!

**Pull request merged**
