### PR TITLE
SAK-41307 Moved Rubrics to litelement

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by mpellicer** [comment]
I've built the branch but there are errors in the console log, as far as I can tell the webcomponents project is not in the root pom.xml, I'll rebuilt it again.

`webcomponents-loader.js:1 Failed to load resource: the server responded with a status of 404 ()
webcomponents-loader.js:1 Failed to load resource: the server responded with a status of 404 ()
jquery-migrate.min.js?version=edc5d4d2:2 JQMIGRATE: Migrate is installed, version 1.4.1
portal:533 PortletIFrame PortalUtils.includeLatestJquery() loaded jQuery+migrate+Bootstrap+UI 1.12.4
portal:589 /library/content/server_info.html does not start with http:// or https://
portal:759 Using tool jQuery 1.12.4
portal:791 Portal adding jQuery UI Touch Punch for touch device support
sakai-rubrics.js?version=edc5d4d2:160 Uncaught TypeError: portal.i18n.loadProperties is not a function
    at sakai-rubrics.js?version=edc5d4d2:160
    at sakai-rubrics.js?version=edc5d4d2:172
portal:855 Portal script load complete PBJQ=1.12.4 jQuery=1.12.4 $=1.12.4
webcomponents/sakai-element.js:1 Failed to load resource: the server responded with a status of 404 ()
webcomponents/assets/lit-element/lit-element.js:1 Failed to load resource: the server responded with a status of 404 ()
headscripts.js?version=edc5d4d2:804 Adding webjar library featherlight, version 1.7.13
portal:621 lti.frameResize of undefined failed height=undefined
portal:622 
portal:621 lti.frameResize of undefined failed height=undefined
portal:622 setImmediate$0.11908549400813184$1
portal:621 lti.frameResize of undefined failed height=undefined
portal:622 setImmediate$0.11908549400813184$2
portal:621 lti.frameResize of undefined failed height=undefined
portal:622 setImmediate$0.11908549400813184$3
`

**Comment by mpellicer** [comment]
Minor issue with the I18N webservice if you're not logged in in Sakai.
`sakai-rubrics.js?version=edc5d4d2:160 Uncaught TypeError: portal.i18n.loadProperties is not a function
    at sakai-rubrics.js?version=edc5d4d2:160
    at sakai-rubrics.js?version=edc5d4d2:172
`

**Comment by mpellicer** [comment]
Minor UI issue with the delete button:
remove_criterion
remove_criterion_hover
create_rating

**Comment by mpellicer** [comment]
Can't grade Forums using Rubrics :'(
nightly

**Comment by mpellicer** [comment]
Rubrics are displayed correctly grading assessments questions but the grade is not stored correctly in the question:
nightly2

**Comment by mpellicer** [comment]
Minor  - debug message in the console
`sakai-rubric.js:140 HERE2`

**Comment by mpellicer** [comment]
When creating a new Rubric, the template is empty, I think it's desirable for the user:
template_current

After the PR:
template_after

**Comment by mpellicer** [comment]
Many thanks @adrianfish, I've retested the PR, we're really close to having it and the improvements are awesome, much better than the current version.

AWESOME NEWS (Good job here!!!!!!!!!!!!!!):

-Drag & drop works for ratings and criterions.
- Works in Firefox.
- Works in Edge

Issues resolved:

- Portal I18N error when not logged in.
- Templates are present when creating a new Rubric.
- Works fine in forums.
- Remove buttons style fixed.

Issues present:
- Duplicate Rubric doesn't copy the criterions and ratings.
- Duplicate criterion doesn't copy ratings.
- Can't grade assessment questions (Short text).

New issues (Really minor):
-Grading forums have minor Javascript errors.
-Sort criterions don't work in Edge.

Grading forums JS errors:
a


`ReferenceError: portal is not defined[Saber más] sakai-rubrics.js:160:3
TypeError: translation is undefined[Saber más] sakai-rubrics-language.js:31:7 `

**Comment by mpellicer** [comment]
I think merging this before finishing my testing and review is bad.

**Comment by ern** [comment]
Hi Miguel I apologize for merging before your review was complete but in the core meeting we had made a decision to merge this and open JIRA issues for what was remaining.

**Pull request merged**
