### PR TITLE
SAK-47795 Ignite - Attendance - optional caches added for Sakai 23

### PR DESCRIPTION
**Pull request by davidpbauer**

### CODE REVIEW

**Comment by davidpbauer** [comment]
Attendance updates for Sakai 23 https://github.com/sakaicontrib/attendance/pull/109

**Comment by ottenhoff** [comment]
Cool ;)

**Comment by csev** [comment]
Ignite is so cool.

**Review by ern — APPROVED** [review]

**Comment by ern** [comment]
Dave we should create a JIRA in the SAK project, Add attendance as optional cache's

**Comment by adrianfish** [comment]
I've setup a JIRA ticket for this:
https://sakaiproject.atlassian.net/browse/SAK-47795

**Comment by davidpbauer** [comment]
Thanks, @adrianfish for creating the JIRA. I've reworded the commit to include the SAK

**Pull request merged**
