### PR TITLE
Provide a template format when GB doesn't contain any items

### PR DESCRIPTION
**Pull request by steveswinsburg**
**Please merge #3107 before this one as this is branched from that one**

If there are no assignments to export, provide some examples
Remove Student ID and Student Name from translations as these are magical
Updated javadoc as these methods return an empty list, not null.
This is part of #1396

### CODE REVIEW

**Comment by payten** [comment]
Boo conflicts after 3107 was merged 🚒

**Comment by steveswinsburg** [comment]
Oh 💩😷. Fixed 👍 .

**Comment by payten** [comment]
Hey @steveswinsburg, now I'm all paranoid about Travis. It's failing but seems to be unrelated? Permission to ignore Travis? 🎱

**Comment by steveswinsburg** [comment]
Kicked it off again, see what happens :)

**Comment by steveswinsburg** [comment]
I re-ran this yesterday and it passed. It's failing again on unrelated problems so I say merge 🎉 🏁

**Pull request merged**
