### PR TITLE
SAK-37978 - Wrong style adding new forum on lesson builder

### PR DESCRIPTION
**Pull request by SedueRey**

### CODE REVIEW

**Comment by ern** [comment]
Maybe this css should live in lessons so that we don't pollute morpheus. I know some people probably will say whaaaaatttt!  I just feel this is a workaround specific to lessons and putting this kind of markup in morpheus just doesn't make sense.

**Comment by SedueRey** [comment]
PR updated

**Comment by SedueRey** [comment]
@ern can you take a look? I forgot to bring it yesterday to the core call, sorry

**Comment by ern** [comment]
This css will need to be (cleaned up) removed in the future.

**Pull request merged**
