### PR TITLE
SAK-43661 Add property to force grader toggle to default to off

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-43661

### CODE REVIEW

**Review by bjones86 — CHANGES_REQUESTED** [review]
Please add the new property to `default.sakai.properties` with documentation.

**Comment by adrianfish** [comment]
@bjones86 It's already there from the previous commit. This is a reopened ticket.

**Comment by bjones86** [comment]
Ok, thanks.

**Review by bjones86 — APPROVED** [review]

**Comment by adrianfish** [comment]
@bjones86 Thanks for the review, Brian.

**Pull request merged**
