### PR TITLE
SAK-30146 - Add capabilities to login with OAUTH2 providers.

### PR DESCRIPTION
**Pull request by mpellicer**
SAK-30146 - Add capabilities to login with OAUTH2 providers.

The default tests were done with MITREID connect and GOOGLE but should work with several providers.

Default config using MITREID demo as oauth2 provider.

### CODE REVIEW

**Comment by ern** [comment]
Since we are already using Spring Security with CAS and (recently SAML) I wonder why you chose not to leverage spring security's support for oauth2? The PR would've mostly been xml if you had.

IMO opinion we should be leveraging libraries to doing this kind of thing vs rolling our own implementation.
http://projects.spring.io/spring-security-oauth/docs/oauth2.html
https://github.com/pac4j/pac4j

In doing so could have avoided creating a separate servlet in the login tool.

**Comment by frasese** [comment]
We faced some problems using spring security libraries, that's why we decided to move to our custom implementation.

**Comment by ern** [comment]
I understand, though would've been nice to have heard about those challenges as people do use spring-security-oauth with MITREid.

**Comment by ottenhoff** [comment]
I've had problems getting started with spring-security too, but the advantages of using a unified library are huge! Earle helped me out with spring-security-saml, and it was very elegant (very little code) once he helped me get going .....

**Comment by mcarropellicer** [comment]
I'm sure about that, but @frasese spent a lot of time trying to use spring-security as the MITREID client does, he had a lot of problems because the spring version was different (3.x v 4.x) and other issues with libraries and the current implementation with CAS.

Our deadline was near so we did it in this way, i agree is not the best or optimal implementation but definitely works, unluckily we cannot put more efforts on this for the moment.

**Comment by ern** [comment]
So the spring-security-web lib that's used with spring framework 4.1.8 is 3.2.8.RELEASE which is compatible with spring 4.1.x. At the time of upgrading spring that was the recommended version to use.

When I have little time I will try to put up an example of spring security using oauth2 and MITREID.

**Pull request closed without merging**
