### PR TITLE
SAK-32161 Make Overview page column widths customisable

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**
and ensure that they fill the whole screen width on a mobile phone.

The column widths can now be customised with Sass variables.  I have checked that the calendar is next to the main content on a desktop sized screen for several column sizes, and that the calendar/announcements sit on top of the content and fill the whole screen width on a mobile sized screen.  See Jira for more screenshots.

Post fix screenshot:
postfixmobile

### CODE REVIEW

**Comment by ottenhoff** [comment]
My PR #4028 contains a fix for the mobile issue

**Comment by RebeccaOxfordUni** [comment]
This fixes the broken two column display.

**Comment by adrianfish** [comment]
There's a bit  of  problem with the new NYU stuff applied. This needs a bit of tweaking but seeing as this is a bug fix, we're good for after tomorrow.

screen shot 2017-03-13 at 22 05 39

**Comment by lardo-de-arnaud** [comment]
can you take a look at the in the light of NYUs changes as of yesterday

**Comment by ottenhoff** [comment]
I will incorporate into SAK-32307

**Pull request closed without merging**
