### PR TITLE
SAK-32498 - Javascript error logging in "moment is not defined"

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
These errors came when bullhorns came in. I feel like the easiest fix is just to fail the bullhorns javascript if these dependencies aren't available since they aren't needed here anyway. Maybe it should print an error to the console?

**Comment by buckett** [comment]
If we're going to use `morpheus.scripts.min.js` in places other than the portal should we have a standard set of dependencies we also pull in?

Otherwise it's easy for someone to create this problem again of adding a library to the portal, using it in a morpheus script and then causing problems for the login tool (or somewhere else).

**Comment by jonespm** [comment]
Yeah, perhaps, but these are pulled in from webjars and then included. Everything else is packed into morpheus.scripts.min.js. I think it's a question of should every dependency be packed into morpheus.scripts.min.js? Or should they all be doing checks to see if the dependency is available? As far as I can see this (bullhorns) is the first one that's relied on other dependencies being available first. And in the context it's in, it's minor since it doesn't seem to actually cause any user facing error son the page it's used on anyway.

I thought about changing xlogin.vm to include all of these dependencies before this individually but also felt we'd run into the same problem where new library has new dependencies and it breaks down the road.

**Comment by jonespm** [comment]
But yeah I'd agree there's two fixes here either
1) Require all morpheus packed in scripts to fail or still work if the libraries it needs aren't available
2) Pack in all scripts that morpheus packed scripts requires via the yuicompressor-maven-plugin in the library/pom.xml and remove from direct inclusion. Or maybe have a  I'm not 100% sure sure if it would work with the webjars and those deps or not but maybe worthwhile?
3) (Not sure how this would happen) but maybe have some type of requirejs style pattern for the morpheus.scripts that would loada the webjars it needs without packing them in??

I feel like either this could be accepted (since it's the only problematic script at the moment) for now, or someone could close and work on 2 (or 3?)

**Comment by buckett** [comment]
I'm not saying we shouldn't make this change, just that it feels like we're papering over the cracks and having a better way of managing JavaScript dependencies and loading is something we should think about for the future of Sakai.

**Comment by jonespm** [comment]
Yeah, I completely agree. I would love to research the requirejs + webjars, or webjars locator or something to make all this javascript inclusion and dependencies a lot better and wrote a little about that on https://jira.sakaiproject.org/browse/SAK-31306. I just don't have the time right now. :/

**Pull request merged**
