### PR TITLE
SAK-47279 Grading: add delete method for comments

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-47279

### CODE REVIEW

**Comment by plukasew** [comment]
Is this a hard delete? If so, what is the rationale for not using a soft delete instead?

**Comment by plukasew** [comment]
I don't know enough about this architecture, but I would think that we'd want to use soft deletion across the board for anything entered by a user like a comment.

**Comment by adrianfish** [comment]
I'm okay with the soft delete. That's how the current assignments are deleted, they just have a column "removed" set to true. However, there is no UI as I can see for hard deleting or restoring them - it must be a dba job. That said, at least the data is still around and can deleted later, or restored just by updating the "removed" column. It's more work, obviously.

**Comment by adrianfish** [comment]
So, as Paul says, the lti service call will just remove it and it will disappear. The grading apis just ignore "removed" stuff.

**Comment by csev** [comment]
@adrianfish - Did you see my comment about line 2446 above?   There are two places to fix in the service.

**Comment by adrianfish** [comment]
there's no history of what grade and comment was applied, so we just have what is in the db. Will this delete a comment method do for now? I feel this has been sat around long enough now, tbh. We could jira keeping a history of grades and comments, or just doing soft delete on it - after a bit more thought.

**Comment by csev** [comment]
Yes @adrianfish - I am perfectly happy with a delete method that just does the delete - we can revisit any time - but lets move this forward.

**Comment by csev** [comment]
Please fix the second place where it wants to delete the comment.  (see above) Could you also change line 2446 to check if the comment from the incoming request isEmpty and call delete comment instead of sending null or blank to setAssignmentScoreString?

**Comment by csev** [comment]
Hey @adrianfish - I want to approve this but your are missing a one line fix described above.

**Review by csev — CHANGES_REQUESTED** [review]
Please look at line 2446 and if the comment is balsnk or noll call the new delete method.

**Review by csev — COMMENTED** [review]
Catch the places where a score came in without a comment.

**Review by csev — CHANGES_REQUESTED** [review]
Did this request make it back from github.dev?

**Comment by csev** [comment]
So @adrianfish - I tried to use the review / submit change to get the changes I needed in.  I think it worked.

**Review by ern — APPROVED** [review]

**Review by csev — APPROVED** [review]

**Pull request merged**
