### PR TITLE
SAK-32698 - Add user-agent to HEAD request

### PR DESCRIPTION
**Pull request by csev**

### CODE REVIEW

**Comment by buckett** [comment]
I can't see the Jira issue for this. https://jira.sakaiproject.org/browse/SAK-32698

I think it should have been committed under: https://jira.sakaiproject.org/browse/SAK-32689

**Comment by csev** [comment]
Yes - How can I fix this?

/Chuck

**Comment by smarquard** [comment]
Hm OK I just created SAK-32698 for another issue and was confused to see this PR already linked :-)

**Comment by buckett** [comment]
The only fix is to re-write history, which creates problems for people so it's probably just best to leave as is.

**Pull request merged**
