### PR TITLE
SAK-33509 Disabled actions on site resources

### PR DESCRIPTION
**Pull request by joaquinmarques**

### CODE REVIEW

**Comment by jonespm** [comment]
I think the language here is a little too 'techie'. Any UX feedback? Maybe something like

"Actions will be enabled after selecting a file or folder"

Also the name of the property with the other property names in this file and not introduce camelcase and underscores.

**Comment by ncaidin** [comment]
How about "To enable the actions, select a folder or content item." 
?

**Comment by ncaidin** [comment]
@jonespm , I didn't notice you had made a suggestion for the wording. Your wording and my wording are just about the same. Whichever seems closer to the current Sakai style? Maybe that is yours?

**Comment by berappl** [comment]
@jonespm and @ncaidin Good afternoon, Neil and I were reviewing a couple of examples during the Sakai Triage call and I feel that the active voice in Neil's is a little closer to the other examples of this: 

"Check a box and use the buttons above or below to take action on a site. Click column headers to sort the table."

"Enter a user id below and click "Become user" to login as that user."

**Comment by jonespm** [comment]
Okay text updated, thanks for the changes.

**Pull request merged**
