### PR TITLE
SAK-29251 Default for Turnitin assignment 'save' option should not be set

### PR DESCRIPTION
**Pull request by steveswinsburg**
When creating a new assignment with TII feature , the default is 'None' for the repository in which to submit/store the student's paper. Remove any default so that the assignment creator is forced to make a conscious selection. Pop up a reminder box if they have not done so.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Again the error from Travis looks unrelated. Is there an issue with the build server?

**Comment by steveswinsburg** [comment]
In a bit of an unusual state here. Merging this PR which has picked up the original commit due to the PR going into my master.

**Comment by baholladay** [comment]
This commit broke the VeriCite content review implementation by requiring VeriCite to select a Turnitin repository

**Comment by baholladay** [comment]
This error message is specific for turnitin but the error can happen for any content review service implementation

**Comment by baholladay** [comment]
I've created a PR https://github.com/sakaiproject/sakai/pull/428 for the accidental revert of https://github.com/steveswinsburg/sakai/commit/0be642e5f1410cce17acee3f5e9043282a4a157b

**Pull request merged**
