### PR TITLE
    LSNBLDR-222 - Add search capability to lessons

### PR DESCRIPTION
**Pull request by jonespm**
LSNBLDR-222 - Changes to canRead for access control, was checking the
    wrong content

### CODE REVIEW

**Comment by jonespm** [comment]
It closed my other pull request from https://github.com/sakaiproject/sakai/pull/185 probably because of a bad rebase. This is the same with the lessonsAccess incorporated and a bug fixed for checking the page Id. It puts a check for siteId in the lessonsAccess if it's null. I'm not sure how to optimize it to reuse the simplepagebean since every reference coming in could be random or even from different sites. . . Maybe if performance is a problem lessons content indexing should be disabled in the init method?

**Comment by ottenhoff** [comment]
@clhedrick thoughts on this PR?

**Comment by ottenhoff** [comment]
@jonespm can you make the edit suggested?

**Comment by jonespm** [comment]
Yeah, I can look at that adjustment tomorrow. I don't have any way of automatically testing search, mostly though the just through using it directly.  I could put a property in to disable this completely even if search.enable=true in general. I was thinking of having properties to disable each indexer, like if some school didn't want to index forums, or content or something, but wanted the other content. But that seemed like a separate feature.

**Comment by jonespm** [comment]
Okay, I made the edit as suggested

**Pull request merged**
