### PR TITLE
KNL-1361 - Add support for @System prefix in sakai.properties

### PR DESCRIPTION
**Pull request by csev**
If a property has the @System prefix as a suffix, it is turned into
a system-wide JVM property instead of a Sakai property.

### CODE REVIEW

**Comment by csev** [comment]
Please review this carefully in case there is a more Spring-ish way to do this. Thanks.

**Comment by ern** [comment]
I've been thinking of a larger idea to provide meta data to configuration via property files. I don't particularly like the "@" annotation since these properties are typically passed to Spring.

Maybe we can have a discussion on this topic?

**Comment by csev** [comment]
I was hoping to have a conversation about it.   The @properties get passed to Spring.  Our code controls that and we could "eat" the @System properties at a really clean place.  But the code that hunts for a bean with the @name and passed theproperty to it does not care if the @bean does not exist:

fred@org.samsonite.briefcase=zap123

Perhaps I should name the suffix something like @SystemLevelProperty so as to make sure we never hit a bean with that name.

I am also happy to change the code that passed the properties into beans and stop the @SystemLevelProperty ones from being forwarded to Spring.

I would be rather opposed to some new place for these kinds of properties - it is jsut one more thing to drag around when supporting lots of clients.   There needs to be some convention in sakai.properties IMHO.

**Comment by csev** [comment]
Lets chat in JIRA so if this PR is closed and resubmitted we have all the conversation in one place.

https://jira.sakaiproject.org/browse/KNL-1361

**Pull request closed without merging**
