### PR TITLE
SAM-2735: Event log showing events for removed assessments

### PR DESCRIPTION
**Pull request by ramonchu2k**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Why is it important for the event log to *not* show events for removed assessments?

**Comment by ramonchu2k** [comment]
The events of removed assessments must not be accessible for teachers since teachers are not allowed to see the rest of information about those removed assessments. Furthermore this info might disorient teachers because they will see all the events but don't know which are from removed assessments and which not.

**Comment by ottenhoff** [comment]
I don't know if I agree.

"Log" seems to indicate a history of events in the site. I don't think a "log" should be altered....

**Comment by jonespm** [comment]
I'm agreeing with Sam. I think if you wanted a separate view (method) that only showed active assessments and hid the deleted that would be fine, but this feels more like a feature. I wouldn't commit this as the default.

**Comment by raulsv** [comment]
Hi @ottenhoff, @jonespm 

The eventLog option only registers the student events when they are taking the assessment or submitting the assessment. These are all the events that can be registered:

No Errors (User submit), Error on Take Assessment, Error on Submit for Grading, Access Error, No Submission, Error on Begin Assessment, No Errors (Timer submit)

There is no creating/deleting assessment events or configuring assessment events or other authoring events.

All the Samigo options should be created to improve the user expierience. What kind of UX improvement is that instructor can check if the students submitted or not an assessment which has already been deleted by this instructor and it is no longer available?

If an instructor publishes 3 assessments with the same name (i.e "First assessment") and he removes 2 of them, Don't you think it might be confusing that all the events from removed and not removed assessments together will be displayed with the same assessment name: "First assessment"?

If a site has 30 assessments which 15 of them has been deleted, Don't you think it might be a little tricky to check the student assessment events between the removed or not removed assessments?

On the other hand, if this PR(https://github.com/sakaiproject/sakai/pull/2216) is not merged, there is a functional conflict in Sakai 12 right now: 

Taking into account that this PR(https://github.com/sakaiproject/sakai/pull/1968) has already been merged to trunk then the Event log filter (the pull down menu: see [image](http://www.evernote.com/shard/s345/sh/47369004-1866-4db2-bd02-6f84d19d1909/4018342e66fd6efc6cb80114ae27a7b6)) only displays the not removed assessments while the Event log list displays either the removed assessments and not removed assessments. Therefore the event log list (displays removed and not removed assessments) is inconsistent with its pull down menu (only displays not removed assessments).

**Comment by ottenhoff** [comment]
I still don't agree. I believe a log should be a full log. If the Teaching and Learning group disagrees, I'm happy to have this merged .....

**Comment by raulsv** [comment]
Hi @ncaidin 

Are you going to include this Jira [SAM-2735](https://jira.sakaiproject.org/browse/SAM-2735) in the next TL meetings: (4/20/2016) or (5/4/2016)? If so, could you take into account the use cases explained in my last comment?

Hi @ottenhoff, @jonespm

If the TL group eventually decide this PR(https://github.com/sakaiproject/sakai/pull/2216) will not be merged, don't you think the PR (https://github.com/sakaiproject/sakai/pull/1968) should be unmerged from trunk? 

I ask it because the PR(https://github.com/sakaiproject/sakai/pull/1968) includes this change: the Event log pull down menu: (see [image](http://www.evernote.com/shard/s345/sh/47369004-1866-4db2-bd02-6f84d19d1909/4018342e66fd6efc6cb80114ae27a7b6)) only is displaying the not removed assessments (removed assessments are excluded) while the Event log list displays the removed assessments and the not removed assessments. Therefore the event log list (displays removed and not removed assessments) is inconsistent with its pull down menu (only displays not removed assessments).

If this Jira eventually is not merged, we believe that another fix might be this feature request:
Display crossed out all the removed assessments and all the events from removed assessments. What do you think about?

**Comment by ncaidin** [comment]
Maybe a solution instead of deleting removed assessments from logs would be to add events to the log that show creating and deleting assessments? I'll see if we can get it on the Teaching and Learning agenda today.

**Comment by raulsv** [comment]
Hi @ncaidin, @ottenhoff, @jonespm

Consensus seemed to be NOT to remove the entries, from the TL call on 20 April 2016. Therefore, the PR (https://github.com/sakaiproject/sakai/pull/1968) from this Jira should be unmerged from trunk, do you agree?

Thanks neal to bring this issue to the call. Regards,

Raúl S.

**Comment by ottenhoff** [comment]
Yes, I agree

**Comment by juanjmerono** [comment]
I think is not necessary unmerge #1968 because is not in 11.x branch and I think you will bring us the final solution soon, so I think it could stay broken in master for a while.

**Comment by ramonchu2k** [comment]
I close this PR since I made new solution according to TL call on 20 April 2016

**Pull request closed without merging**
