### PR TITLE
SAK-30809: Make Contact Us added to new site by default

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Anyone else have thoughts on this default change?

**Comment by lardo-de-arnaud** [comment]
This tread was very supportive of this approach so long as there is a way you can opt out of deploying to every site. We believe we do have a way of doing this.

That thread again: https://groups.google.com/a/apereo.org/forum/#!msg/sakai-dev/ykKbU_q88yY/AfLRHwkiEQAJ

**Comment by ottenhoff** [comment]
required=true means there is no way to opt out.....

**Comment by lardo-de-arnaud** [comment]
Ah - we definitely need a way to opt out. I'll get Nick (@nicholaswilson100 ) and Matthew to figure out what to do

**Comment by lardo-de-arnaud** [comment]
Our idea was that they would change the XML file to remove required=true then restart the server. We will provide guidance in the readme.md about this. Matthew also seemed to think that there was a way to remove required=true without a server restart.

If there's a better way to do this then let us know

**Comment by ottenhoff** [comment]
If the majority of institutions want this tool to be required, I'm fine with this change.... I have no idea if that's true though....

**Comment by lardo-de-arnaud** [comment]
I posted to Sakai-user and Sakai-dev - 3 people said it was a good idea and nobody spoke up against it. At the T&L call (a few weeks ago) most people thought it should be on every site. The only negative comment was that one should be able to disable this feature which we think we can achieve by telling people to remove the "required=true" line from the XML (& not run the backfill XML).

I know this isnt very scientific and it's not a big sample! I could ask again if you like.

**Comment by ottenhoff** [comment]
I think it should be added as just another tool ..... not required ....

**Comment by steveswinsburg** [comment]
Agree, add it as a tool but don't force it on everyone.

**Pull request closed without merging**
