### PR TITLE
SAM-3252 fix deadlock issue observed in trunk

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by plukasew** [comment]
Does this change get us back to square one where one "bad" attempt will roll back all the current attempts the job is processing?

**Comment by ottenhoff** [comment]
> Does this change get us back to square one where one "bad" attempt will roll back all the current attempts the job is processing?

I don't know how to replicate that, but this change allows the auto-submit job to run without error in my testing. The current code in master does not work in my testing, even on one single submission.

**Comment by plukasew** [comment]
The code did work on multiple submissions when I contributed it originally. The details to replicate the situation this was meant to address are on the Testing tab of SAM-2940.

**Comment by ottenhoff** [comment]
REQUIRES_NEW: "Create a new transaction, and suspend the current transaction if one exists." Suspending the current transaction seems problematic with our use of Hibernate

Multiple submissions still works with this change. " The AutoSubmit job encountered errors during processing and had to skip 1 attempts/submissions. The remaining attempts/submissions were processed successfully."

**Comment by plukasew** [comment]
Awesome, so we didn't lose anything. Maybe isolating the updates into their own method was enough without having to create a new transaction each time.

**Pull request merged**
