### PR TITLE
SAK-32637 AutoFavorites: Issue after using the auto-favourite featur…

### PR DESCRIPTION
**Pull request by josecebe**
…e for the first time

### CODE REVIEW

**Comment by mpellicer** [comment]
Please don't merge this yet, it's still under discussion with SAK-32583

**Comment by mpellicer** [comment]
Please mark this as "work in progress".

**Comment by ern** [comment]
There were 2 commits/reads for the same users Preference, could this be reduced to a single?

**Comment by mpellicer** [comment]
Hi @ern, I've tested the PR and works fine for me, I've migrated an 11.x instance and the admin doesn't have 1000 sites as favorites.

I think @josecebe saved the preferences twice because there is a return sentence if the newFavorites list is empty, in this case, the preferences will not be updated.

https://github.com/sakaiproject/sakai/pull/4535/files#diff-e61e31c57df240fc045355e93899e1ddR181

@josecebe Would you mind to rebase this PR?

Would be good if someone else could take a look at the PR.

**Pull request merged**
