### PR TITLE
SAK-33399 Search service decimal fix

### PR DESCRIPTION
**Pull request by jayee**

### CODE REVIEW

**Comment by jayee** [comment]
So... you are not maintaining the current released sakai with bug fixes?

**Comment by ottenhoff** [comment]
The Sakai community maintains 11.x via a maintenance branch strategy. A JIRA must be created for every issue. The PR should be submitted against the JIRA. Once the PR is accepted, the JIRA will transition to Resolved status. The QA team then verifies the bug was fixed. Then, if the "11.x Status" on the JIRA is set to "Merge", the maintenance branch maintainer will merge the fix into the maintenance branch.

**Comment by jayee** [comment]
Hi Sam, I still don't get it. In this case the code has been rewritten so the original (11.x) problem is not in the master. You are saying you won't fix bugs in maintenance unless they are in master too?

**Comment by ottenhoff** [comment]
If it's a special 11.x that does not apply to master, then yes, submit it as a PR and make it clear why it is a special PR against 11.x

**Comment by jonespm** [comment]
Also this should be using the utility method

FormattedText.getNumberFormat(dec);

**Comment by jayee** [comment]
My fault I missed the problem in master too. I did not search for the bug thoroughly enough.

For this case I think it's overkill to use FormattedText and juggling with decimal format. It is a double representing a size in GB that should be output in the statistics view for a search admin.

**Pull request closed without merging**
