### PR TITLE
SAK-29446 add username as custom launch data

### PR DESCRIPTION
**Pull request by mcarropellicer**
SAK-29446 add username as custom launch data

### CODE REVIEW

**Comment by buckett** [comment]
Could you correct the author on this please.

**Comment by ottenhoff** [comment]
Two quick questions:

1) Can the display id return null?

2) Why not always display this value instead of only displaying it if different from eid?

**Comment by buckett** [comment]
The display ID is always defined.
I think it was originally so that it didn't clutter up peoples LTI URLs unless they needed it.

**Comment by buckett** [comment]
@ottenhoff Are you still thinking we should always ship the display ID across?

**Comment by ottenhoff** [comment]
I think it makes more sense to always display it ........ it's easier on custom tool developers

**Comment by mcarropellicer** [comment]
Close as duplicated.

**Pull request closed without merging**
