### PR TITLE
KNL-1352 - Tools should have their own TitleCustom property

### PR DESCRIPTION
**Pull request by danielmerino**

### CODE REVIEW

**Comment by csev** [comment]
Like looks harmless - but does not appear to actually persist the custom title information.

**Comment by steveswinsburg** [comment]
Yeah is this relying on someone else calling a commit/save on the objects?

**Comment by danielmerino** [comment]
I'm currently migrating my university's deployment to 10.4 version and I don't have time to complete this PR in this moment. I have been suggested to close it and reopen when I have time to do it (probably in one-two months).

**Comment by danielmerino** [comment]
I'm having a hard time trying to solve this issue.

BaseToolConfiguration receives a SitePage object as parameter when it's created. When a tool's title is retrieved, the getTitleCustom method looks for sitePage's customTitle property.

However, Placement properties are not set at this point, so I don't know how to override sitePage's property.

By the way, there is some duplicate code in BaseToolConfiguration.getTitleCustom method that is also in SitePage.getTitleCustom.

Trying to get the placement from SitePage object passed as parameter causes a database block, maybe some kind of circular dependency.

I don't know what more to try. Suggestions are welcome.

**Pull request closed without merging**
