### PR TITLE
SAK-46555 Text descriptions for Sign-up permissions view are not defined

### PR DESCRIPTION
**Pull request by josecebe**

### CODE REVIEW

**Comment by josecebe** [comment]
I extracted these texts from signup Readme.md

**Comment by jesusmmp** [comment]
@josecebe Please, could you add permission ES properties? Thanks!

**Comment by josecebe** [comment]
> @josecebe Please, could you add permission ES properties? Thanks!

Hi @jesusmmp , I have the translation but should I add it now or it would be better to add by transifex?

**Comment by jesusmmp** [comment]
> > @josecebe Please, could you add permission ES properties? Thanks!
> 
> Hi @jesusmmp , I have the translation but should I add it now or would be better to add it by transifex?

If you add it, we could check all is right when merged, so we don't have to wait until another translation PR.

**Comment by josecebe** [comment]
@jesusmmp I've just added the translations for spanish and català

**Review by jesusmmp — APPROVED** [review]
LGTM! Thanks @josecebe

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
