### PR TITLE
KNL-1221 use new Java 7 Zip methods that allow for charset

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by buckett** [comment]
Nice one.

**Comment by buckett** [comment]
There's a comment in the Jira about supporting other character encodings.

**Comment by ottenhoff** [comment]
Okay, I'll wait for feedback from Gao Jun. I'm a bit wary of the idea of Sakai supporting additional charsets besides UTF-8

**Comment by buckett** [comment]
@ottenhoff Yeah, I was wondering why you would use anything other than UTF-8.

**Comment by csev** [comment]
Everything I hear is that best practice is UTF-8 for transmission and storage.  That said, some computers run with UTF-16 all the time in their internal files and characters for efficiency.  While it is best practice to convert to UTF-8 in areas where data will leave the system, mistakes will be made and files will escape as UTF-16.   To me the right approach is to *deal* with UTF-16 as the file is unzipped - but make *sure* that before Sakai stores any string information or file data that it is converted to UTF-8.  The Sakai DB does not support UTF-16 and is not likely to every support UTF-16.  But we will increasingly see UTF-16 data wandering in.

**Comment by Gao-Jun** [comment]
I have made another PR to this issue.

**Comment by buckett** [comment]
The other pull request is #906

**Pull request closed without merging**
