### PR TITLE
SAK-46273 Turnitin > files over 100mb should be rejected before attempted submission

### PR DESCRIPTION
**Pull request by baholladay**
https://jira.sakaiproject.org/browse/SAK-46273

### CODE REVIEW

**Comment by baholladay** [comment]
This led me down a rabbit hole... turns out, the only library I could find that would handle the "Too Large" case was Apache's HttpAsyncClient since it has non-blocking IO. I also took the liberty to make the request method use the more common method for making requests for this library.

I tested locally with several examples and all looks fine. I'm not 100% sure about production level traffic. It uses the default client settings (just like the previous code).

**Review by adrianfish — APPROVED** [review]
Looks good to me. You've improved the response code handling and switched to using apache's asynchronous http client api. The http code is cleaner. Thanks :)

**Comment by bjones86** [comment]
So when I created this JIRA I had a bit of a different idea in terms of implementation. As the title suggestion, I don't like that these files are even submitted to TII. It's already known that they're too big, so we shouldn't even bother submitting it. Also the error message here is still misleading: 

> An error occurred submitting this item to the originality checking service. The system will automatically try to re-submit this item. Troubleshooting information: 413: Payload Too Large

This could leave the user with the impression that the system will attempt to resubmit the item, and there doesn't need to be any action from the user.

I think a better use case for this would be to not upload the submission at all. Once the file is determined to be too large, abort then and there, don't send it to TII. The error message should be something like "This file is too large. Files larger than 100mb cannot be submitted to Turnitin. Please upload a different file."

It should not continuously attempt to submit the file when it's too big.

**Comment by baholladay** [comment]
I agree with most of what you are requesting. A few issues I have are with the 100MB pre-check:
-There isn't a hook in the content review service to provide max filesize limit (maybe we should add one). Would you want the student to not be able to submit the file or just give them a warning?
-The assumption that 100MB is static (and no way of providing this dynamically, at least in TII's API)

>It's already known that they're too big
There isn't a way to know the file size limit dynamically... we can assume the 100MB limit and hard code it, but it could change

>error message here is still misleading
I can see if I can make this cleaner (without mentioning 100MB)

>It should not continuously attempt to submit the file when it's too big.
agreed

In all cases, these requests should build on top of this PR since it still improves the handling for the httpclient requests. Should we create a new Jira or hold off on this PR?

**Comment by bjones86** [comment]
I don't think we need a new JIRA. It would be great if this work was all done here (sorry).

I think hard-coding the 100MB limit in Sakai is fine. If TII changes it at a later date, we can change it too. Also, if we have the limit hard coded, then you can include it in the error message so that students are aware of the file size limit, and aren't just uploading random file sizes in the hopes that something works.

> Would you want the student to not be able to submit the file or just give them a warning?

The submission in Assignments should be allowed, in case the instructor wants to see what the student submitted. Only the TII error message should indicate the file is too big, and won't be uploaded to TII as is (tell them they need to provide a file under the 100mb limit in order to upload it to TII).

**Comment by baholladay** [comment]
>The submission in Assignments should be allowed, in case the instructor wants to see what the student submitted. Only the TII error message should indicate the file is too big, and won't be uploaded to TII as is

This sounds like what is already happening, except currently with a less helpful error message. If I do the following, would this satisfy your requirements:
-Update the error message to say the file is too large with a static 100MB stated limit
-Update the error handling so that it doesn't say it will retry (I'm not 100% sure if that is something I can change, it may be an automatic error message and retry mechanism from content-review service)

**Comment by bjones86** [comment]
I'm not sure about how the new integration works, but in previous incarnations you could just avoid putting the item in the queue and give it any error message and status you wanted in the code.

What we're trying to achieve here is to not submit the paper to TII if the paper has a known issue (like file is too big). There's not much point in putting it in the queue and retrying it indefinitely if the file is over the limit.

If it's not possible to check file size before attempted upload to TII, this would be surprising to me. If this is actually the case, and the only option we have is to submit it to TII and then tell the user the problem and lie to them that it won't be retried, then I guess that's the lowest common denominator. That said, I would prefer that it not enter the queue at all, and we just put a static error message on it saying "File is over X limit for uploading to Turnitin...." etc etc

**Comment by baholladay** [comment]
>What we're trying to achieve here is to not submit the paper to TII if the paper has a known issue (like file is too big). There's not much point in putting it in the queue and retrying it indefinitely if the file is over the limit.

I think it only matters what the user's experience is. If we are not trying to warn them or prevent them from submitting and we are only concerned about notifying them of the TII error after submission, then I think the queue is the best place to handle this. This way, it will be self contained inside the content-review service and we won't have to make assumptions for file size by relying on the process to upload the papers and get the failed status from the API. From TII's integration perspective, its relatively cheap to try to upload and fail immediately (it fails before the file is even uploaded by inspecting the content-length header). I agree we should fix the error messaging and stop reattempts after we get the 413 error from the API. Also, by keeping it in the queue, we can retain the error data in the database for reporting/debugging.

**Comment by bjones86** [comment]
Okay, thanks for the explanation. I think that sounds reasonable.

**Review by bjones86 — APPROVED** [review]
Thanks, @baholladay!

**Pull request merged**
