### PR TITLE
SAK-33901 Add scrollbars in grades table (11.x)

### PR DESCRIPTION
**Pull request by josecebe**

### CODE REVIEW

**Comment by josecebe** [comment]
With my PR it looks like this:
61cecd2f1bac2b40757cef5f13d09ef3

**Comment by sinmsinm** [comment]
Looks great. This is an issue our teachers have already detected. (not having scrollbars at table level). So this patch solves it perfectly. @payten I would love to have it in 11.x. It would be great if you approve it if it's right.

**Comment by payten** [comment]
Noticed a few little things:
- When keyboard navigation around the cells and using the up arrow also affected the outer window scroll causing the viewport to bounce vertically and the selected cell to sometimes be hidden below the fold or the fixed header
- Cell context menus can open below the fold
But agreed, looks good!

**Comment by sinmsinm** [comment]
Is something else that has to be done here to merge? Maybe your suggestions @payten have to be implemented before? 

Thanks in advance.

**Comment by mpellicer** [comment]
Hi @payten, 

I think your request is fine but in my opinion is minor, and would require an important amount of work for a source that has diverged too much from 12.x/Master, where the problem is already fixed. We could provide more details if needed, we tried to backport the changes but 12 is completely different.

Would you mind to apply this changes as is? This has been tested by us and other institutions like UDL.

Thanks in advance

**Pull request merged**
