### PR TITLE
SAK-41080 Add tests for HelpManagerImpl

### PR DESCRIPTION
**Pull request by buckett**
This involved creating testings and removing unused code in the HelpManager API. Also unused files (hibernate) were removed and SizedList was also removed. The Sakai component configuration was split out into multiple files to make it easier to test.

### CODE REVIEW

**Comment by buckett** [comment]
There's quite a bit more cleanup of `HelpManagerImpl` that's possible however I didn't want to put too much in one change and it's a solid step forward.

The `HelpManager` API had lots of unused methods that weren't used outside being referenced in the implementation and I've culled most of these to make the API clearer.

Also commented out HBM files have been removed along with their matching class files.

**Comment by ottenhoff** [comment]
Running org.sakaiproject.component.app.help.HelpManagerImplTest
Tests run: 5, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 3.787 sec <<< FAILURE! - in org.sakaiproject.component.app.help.HelpManagerImplTest
testGetResourceByDocId(org.sakaiproject.component.app.help.HelpManagerImplTest)  Time elapsed: 0.025 sec  <<< FAILURE!
java.lang.AssertionError
	at org.sakaiproject.component.app.help.HelpManagerImplTest.testGetResourceByDocId(HelpManagerImplTest.java:73)
testTableOfContents(org.sakaiproject.component.app.help.HelpManagerImplTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NullPointerException
	at org.sakaiproject.component.app.help.HelpManagerImplTest.testTableOfContents(HelpManagerImplTest.java:39)
testSearch(org.sakaiproject.component.app.help.HelpManagerImplTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError
	at org.sakaiproject.component.app.help.HelpManagerImplTest.testSearch(HelpManagerImplTest.java:58)

**Comment by buckett** [comment]
Thanks, yeah. I can't reproduce this on my local Mac OS build, I'm wondering if it's only happening on Linux.

**Comment by buckett** [comment]
Fixed tests (was filesystem case issue).

**Pull request merged**
