### PR TITLE
SAK-44307 Legacy translations cleanup: en_ZA?

### PR DESCRIPTION
**Pull request by axxter99**
en_ZA check

### CODE REVIEW

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Thank you!

**Comment by mpellicer** [comment]
I'm curious, why do you want to add this locale to the defaults if the language pack is not part of Sakai right now?

**Review by mpellicer — CHANGES_REQUESTED** [review]
I'm curious, why do you want to add this locale to the defaults if the language pack is not part of Sakai right now?

**Comment by axxter99** [comment]
@mpellicer  
date English:
en_US: May 5, 1992
en_GB: 5 December 1922 (en_ZA, en_AU, en_NZ, ...)

US: Wednesday, September 16, 2020 3:18:25 PM SAST
GB: Wednesday, 16 September 2020 15:18:25 SAST
ZA: Wednesday 16 September 2020 3:18:25 PM SAST
AU: Wednesday, 16 September 2020 3:18:25 PM SAST
NZ: Wednesday, 16 September 2020 3:18:25 PM SAST
CA: Wednesday, September 16, 2020 3:18:25 PM SAST

**Pull request closed without merging**
