### PR TITLE
SAK-32379 Incorporate NYU skin changes for header, favorites and tool menu

### PR DESCRIPTION
**Pull request by payten**
Header Row Updates

* Update the Sakai Logo and make it larger
* Make separator between Noodle bullhorns and “Sites” menu the same height
* Hover states for the bullhorn icons is currently dark blue. Apply the same light white box-shadow glow on hover for these.
* Reduce the height of the banner row to 52px
* Remove animation and only fix the top logo banner when scrolling
* Add slight amount of padding on the right of the window to user dropdown menu
* Change styling of the profile picture "Change" button
* To ensure WCAG contrast compliance for the text in the header, use a darker blue for secondary background color: #3949AB
* Moved the role switcher from the tool menu to the top banner

Favorites Row Updates

* Match favorite sites row min-height with the banner height: 52px
* Implement NYU Classes styles for the default/hover/active button states
* Implement NYU Classes styles for the tool submenu and menu item default/hover/active states
* Remove padding from the right of the “Home” button

Left Tool Menu

* Appy NYU Classes styles for default/hover/active button states
* Affix the collapse toggle menu item to the bottom of the page and apply NYU Classes styles
* Set the tool menu width to 200px
* Clean up styles on mobile version

Portlet Content

* Apply a minimum height to portlet content so it minimally matches the toolmenu height

### CODE REVIEW

**Comment by ottenhoff** [comment]
Okay, mostly looking good. Main issue: View Site As in upper bar is tough on mobile. Here is a screenshot:

screen shot 2017-03-26 at 8 55 20 pm

**Comment by payten** [comment]
Thanks @ottenhoff!  I think I've fixed it:
screen shot 2017-03-27 at 1 35 33 pm
screen shot 2017-03-27 at 1 36 12 pm

**Comment by adrianfish** [comment]
@ottenhoff I'll try it out, too, if you want.

**Comment by ottenhoff** [comment]
Awesome, yes, please

**Comment by adrianfish** [comment]
Okay, I'm on with it.

**Comment by adrianfish** [comment]
Bit of weirdness going on here. Can be fixed later, though.

screen shot 2017-03-27 at 18 46 33

**Comment by adrianfish** [comment]
Enter access view needs some margin on the left, or something like that.

screen shot 2017-03-27 at 18 51 59

**Comment by adrianfish** [comment]
The minimised tool panel flyouts are messed up.

screen shot 2017-03-27 at 18 54 18

**Comment by adrianfish** [comment]
This is all small stuff we can sort and if you don't merge it soon, other stuff will clash with it. So +1 from me.

**Comment by adrianfish** [comment]
I just did some testing on IE11 and there are some problems. The usernav area is messed up, see the screenshot.
screen shot 2017-03-27 at 21 24 13

**Comment by payten** [comment]
Thanks @adrianfish, @ottenhoff. I've had a go at fixing those bugs:

Style the flyout to match the bg of the tool menu item:
screen shot 2017-03-28 at 11 14 46 am

Hide the role switcher icon when on mobile:
screen shot 2017-03-28 at 11 14 37 am

Fix the bullhorn count size and positioning:
screen shot 2017-03-28 at 11 14 29 am

**Comment by payten** [comment]
A request came in to change the Sakai logo - this has now been applied:
screen shot 2017-03-28 at 2 20 47 pm

**Comment by adrianfish** [comment]
Sweet. I'll check it out again.

**Comment by adrianfish** [comment]
I'm happy with this now. I've tested Payten's latest on FF, Chrome, Safari and IE11 and it looks good.

**Comment by lgekeler** [comment]
Form and Function:
nextbuttoninmaster

**Pull request merged**
