### PR TITLE
SAK-33985 - Portal: Page reset link in conflict with the tool list (Mobile)

### PR DESCRIPTION
**Pull request by SedueRey**
The "Tool" word width was harcoded on CSS, this PR modifies the behaviour and adapts to every language not just english.

### CODE REVIEW

**Comment by SedueRey** [comment]
This is the new behaviour
spanish_language
chinese
english
german_language
japanese
only-icon

**Comment by mpellicer** [comment]
Wow, thank you so much @SedueRey! This is really important for the 12 release.

**Comment by jesusmmp** [comment]
You have left some CSS styles commented ;)

**Comment by SedueRey** [comment]
Thanks to take a look, @jesusmmp ... it's fixed now.

**Comment by jesusmmp** [comment]
Great

**Pull request merged**
