### PR TITLE
SAK-41516 - dropbox scss needed a style for div.alertMessage to match…

### PR DESCRIPTION
**Pull request by maurercw**
… what is in the resources scss.

### CODE REVIEW

**Comment by maurercw** [comment]
My change is consistent with the rest of the file, so I'm not sure if you want me to make Codacy's suggested change or not.

**Comment by mpellicer** [comment]
The change looks good to me, any thoughts @fostersdesign ?

**Comment by fostersdesign** [comment]
Is this alert box never needed in Dropbox? If it is needed, then the proposed style changes will prevent the box from ever displaying.

Would it be better to control the visibility of this box in Java with a conditional that will only make the box render if there is a message to display?

**Comment by maurercw** [comment]
I just used the same style that resources was using since it's a shared page.  I'm not sure if there are validation messages that would show up here in either case or not.  If neither tool needs that, I'd suggest just removing it, but I didn't dig too deeply on it.

**Comment by maurercw** [comment]
Finally came back around to look at this.  If you set `copyright.requireChoice=true` in sakai.properties, it will perform a copyright check.  If you don't choose anything, there is javascript that will use jquery and put text in that div and show the validation warning.  So, I believe what I did is correct.

**Comment by fostersdesign** [comment]
Okay. Thanks, @maurercw! 

Maybe just add an inline SASS comment beside that display:none to remind us in the future that the banner is hidden by default, but JS will make it visible when it's needed. Thanks.

**Comment by maurercw** [comment]
Comment added

**Comment by adrianfish** [comment]
@bjones86 @fostersdesign Good to go? Chris has made the changes.

**Pull request merged**
