### PR TITLE
S2U-31 5.1.4.2 Assignments: Grades in the main view of assignments th…

### PR DESCRIPTION
**Pull request by JuanDavid102**
…at have already been evaluated - fix

### CODE REVIEW

**Comment by mpellicer** [comment]
@JuanDavid102 Check this comment please

https://github.com/sakaiproject/sakai/pull/11207#issuecomment-1410386804

**Comment by mpellicer** [comment]
@JuanDavid102 Did you test all of this with all the possible grade combinations and groups? We can retest in QA, the data exists.

**Comment by JuanDavid102** [comment]
Yes, i try all possibilities

**Review by mpellicer — APPROVED** [review]
Nicely done!

**Pull request merged**
