### PR TITLE
SAK-31516 Assignments submissions allow hidden perm

### PR DESCRIPTION
**Pull request by buckett**
When a user is submitting an assignment we grant them the ability to see hidden folders so that they
can see inside the hidden attachments folder. This also switch the content review security advisor to use the same code. The permissions it granted were slightly different but I don’t think that the additional permissions are needed.

### CODE REVIEW

**Comment by buckett** [comment]
@baholladay @bjones86 Do either of you know why the content review advisor wanted permission to overwrite files owned by other people?

**Comment by bjones86** [comment]
I have no idea. Seems a little suspect to me.

**Comment by baholladay** [comment]
My guess is that there may be a case where a TA is trying to view a plagiarism report but it has not been submitted. This would trigger the content review service to resubmit the paper, which seems to need to have write capabilities. It may not be safe to assume that TA's have permission to write this file.

**Comment by buckett** [comment]
The only call into `prepareInlineForContentReview` is from the `post_save_submission` which should be done by the submitter. However what I don't follow is how the code handles group based assignments that allow re-submission.

**Comment by jonespm** [comment]
I think if we have concern about the AUTH_RESOURCE_WRITE_ANY permission, we should just add that in as an else case here, and print it out as an info or debug message. Then we'll see it all over the logs if it is being hit from something. If it doesn't get hit, there won't be anything!

Then we'll know early if it needs to be fixed or whats using it.

**Comment by buckett** [comment]
This does however leave mean that when you upload an attachment you get logging along the lines of:
```
app_1  | 2016-07-19 17:30:27,651  WARN http-nio-0.0.0.0-8080-exec-15 org.sakaiproject.content.impl.BaseContentService - availability check for attachment collection /attachment/e4343988-cd13-47d2-8f34-6f37749cacea/
app_1  | 2016-07-19 17:30:27,653  WARN http-nio-0.0.0.0-8080-exec-15 org.sakaiproject.content.impl.BaseContentService - availability check for attachment collection /attachment/e4343988-cd13-47d2-8f34-6f37749cacea/Assignments/
app_1  | 2016-07-19 17:30:27,653  WARN http-nio-0.0.0.0-8080-exec-15 org.sakaiproject.content.impl.BaseContentService - availability check for attachment collection /attachment/e4343988-cd13-47d2-8f34-6f37749cacea/Assignments/c9eb10d7-d518-4702-844b-0a8ffc0fa354/
app_1  | 2016-07-19 17:30:28,669  WARN Dashboard Event Processing Thread org.sakaiproject.content.impl.BaseContentService - availability check for attachment collection /attachment/e4343988-cd13-47d2-8f34-6f37749cacea/Assignments/c9eb10d7-d518-4702-844b-0a8ffc0fa354/
app_1  | 2016-07-19 17:30:28,671  WARN Dashboard Event Processing Thread org.sakaiproject.content.impl.BaseContentService - availability check for attachment collection /attachment/e4343988-cd13-47d2-8f34-6f37749cacea/Assignments/c9eb10d7-d518-4702-844b-0a8ffc0fa354/
```

The simple bypass for this logging is to make the user a superuser instead of just allowing these limited checks.

**Comment by jonespm** [comment]
Yeah, well that warning was put in there so we could see if anything was trying to access this.

I don't know about making the user a super user. Maybe lowering the log level of this message? It doesn't really say very much. I think if it wanted to be a little better it would log a little more information at a lower level.

I'm not worried about the dashboard ones.

**Comment by buckett** [comment]
I'm OK with this as it is now and we can fix the over verbose logging later on.

**Pull request merged**
