### PR TITLE
SAK-31675 Add a cache for the PA System templates.

### PR DESCRIPTION
**Pull request by buckett**
We ignore timestamp changes on the files as we're inside a JAR in a component so we never need to check for newer files.

### CODE REVIEW

**Comment by buckett** [comment]
Simple fix would just be to use `com.github.jknack.handlebars.cache.ConcurrentMapTemplateCache`

**Comment by ottenhoff** [comment]
Okay ready to commit?

**Comment by buckett** [comment]
@ottenhoff I think so. I was wondering if @marktriggs has a reason for not using the cache. Without the cache on every request handlebars will check the filesystem to see if the files have changed as the PA tool is in the footer of every page, there are 3 or 4 templates used in the footer so it results in needless IO.

I couldn't find any explicit documentation stating that the cache was threadsafe, but having a cache that only works on one thread isn't common and if that was the case why worry about concurrent use (classname).

**Comment by marktriggs** [comment]
I didn't worry about caching because frequently accessed files are cached at the OS level already, so my feeling was that IO difference would be negligible.  No strong feelings though, so add the cache if you found it makes a measurable difference.

**Comment by buckett** [comment]
@marktriggs Thanks. Yeah, I noticed this when I was profiling and it's just because it was showing up as eating up a few ms on each request. It's not a big part of the hit on each request, it's just because YourKit highlights calls that leave the JVM (file, network).

I agree that the OS cache means the timestamp check shouldn't cause a disk seek.

**Pull request merged**
