### PR TITLE
SAK-42390 Hierarchy: Update Test Spring 4

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by ern** [comment]
Why create another class? If it was because Codacy just ignore that class is to long bit! Some of the rules in Codacy are just guidelines!

**Comment by ern** [comment]
Hey Dave lets drop commit 2580275 it's not needed.

**Comment by axxter99** [comment]
@ern Codacy X: HierarchyServiceImplTest '"Avoid really long classes."

**Comment by axxter99** [comment]
@ern thanks! :)

**Pull request merged**
