### PR TITLE
SAK-41458 Block invalid key chars for point override

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by bgarciaentornos** [comment]
This doesn't solve all the issues described in the jira.

**Comment by adrianfish** [comment]
The behaviour with the ratings and the point override seems correct to me, and the code is a lift from the old version. If you override the points, they should stay overridden, it seems to me.

**Comment by adrianfish** [comment]
It's an easy change to make, but I don't want to change the behaviour from what it was before, unless I've got it wrong.

**Comment by bgarciaentornos** [comment]
I've attached a gif on the jira with the way it used to work, I can understand what you mean but, as it used to be different, I believe it's better to keep it like that. Consider it "overriding the override"...

**Comment by adrianfish** [comment]
Okay, I've watched it, thanks. I'll sort that out.

**Pull request merged**
