### PR TITLE
LSNBLDR-542 Added new lessons component "Add Resources Folder".

### PR DESCRIPTION
**Pull request by ouit0408**
Have added new method getResource() in ContentEntityProvider class to
serve resources for a site in json format.

To display folders in sakai, have added folder-listing.js,file-tree.js,
get-available-sites.js and file-tree.css in the reference folder which uses
getResource() method from ContentEntityProvider class.

In Lessons tool have created FolderPickerProducer.java and folderPicker.html
for the new screen.Edited ShowPageProducer.java,ShowPage.html and
SimplePageBean to accomodate requests from new producer.
messages.properties is edited to add new texts.

### CODE REVIEW

**Comment by buckett** [comment]
The tests don't pass.

**Comment by buckett** [comment]
@clhedrick It's a lessons one, do you have any comments?

**Comment by clhedrick** [comment]
I haven't actually tried the code. But in folderPickerSubmit, you need to start with 

                if (!itemOk(itemId))
                    return "permission-failed";
                if (!checkCsrf())
                    return "permission-failed";

canEditPage isn't good enough to validate access to an item. You have to check that the item is actually in the page. Otherwise you could hack on someone else's item. That's what itemOk does. This assumes you're in the Lessons UI, which mean you have a current page and site. You could also find the page and then the site from the item, then check permissions in that realm. But this code is right for most cases.

**Comment by clhedrick** [comment]
Also, I'm not so happy about looking for a string in the HTML to decide whether it's a folder or not. I suggest setting an item attribute, e.g. i.setAttribute("isFolder", "true") and then checking for that. Indeed overloading the TEXT method to show a folder seems weird to begin with, but I've done stuff that bad myself. I'd think it would be more like a special kind of resource.

Also, I'm now trying to use fontAwesome icons rather than images.

**Comment by ouit0408** [comment]
Have implemented above review comments and updated the PR.

**Comment by clhedrick** [comment]
OK. You're in a better position to test it, so I'll let you check it in. But please note that messages.properties currently removes messages from some new features. Make sure your patch doesn't remove anything.

**Comment by buckett** [comment]
Pull request has merge conflicts at the moment.

**Comment by clhedrick** [comment]
Can Oxford fix the conflicts? If not, I'll do it.

**Comment by clhedrick** [comment]
There's a reasonable chance that the code is OK, but tests need to be updated. The tests are in an area I'm not familiar with.

**Comment by ouit0408** [comment]
I will fix this.

**Comment by ouit0408** [comment]
Have fixed tests and updated PR.

**Comment by clhedrick** [comment]
I put it in, and built it. When I choose add resource folder, I get a chooser like this:


Adding files or folder to:main

Choose your Folder


Selected Folder
[  text field ]

 Save  Cancel

I can't type in the text field. What's supposed to be happening?

**Comment by ouit0408** [comment]
If you have files or folders added in resources for the site then in the 'Add resources folder' option of Lessons you will be able to add them in lessons.

**Comment by clhedrick** [comment]
OK, I'm back to new features, now that 11.1 is out.
It looks to me like the FolderChooser doesn't work. 
There's code under
            if (itemId != null && itemId != -1) {
for editing an existing item. But if itemId is null, which it will be when you're trying to add the tool the first time, there's no code. So the chooser doesn't show anything useful.

So you need to fix two things:
* make it work when adding a new item
* if there's no folders found, there should be a message saying something like "there are no folders in resources"

**Comment by ouit0408** [comment]
I am confused about the first comment as 'itemId ' will be -1 in this case for the new item and item can be null which we are checking at the top so don't have to worry later .

**Comment by nicholaswilson100** [comment]
The uptodate PR for LSNBLDR-542 is here :https://github.com/sakaiproject/sakai/pull/3622

**Comment by ncaidin** [comment]
will be incorporated by 3622

**Pull request closed without merging**
