### PR TITLE
SAK-41566 Cache the has associated rubric call

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-41566

### CODE REVIEW

**Comment by mpellicer** [comment]
Awesome! I saw many many calls for that data which is 99% of the time the same data, this will save a lot of resources. Thank you so much @adrianfish

**Comment by bgarciaentornos** [comment]
Lovely work, thanks!

**Comment by adrianfish** [comment]
@mpellicer @bgarciaentornos I feel like I have spread a little happiness today!

**Comment by mpellicer** [comment]
We need some kind of AI on the server side that should tell us "Why the hell are you asking me the same question again and again thousands of times?"  😆

**Comment by adrianfish** [comment]
@mpellicer Yes. Google AI - the one that works so well on YouTube!

**Pull request merged**
