### PR TITLE
LSNBLDR-453: fix inconsistent and improper syntax in CSS and JavaScript

### PR DESCRIPTION
**Pull request by bjones86**
The file Simplepagetool.css uses an invalid character ('#') to comment out lines, which is invalid syntax:

http://webdesign.about.com/cs/css/ht/htcommentcss.htm

Several of the JavaScript files (excluding jQuery stuff) use improper equation operators ( ==/!= vs ===/!==). These files are also missing several semicolons, which are syntax errors. An explanation of the differences between the operators, and why the identity operators should be used instead of the equality operators can be found on the following StackOverflow:

https://stackoverflow.com/questions/359494/does-it-matter-which-equals-operator-vs-i-use-in-javascript-comparisons

### CODE REVIEW

**Comment by bjones86** [comment]
Some of the JavaScript files have huge chunks marked as removed and re-added, I'm not sure why git/github did this.

The only changes to these JavaScript files are replacing ==/!= with ===/!==, adding missing semicolons, and removing some unnecessary commas.

**Comment by jonespm** [comment]
More likely it's changing your line endings. Like if you check in a file with Windows that was authored in Linux. Github is altering the line endings. I've seen this when using windows clients and working with Flash files in the past, it would look like the entire file was changed. I think I fixed it with this, but it would have to be re-committed.

https://help.github.com/articles/dealing-with-line-endings/

**Comment by bjones86** [comment]
Interesting, I'm using Linux; I'll have to look into that article. Also just realized that I forgot to check tab format in those files (spaces vs tabs), so that could also be causing it.

I'm going to close this PR and open a new one when I figure it out. Thanks Matt!

**Comment by jonespm** [comment]
Yeah, it could have been originally created with windows newlines too. Or it could be tabs if some editor is doing that, but it seems unlikely if you didn't even touch that file. We need to come up with some sensible configuration to try to avoid those problems though. Thanks!

**Comment by bjones86** [comment]
Turns out it wasn't line-endings or tabs vs. spaces, as I didn't add either. Literally all changes were adding a '=' or ';' here and there, and removing some un-needed commas.

I reverted the changes to rsf.js because that was the one that was most eye-offending; also decided since I'm not updating jquery stuff, I shouldn't update the rsf stuff either.

Created a new PR, #38

**Pull request closed without merging**
