### PR TITLE
SAK-42539 Move maximise button to tool header

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-42539

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 13
           

Complexity decreasing per file
==============================
+ library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=4742973&bid=15827822)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 13
           

Complexity decreasing per file
==============================
+ library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=4742973&bid=15827822)

**Comment by adrianfish** [comment]
Checkout the jira for some screenshots

**Comment by fostersdesign** [comment]
I would prefer for the fullscreen button to be on the left of the Link/Help buttons so that those buttons don't shift when you move between tools with the fullscreen option and tools without it.

**Comment by adrianfish** [comment]
@fostersdesign I initially had the button to the left of the help buttons, but I thought it would make more sense to keep it anchored to the top right, ie: to stop the max button jumping about.

**Pull request merged**
