### PR TITLE
Issue-2954 - Allow GradebookNG to use built-in letter grading schema

### PR DESCRIPTION
**Pull request by fgeraci**
#2954

### CODE REVIEW

**Comment by steveswinsburg** [comment]
There is quite a lot more to it than just enabling the option. There is the entire GradebookNgBusinessService that needs to be updated, as well as every panel that displays and formats grades needs to be reviewed.

**Comment by fgeraci** [comment]
Hello Steve. I will look into that tomorrow. But for what we intended to
do, it works by translating scaled points into letters. Thanks for the
heads up. Any case I could look at?

**Comment by jeffpasch** [comment]
Hi @fgeraci Thanks for raising this.

Aside from the technical considerations, we think there are important UX considerations around letter grade score entry, and it's a feature that could greatly benefit from user research, usability testing, and competitive analysis prior to implementing it in GBNG. Some quick examples that highlight this need:

- The letter grade entered correlates to the _lowest_ percentage score for that letter grade in the GB's grading schema. This isn’t transparent to the user. If you ask users, how many will guess that a letter grade maps to the midpoint percentage for that letter grade--e.g., 75% for a C rather than 73% (where a C has a range of 73% to 78%).  

- More problematic, because users can switch between letter grade, points, and percentage at any time, it’s possible for two students to have the same letter grade in the UI, but with two different numerical scores in the database. (e.g., Student-1 has a 73% and Student-2 has a 78%, but both show as a C in the UI). There’s no indication of this fact in the UI, which lacks transparency for both instructor and student. This could lead to two students having the same letter grades on items in the UI, but two different final grades or category averages. 

- Finally, interactions with tools that feed grades to the GB will need to be considered closely. Instructors who wish to use letter grades in the gradebook will mostly likely also want to use them in other tools, like Assignments. However, even though Assignments has the option to use letter grades or percentages for grading, instructor can only use points to send scores to the GB from Assignments. 

So, we think letter grades in gradebook is an area that’s ripe for user research, usability testing, and competitive analysis. Something to consider for the future, definitely.

**Comment by fgeraci** [comment]
thanks @jeffpasch for the feedback. This might have not be considered by the QA here. I will proceed to close this PR, look into this issues and get back later on.

**Comment by fgeraci** [comment]
@jeffpasch @steveswinsburg Thank you for the feedback. I understand switching between letter to points might carry instructional design complications. Still, our instructional design staff requested to enable this features. The short demo demonstrates how they tested it [demo - points to letters and back](https://goo.gl/bDTCBM) - We will continue working on this feature, and appreciate any ideas/ feedback.

**Pull request closed without merging**
