### PR TITLE
SAK-31274 - Order by term the hidden sites page

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
This is currently a work in progress. I'm moving this sorting method (getPortalTermOrder) over to portal utils because it incorporates both a portal server configuration variable and some logic that was already in portal, though it seems like it could just be right in CourseManagementService instead. 

Also I feel like we should change the sort order here to be newest first rather than oldest. Probably make reverse the default rather than reversing afterward? But this could also be changed in the CourseManagementService. Still testing and thinking about this one.

**Comment by jonespm** [comment]
I'd vote for it to stay in portal. I have another jira to refactor portal utils back into a service again, but that's for another day. It looks like the more sites is already reversing the order somewhere after this method . . .

**Comment by ottenhoff** [comment]
This makes sense to me. Anyone else have comments?

**Comment by mpellicer** [comment]
Makes sense to me too.

**Comment by jonespm** [comment]
Okay fixed a few small things, this is looking good for me now in testing

**Pull request merged**
