### PR TITLE
SAK-32223 Drop down now works as expected.

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by fostersdesign** [comment]
@adrianfish, what is the original ticket for the addition of the picture changer? Thanks.

**Comment by adrianfish** [comment]
@fostersdesign 

https://jira.sakaiproject.org/browse/SAK-32211

**Comment by adrianfish** [comment]
@fostersdesign Nice avatar :)

**Comment by fostersdesign** [comment]
So does this fix (for SAK-32223) remove the changer from the profile photo, so it only appears on the profile photo in the account menu?

**Comment by adrianfish** [comment]
@fostersdesign Yep, spot on. That was how NYU had it in the first place - I just ported it wrong :(

**Comment by adrianfish** [comment]
@fostersdesign Good to go? Pirate Golf?

**Comment by adrianfish** [comment]
@fostersdesign Can I merge it? You are now the reviewer, so you have to say.

**Comment by fostersdesign** [comment]
Sorry @adrianfish. I was out at lunch. I see you merged it. 

Your changes make sense. I'll take a look at the nightlies tomorrow morning when it updates to confirm the functionality, as my local instance isn't set up to use Profile at the moment.

**Comment by adrianfish** [comment]
@fostersdesign No worries. Lunch is important. Meatzza?

**Pull request merged**
