### PR TITLE
SAK-30136 refer to a 'Gradebook entry' consistently

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by steveswinsburg** [comment]
The gradebook actually calls them 'gradebook items'. Do you want to change these strings to match the gradebook?

**Comment by ottenhoff** [comment]
Thanks Steve. Yes, I should re-do this to be more consistent.

**Comment by ern** [comment]
Steve can you fix up the conflicts?

**Comment by ottenhoff** [comment]
modified per @steveswinsburg  and rebased per @ern

**Pull request merged**
