### PR TITLE
SAK-45648 - Unable to add tools in site info or when creating a site

### PR DESCRIPTION
**Pull request by jonespm**
Regression from a recent commit. Just changed this to return an empty HashMap rather that do another NPE check.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Or #9374

**Comment by jonespm** [comment]
Thanks @ottenhoff, I didn't see this other PR already created. This one follows the existing pattern here, though they both would solve the problem.

**Comment by bjones86** [comment]
I don't have strong feelings either way. Let's just pick one and merge it.

**Review by bjones86 — APPROVED** [review]

**Comment by ern** [comment]
Saw and merged Sam's PR before this one, so will close this one.

**Pull request closed without merging**
