### PR TITLE
SAK-32777 increased GradebookNG comment length to 4000 characters

### PR DESCRIPTION
**Pull request by ayersjr**

### CODE REVIEW

**Comment by bjones86** [comment]
This is slightly related to/competing with https://jira.sakaiproject.org/browse/SAK-33836 (#5216). I don't think we should merge this until decisions have been made on SAK-33836.

**Comment by jonespm** [comment]
This PR is also incomplete, since there's more places this is checked. I think both this and #5216 should be closed and we should put in a default of 20000, defined either as a constant value somewhere in this code or as a sakai property.

**Comment by bjones86** [comment]
I'm fine with that decision. I can write a CommentValidator while I'm at it, to coincide with my work on https://jira.sakaiproject.org/browse/SAK-33849 to provide as much up front validation as possible for the Import process.

**Comment by jonespm** [comment]
Cool! Sounds good to me! Would be nice to just have this one resolved. ;)

**Comment by bjones86** [comment]
Agreed! I'll comment on SAK-33836 with regards to the decision here, and I'll get another PR hopefully this week. Thanks, @jonespm!

**Pull request closed without merging**
