### PR TITLE
SAK-29670 The newtopic event is never triggered

### PR DESCRIPTION
**Pull request by annuelo**

### CODE REVIEW

**Comment by juanjmerono** [comment]
I guess this is becaus topic id is not null after saving it, so I'm wondering if this could be solved replacing this condition:
```
1226: if (topic.getId() == null) {
```
by this one:
```
1226: if (saveForum) {
```

**Comment by annuelo** [comment]
Yes, It could be solved changing the line you suggest. It would be another way to solve the problem.

**Comment by ottenhoff** [comment]
The @juanjmerono  suggestion makes sense to me

**Comment by annuelo** [comment]
Sorry! I made a mistake.
I've created the PR again, with the changes proposed by @juanjmerono. It's the PR #931 
Thank you

**Pull request closed without merging**
