### PR TITLE
SAK-31587 - Ensure simulated dialogs can be closed via the keyboard

### PR DESCRIPTION
**Pull request by jonespm**
I think this jescape is kind of a cool (although not maintained) library that could be useful including in the general portal. I just have it here included in chat though as I don't think we have many other "non-jquery" dialogs?

### CODE REVIEW

**Comment by ern** [comment]
I don't think this is hard in jQuery!
And having some little lib to just do escape seems distracting, meaning I would want to handle all key codes the same way. Managing every other key press one way and doing escape differently just seems like an anti-pattern (KISS).

var KEYCODE_ENTER = 13;
var KEYCODE_ESC = 27;

$(document).keyup(function(e) {
  if (e.keyCode == KEYCODE_ENTER) $('.save').click();
  if (e.keyCode == KEYCODE_ESC) $('.cancel').click();
});

**Comment by jonespm** [comment]
@ern Yeah but you don't want a global escape handler, you only want to handle escape when this dialog is up. I felt like that was pretty tricky to do, and I can imagine multiple dialogs being up at once needing escaped. If you want to implement it different go ahead and close this one.

**Comment by jonespm** [comment]
I didn't see any existing widget that seems like it would do what we want. It feels like it's going to have to be a custom extension on the dialog plugin as I described on here https://jira.sakaiproject.org/browse/SAK-32009 which is a lot of work beyond this.  This seems like the easiest short term fix for this to me.

**Comment by buckett** [comment]
Yeah, I think this is good to go.

**Pull request merged**
