### PR TITLE
SAK-45024 - Admin Workspace - User Membership Actions menu not keyboa…

### PR DESCRIPTION
**Pull request by mpellicer**
…rd accessible.

Better user experience, fewer clicks, less CSS, less jQuery and accessible.

### CODE REVIEW

**Review by ottenhoff — APPROVED** [review]

**Comment by bjones86** [comment]
Changing the brace style here was unnecessary in my opinion

**Comment by mpellicer** [comment]
> Changing the brace style here was unnecessary in my opinion

What do you mean with brace style @bjones86 ? You removing that accordion in favor of plain buttons or what?

**Comment by bjones86** [comment]
No, I'm referring to the changes in `usermembership.js`. This file used to be Allman style, but you've changed it K&R style.

Not really a big deal, but historically we've told people to abide by the code style already prevalent in the file in question.

**Comment by mpellicer** [comment]
Ahh ok that makes sense @bjones86, we're just trying to use namespaces to avoid global scripts, that's why I rewrote the JS. Also removing jQuery in favor of vanilla JS, I'm fine addressing any concern you have. Thanks for the review!

**Comment by bjones86** [comment]
No concerns, just thought I'd mention it.

**Pull request merged**
