### PR TITLE
SAK-31657 - Can only access 16 tools on a mobile phone

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by buckett** [comment]
This is better than before, but it still doesn't quiet work as I can't see the last row of tools in landscape (can't scroll down any further), the screenshots are of the same site (Statistics and Help missing).

It's a step in the right direction so maybe we should put this in and open another bug to access the last row of tools.

screen shot 2016-08-12 at 09 10 09
screen shot 2016-08-12 at 09 09 57

**Comment by jonespm** [comment]
Thanks @buckett it looks like having top: 6.3em; pushes that last row off the page permanently. I set the height to 95% and it gives access to that last row and the scroll bar works for me. Tested just in the browser but seems good.

**Comment by buckett** [comment]
Works across Chrome/Firefox/Safari with the only edge case being Safari emulating iPhone where you can't quite see the text (doesn't scroll any more). Again, it's good enough I think.

screen shot 2016-08-12 at 16 35 40

**Comment by jonespm** [comment]
Yeah, I'll just merge it for now, maybe someone can refine it later if desired.

**Pull request merged**
