### PR TITLE
SAK-31365 these quartz foreign keys are case sensitive

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by buckett** [comment]
Looking at our local instance of 10.x we don't have these indexes at all and looking in the upgrade scripts I can't see any reference to them getting created during any of the migrations.

I'm not saying this patch is wrong as the standard 10.x may have them from a newer quartz database setup code, but it looks like some institutions will be missing these as they were never added in an upgrade script.

**Comment by buckett** [comment]
My mistake MySQL Workbench isn't currently showing me any Foreign Keys for any of my tables. However falling back to SQL shows them, 
```
SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  REFERENCED_TABLE_SCHEMA = 'sakai'
  AND
  REFERENCED_TABLE_NAME = 'QRTZ_TRIGGERS';
```
however we look to have a mixed case trigger needing:

    ALTER TABLE QRTZ_TRIGGERS DROP FOREIGN KEY QRTZ_TRIGGERS_ibfk_1;

and don't have any FKs on the cron/blob/simple tables.

**Comment by buckett** [comment]
I don't know how but we have mixed case table names:

QRTZ_TRIGGERS_ibfk_1
QRTZ_BLOB_TRIGGERS_ibfk_1
QRTZ_SIMPLE_TRIGGERS_ibfk_1
QRTZ_CRON_TRIGGERS_ibfk_1

**Comment by steveswinsburg** [comment]
The indexes on these tables need a complete overhaul, there are 13 indexes on the `qrtz_triggers` table alone - each successive one just adds a new column to the set from the previous one. Whoever did this didn't understand how multi column indexes are actually used by the query optimiser. New SAK for this, WDYT?

**Comment by ern** [comment]
All of the quartz SQL came off their website
http://www.quartz-scheduler.org/documentation/quartz-2.2.x/migration-guide.html

I copied it verbatim though it appears to have changed!

**Comment by ern** [comment]
The index QRTZ_TRIGGERS_ibfk_1 should not exist anymore as this is deleted by the upgrade....

--
-- drop all foreign key constraints, so that we can define new ones
--
alter table qrtz_triggers drop foreign key qrtz_triggers_ibfk_1;
alter table qrtz_triggers drop key JOB_NAME;
alter table qrtz_blob_triggers drop foreign key qrtz_blob_triggers_ibfk_1;
alter table qrtz_blob_triggers drop key TRIGGER_NAME;
alter table qrtz_simple_triggers drop foreign key qrtz_simple_triggers_ibfk_1;
alter table qrtz_simple_triggers drop key TRIGGER_NAME;
alter table qrtz_cron_triggers drop foreign key qrtz_cron_triggers_ibfk_1;
alter table qrtz_cron_triggers drop key TRIGGER_NAME;

**Comment by ottenhoff** [comment]
This command will not delete "QRTZ_TRIGGERS_ibfk_1":

   alter table qrtz_triggers drop foreign key qrtz_triggers_ibfk_1;

**Comment by ern** [comment]
See #2868 for as an alternative to updating the foreign keys...

**Pull request closed without merging**
