### PR TITLE
SAK-29528 - Sitestats - Spelling error in Reports

### PR DESCRIPTION
**Pull request by mcarropellicer**
SAK-29528 Sitestats - Spelling error in Reports

### CODE REVIEW

**Comment by steveswinsburg** [comment]
I've reverted this. Both 'sucessfuly' and it's replacement in this PR 'sucessfully' are incorrect. The correct spelling is 'successfully'!

**Comment by steveswinsburg** [comment]
Push a new commit to this branch and we'll get it in ;)

**Comment by buckett** [comment]
@mcarropellicer I think it's in https://github.com/ox-it/wl-sitestats/commit/4806b0904cb6e8799ba3d96b528349a6cac8e03f

**Comment by mcarropellicer** [comment]
Yeah my mistake, btw i've created another pull request that was merged:

https://github.com/sakaiproject/sakai/pull/681

**Pull request merged**
