### PR TITLE
SAK-34102 Disabled update details button when editing user details

### PR DESCRIPTION
**Pull request by maramar7**

### CODE REVIEW

**Comment by maramar7** [comment]
I've tried to change the code to:

`#if ($service.allowUpdateUserName($user.Id) || !$user)
 				#if($user)
 					<input type="text" name="first-name" id="first-name" value="$validator.escapeHtml($user.FirstName)" onkeyup="active_doSave();"/>
				#else
					#if($valueFirstName) 
						<input type="text" name="first-name" id="first-name" value="$validator.escapeHtml($valueFirstName)" onkeyup="active_doSave();"/>
					#end
 				#end`

but that doesn't pass the Codacy/PR Quality Review, anybody knows how to fix it?

**Comment by bgarciaentornos** [comment]
The codacy review is not (for now) of mandatory compliance. It warns you of some practices to avoid and might provide with good code patterns if possible, but it's not stopping merges at this stage. Also I wouldn't change legacy vm code if it's not related to your PR.

**Comment by plukasew** [comment]
This change is not ideal. All it does is enable the submit button on every keystroke in the name and email fields, making the logic that controls the enabling of the submit button pointless.

What should have been done is to change the logic the disables the button on initial page load to be aware of the case where the password fields are not required.

**Comment by maramar7** [comment]
I've tried to use the "revert" button but it showed me this message: "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged."

What should I do to revert the PR?

**Comment by ottenhoff** [comment]
Okay here are steps I tested locally on the command-line. The sakaiproject/sakai Git project is my remote called "upstream". My own fork is called "origin"

git fetch upstream 
git checkout -b SAK-34102-revert upstream/master
git revert  8ae7605 
git push origin SAK-34102-revert

**Comment by maramar7** [comment]
I've already executed the commands that you indicate me and in the PR it continues to indicate merged, is this correct?

**Comment by ottenhoff** [comment]
Yes, this is correct. This PR will always be merged. The new branch can be used to create a new PR that will revert this commit.

**Pull request merged**
