### PR TITLE
SAK-41546 Update default url for RSS tool

### PR DESCRIPTION
**Pull request by bgarciaentornos**

### CODE REVIEW

**Comment by fostersdesign** [comment]
There are some default properties that should also be changed and potentially cleaned up with this change:

`# Attribute for news tool (static) for Sakai 10 and earlier
# DEFAULT: none (set this if you want it to work)
# wsetup.config.tool.attribute_sakai.news=channel-url

# Title for Default RSS Feed (10-)
# DEFAULT: Sakaiproject
# wsetup.config.tool.title_sakai.news=CNN Top Stories

# RSS feed to set for the default (10-)
# DEFAULT: https://www.sakaiproject.org/feed
# wsetup.config.tool.attribute.default_sakai.news=http://rss.cnn.com/rss/cnn_topstories.rss


# Attribute for news tool (static) for Sakai 11 and later
# DEFAULT: none (set this if you want it to work)
# wsetup.config.tool.attribute_sakai.simple.rss=javax.portlet-feed_url

# Title for Default RSS Feed (11+)
# DEFAULT: Sakaiproject
# wsetup.config.tool.title_sakai.simple.rss=CNN Top Stories 

# RSS feed to set for the default (11+)
# DEFAULT: https://www.sakaiproject.org/feed
# wsetup.config.tool.attribute.default_sakai.simple.rss=http://rss.cnn.com/rss/cnn_topstories.rss`

**Comment by adrianfish** [comment]
@fostersdesign Shawn, just to be clear, you want those props cleaning up just to not use sakaiproject in the text? So ...

# Title for Default RSS Feed (11+)
# DEFAULT: Sakai LMS
# wsetup.config.tool.title_sakai.simple.rss=CNN Top Stories 

# RSS feed to set for the default (11+)
# DEFAULT: https://www.sakailms.org/blog-feed.xml
# wsetup.config.tool.attribute.default_sakai.simple.rss=http://rss.cnn.com/rss/cnn_topstories.rss

??

If so, that default URL will also need setting in the tool itself, if not done already.

**Comment by fostersdesign** [comment]
Yes, that is correct, @adrianfish: since the default is changing in the submitted PR, the default.sakai.properties file should be updated too to reflect those changes:

```
# Title for Default RSS Feed (11+)
# DEFAULT: Sakai News
# wsetup.config.tool.title_sakai.simple.rss=Sakai News

# RSS feed to set for the default (11+)
# DEFAULT: https://www.sakailms.org/blog-feed.xml
# wsetup.config.tool.attribute.default_sakai.simple.rss=https://www.sakailms.org/blog-feed.xml
```

(I'm also suggesting removing the reference to the third-party CNN site.)

**Comment by adrianfish** [comment]
@bgarciaentornos Can you make the change along Shawn's suggestions? Makes sense to me. The props are all under:
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle

**Comment by bgarciaentornos** [comment]
Done, thanks for the tips!

**Pull request merged**
