### PR TITLE
SAK-30004 remove audiorecorder placeholder image creation

### PR DESCRIPTION
**Pull request by ktakacs**

### CODE REVIEW

**Comment by ktakacs** [comment]
https://jira.sakaiproject.org/browse/SAK-30004

**Comment by buckett** [comment]
There's lots of discussion in the Jira about this one and it doesn't seem clear this should go in.

**Comment by ern** [comment]
Kevin is in the ICLA list.

**Comment by jonespm** [comment]
Comments on the jira about closing this

**Comment by jonespm** [comment]
I'm re-opening this one. It seems like now is the better time for this to get in than it was 2 years ago.

**Comment by jonespm** [comment]
Actually because library moved there's too much to resolve, I'll just open a new PR.

**Pull request closed without merging**
