### PR TITLE
SAK-43194 - Stack trace when returning to PostEm landing page after adding item

### PR DESCRIPTION
**Pull request by jonespm**
Adding a property for auto reset to be able to be defined on the tool level.

This will cause these tools to reset when navigating back into them from another tool.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- portal/portal-util/util/src/java/org/sakaiproject/portal/util/ToolUtils.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5540785&bid=18164952)

**Comment by ern** [comment]
There is this init param to control whether a tool supports last view or not:
```
         <init-param>
            <param-name>default.last.view</param-name>
            <param-value>true</param-value>
        </init-param>

```
This seems to be the same concept.

**Comment by jonespm** [comment]
I didn't notice that `default.last.view` option for JSF tools.

It looks like a few tools do set that including Samigo. That would simplify this fix since this tool is JSF.

**Comment by jonespm** [comment]
So I tried the fix you suggested, setting the default.last.view to false.

It causes a worse regression.
- After clicking "Add" -> Choose a file -> Uploading a File and Continue
- The tool goes back to the main page. Previously it would go back to the add window
- Clicking Add again still has the feedback file selected but the title removed. If I put in a title and post it works.

It does fix the problem of keeping the tool reset but I don't know what's up with this new issue. This doesn't happen before or with this patch, only changing this setting. It *seems* like this setting is causing it to reset after the file upload.

**Comment by ern** [comment]
Closing this as the goal is to fix this in the tool.

**Pull request closed without merging**
