### PR TITLE
SAK-30267 Drag n Drop updates

### PR DESCRIPTION
**Pull request by ern**
- update dropzone from 3.8.4 to 4.2.0
- remove support for the older file upload method
- remove content.upload.dragndrop property as dragndrop is the standard
- add styling to dropzone
- add Availability control to the dnd uploads
- new property content.dnd.visibilty.hidden to control default in the ui

screen shot 2016-01-28 at 12 34 02 am

### CODE REVIEW

**Comment by buckett** [comment]
Could we switch to using the dropzone JAR from webjars.org?
```
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>dropzone</artifactId>
    <version>4.2.0</version>
</dependency>
```

**Comment by ern** [comment]
I totally agree be nice to be using webjars!

Created a new jira for that change see https://jira.sakaiproject.org/browse/SAK-30278

**Comment by ottenhoff** [comment]
+1 nice set of upgrades for sakai 11!

**Comment by danielmerino** [comment]
This change has broken D&D uploads in Dropbox tool due to new Availability radio button. A javascript error is thrown when a file is uploaded there, because radio button is not present (and neither is needed in Dropbox IMHO).

I have reported it in https://jira.sakaiproject.org/browse/SAK-30341

**Pull request merged**
