### PR TITLE
SAK-29665 add user id tracking to google universal analytics

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
@csev look good?

**Comment by steveswinsburg** [comment]
Does this need a warning to users that they are being tracked?

sent from my mobile device

**Comment by jonespm** [comment]
@steveswinsburg  I believe that just being tracked in general might be something that you'd need to put up a notice about as part of the EU cookie law (and other countries that might have that) done in #624 maybe just modify that? You could probably have a new feature to opt out of GA or userId tracking since it isn't critical to actually using Sakai. To actually have this, the administrator of the system has to enable it in the GA dashboard.

**Comment by steveswinsburg** [comment]
I am almost certain this will breach the Australian Privacy Principles in
terms of unnecessary collection of personal info. However if it's disabled
by default with big warnings when enabling then we are fine and it's up to
the installation to abide by them.

sent from my mobile device

**Comment by csev** [comment]
Looks good.  We could make a separate property for this (yes I know 20 lines of stuff for a 1 line change) - but that way each could be turned on/off separaterly to make various jurisdictions happy.

**Comment by jonespm** [comment]
I don't think there's any point for a property. An admin turning it on also has to explicitly enable it in GA (by default disabled) nothing happens by default without doing this, the user doesn't know either way if they're using this or not (if they know/care enough to even look for GA javascript). The only usefulness I can see would be as a user preference to avoid being tracked (though I think most people who really didn't want to would run a browser plugin) or as a notification as part of the cookie notification.

**Comment by ottenhoff** [comment]
I agree with Matt here. Google Analytics support is disabled by default. If your institution or jurisdiction has strict privacy rules, you should not sign up for a Google Analytics account and should not enable it in Sakai.

My intention is to commit this one-line change in the next 24 hours unless there is a compelling case how this change alters expectations of the existing use of GA.

**Pull request merged**
