### PR TITLE
SAK-47452 Print calculated questions

### PR DESCRIPTION
**Pull request by ropemar**
I've approached this from a new perspective. We now display random values in formulas and variables when printing an evaluation with calculated questions.

### CODE REVIEW

**Comment by ropemar** [comment]
@mpellicer you can take a look on this PR.

**Comment by mpellicer** [comment]
@ropemar Could you please upload a screenshot with the new document? Thanks!

**Comment by ropemar** [comment]
Yes, of course. I've updated the JIRA to show some photos (on screen and in PDF).

**Comment by jesusmmp** [comment]
Awesome! Let me test this no my local instance.

**Review by jesusmmp — APPROVED** [review]
Awesome work!
Tested on my local instance. It works like a charm.

**Review by mpellicer — APPROVED** [review]
Well done @ropemar !

**Pull request merged**
