### PR TITLE
SAK-49276 Lessons: Add dataDirectory field to lesson endpoint for RESOURCE_FOLDER type

### PR DESCRIPTION
**Pull request by stetsche**
Added missing dataDirectory field to response of lesson endpoint for the resource folder item type.

https://sakaiproject.atlassian.net/browse/SAK-49276

### CODE REVIEW

**Review by mpellicer — APPROVED** [review]
This makes sense to me. Do we need this in 22.x ?

**Comment by stetsche** [comment]
Yes, I think this should be merged back. I consider it a bug.

**Comment by mpellicer** [comment]
> Yes, I think this should be merged back. I consider it a bug.

Okay, set in the Jira the 22.x status.

**Comment by stetsche** [comment]
> Okay, set in the Jira the 22.x status.

Already done ;)

**Review by mpellicer — APPROVED** [review]
Well done Markus.

**Pull request merged**
