### PR TITLE
SAK-42730 Move grader to use sakai-group-picker

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-42730

### CODE REVIEW

**Comment by mpellicer** [comment]
Hi @adrianfish , I started replacing all the group selectors some years ago by this component:

http://davidstutz.de/bootstrap-multiselect/

Do you think it's a good idea to use this component and replace all the references with your webcomponent? It can be done in the future, after this feature.

Anyway, thanks for this contribution, is awesome and I'd love to use more webcomponents like this!

**Comment by mpellicer** [comment]
Example:

https://jira.sakaiproject.org/browse/SAK-40282

**Comment by adrianfish** [comment]
I think you'd probably want to implement another component for that, wrapping the bootstrap/jquery funciontality into a single tag. It's a lot richer than what I needed for the places I'll be using it. Or, we could make the behaviour switchable with an extra attribute and build the code into this component.

**Comment by mpellicer** [comment]
Looks good @adrianfish ! I'm going to start writing webcomponents too, in order to avoid code repetition :)

**Pull request merged**
