### PR TITLE
KNL-1284 Allow paths inside WEB-INF for tool registration

### PR DESCRIPTION
**Pull request by buckett**

### CODE REVIEW

**Comment by ern** [comment]
Why is not moving all of the webapps tools dir to inside WEB-INF not part of this PR?

**Comment by buckett** [comment]
I think it's worth supporting both as the default if we do that so that existing contrib tools don't have to change too much for the Sakai 11 upgrade.

**Comment by ern** [comment]
You should move tools in this repo to doing it the new way, and I agree that supporting the old way helps for contrib tools so should leave a comment and mark deprecated so they know to move away from that.

**Comment by buckett** [comment]
Ok, loads from both places now, moved across all the tools registration files in Sakai and added unit tests.

**Pull request merged**
