### PR TITLE
SAM-3133 - Extended time area, extra scrollbar present after adding e…

### PR DESCRIPTION
**Pull request by jonespm**
…xtended time

### CODE REVIEW

**Comment by ottenhoff** [comment]
extendedTimeHeading=Exceptions to Time Limit and Delivery Date: you must click the 'Add an Exception' button to add individual exception(s) before saving settings

**Comment by jonespm** [comment]
Yeah, I think that sounds good. The way the workflow works, it saves the last entry even if you don't click that button now (it didn't before) but it's better if you click after adding each entry and if you have more than one you have to click each.

**Comment by jonespm** [comment]
I mostly was interested in feedback around changing the padding for the accordion. If I didn't update this padding them the bootstrap offset (for a little indent) results in the browser having an overflow-x scrollbar in the content. (Since it goes slightly off the edge) 

Removing the padding, it looks fine but a little tight on the edges. I feel like having the offset is better than padding the edges of the accordion.

**Comment by ottenhoff** [comment]
I think possible to get of padding by using "clearfix" as class instead of "row"

**Comment by ottenhoff** [comment]
I will submit a new PR

**Pull request closed without merging**
