### PR TITLE
SAK-42172 - Add the validator to be called when deleting rows so that…

### PR DESCRIPTION
**Pull request by maurercw**
… any changes made to other rows will come along for the ride.  Otherwise, when the page re-renders, the date picker will initialize with the old value.

### CODE REVIEW

**Comment by ern** [comment]
Hi Chris I noticed there is only one line that actually changed and not the whole file! Let's keep one liners localized!

**Comment by maurercw** [comment]
Dang it!  Stupid IDE must have done that.  I'll get that cleaned up.

**Comment by maurercw** [comment]
Line endings are stupid!  I feel like I had this problem once before.

**Comment by maurercw** [comment]
#7209 replaces this PR.

**Pull request closed without merging**
