### PR TITLE
SAK-45282 Move to Karma and Jasmine for WC tests

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-45282

### CODE REVIEW

**Comment by adrianfish** [comment]
@fostersdesign @profmikegreene Take a look at this, see what you think.

**Comment by profmikegreene** [comment]
I think I like where this is headed. Won't build for me using our docker images because they don't have Chrome Headless in the image. I'll see if I can work up a quick fix for that.

**Comment by profmikegreene** [comment]
```
[INFO] --- frontend-maven-plugin:1.8.0:npm (npm test) @ webcomponents ---
[INFO] Running 'npm run test' in /source/sakai/webcomponents/tool/src/main/frontend
[INFO] 
[INFO] > webcomponents@1.0.0 test /source/sakai/webcomponents/tool/src/main/frontend
[INFO] > karma start
[INFO] 
[INFO] 01 04 2021 01:28:21.090:INFO [karma-server]: Karma v6.3.2 server started at http://localhost:9876/
[INFO] 01 04 2021 01:28:21.091:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
[INFO] 01 04 2021 01:28:21.097:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 01 04 2021 01:28:21.097:ERROR [launcher]: No binary for ChromeHeadless browser on your platform.
[INFO]   Please, set "CHROME_BIN" env variable.
[INFO] 
[INFO] 
[INFO] 
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! webcomponents@1.0.0 test: `karma start`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the webcomponents@1.0.0 test script.
```
For reference

**Review by ern — APPROVED** [review]
[INFO]   Sakai Maximise Button
[INFO]     ✓ Renders normal
[INFO] 02 04 2021 17:45:17.600:WARN [web-server]: 404: /webcomponents/assets/@fortawesome/fontawesome-free/sprites/solid.svg
[INFO]     ✓ Renders full screen
[INFO]
[INFO]   Sakai Rubric Grading
[INFO]     ✓ Adds Bearer to the token
[INFO]
[INFO]   Sakai i18n
[INFO]     loadProperties
[INFO]       ✓ Expects to work with portal.locale set
[INFO]       ✓ Expects properties to not be in sessionStorage if caching is off
[INFO]       ✓ Expects properties to be in sessionStorage after the call
[INFO]       ✓ Expects to work with an explicit lang
[INFO]
[INFO] Chrome Headless 89.0.4389.114 (Mac OS 11.2.3): Executed 7 of 7 SUCCESS (0.074 secs / 0.035 secs)
[INFO] TOTAL: 7 SUCCESS

**Pull request merged**
