### PR TITLE
SAK-29705. Add 4 new ck editor buttons

### PR DESCRIPTION
**Pull request by mcarropellicer**
Add media to CK Editor. YouTube, Vimeo, Creative commons images and
Twitter

### CODE REVIEW

**Comment by ern** [comment]
Added to ckextraplugins +1

**Comment by jonespm** [comment]
Did you test this with https? I'd remember wanting to add this but from what I remember by default it breaks on a secure site when embedding most of the links (because of the browser restrictions) I think this was actually fixed in OAE and was going to use their version instead, and actually have either modified our local copies or used their version. I don't know if this was ever fixed in the upstream plugin or not.

https://github.com/oaeproject/3akai-ux/pull/3011

**Comment by mcarropellicer** [comment]
TBH i did not tested this on https :(

AFAIK, in a https environment, secure links will render correctly and not secure links not, due to mixed content.

Maybe this? https://github.com/w8tcha/CKEditor-oEmbed-Plugin/issues/56

**Comment by jonespm** [comment]
I think all that PR you mentioned fixes is being able to load the jquery library (which this depends on if not available) correctly via http or https. The one I mentioned actually fixes up the links if they're pasted in as http instead of https. I think the big sites (youtube, etc) are defaulting to https links nowadays but it would break others that aren't if it doesn't change the urls. I believe it's just the js library which was used for detection, I'm not sure if the one on this PR is the most up-to-date (the one that's updated and includes the OAE patch is here https://github.com/nfl/jquery-oembed-all)

**Comment by jonespm** [comment]
Also, it looks like as of last week there's an "official" CKEditor embed plugin. The notice on the github repo for this plugin is that it will no longer be developed. Maybe we need to use that one?
 
http://ckeditor.com/addon/embed

**Comment by jonespm** [comment]
The downside of the official embed is that it relies on https://iframely.com/ which doesn't work under ssl in the free version. We'd either have to host a copy (it's open source) or pay them to host it and distribute the api key.

I remembered with the old oEmbed plugin that uses longurl.org which had similar problems, it might go down or be unavailable and then you'd have to host your own copy of it. I'm not sure what to do about that in this case. Maybe include one or the other but not sure about enabling it by default.

**Comment by mcarropellicer** [comment]
@jonespm 

The one of this PR is the latest version (1.17) of the plugin page: 

http://ckeditor.com/addon/oembed

I've updated the library to the reference you mentioned, also i've tested the plugin with HTTPS and doesn't work, the console says will not load mixed content :-1:

**Comment by mcarropellicer** [comment]
I've tested with the original library of the Plugin and works OK with HTTPS, you can test this branch but i think it's ready to be merged :+1:

**Comment by jonespm** [comment]
Yeah, I don't know what to do with this. I really don't want to commit a plugin that the author has acknowledged is no longer supported or recommended to use that would be up to us to update.

"This plugin is no longer developed, please migrate to the official CKEditor Embed Plugin - http://ckeditor.com/addon/embed"" - https://github.com/w8tcha/CKEditor-oEmbed-Plugin/blob/master/README.md

But I also don't want to commit the recommended plugin (http://ckeditor.com/addon/embed) that won't work with https unless we either setup our own server to run an instance of it or require people using it to pay for iframely.

**Comment by ern** [comment]
Lets add this to the weekly Core Team discussion.

**Comment by mcarropellicer** [comment]
Any news on this?

**Comment by buckett** [comment]
There is a copy of the JS version of the jQuery oembed plugin in lessons.

**Pull request closed without merging**
