### PR TITLE
SAK-39927 - Support for older version sitestats properties

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
I'm putting WIP on this because I think I'm going to add a log message if the old properties are use that they are deprecated. I'd like a way to do this in the kernel, but no good way yet.

**Comment by ern** [comment]
My feeling is that the original property sitestats.db which controls this feature hasn't changed which is all that matters here.

**Comment by jonespm** [comment]
I partially agree. However the old configuration used 4 other required properties that did change.

driverClassName@org.sakaiproject.sitestats.externalDbDataSource |  
url@org.sakaiproject.sitestats.externalDbDataSource
username@org.sakaiproject.sitestats.externalDbDataSource
password@org.sakaiproject.sitestats.externalDbDataSource

And the value of sitestats.externalDb.auto.ddl was previously true/false and that also changed to be in line with hibernate. So this just updates this to work with what was there.

https://confluence.sakaiproject.org/display/STAT/Configuration+Options#ConfigurationOptions-2.5.Externaldatabaseconfigurationoptions

**Comment by ern** [comment]
+1 for adding the default properties

**Pull request merged**
