### PR TITLE
SAM-1263 imageMap question type

### PR DESCRIPTION
**Pull request by gillmanjc**
Hi Steve
I have applied all the changes in the patch attachment in SAM-1263 and pushed to this branch. 
I manually added the sql insert from the patch but when I test locally I don't see any ImageMap question type when creating an new Assesment. Any suggestions?

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Hi Jaco,
Have a look through this page and see if everything has been implemented:
https://confluence.sakaiproject.org/display/SAM/How+to+add+a+new+question+type

**Comment by gillmanjc** [comment]
Hi Steve
I have just again double checked all the files changes in the patch and compared that to the changes mentioned in the Confluence document link that you send. I still do have this new question type in the dropdown. Will debug and dig a little deeper.

**Comment by steveswinsburg** [comment]
Hi Jaco, have you managed to get the new question type going?

**Comment by jonespm** [comment]
We have this running fine on all versions from 2.8 to 10. The reason it was never merged into trunk is really because of the lack of QTI support. It looks like there's nothing changed in this patch with regard to that. It probably would need some updates for the JSF 1.2, so if you're not seeing anything my guess would be that would be why. I haven't tested it in trunk yet.

**Comment by steveswinsburg** [comment]
OK yeah that sounds about right. Can you upgrade the version of JSF and see if it works? You may need to check with the other tools that have been upgraded to see if anything else needs to change apart from the dependency version.

**Comment by gillmanjc** [comment]
Hi Steve, Matthew

After further investigation it seems like the JSF version is fine. I searched for JSF upgrade related mails, etc and found relevant info in the mailing list, and online. Here is a list of some those changes needed:

1) replacing the 'sakai:tool_bar_item'  with <h:commandLink .. /> or <h:commandButton ../> Tags if any.
2) at the commandButton/link  Tag, the  Action='' empty value is not allowed for 1.2 version
3) The  valueChangeListener  should not assign/return an empty value with ''.
4) The returning-Action method value should not be with an empty value (especially with JSF 2.0) (normally, if return a value with ‘’, it means staying at the same page)
5) no escape attribute for <h:outputLabel> Tag
5) modify the web.xml head with version="2.5”

https://jira.sakaiproject.org/browse/SAM-2374
https://jira.sakaiproject.org/browse/SAM-2399

From my understanding JSF is upgraded in trunk so I just looked at patch file of SAM-163 and tried to see if the above mentioned changes are to be made on the patch changes. I could not find any.

I have made a minor change to get the property value "showImageMapQuestion" like the other question types does so I now have the Q type "Hot Spot" in the drop down. Upon selecting an image and then clicking Upload, the image appears in the background with some other alignment display issues. (see image below)

First thing that comes to mind... how will the changes required for Morpheus affect this patch? Should those changes be included as part of this change?

hotspot

**Comment by steveswinsburg** [comment]
Ok awesome that you have this working. Looks like we need some Morpheus mods, but if the feature is working then lets get that in and we can resolve the styling issues afterwards.

**Comment by steveswinsburg** [comment]
Hi Jaco, if you could resolve conflicts on this branch that would be great. I'll then pull it down and test. The morpheus issues can be addressed afterwards and I can liaise with people to sort it out.

**Comment by steveswinsburg** [comment]
Hi Jaco, Conflicts on this branch (maybe a previous merge). 
Could you resolve and we can get this in? Cheers.

**Comment by ern** [comment]
Jaco you've merged commits instead of doing a rebase your going to have to reset this branch.

1st remove the merged commits until you get back to your commit being HEAD on this branch with
git log 
git reset --hard HEAD^

repeat the above until git log shows your commit as the first one.

git rebase master

should be good to go after that, also i would look at squashing as commits with a message like "no message" should be removed.

**Comment by steveswinsburg** [comment]
New question type appeared ok. However when uploading an image it displays it full size in the background. Have you any thoughts about how this is going to work? What if the image is enormous?

Selecting one of the zones and drawing the box, I can't see how its setting the coordinates. It looks like it's doing something but when I click to save it displays an error: `You must set all image zones`.

When drawing the box it also highlights the text from the question setup.

**Comment by steveswinsburg** [comment]
This is now being tracked in #1156.

**Pull request closed without merging**
