### PR TITLE
SAK-32715 - Configure permissions to be hidden from user's view so on…

### PR DESCRIPTION
**Pull request by danielmerino**
…ly admins can enable or disable them.

### CODE REVIEW

**Comment by jonespm** [comment]
This seems like a reasonable idea. It seems like other tools may want to take advantage of this and don't know if this implementation is the best but maybe this is fine "for now". 

Like you'd want to disable this in the regular authz helper and have any possible permisison in here. I think there could also be confusion if it just hides the checkbox, it seems like it'd make more sense to have it disabled in the UI. And you'd also probably need to disable it on the backend too, but I don't know how likely people would be doing this.

**Comment by ern** [comment]
Be good to understand if this differs from the authz helper as adding properties to control viewing permissions would be something new/different than how other tools handle this. Keeping things consistent with how this is done on other tools should be considered.

**Comment by danielmerino** [comment]
@jonespm , I hide the permission because is the same action done in SAK-31350 with the permission to show visits. Setting the permission to false in sakai.properties hides the "Show visits" permission in the tab, it doesn't disable it. I'm not sure if it's better to hide or just to disable the permissions, I think that it is a good question for Teaching and Learning group. Anyway, it could be easily changed in the future.

@ern , the tools I have checked don't handle this in any case. The permissions are fully mapped from authz roles in several tools (Resources, Assignments, Announcements, Calendar, Messages...) and are not shown at all in others (Lessons, Tests & Quizzes, Syllabus). But this is a special case because the permission to view official photos or emails allows to the users to do something that exceeds the site's scope.

I think that some mechanism to limit the permissions that users can change in a tool is a good addition that could be useful in some use cases. I know of colleges that completely disable the permissions for users because they don't like some of them. A list of non-desired permissions in sakai.properties seems to me a simple way to give greater flexibility in tools for admins.

**Comment by jonespm** [comment]
This is a good idea but closing this PR because core team believes roster2 should use the standard authz widget and this feature should be implemented there for all permissions.

**Pull request closed without merging**
