### PR TITLE
KNL-1506 Add Hibernate 4 JMX support

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by ern** [comment]
The only way I could do this was using spring EL as there are no concrete classes to use.

**Comment by buckett** [comment]
I don't follow, why do you need a concrete class?

**Comment by ern** [comment]
So we can do it using Spring EL or with a bean declaration like:
```
 	<bean id="org.sakaiproject.springframework.orm.hibernate.GlobalSessionFactory.statistics"
		  factory-bean="org.sakaiproject.springframework.orm.hibernate.GlobalSessionFactory"
		  factory-method="getStatistics"/>

	<bean id="org.sakaiproject.springframework.orm.hibernate.jmxExporter" class="org.springframework.jmx.export.MBeanExporter">
		<property name="beans">
			<map>
				<entry key="Hibernate:type=statistics" value-ref="org.sakaiproject.springframework.orm.hibernate.GlobalSessionFactory.statistics"/>
			</map>
		</property>
	</bean>
```

**Comment by ern** [comment]
OK opting for the XML approach!

**Pull request merged**
