### PR TITLE
SAM-2589 Wrong check marks in "Question Scores" for calculated questions

### PR DESCRIPTION
**Pull request by joserabal**

### CODE REVIEW

**Comment by joserabal** [comment]
I've discovered a possible bug in this patch. Changing status to "In progress"...

**Comment by ern** [comment]
There is an issue with this PR can you remove the commit that is not related.

**Comment by ncaidin** [comment]
ICLA is on file. removed cla? label.

**Comment by joserabal** [comment]
Hi,

The commit that is not related has been removed.

Thanks!

**Pull request merged**
