### PR TITLE
SAK-30322: Bug fixes and tidyings up of SAK-29974

### PR DESCRIPTION
**Pull request by nicholaswilson100**
There are different things in this request, all to do with bug fixes or small additions I should have put in the SAK-29974 Nested Citations request:

1.   Adding an 'Export' button next to the 'Import' button on the Citations screen - which exports all the citations on the page to a RIS file.
2.   For every each citation, adding a 'export' link (next to the 'remove' link) which exports just that citation to a RIS file.
3.   Fix for a bug where if you try to copy a nested reading list (either click 'Duplicate' or 'Copy' in the 'Actions' dropdown), it does not copy the nested structure, just the citations.
4.   Fix for a bug where if the title of a section is left blank, it shows 'null' as the text for the student view.           
5.   Adding some unit tests for the logic that controls what kinds of sections and citations you are allowed to add to what. 
6.   Adding 'Print' and 'Export' links and Last Updated Date to the top right of a reading list (student view)

### CODE REVIEW

**Comment by steveswinsburg** [comment]
@ncaidin is there a CLA?

**Comment by ncaidin** [comment]
Funny, I thought he did but I don't see one.

@nicholaswilson100 
info on licensing here:
https://www.apereo.org/licensing

Here is the specific form 
https://www.apereo.org/sites/default/files/Licensing%20Agreements/apereo-icla.pdf

send to licensing@apereo.org 

Thanks

**Comment by nicholaswilson100** [comment]
Thanks Neal and Steve.  Yes funny, I thought Adam had put something in front of me at some point that I had signed but I can't fully remember.  

I've just sent off an email with the CLA.

**Comment by ncaidin** [comment]
CLA received on and on file. Thanks @nicholaswilson100  !

**Pull request merged**
