### PR TITLE
SAK-28978 avoid 404 on login in Firefox because of issues when escaping ...

### PR DESCRIPTION
**Pull request by ottenhoff**
...the tilde in the

My Workspace site id and the inlining code

### CODE REVIEW

**Comment by ottenhoff** [comment]
This needs review... Is there ever a case where we would need to escape the tool id? Am I fixing this in the correct place?

**Comment by csev** [comment]
Well that seems to fix it in on FireFox and does not break it on Chrome and Profille seems to be working as well both places..  I am happy to merge this.  But I am left wondering why this fixes it.  I can see no evidence that dashboard uses org.sakaiproject.portal.util.ToolUtils.

**Comment by ottenhoff** [comment]
Correct, I don't think this is Dashboard related. I think this is SiteHandler.java around line 360.  If we are inlining, then ToolUtils.getPageUrl and do a res.sendRedirect(pagerefUrl)

My guess is Chrome is being nice and un-escaping for us to avoid the bug.

**Comment by steveswinsburg** [comment]
I say we get this in and test it out. I get this error constantly, I will soon tell you if it goes away ;)

**Comment by csev** [comment]
It is in.  I will pull this into my copy and then continue my line of inquiry.

**Comment by clhedrick** [comment]
Yes, this seems to do it. I guess it's preferable to PR 303, though they're both voodoo.

**Comment by clhedrick** [comment]
As to whether we might even need to escape it, it's unlikely to happen in practice. However in some old versions of Sakai you can set the site ID. You can still do it as administrator. That could require it to be escaped. I was more specific, allowing leading ~ unescaped only. But if there's a problem in the dashboard/wicket/sakai interface, most likely it's not unescaping somewhere. So if dashboard is ever in a site that needs to be escaped, the actual bug would have to be fixed.

**Comment by clhedrick** [comment]
I spent a fair amount of time trying to find the real problem. I found that Wicket is calling getRequestURI, and that replacing %7E with ~ there fixed it. So someone seems to be taking the request URI and not unescaping it. But it's unclear to me where that would be. I don't see why wicket would care what the siteId is. I instrumented site service,get Site, and didn't find it ever being called with a site ID starting in %7E. At that point I gave up trying to figure out what's going on, but it seems likely that somewhere there needs to be an unescape.

**Comment by clhedrick** [comment]
answering csev: it's not that dashboard uses ToolUtils. It's that this fix causes the URL in the left margin to be written with ~ rather than %7E. That works around the wicket / dashboard problem, whatever it is.

**Comment by clhedrick** [comment]
Just looked at the wicket 1.4.x source. It does things like get pathInfo from requestURI with a substring. But requestURI is not decided, and pathinfo is. This problem occurs several places in the code. I'm not up for fixing the innards of Wicket, I don't think. I looked at the next version of Wicket. The code has been rewritten. It's not obvious that the same confusion exists there.

**Pull request merged**
