### PR TITLE
SAK-30952 Show instructions for the hidden sites preference

### PR DESCRIPTION
**Pull request by marktriggs**
Introduces a new `hidden_instructions` I18N key that will need
localization.

### CODE REVIEW

**Comment by SedueRey** [comment]
:+1:

**Comment by juanjmerono** [comment]
After merging #2342 now you have a conflict in this one, please solve it.

**Comment by marktriggs** [comment]
Just fixed, thanks :)

**Comment by juanjmerono** [comment]
Cool !! Thanks !!

**Pull request merged**
