### PR TITLE
SAK-33561 Support for filter custom properties.

### PR DESCRIPTION
**Pull request by buckett**
This allows local deployments to customise the LTI substitution
properties that are used for custom property subsitution.

### CODE REVIEW

**Comment by buckett** [comment]
Not yet tested, but I was thinking about something like this @csev

**Comment by buckett** [comment]
`org.tsugi.lti2.LTI2Servlet#doLaunch` and `org.sakaiproject.basiclti.util.SakaiBLTIUtil#postReregisterHTML` also call `org.tsugi.lti2.LTI2Util#substituteCustom`

**Comment by csev** [comment]
This looks great.  The cut point is correct.  I approve this.   Would it be a good idea to provide a sample filter provider?

**Comment by buckett** [comment]
Added sample filter that is added automatically in demo mode.

**Pull request merged**
