### PR TITLE
SAM-2970 Refactor Extended Time

### PR DESCRIPTION
**Pull request by master-bob**
Front end is working. Jquery date selector only for new items.

When saving the extended time entries, all new entries are compared to what is in the database by ID. If there are no matches than (that is an old entry is not present in the new ones), than that entry is removed. (see [saveExtendedTimeEntriesHelper](https://github.com/sakaiproject/sakai/pull/3458/files#diff-1e372d0d706dd629e9783492a0f663a4R98) within ExtendedTimeFacade.java).

ExtendedTimeDeliveryService (used to be ExtendedTimeService) is used as a medium for the delivery aspect of the assessments. This has been modified to use the new ExtendedTime entries. This should reduce the testing load necessary.

Entries are validating when an assessment is published / all ready published exam is saved. Entries are copied from an assessment to a published assessment within the [PublishAssessmentListener](https://github.com/sakaiproject/sakai/pull/3458/files#diff-5d75f70eab0574689487026b998c83beR212) using the [copyEntriesToPub](https://github.com/sakaiproject/sakai/pull/3458/files#diff-1e372d0d706dd629e9783492a0f663a4R62) method within ExtendedTimeFacade.

Minor testing done. Some clean up done in modified files. Some copyrights updated. Time zone testing needs to be done.

### CODE REVIEW

**Comment by master-bob** [comment]
I will need to re-do a portion of this commit so that the history in ExtendedTimeService.java (which was modified and renamed to ExtendedTimeDeliveryService) is not lost.

**Comment by jonespm** [comment]
I think it's fine if that history is "lost". It stlil will be in the repository in prior tags of 11 and older revisions and relatively easy to find if it was ever necessary on github. Was there anything else left to this other than the auto submit? I'd say commit so people can start trying this out it and I can add in that part next week.

I'm seeing some bugs right now with the UI that I could just file as jiras.

1) The formatting (headers) appears misaligned in the UI if there's no users added 
image

As soon as I add a user exception though it seems okay
image

2) There also seems to be a confusing error when selecting User AND Group it says
"User OR group must be set for extended time entry, with user" but I have both user and group filled in, not the OR. I feel like the UI should block out the group select box when the user is entered and vice versa so you don't run into this error.

So I can open up some new jiras and I'd have time to work on anything you don't after this is committed but it looks like it's a pretty good base.

3) When creating the initial exception it seemed like I could leave the dates blank and just fill in a time. However when editing it would either fill in a default time or return an NPE stack trace
```
caused by: java.lang.NullPointerException
    at org.sakaiproject.tool.assessment.ui.bean.author.AssessmentSettingsBean.saveEditedExtendedTime(AssessmentSettingsBean.java:1776)
```

4) I'm not seeing the extended time get "copied" to the published assessment to the table, it looks like it just switches over. It seems like the extended time entries should remain on both the published and unpublished assessment if you're going to be using the same table for both.

**Comment by jonespm** [comment]
Really though if you can resolve the conflicts here I still think this is good enough to commit and I can also work to fix any of these these bugs that are remaining against this. This is a feature I'd really like to have in for 11.3. Thanks for the work on this.

**Comment by master-bob** [comment]
I just rebased this on master, fixed the conflicts, and did a force push.

2) On the settings page, no other element has validation within the UI. Thus it is possible to have the Due date occur prior to the available date. This, and other errors, are all caught when the assessment is attempted to be published. I thought about putting in validation with the UI, but as no other element has that, I opted to stay in line with the rest of the validation (i.e. only when publishing).

3) I can see how that may occur.

4) I'm not sure why that is occurring. Nonetheless, we need to have separate entries for published and unpublished assessments. Separate extended time entries are necessary as it would not make sense for modifications of an entry in a published assessment to change an entry in an unpublished assessment; just like all the other settings.

I am of the firm opinion that having duplicate tables for published and unpublished assessments is a big design flaw within Samigo. In an effort to make Samigo better, I opted to use one table for all extended time entries. This will reduce the workload in the future if Samigo is ever refactored.

**Comment by jonespm** [comment]
2) Yeah I guess that makes sense, I guess it's a *nice to have* feature here and probably some other places on this page. Maybe just a label that says "Please select only one user OR group" right there on the page so save some errors going back.

3) We can file this as a new issue after this one is saved

4) I completely agree with you about the database design and I'm willing to give it a go with this single table. I just think that it's a bug if it removes it from the unpublished when it publishes it. This is what I was seeing occurring when I was testing. So when I set up all my dates, published, the unpublished would lose these exceptions. Perhaps another bug.

In any case, I feel like this can be merged and we can resolve these after.

**Comment by jonespm** [comment]
I'm going to click the merge on this tomorrow morning if there's no objections or nobody does it before me.

**Comment by jonespm** [comment]
Okay, I merged this and created a number of subtasks as part of https://jira.sakaiproject.org/browse/SAM-2970 and just assigned to me. Re-assign if you work on anything and I'm sure QA will be looking at it next week.

I don't know how much time I'll have left this week but I'll have time next week. Thanks a lot of the work on @master-bob

**Pull request merged**
