### PR TITLE
SAK-29117 use the same course grade calculations when viewing one student

### PR DESCRIPTION
**Pull request by ottenhoff**
When viewing an individual student's course grade, different calculations were being done in the getStudentCourseGradeRecord method than were being done in the All Grades page that uses getPointsEarnedCourseGradeRecords. So this commit removes getStudentCourseGradeRecord because it is incorrect and stays consistent for the individual student display by calling the same method getPointsEarnedCourseGradeRecords.

I'm also removing several very old methods that are performing calculations. I'm removing directly instead of deprecating because I find all of this old code incredibly dangerous. We need to minimize the number of places that are performing grade calculations. We need to focus on maintaining only a few methods and the proliferation of various methods is the cause of some of these nasty errors like SAK-29117.

### CODE REVIEW

**Comment by ottenhoff** [comment]
@steveswinsburg I'm hoping this has zero effect on your efforts... But please let me know if it does trample on separate work you are doing.

**Comment by steveswinsburg** [comment]
No impact on the gradebook enhancement, 100% agree with removing the cruft. Nice work here.

**Comment by steveswinsburg** [comment]
I'll give this another day or so for comments, is that ok, then I'm all good to merge this.

**Comment by ottenhoff** [comment]
I just did a search of GB2 and didn't see any of these edu-services methods used.

I will leave this open until Friday for more comments....

**Pull request merged**
