### PR TITLE
SAK-23666 Add OAuth module to Sakai

### PR DESCRIPTION
**Pull request by steveswinsburg**
This PR adds the OAuth module to Sakai, as well as the hooks to EntityBroker for it to work. It is turned OFF by default though the tools are added to the Admin Workspace and My Workspace templates via the SQL upgrade.

### CODE REVIEW

**Comment by buckett** [comment]
Would you be ok making Colin Hebert the author as he wrote most of this originally and deserves credit for it.

**Comment by steveswinsburg** [comment]
Sure, I did a fair bit of tweaking to get it into shape but I can let those ones go. Not sure how to change the author though.

**Comment by ottenhoff** [comment]
Ideally this would be a couple of commits.  One with the git author set to Colin and then one with the git author set to Steve.

You can modify the latest commit with:

git commit --amend --author="Author Name <email@address.com>"

I believe you will need to rebase to modify older commits.

**Comment by steveswinsburg** [comment]
Ok I have amended the last commit to Colin as a gesture of thanks for this work on this.

**Comment by ottenhoff** [comment]
@buckett does this look okay to merge into master?

**Comment by buckett** [comment]
The Jiras for this are:
https://jira.sakaiproject.org/browse/SAK-23666 
https://jira.sakaiproject.org/browse/SAK-20838
https://jira.sakaiproject.org/browse/SAK-22278

**Comment by buckett** [comment]
The commits should have a Jira prefix and it would be good to also deploy the filter on /access so that you can request uploaded content easily.

But on a checkout of trunk this pull request builds fine and accesses with oacurl work a treat for /direct/user/current.json.

Thanks.

**Comment by buckett** [comment]
Ah, didn't spot that you've put all your SAKs in the main part of the commit, rather than the header.

**Comment by buckett** [comment]
If you wanted to re-write the git commits you can do:
```
git rebase -i HEAD^^^^
```
then change the word pick to reword on the first 4 lines and exit the editor. You'll then get the option to update the commit message for each of the commits. But be careful as rebases can be dangerous.

**Pull request closed without merging**
