### PR TITLE
SAM-2515: Samigo autosave doesn't work (inlining related)

### PR DESCRIPTION
**Pull request by ramonchu2k**

### CODE REVIEW

**Comment by jonespm** [comment]
This seems to duplicate the code in the body onload in 115. Is that not working and not needed or something else wrong with this? I don't think broken code should be left in there.

**Comment by ramonchu2k** [comment]
You're right, I forgot to remove the onload code. Indeed, all the onload code is unreachable due to the morpheus inline changes so I moved it to the bottom of the file.

**Comment by jonespm** [comment]
Thanks, well in some delivery context it might have been reachable. Like for instance you can take an assessment via a URL or you can add a link to it in CKEditor and I believe that opens the delivery in it's own window. So I'd just want to make sure having two initialization won't cause a problem. Having it once outside of the body makes sense though. Did you test other delivery context, like from Lessons or from the URL link?

**Comment by ramonchu2k** [comment]
I've tested the other delivery contexts (Lessons and URL link) and the autosave was disabled for "takeAssessmentViaUrl" cases so I've enabled it. 
Thanks for your check.

**Pull request merged**
