### PR TITLE
SAK-26142 Include ability to add syllabus content (and not just a syllab...

### PR DESCRIPTION
**Pull request by teetoppz28**
...us title) to Add syllabus item workflow

### CODE REVIEW

**Comment by baholladay** [comment]
This is cool! I tested locally and it works great. Code looks good too. You should remove the "edititem" class from the div however: ...<div class='editItem bodyInput'...

**Comment by baholladay** [comment]
Also, about 50% of that patch is just format/style changes. They changes are for the better and easier to read, just made the patch harder to follow

**Comment by baholladay** [comment]
Crap, guess I should have waited for the minor css adjustment I requested before merging the pull request. Create another pull request and put in that change.

**Comment by teetoppz28** [comment]
Removed the unneeded class name and merged.

**Comment by buckett** [comment]
If you put small indentation tidy ups in a different commit it makes it much easier to separate them from the actual code changes.

**Pull request merged**
