### PR TITLE
SAK-40004 - Javax.mail

### PR DESCRIPTION
**Pull request by deinok**
Upgrade javax.mail to 1.6.1

### CODE REVIEW

**Comment by ern** [comment]
Have you tested sending mail after these lib updates?

**Comment by deinok** [comment]
Yes, I run some manual tests and also mvn test.
Have you found some bug?

**Comment by deinok** [comment]
@ern Can we just make a Squash & Merge?
I try to make the PRs relatively atomic

**Comment by ern** [comment]
@deinok We don't need a bunch of PR's for the same concept or goal . Typically you only need one PR per JIRA issue. The PR should represent and achieve the goal of the JIRA issue, creating a bunch of JIRA issues or a bunch of PR's related to the same goal just is a lot of extra work.

You can logically create individual commits representing the different pieces of the work on the PR, keep in mind the commits should be well formed logically.

**Comment by ern** [comment]
Just waiting for you to combine these...

**Comment by deinok** [comment]
ref https://github.com/deinok/sakai/pull/2

**Pull request closed without merging**
