### PR TITLE
SAK-29252 - Remove portal chat backward compatibility with neoportal

### PR DESCRIPTION
**Pull request by sinmsinm**
Removed from portal chat exclusive code for neoportal. Now all reference are just for Morpheus

### CODE REVIEW

**Comment by csev** [comment]
Do you know whay this won't merge cleanly?

**Comment by sinmsinm** [comment]
It seems that travis failed from previous PR and it is preventing merging. I don't see anything disruptive in my commit. Just changing some js lines.

**Comment by sinmsinm** [comment]
@csev Now that travis build is fine, automatic merge is possible. I closed & reopened this PR to force travis build once I saw that the project was building was fine again.

**Comment by steveswinsburg** [comment]
LGTM

**Pull request merged**
