### PR TITLE
SAK-46301 Search: include content in indexing ops

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-46301

### CODE REVIEW

**Comment by axxter99** [comment]
@adrianfish cheers!

**Comment by adrianfish** [comment]
@axxter99 No problem! You were right about those bananas all along.

**Review by ern — APPROVED** [review]

**Review by ern — CHANGES_REQUESTED** [review]
This looks like it would always add content during the initial addition of the item to the index vs letting the queue process it.

**Comment by adrianfish** [comment]
@ern I've updated this now. The issue was with the various es queries used in the post processing phase

**Comment by ern** [comment]
See #10242 which solves this issue

**Pull request closed without merging**
