### PR TITLE
LSNBLDR-600; need conversoin for oracle, lesson_builder_groups

### PR DESCRIPTION
**Pull request by clhedrick**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Should these also be added to the conversion scripts in reference/docs/conversion?

**Comment by clhedrick** [comment]
yes. actually I think there are other things not in the script as well. Please look at

lessonbuilder/components/src/ddl/oracle/simplepage.for-11.sql

for the full list.


I haven't put this fix into 11 yet because no one has confirmed that it works. Can we find an Oracle site to do so?


________________________________

**Comment by clhedrick** [comment]
I've just confirmed that the commands seem to work in my copy of Oracle, though I'm not set up to do a real QA. I'm going to merge this into 11.

**Comment by sinmsinm** [comment]
Yes, I think we must add also in the reference conversion scripts.

**Pull request merged**
