### PR TITLE
SAK-32513 roster2 Sakai 11.x update from master

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by master-bob** [comment]
What's the difference between this & #4354 ?

**Comment by adrianfish** [comment]
None, other than I had to fix a conflict with the latest 11.x. I issued the old PR and then couldn't find it. I assumed I'd either imagined issuing it, or that it had been closed :(

**Comment by ern** [comment]
Yeah before doing something like this lets at least try the normal process?

**Comment by ottenhoff** [comment]
@adrianfish how many JIRAs are included here? Can we do this the traditional way via JIRA?

**Comment by adrianfish** [comment]
@ottenhoff When you say the trad JIRA way, you mean JIRA ticket by ticket? I thought we'd discussed bring the whole codebase across from master?

**Comment by ottenhoff** [comment]
Merging everything from master into the maintenance branch is usually a last resort when the normal process doesn't work. If the normal process isn't working, and can't work, then we need to explain why to justify a special merge like this.

**Comment by ottenhoff** [comment]
I've tested this branch on a client's DEV 11.x instance, and it doesn't work. 

It appears there are dependencies on library/webjars handlebars 4.0.5 which seems to have been added in SAK-32083.

**Comment by adrianfish** [comment]
SAK-32083 seems to specify 2.1.0, not 4.0.5. I'll update the branch.

**Comment by adrianfish** [comment]
Have you rebuilt library? It's in the pom and should be okay.

**Comment by adrianfish** [comment]
@ottenhoff What's the status with this? Has it been discussed?

**Comment by ottenhoff** [comment]
@adrianfish I looked through all roster2 JIRAs and only see two relevant JIRAs: SAK-32180 and SAK-32424. Are those the only two that need merging from master into 11.x? 

If yes, our process is pretty simple: Set the Merge flag on those two JIRAs and then mark as Verified and a branch manager will make the merge.

**Comment by adrianfish** [comment]
@ottenhoff At the time, when I looked at it back in April there was more missing than just those two commits - that's why I asked you for clearance to bring the whole lot over. It *felt* a lot less time consuming. I'll need to reconstruct why I made that decision since I've cleared it off my cognitive intray. I need to reiterate that I do understand the Sakai process and thus understood that I should make sure I was clear to do it this way.

**Comment by adrianfish** [comment]
More tickets that need merging ...

SAK-31075
SAK-32512
SAK-32474

**Pull request closed without merging**
