### PR TITLE
SAK-50711 Calendar first xhr request /direct/calendar/site/siteid.json returns invalid json

### PR DESCRIPTION
**Pull request by hornersa**
Jira: https://sakaiproject.atlassian.net/browse/SAK-50711

I demo and explain the approach of this proposed fix in the video, SAK-50711-ProposedFix-20241122.mp4, attached to the jira.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Yes, sorry, not a fan of this type of solution

**Comment by hornersa** [comment]
@ern @ottenhoff  - Can y'all point me to where in the code the REST call is being served? I'm not (very) familiar with where/how calls to /direct URIs is routing calls to which classes.

**Comment by ottenhoff** [comment]
Find the request in Chrome console -> Network -> Look at the response

```
{
    "entityPrefix": "calendar",
    "calendar_collection": [
        calendar: ED: ref=/calendar:display=aa:url=https://sakai.example/direct/calendar: props(0): dataOnly=false: data=CalendarEventDetails(location=,
        lastTime=20241122215959999,
        description=aaa,
        descriptionFormatted=<p>aaa</p>
, eventReference=/calendar/event/b7c54a14-d048-49 b9-846e-8356 ebcaf3aa/main/30762426-e540-4507-bd9d-7 c1b259b5df0,
        attachments=[])
    ]
}
```

calendar_collection obviously bad. do a refresh and now it's:

```
{"entityPrefix": "calendar", 
"calendar_collection": [
{
  "assignmentId": "",
  "attachments": [],
  "creator": "8c39209a-20ed-4ab5-a0d3-2ba5f28effbe",
  "description": "aaa",
  "descriptionFormatted": "<p>aaa<\/p>\n",
  "duration": 3600000,
  "eventIcon": "icon-calendar-activity",
  "eventId": "30762426-e540-4507-bd9d-7c1b259b5df0",
  "eventReference": "\/calendar\/event\/b7c54a14-d048-49b9-846e-8356ebcaf3aa\/main\/30762426-e540-4507-bd9d-7c1b259b5df0",
  "firstTime": {
    "display": "Nov 22, 2024, 4:00 pm",
    "time": 1732309200000
  },
  "lastTime": {
    "display": "Nov 22, 2024, 4:59 pm",
    "time": 1732312799999
  },
  "location": "",
  "recurrenceRule": null,
  "reference": "\/calendar\/calendar\/b7c54a14-d048-49b9-846e-8356ebcaf3aa\/main",
  "siteId": "b7c54a14-d048-49b9-846e-8356ebcaf3aa",
  "siteName": "SMPL101 Summer 2024",
  "title": "aa",
  "type": "Activity",
  "entityReference": "\/calendar",
  "entityURL": "https:\/\/sakai.example\/direct\/calendar",
  "entityTitle": "aa"
}
]}
```

`git grep -i calendar_collection`

then i look at that line using tig:

tig blame calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js

**Comment by hornersa** [comment]
@ottenhoff - Thanks, but I think I eventually found what I was looking for on the server site-- specifically that CalendarEventEntityProvider.getCalendarEventsForSite as the service method responding to the REST call. Presumably this is happening via the @EntityCustomAction annotation (presumably custom to Sakai) which I haven't delved into before. Nevertheless, I think I may have enough leads to pursue this further for now.

**Comment by hornersa** [comment]
I've ascertained that the problem is not due to the List object returned by CalendarEventEntityProvider.java.getCalendarEventsForSite when invoked for the first time. In other words, the list has events if you follow the test plan.

Therefore, the problem is likely somewhere within whatever RESTful architecture is being used by Sakai and/or an initialization problem with the custom annotation, EntityCustomAction... perhaps. That is to say that this bug is currently too far into the weeds for me to dig much further.

**Pull request closed without merging**
