### PR TITLE
SAK-31957 Don't NPE when announcements sorted by user.

### PR DESCRIPTION
**Pull request by buckett**
If the list of announcements contains an announcement made by a user who is now deleted then sorting by "Saved By" will cause a NullPointerException and the tool to crash.

### CODE REVIEW

**Comment by ottenhoff** [comment]
LGTM. Do you want a Squash and merge or a Merge preserving the three commits?

**Comment by buckett** [comment]
Err, not sure. We might want to merge this back 11.x as it's a bug fix and if we don't squash then we could leave out the API generics, although I'm not 100% sure that it will build like that. Announcements doesn't change much so a large merge will probably work.

**Comment by jonespm** [comment]
I'd typically say the only time(s) we wouldn't squash would be when there are multiple authors on a PR or when we're pulling in a new project with an existing history. This one seems better as a squash.

**Comment by buckett** [comment]
We get better `git blame` if we don't squash as the adding of generics isn't really related to fixing a NPE in the comparator, it just made it easier to see what to code was doing with the generics in there and the friction of creating another jira just for that change is too high.

**Comment by jonespm** [comment]
Yeah, maybe git blame a little better. If the individual commits actually had different jira's in them then I'd be fore retaining it but I think with just the message it will be confusing here and make merging harder.

**Pull request merged**
