### PR TITLE
Fixed sakai version in the master pom.xml

### PR DESCRIPTION
**Pull request by mpellicer**
Fixed sakai version in the master pom.xml

### CODE REVIEW

**Comment by buckett** [comment]
Yeah, I'm seeing this as well, if travis is happy I think this should be merged.

**Comment by buckett** [comment]
Whops, this probably should have had a SAK of the 11.x release on it.

**Comment by mpellicer** [comment]
The previous commits (The one which broke this) doesn't have a SAK, that's why i've requested against 11.x

Let me know if i can help

**Comment by buckett** [comment]
Yeah I just saw that, it's not a real problem, just nicer if a git blame has a SAK that the change is related to.

Thanks for the fix.

**Comment by jonespm** [comment]
Thanks guys, looks like a step I missed at the end of the release notes. As long as it's correct in the repo! (http://search.maven.org/#artifactdetails%7Corg.sakaiproject%7Cmaster%7C11.0%7Cpom) 

I don't know what to do with this version. I'm thinking of just removing it because I use the versions:set and it correctly updates all of the deps in dependency management during the release. We could also maybe leave the variable in there but set it to ${project.version}. It's the only unusual thing as part of the release right now.

**Pull request merged**
