### PR TITLE
SAK-32758 New add participants picker with typeahead.

### PR DESCRIPTION
**Pull request by buckett**

### CODE REVIEW

**Comment by ottenhoff** [comment]
The node people are invading 😕

**Comment by buckett** [comment]
@ottenhoff Yep it's not what I'd initially have liked, but all the nicer frontend build environments need node. When developing this it was quite nice in that I could run `npm run dev` where it starts up a webserver and watches files in the project and rebuilds when required. This allows development without the longer webapp re-deploy times as well as allowing a JavaScript build pipeline.

**Comment by ottenhoff** [comment]
I'm with you ..... I like the node environment also.

What I'm scared of is even more UI frameworks being introduced to Sakai. I've always found site-manage difficult as you have to jump between the RSF and the velocity parts. The Rubrics code recently introduced seems to be built using webcomponentsjs and uses bower and gulp. I'm sure i I will like the code here but am getting seriously scared about maintainability of these new components.

**Comment by bjones86** [comment]
> I'm sure i I will like the code here but am getting seriously scared about maintainability of these new components.

+1 to that

**Comment by ern** [comment]
I also share sentiment that each project should stick to one templating engine...

**Comment by adrianfish** [comment]
What makes Vue superior to just using jQuery and require?

**Comment by buckett** [comment]
Ok, I wasn't aware that rubrics was using polymer for it's new components, had I have known I would have looked at polymer/web components. But have we effectively decided that this is "the way" todo componentized development in the frontend because it's now merged?

Is the issue with the build that it uses npm/webpack, rather than using npm/gulp todo the build? The reason it uses webpack is that the VueJS starter project uses webpack. But webpack is designed to allow custom packaging of the dependent components so that you can serve up just what you need in a large application which is something that seems very applicable to Sakai.

Regarding frameworks I looked at:
- Angular, looked a little messy to introduce into an existing web application, but a possibility if starting from a cleaner slate.
- React, I've done a tiny bit and found it's learning curve a little steep and more detached from HTML (is you use JSX). I also wasn't sure about the patent issue in the license.

VueJS worked for me because:
- Simple starting point. Templates still look like HTML and it's not a tricky to grow.
- Small in size and not very invasive.
- Performant; the overhead on doing stuff in VueJS isn't very high and works on mobile well.
- Reasonable documentation, non-trivial community, not brand new (on version 2) so hopefully worked out most pain points.
- Can be used without build process.
- Nice starter project.
- Single file components (HTML/JS/CSS in one file).
- Has bootstrap components, although I didn't actually end up using them because I wanted more control over the components. 


I thought for something smallish like the user picker there's enough code to see how it all fits together without committing a huge amount of developer effort if it all goes wrong.

The backend code is all Apache CXF JAX-RS.

@ern What's your scoping on "project" here?
@adrianfish I like the component approach to development and the isolation/abstraction it provides. 

I think as/(if) we move to developing large chunks of Sakai in the frontend we're going to want some standard practices and while we could develop our own (RSF) it seems sensible to evaluate and rule out existing ones. Building on an existing project/community that's doing this just seems to get you so much, although picking the right project/community seems tricky.

**Comment by ern** [comment]
The scope I am referring to is the tool which is where a template engine would typically be employed so in this case were talking site-manage. I would use the same templating engine already in use in that project. If I were absolutely convinced that using a new template engine was needed I would first talk about with others in the community first. 

For a new project like "rubrics" they have more leeway in choosing a primary view technology.

**The idea is to have a single "View" technology employed in a tool.** 

This doesn't cover JS libs like jQuery, require, and moment because they are usually supporting the primary View technology.

For example in Samigo the primary view tech is JSF. There shouldn't be any RSF, Struts, Handlebars or other  templating engine in use. Of course JQuery and supporting libs are allowed since they support the primary view technology.

Furthermore for tools that employ multiple "view technologies/templating engines", I would understand what is the primary and only allow additions using that tech with the idea of converting the other tech to the primary. For example Samigo makes use of JSF and RSF I would be against any new RSF contributions to Samigo with the intention of removing RSF from Samigo all together, any future contributions to Samigo **must** be using JSF.

Caveat what I described above is my general outlook and doesn't mean that I would never allow an exception to that rule but it must have a good justification and be accepted by others in the community.

**Comment by adrianfish** [comment]
@buckett Thanks for the comprehensive background. We do need to get a grip of front end development in Sakai - it's a bit of a melange at the moment. How hard would it be, down the line, to migrate this VueJS stuff to Polymer if some decision's made to just support one client side framework?

**Comment by adrianfish** [comment]
@buckett There's a course, too.

https://www.udemy.com/vuejs-2-the-complete-guide

**Comment by buckett** [comment]
The existing site-manage tool call out to a helper to to add participants to a site so while this is in the same folder and SiteAction it is decoupled from it. This is taking an RSF part of site-manage and providing a REST webservice and JS frontend replacement for it. Re-writing it as AddPariticpantAction and accompanying velocity templates would have kept it more in-line with the existing code, but developing a JS frontend using these technologies wouldn't have been as re-useable.

The existing add participants helper can remain and this helper can be switched in on a per deployment basis.

Doing a wholesale re-write of a tool in a new technology doesn't allows for low risk evaluation of other technologies, but this does create risks for long term maintainability. But I would also argue that failing to develop/progress poses risks, as does writing our own frameworks or developing large chunks of code without a framework because we can't use one.

**Comment by csev** [comment]
So I am late to the party on this discussion.  As I look at the spec for this in the JIRA, I see no reason at all to introduce a whole new set of frameworks and new approach to dependency management etc etc etc  just to add clever typeahead in a text field.   There is a JQuery autocomplete feature already in the files we include in All Sakai pages:

https://jqueryui.com/autocomplete/

A bit of server side database query, some JSON return, and a bit of JQuery in the browser to add new fields as each field is completed and this seems to me to be a super simple thing to implement without incurring significant future technical debt and yet another corner of the code where the average Sakai developer is unable to understand / debug / fix.   An entire new UI framework that has 100+ lectures on Udemy seems like a lot of heft for extremely small gain.  The JQuery autocomplete is easy to use - I even teach it in my new Coursera specialization aimed at beginning web devs  :)  https://youtu.be/LpFt1AMfF3E?t=24m47s

And the problem is that this new framework will almost certainly have a "supported lifetime" of 2-3 years anyways and it will become our next un maintained legacy cross to bear as the Node hipsters move on to Zvue-1000.

If I am mis-understanding, I apologize.

**Comment by csev** [comment]
Lest I leave folks with a sense that I am just "that grumpy old guy", I think that it is a good time to talk about possible next-gen UI frameworks that we can and should start using in Sakai when we add significant new functionality or replace / rewrite functionality.

From the Tsugi perspective I want so both stay safe (jQuery / JQuery UI) but dabble in the future (as Matthew mentioned) to create experimental bits of my UI that I put in production to see if they hold up and/or cause problems.

I now have Tsugi dabbling in web components - which I am growing to like.  I am not ready (like ELMSN) to just rewrite all my UI as fast as I can - but at this point all my Analytics UI in Tsugi is web components.  If it breaks - only a small recently added part of Tsugi will break.

I like web components because the model is "built in to the browser by default" and polyfilled as needed.  The polyfill is a single file. This means that over time moving to web components has the potential to *reduce* the download footprint of our pages as browsers evolve and we switch from added frameworks to core browser features.

You have to be careful as you read about webcomponents because there is a lot of tooling (bower, gulp, npm, zippy999) to automate management/download of components that is *absolutely not necessary*.  You can use web components with nothing more than web component source code in static html files, a statically hosted polyfill and a bit of JS in your markup.  And you need to be careful about the JS footprint that you put into your web components.  I like that web components  are better suited to cacheing / being served out of a CDN than any other JS framework I have seen.

I am happy to show my simplistic / conservative approach I have taken w.r.t. web components.  Brian Olendyke of ELMSN takes the "burn the boats" / rewrite it all / use magic dependency management / run server side scripts to build markup / reuse other folks components/ "checkout edge" approach. 

His approach is a bridge way too far IMHO - but both approaches are using and testing the use of core webcomponents as the "next browser framework".

**Comment by adrianfish** [comment]
@csev Udemy lectures are really short, most of the time. 100 looks a lot, admittedly. I'm not advocating for switching to vuejs, particularly, but I do like the fact that Matthew has dumped out some RSF for this approach. That's a definite positive, for me.

**Comment by buckett** [comment]
Closing this as the Sakai community has reservations and wants it re-written.

**Pull request closed without merging**
