### PR TITLE
SAK-42834 StringUtils: Replace StringUtils.EMPTY references to the ba…

### PR DESCRIPTION
**Pull request by mpellicer**
…sic Java empty string

### CODE REVIEW

**Comment by adrianfish** [comment]
I don't agree.

"Down votes just because, no, I actually don't think "" is clear enough :( Is it blank? Is it empty? Is there a space in there I can't see because my font size is small? Was it intended to be empty? Are there any strange "invisible" chars?"

I agree with that.

**Comment by mpellicer** [comment]
I like StringUtils.EMPTY, more clear to me, I've raised this PR because of @jonespm comments on #7580.

What do you think @adrianfish ?

**Comment by jonespm** [comment]
I don't remember ever running into a bug where "" had invisible characters. I think it's unfortunate in java we have to worry about things like this, mostly because it this isn't set then it returns null which often becomes the full String value "null". That's the problem that's 99% more likely. 

I don't think we need to change everything one way or another was just curious when I saw it used.

**Comment by mpellicer** [comment]
"new String()" looks good to me, I think that's the desirable pattern when dealing with these cases.

Let's replace the StringUtils.EMPTY patterns?

**Comment by adrianfish** [comment]
I think you're replacing something that isn't broken. Maybe look at why we need to pass that empty string in the first place, rather than just replacing something seen as mysterious with something else seen as mysterious?

**Comment by ern** [comment]
Using a constant is generally always preferred whenever using a value repeatedly.
It removes ambiguity.
static String MAGIC = "magic";

if (someValue.equals(MAGIC))
vs
if (someValue.equals("magic"))
Now imagine if you repeatedly use this same string in many other places and the constant begins to show it's value.

This holds true for the an empty string all the same where EMPTY should be preferred over "".

The case for "new String()" is actually worse because your avoiding the java's string literal pool which is much faster than calling "new".

**Comment by mpellicer** [comment]
Sounds good to me, lets close this discussion.

**Pull request closed without merging**
