### PR TITLE
SAK-41982 - Second idea for - Instructor View: Switch View Select box

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by adrianfish** [comment]
I'm trying to test this out but can't even get the role switching box to display! Am I inhabiting stupid land, or what?

**Comment by jonespm** [comment]
Are you testing in a course site?

**Comment by ottenhoff** [comment]
Test as instructor1 in a course site. Do not test as admin

**Comment by fostersdesign** [comment]
Is it going to be clear to all users that they have to click "Enter" to activate the change now?

**Comment by jonespm** [comment]
It should work the same way as it does not for mouse users.

For Windows keyboard users before they couldn't switch to anything else other than the first option. For Mac keyboard users it seems they only had to hit enter once? I don't have a Mac easily available to test this on or to try to refine this better for Mac users.

**Comment by ern** [comment]
At the core call was discussed and decide to close this issue for the following reason:

In its current form this while this fixes and issue with a certain browser/os it introduces and another. It's a shame there aren't simpler solutions to these issues or jQuery handling the differences.

**Comment by jonespm** [comment]
Was there any comment on a potential fix? This should haven't any change for mouse users and for keyboard users this currently doesn't work at all right now. So I'm not sure how having to press enter twice for this box is a that big of a new issue introduced. There's probably a way to fix that but I can't easily test on a Mac, and it works great on Windows . . .

**Comment by fostersdesign** [comment]
From what I can recall from that Core call, there was concern about the inconsistent behaviour this would introduce with other dropdown menus in Sakai that also use the onchange functionality and about inconsistency between browsers, OSs, and devices. 

We wished that there was a better component that could address this behaviour for us, which is what Earle is implying in his last comment about having something like jQuery handle it for us.

**Pull request closed without merging**
