### PR TITLE
SAK-29706 Changed Label of Joinable Set to Joinable Group.

### PR DESCRIPTION
**Pull request by ouit0408**
SAK-29707 asks for confirmation when Joinable Group is deleted.
Confirm message comes when user clicks "Delete all groups" button and for
that have created 'JoinableGroupDelProducer.java',
'JoinableGroupDelViewParameters.java' and 'JoinableGroupDel.html'.Also, have
edited 'CreateJoinableGroups.html' and 'CreateJoinableGroupsProducer.java'.

### CODE REVIEW

**Comment by bjones86** [comment]
From SAK-29706:
The reason for the terminology of "set" was to mean a "group of groups". A group can be joinable and, therefore, a "joinable group". But how will we refer to a "group of joinable groups" where a student can join only one of those groups?    -Shawn Foster

I don't think the term 'Joinable Group' is accurate, as it's not referring to a singular group, but rather a group of groups, of which a user can join one of the 'set'.

**Comment by bjones86** [comment]
Also, the confirmation may be a good idea, but unless the original behaviour was changed, the messaging is inaccurate.

When you elect to delete a set now, it doesn't delete the groups associated with that set. It merely removes the group property to associate the groups with the set. Essentially, the 'set' is deleted, not the groups.

**Comment by plukasew** [comment]
As mentioned above, a simple replacement of the term "set" with "group" is going to cause confusion. Perhaps we could rename the page title from "Create New Joinable Set" to "Create New Joinable Groups", yet retain and properly explain the "set" terminology once we're on that page. This would get us over the hurdle of users not recognizing the term "set" in the menu bar.

**Comment by ern** [comment]
I don't recognize this contributor do you have a Apereo/Sakai CLA submitted?

**Comment by lardo-de-arnaud** [comment]
"I don't recognize this contributor do you have a Apereo/Sakai CLA submitted?" 

is this directed at "ouit0408"? if so it's Neelam from Oxford, she is covered by Oxford's CLA.

**Comment by ern** [comment]
Yeah worked it out but would be nice if user updated their github account so we don't have to look them up?

**Comment by lardo-de-arnaud** [comment]
Neelam has updated her details now.

**Comment by ouit0408** [comment]
As per discussion above closing this pull request.

**Pull request closed without merging**
