### PR TITLE
Update library\pom.xml

### PR DESCRIPTION
**Pull request by Santhanam**
while building sakai using the command `mvn clean install`,  the following error occurs :

---------------------
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (default-minify) on project library: Unable to parse configuration of mojo com.samaxes.maven:minify-maven-plugin:1.7.6:minify for parameter jsSourceIncludes: Cannot assign configuration entry 'jsSourceIncludes' with value '*.js' of type java.lang.String to property of type java.util.ArrayList -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (default-minify) on project library: Unable to parse configuration of mojo com.samaxes.maven:minify-maven-plugin:1.7.6:minify for parameter jsSourceIncludes: Cannot assign configuration entry 'jsSourceIncludes' with value '*.js' of type java.lang.String to property of type java.util.ArrayList

-----------------------------
For fixing the above error , i have removed the line - `<jsIncludes>*.js</jsIncludes>`

and added all .js files within the `<jsSourceFiles>` tag as given below :

-----------------------------------------

`<jsSourceFiles>
         <jsSourceFile>sakai.morpheus.authz.js</jsSourceFile>										 
         <jsSourceFile>sakai.morpheus.bullhorns.js</jsSourceFile>
         <jsSourceFile>sakai.morpheus.chat.js</jsSourceFile>
         <jsSourceFile>sakai.morpheus.connection-manager.js</jsSourceFile>
         <jsSourceFile>sakai.morpheus.footer.js</jsSourceFile>
	  <jsSourceFile>sakai.morpheus.i18n.utils.js</jsSourceFile>										 
          <jsSourceFile>sakai.morpheus.keyboard.sortable.js</jsSourceFile>							 
           <jsSourceFile>sakai.morpheus.more.sites.js</jsSourceFile>										 
           <jsSourceFile>sakai.morpheus.profile.popup.js</jsSourceFile>										 
           <jsSourceFile>sakai.morpheus.publish.site.js</jsSourceFile>										 
           <jsSourceFile>sakai.morpheus.quicklinks.js</jsSourceFile>										 
           <jsSourceFile>sakai.morpheus.reorderer.js</jsSourceFile>										 
           <jsSourceFile>sakai.morpheus.responsive.menus.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.session.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.short.url.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.skipnav.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.subnav.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.toggletools.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.update.presence.js</jsSourceFile>
           <jsSourceFile>sakai.morpheus.usernav.js</jsSourceFile>
	    <jsSourceFile>sakai.morpheus.utils.js</jsSourceFile>
            <jsSourceFile>sakai.morpheus.xlogin.js</jsSourceFile>
</jsSourceFiles>`

--------------------------

### CODE REVIEW

**Comment by adrianfish** [comment]
What version of maven are you running? The current poms work fine for me on Maven 3.6.0.

**Comment by SedueRey** [comment]
Unmodified pom is working fine in our servers, no need to upgrade.

**Comment by Santhanam** [comment]
Hello Adrian / Eduardo,

I have tried with Maven 3.2.5 as mentioned in "Technical environment for nightlies:" section of "Quick Start from Source" (URL : https://github.com/sakaiproject/sakai/wiki/Quick-Start-from-Source ).

So i was getting the error mentioned in my post.

Now as you have mentioned,  i upgraded Maven to 3.6.1 and  tried to build.

Now i am able to successfully build Sakai without any issues.

Thank You
With Regards
Santhanam

**Comment by SedueRey** [comment]
Thanks @Santhanam, I'm going to update wiki information.

**Comment by adrianfish** [comment]
@SedueRey I'd just started doing that, but I'll leave it to you if you want. The 10 information should come out - we don't run a 10 nightly any longer.
@Santhanam Thanks for pointing that out and sorry for your time being wasted on these PRs :(

**Comment by SedueRey** [comment]
@adrianfish I've just modified maven version. If you've got more information to add, feel free to do it. Thanks a lot.

**Pull request closed without merging**
