### PR TITLE
SAK-29884 Support elfinder as file picker.

### PR DESCRIPTION
**Pull request by buckett**
This add support for using elfinder as a picker for files with CKEditor instead of FCKBrowser. It's split into multiple commits so it's clearer what are the actual new code changes and what are the code dumps from other projects.

This isn't completely finished yet (it only supports resources/dropbox) as there's no Forums/Samigo/etc support. But's it can be configured with a property so can continue to develop inside Sakai.

### CODE REVIEW

**Comment by ern** [comment]
Would be nice if there was a little rebasing to clean up the the commits... Not against adding logical commits but there are some here that could be cleaned up.

**Comment by buckett** [comment]
Ok, the upstream project is fully released to maven central. This project still includes a copy of the elfinder JS code as that isn't available as an up to date webjar. But is much smaller than it was.

**Comment by buckett** [comment]
And it finally builds.

**Comment by ern** [comment]
FYI this is a perfect opportunity to use a webjar!

**Comment by buckett** [comment]
It does for the codemirror javascript. Are you suggesting making our own release of elfinder as a webjar?

**Comment by ern** [comment]
Nope I looked online and found an elfinder webjar here http://www.webjars.org/

**Comment by buckett** [comment]
Yep, that's 2.0rc-1 which is very old. This work was done against the 2.1
branch.

On 29 October 2015 at 19:17, Earle Nietzel <notifications@github.com> wrote:

> Nope I looked online and found an elfinder webjar here
> http://www.webjars.org/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sakaiproject/sakai/pull/1095#issuecomment-152291883>.
>



-- 
  Matthew Buckett

**Comment by ern** [comment]
Ok no worries

**Pull request merged**
