### PR TITLE
SAK-29496 - Podcasts: Use the Jquery datepicker

### PR DESCRIPTION
**Pull request by mpellicer**
Podcasts publish is using old style date picker instead of the new one.

File cleanup of the old datepicker component.

### CODE REVIEW

**Comment by ottenhoff** [comment]
This is looking good to me. I can test next week if no else gets to it sooner.

**Comment by mpellicer** [comment]
I've tested it with ES locale and works fine, the reason is the server validation, it uses a translation key to validate the format:

date_by_hand_format=MM/dd/yyyy hh:mm a

This translation key is not defined correctly in the SV file:

date_by_hand_format=dd-MM-yyyy hh:mm:ss

I agree with all the comments, having a translation key containing the format for each locale is a wrong solution, i'll work on improve this.

**Comment by mpellicer** [comment]
@ottenhoff I've did a hard effort here, i'm mostly convinced about this but want other opinions.

I'm ignoring the <h:inputText> value in the bean because it depends on the locale and i'm considering the hidden value as always comes in ISO format.

It only uses translation keys for displaying formats, as the current implementation does.

If this is a good way to do it, i'll implement the same strategy in other PRs.

**Comment by ottenhoff** [comment]
>  i'm considering the hidden value as always comes in ISO format.

Yes, that is a good way to fix it.

**Comment by buckett** [comment]
@ottenhoff Are you still wanting changes on this?

**Comment by ottenhoff** [comment]
Yes, I think we are still waiting on changes here. Correct @mpellicer ?

**Comment by mpellicer** [comment]
No no, the PR is up to date! All our PRs around the jQuery datepicker are up to date :)

Thanks @ottenhoff & @jonespm

**Comment by mpellicer** [comment]
You can see i'm considering always the ISO format, so it's independent from the user's locale

https://github.com/sakaiproject/sakai/pull/4138/files#diff-ca07e46a74f2ecccc75bebe21710c622R99

**Pull request merged**
