### PR TITLE
SAK-31738 Remove text on subsite button when the menu is collapsed.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**
Remove the ul from the subsites selector as this was preventing these styles being applied including one to remove the subsite text on a mobile sized screen.
Tweak the styles on the subsites selector so that the buttons look better in a desktop or mobile screen.
Made the border line between the tools and subsite buttons a bit darker so that the line can be seen for subsites as well as tools.

### CODE REVIEW

**Comment by lardo-de-arnaud** [comment]
could somebody review and merge?

**Comment by juanjmerono** [comment]
Some of the changes added in this PR were already applied in #3605. I think that SAK-31739 was reopened due to some problems raised during testing. I don't know if it is worth to wait until SAK-31739 is finally solved and then test this again and fix the remaining problems.

**Comment by juanjmerono** [comment]
This is an screenshot with the situation in master now (not exactly the same related in jira).
screenshot

**Comment by RebeccaOxfordUni** [comment]
I'm dealing with the conflicts.

**Comment by RebeccaOxfordUni** [comment]
I have fixed the issues mentioned by Juan apart from one.  See Jira for more info.  See the code for the fix for an issue with merging the code from master.
flyouts
flyoutsmenucollapsed
flyoutswithscroll
flyoutswithscrollmenucollapsed

**Comment by RebeccaOxfordUni** [comment]
Can this be reviewed soon please, I have another Jira that needs changes that are in here.

**Pull request merged**
