### PR TITLE
SAK-47951 grader: improve on smaller screens

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-47951

### CODE REVIEW

**Comment by adrianfish** [comment]
Screenshot 2023-03-27 at 17 56 40
Screenshot 2023-03-27 at 17 56 28
Screenshot 2023-03-27 at 17 56 17

**Comment by adrianfish** [comment]
Screenshot 2023-03-28 at 15 33 39
Screenshot 2023-03-28 at 15 33 25

**Comment by adrianfish** [comment]
@jesusmmp I think I've finished with this PR now. If you could please have another look, that would be great :)

**Review by ottenhoff — APPROVED** [review]

**Comment by jesusmmp** [comment]
@adrianfish Awesome work! 
I'll test this piece of work next week!

**Pull request merged**
