### PR TITLE
SAK-40356 - Problems with CSV/XML content when downloading grade file in a group assignment

### PR DESCRIPTION
**Pull request by adrianmticarum**

### CODE REVIEW

**Comment by ern** [comment]
Have you tried uploading a grade file to make sure it works with these changes?

**Comment by adrianmticarum** [comment]
We've tried to upload grade files in both our 11 version and nightlies (12.X and 19) but it doesn't work, so we've decided to fix these format problems with the zip and xls/csv files first and fix the upload later in another JIRA.

**Comment by ern** [comment]
Since this change is going to cause another issue, I think you should address both the download and upload in the same issue to avoid possible issues with merging one issue and not another.

Meaning if someone were to merge this issue or the other issue and not both there is more than likely going to be an issue with either the download or the upload, so lets keep them together on a single fix.

**Comment by adrianmticarum** [comment]
We can address both problems in this issue but the problem with the upload is not  caused by this change, it is failing right now in the nightlies (even in 11.X).

**Comment by ern** [comment]
I think its appropriate to use the column numbering vs looking at the header (as they maybe internationalized)...

**Pull request merged**
