### PR TITLE
SAK-31608 Adding context.xml for all webapps to set scanClassPath=false

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
It's entirely possible that EVERY webapp/META-INF doesn't need a context.xml and only a few would fix this bug. But I don't know how to figure out which few need it. I started up without errors and without log warnings after adding it to everyone. 2 of them already had a context.xml which I just modified.

**Comment by jonespm** [comment]
From what I can tell not *every* webapp needs this, it just looks like maybe these ones. And it some contrib tools might have a problem. I'm not sure what it is about these that are causing it. The easiest solution is just to modify conf/context.xml but OOTB this provides a better experience.

Ideally if someone could dig into this more and provide a test case/fix to tomcat it would be great, but I don't see that as a valuable time investment with such an easy workaround.

```
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/oauth-tool.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/authn.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/sakai-calendar-tool.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/emailtemplateservice-tool.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/sakai-editor.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/sakai-syllabus-tool.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/sakai-mailarchive-tool.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/sakai-reset-pass.war
INFO: Deploying web application archive /home/matt/sakaibin/sakai-bin-12-SNAPSHOT/webapps/dashboard-tool.war
```

**Comment by ern** [comment]
One thing to remember is that this will not cover contrib tools or other webapps someone may include.
Optionally the sakai maven plugin's deploy mojo could be updated to have the context.xml be added to tomcats global context.xml.

But yeah any of these strategies are secondary to having the Apache Tomcat project just fix the issue!

**Comment by jonespm** [comment]
Yeah, if this error did come in a contrib tool it could be fixed by adding this context.xml

And yeah, we could deploy it there but there might be local modifications someone would make rather than use this version. So yeah nothing is ideal. 

They already ignore a lot of specific jars from the scanner for some reason and I'm not sure why .

**Comment by ern** [comment]
One other thing to note if any webapp in the future wanted to perform configuration via annotation's like servlet 3.0's @WebServlet they will probably need this to work, and not have it disabled!

**Comment by jonespm** [comment]
So with the tomcat issue merged what do you think about this one? Was either merge this change to every tool, or just try it on the ones specifically affected. It doesn't *seem* to matter either way.

**Comment by jonespm** [comment]
Closing, will be incorporated by SAK-25750

**Pull request closed without merging**
