### PR TITLE
SAK-43473: Assignment: Info peer icon should be with cursor: pointer

### PR DESCRIPTION
**Pull request by FerAlvarez95**
https://jira.sakaiproject.org/browse/SAK-43473

### CODE REVIEW

**Comment by ern** [comment]
Should we use a fontawesome icon here?

**Comment by SedueRey** [comment]
We'll handle it :)

**Comment by fostersdesign** [comment]
It is already using FontAwesome (and a Bootstrap popover, by the looks of it): 

`<span id="peer-info" class="fa fa-info-circle" data-toggle="popover" data-container="body" data-placement="auto" data-content="You are able to accept or override the averaged peer review grade in this section.  Once this grade is released, this is the grade that will appear in the gradebook." data-original-title="" title="" aria-describedby="popover396596"></span>`

I think this PR is beneficial, but I don't think it addresses the whole issue, which is that the popover is not focusable, meaning it is not keyboard accessible and why the icon doesn't show the cursor pointer. 

Changing the span to a link `<a>` like the footer's information popover might solve all three issues.

**Comment by jesusmmp** [comment]
Please, don't merge yet. WIP

**Comment by jesusmmp** [comment]
Just finished. Please remove WIP label. Thanks!

**Pull request merged**
