### PR TITLE
SAK-40521 copy sort order to export

### PR DESCRIPTION
**Pull request by RyanAFinney**
When Categories are enabled exported excel files match the sort order
of categories and assignments

SAKAI-3183 Compare strings with string utils

SAKAI-3955 add back gradebook export sort

minor changes to comply with SAKAI 12.

SAKAI-3955 add back gradebook export sort

minor changes to comply with SAKAI 12, fix file names for export.

SAKAI-3955 gradebook export sort

minor change in import helper to stop NPE from happening on Section column.

SAK-40521 add missing constant.

SAKAI-3955 add gradebook export sort

implemented createTempFile method locally to avoid random hash being added to file name.

SAK-40521

### CODE REVIEW

**Comment by bjones86** [comment]
I don't recognize @washingtonj3. Do we need a completed CLA here?

**Comment by washingtonj3** [comment]
I'm @washingtonj3 I'm a student developer at the University of Dayton where @RyanAFinney works.
I'm pretty certain I filled out the CLA at some point and if I haven't can somebody point me to where I would need to fill it out.

**Comment by bjones86** [comment]
Thanks, @washingtonj3. The list of completed CLAs can be found @ http://licensing.apereo.org/completed-clas

If your name is on the list, then you're all set. If not, you can find the links to the agreements @ https://www.apereo.org/licensing/agreements

**Comment by washingtonj3** [comment]
Yeah that is me.

**Pull request closed without merging**
