### PR TITLE
SAK-47156 Assignments > late status is not communicated to students

### PR DESCRIPTION
**Pull request by bjones86**
https://sakaiproject.atlassian.net/browse/SAK-47156

Instructor’s see the “ - late” label applied to late submissions in both the submission list and the submission grading UIs. However, students do not see the late status on any of the UIs (assignment list, nor view submission). This information has meaning for both students and instructors, and should be communicated to both.

Part of this is a regression: the late status used to be displayed to students in the assignment list table. However this doesn’t seem to be the case in 23. Also, the "status" column for the student assignment list should not display the status in red bold text. Only the "late" label is meant to receive this styling.

### CODE REVIEW

**Comment by ottenhoff** [comment]
I wish I could create a Cypress test to prevent this from being regressed in the future, but writing browser tests with dates is insanely difficult.

**Comment by ottenhoff** [comment]
I'm going to defer to @ern here, but I think this is undoing Earle's intentions of moving this logic into a shared method getSubmissionStatus (SAK-45507)

`String i18nStatus = getFormattedStatus(submissionStatus, submitTime);`

**Comment by bjones86** [comment]
Yeah, I saw that too. However, there are other places in the UI that apply the late label this way, not through the Service method.

**Review by ern — APPROVED** [review]
It looks like the getSubmissionStatus is not returning the late status and it appears common place for ui to add this and this PR just fixes these specific locations to match.

Will create a new issue to fix getSubmissionStatus 🗡️

**Pull request merged**
