### PR TITLE
SAK-42658 T&Q : show submitted files on confirmation screen

### PR DESCRIPTION
**Pull request by bgarciaentornos**
The changes are mostly in the jsp file and in the SubmitToGradingActionListener. I couldn't keep myself from cleaning up the code a bit, reduced the DeliveryBean class in more than 1500 lines and 20kb. Still far from perfect but definitely a bit more light and readable...

Guess I could make simpler PRs for the backport.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 14
           

Complexity increasing per file
==============================
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakaiproject/sakai/pullRequest?prid=4691110&bid=15684294)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           

Complexity increasing per file
==============================
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java  2
         

Complexity decreasing per file
==============================
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakaiproject/sakai/pullRequest?prid=4691110&bid=15684294)

**Comment by bgarciaentornos** [comment]
> @bgarciaentornos There are a few Codacy recommendations that seem valid other than that LGTM.
> Will let you merge once your happy with Codacy recommendations.

Thanks, worked on quite a few of them. I tried to solve as many as possible, but there are endless recommendations from other files too, all related to previously existing code.

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 3
           

Complexity increasing per file
==============================
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java  2
         

Complexity decreasing per file
==============================
+ samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakaiproject/sakai/pullRequest?prid=4691110&bid=15684294)

**Pull request merged**
