### PR TITLE
Merge GradebookNG into Sakai master

### PR DESCRIPTION
**Pull request by steveswinsburg**
Note only the latest 250 commits are being shown.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Okay, looks pretty good.... note that LICENSE is Apache 2.0 and not ECL 2.0

**Comment by steveswinsburg** [comment]
Yeah I'll update that once in, this was a bit fragile commandline stuff and I dont want to mess with the matrix.

**Comment by ottenhoff** [comment]
Sounds good

**Comment by ern** [comment]
Awesome! I thought you were going to wait til Christmas!

ho ho ho!

**Comment by steveswinsburg** [comment]
Your Christmas came early!

sent from my mobile device

**Comment by steveswinsburg** [comment]
Removed license so it inherits and updated master pom to bootstrap this into the build. Ready to merge?

**Comment by ottenhoff** [comment]
+1 from me

**Comment by ern** [comment]
yeah if your ready steve make it so!

**Pull request merged**
