### PR TITLE
SAK-30439 switch to libsass for morpheus

### PR DESCRIPTION
**Pull request by ern**
Removed ruby sass and compass switched to libsass which is much faster.

Re created all the mixins we were using in compass.

There may still be some small issues here and there but we should just create new jira's for those.

### CODE REVIEW

**Comment by SedueRey** [comment]
I'm going to test this if it has side-effects.

**Comment by juanjmerono** [comment]
I was not able to compile with this new libsass at all. The `mvn clean install` just freezes here and never ends (the same behavior in travis) :disappointed: 
```
[INFO] morpheus.plugins.min.js (5451b)
[INFO] nb warnings: 79, nb errors: 0
[INFO]
[INFO] --- libsass-maven-plugin:0.2.2-libsass_3.3.3:compile (default) @ library
---
```

**Comment by SedueRey** [comment]
I'm very afraid of this changes right now that we are trying to fix all problems related to morpheus to release 11

**Comment by ern** [comment]
Yeah I understand your position Eduardo but I if you could just check it out, I went all around and things looked good.

**Comment by jonespm** [comment]
@juanjmerono It looks like the error with it freezing is this one. https://github.com/sass/libsass/issues/1931 I only see one place where this is an error for us in _defaults.scss.

I think Earle will update this.

**Comment by ern** [comment]
thanks @jonespm updated

**Comment by SedueRey** [comment]
I've been testing and I just have seen two little issues (very tiny).

On `pom.xml`, the `<outputStyle>nested</outputStyle>` should be `<outputStyle>compressed</outputStyle>`, if anyone wants to see it uncompressed can change it on its own branch :) 

The only problem I've seen removing compass is on a default style for `ul` and `ol`, if you could add this 4 lines to `base/_defaults.scss` file would be great, this lines reset the behaviour for some list UI (I've seen, at least, sitesNav, toolbar and profile). 

```
ul, ol {
    list-style: none;
    padding: 0 0 0 0;
}
```

Now it compiles faster than ever!!

**Comment by ern** [comment]
thanks @SedueRey for reviewing I updated the PR with your suggestions

**Pull request merged**
