### PR TITLE
LSNBLDR-644 - Add receiver code for post.message

### PR DESCRIPTION
**Pull request by csev**

### CODE REVIEW

**Comment by csev** [comment]
Chuck - this includes your fix to the simplepage.css removal - I verifies that was fixed as well.

**Comment by clhedrick** [comment]
Why are you removing add-before from the HTML file? Without that, items will only be added at the bottom of the page.

**Comment by csev** [comment]
I did not see the add before - oops.  Let me fix that.

**Comment by csev** [comment]
I just restored the add-before in a second commit - I think they can be squashed at the point of merge.

**Comment by clhedrick** [comment]
Done. I’m still trying to figure out git. I know how to squash my own commits, but not someone else’s, without unreasonable effort.

On Jun 2, 2016, at 7:44 PM, Charles Severance <notifications@github.com<mailto:notifications@github.com>> wrote:


I just restored the add-before in a second commit - I think they can be squashed at the point of merge.

**Comment by bjones86** [comment]
@clhedrick you can do it via the 'Merge' button now on the PR. It'll give you two options, one to merge with a merge commit, or to merge and squash.

The later option squashes all commits in the PR into one commit, and also let's you revise the commit message at the same time.

**Comment by ottenhoff** [comment]
In early April, Github introduced the ability to squash all commits from a contributor into one clean commit via the Github pull request interface. The merge pull request button is now a dropdown that provides the additional option:

  https://github.com/blog/2141-squash-your-commits

The legacy behavior creates a merge commit (by the merger, Hedrick) and then brings in the two commits from the author csev. The new behavior would have created one commit only (csev) in master.

**Pull request merged**
