### PR TITLE
SAK-32411:Changes to eliminate html escaping to show correctly group …

### PR DESCRIPTION
**Pull request by mateullas**
…names with non-ascii characters

### CODE REVIEW

**Comment by ern** [comment]
Escaping html is there because it is displaying output that came from some input which needs to be sanitized, was this considered?

**Comment by ern** [comment]
Please don't submit PR's directly to 11.x that should goto master first.

**Comment by mateullas** [comment]
In master code there is no escaping, so this patch can't be applied there (I have indicated that this issue affects only 11.x code). 
I guess currently there is no reason to sanitize input with escaping html. 
In our 11.3 instance it works well, now group names with non-ascii character appear well.

**Comment by ern** [comment]
Looks like it is still in master,
https://github.com/sakaiproject/sakai/blob/master/site-manage/site-manage-group-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroup/rsf/GroupListProducer.java#L119

**Comment by ern** [comment]
OK so what we need to do is merge SAK-27980 PR #4093 to 11.x but please don't open a new PR for the same fix to a different branch.

**Comment by mateullas** [comment]
Hi, Earle. 
You are right, there is a PR in SAK-27980 to eliminate html escaping that should be applied to 11.x. 
I apologize for the annoyance, I didn't notice there was this PR related with SAK-27890 because the main issue there was another one (according to testing plan in ticket, which I tested in nightly).

**Comment by mateullas** [comment]
Regarding html escaping in site-manage-group-helper folder I guess should produce similar problems with non-ascii characters, because the code there apparently works like the one in site-manage-group-section-role-helper (in fact is nearly a duplicate for creating groups). 
I have made tests in nightly with the tool but I'm not able to find a use case that uses code in site-manage-group-helper, apparently code in site-manage-group-section-role-helper  is always used.

**Pull request closed without merging**
