### PR TITLE
SAK-32558 Unescaping any html entities in titles before sorting.

### PR DESCRIPTION
**Pull request by LHSnow**
Proposed fix for SAK-32558
Unescaping any html entities in titles before sorting.

### CODE REVIEW

**Comment by buckett** [comment]
So it looks like because of the complexity of SAK-29138 we can't just use `Site.getTitle()` and sort earlier.

I'd prefer it if we did the sort on the raw list of Sites and then after they are correctly sorted converted them into a map. That means calling `SiteService.getUserSpecificSiteTitle()` for each site  which can be expensive. ugh...

**Comment by LHSnow** [comment]
How do we move this forward? Are we waiting for review or for a different, better fix?

**Comment by steveswinsburg** [comment]
Looks like TitleSorter actually has the site objects. Could it just use `getUserSpecificSiteTitle` instead or is that expensive? 

Also, `List<Map>`.... wtf are with those types!

**Comment by ncaidin** [comment]
Hi @LHSnow , could you please submit a licensing agreement so that we can accept your contributions? 

Information about the Apereo Licensing process and a link to the ICLA online form (individual contributor license) can be found at 
https://www.apereo.org/licensing

**Comment by LHSnow** [comment]
@ncaidin Thank you for the reminder, licenses are now signed!

**Comment by ncaidin** [comment]
Thanks @LHSnow  ! License on file.

**Pull request merged**
