### PR TITLE
SAK-45008 LAST_VISIT_TIME is NULL when site presence is enabled

### PR DESCRIPTION
**Pull request by austin48**

### CODE REVIEW

**Review by adrianfish — APPROVED** [review]
Just added a space around those ternary colons.

**Comment by austin48** [comment]
can this be unmerged?  I believe it's causing test failures

**Comment by austin48** [comment]
please see my comments in https://sakaiproject.atlassian.net/browse/SAK-45008?focusedCommentId=206553

**Comment by ern** [comment]
Hi Austin we can revert this

**Comment by austin48** [comment]
Thanks

**Pull request merged**
