### PR TITLE
SAK-29074 polls ability to clear votes and allow revoting

### PR DESCRIPTION
**Pull request by adrianfish**
Added the ability to clear votes in polls and enable them to be revoted
on. Original work done by Nick Wilson at Oxford.

### CODE REVIEW

**Comment by ottenhoff** [comment]
+1 on the functionality

**Comment by yq12** [comment]
sounds like a good feature to benefit all.

**Comment by yq12** [comment]
Also heard from our support lead Whiitten Smart for a +1.  

QUOTE:
While I have not heard of this request from faculty members personally, I do believe it would be a feature worth having.  I can see the benefit of resetting votes on a poll so that the poll can be reused.

**Comment by yq12** [comment]
Just curious to know:  Does  the new feature includes keep history record of votes for the poll?

**Comment by adrianfish** [comment]
No, it doesn't keep an audit trail of votes. If you think this is a good idea, please JIRA it.
Adrian.

**Pull request merged**
