### PR TITLE
SAK-29791 Remove covers from assignments.

### PR DESCRIPTION
**Pull request by buckett**

### CODE REVIEW

**Comment by buckett** [comment]
The old PR for this was #976 which because was closed when I forced pushed the branch didn't want to re-open.

**Comment by buckett** [comment]
I've fixed the comments @ottenhoff made about the .eu properties file which Intellij mangled. I'm basically unable to edit it in Intellij, although vim worked without any problems.

**Comment by juanjmerono** [comment]
Is this commit "Updated message bundle for assignments." related with this issue?

**Comment by buckett** [comment]
I think in an earlier version of this PR I removed some code that was the last use of these 2 properties so I dropped them. In my searching they are both unused. You prefer it if I move them to a different PR?

**Comment by ottenhoff** [comment]
I don't mind dropping them in this PR.

Are we aiming to merge this into 11.x?  If no, then I may advocate for keeping this as a PR until we get to early 2017 to help the mergers out

**Comment by ern** [comment]
Yeah I don't think this is a change for 11 its a good improvement but its not addressing some bug!

**Comment by buckett** [comment]
Branch is rotting, with more merge conflicts again. Shall I update them or are we not wanting improvements like this until 2017?

**Comment by jonespm** [comment]
I think getting these covers out are something we want. Just rebase this and merge it in now.

**Comment by buckett** [comment]
Updated again.

**Comment by buckett** [comment]
I'll merge this the next time I resolve conflicts.

**Comment by buckett** [comment]
Branch updated with fixes. Assignments tool starts up and I can create an assignment. I'll merge when travis is happy.

**Pull request merged**
