### PR TITLE
SAK-32675 - Update license plugin and license headers

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
I tried to tweak this plugin configuration the best I could. I'm not too sure if we can do any better automatically without changing the plugin? 

This does not update any existing files (mostly it was changing the copyright year and the URL's) but for some reason a "few" files could not be detected correctly and have completely duplicate license headers here. I'd like to figure out a good idea for how to detect these and probably just remove the older one.

**Comment by buckett** [comment]
I see quite a few with duplicates (crude way to find them):

     egrep -rc 'Licensed under the Educational Community License,' . | grep ':2$' | wc -l

gives 192.

**Comment by jonespm** [comment]
Yeah, do you have thoughts on an easy way of removing the duplicates? I thought about writing up a script but really this didn't seem like big enough of a deal to me. Ideally the license plugin would do it but again modifying it just for this didn't seem worth the effort. I'm 100% happy for someone else to do this better or find a better plugin/process.

**Comment by jonespm** [comment]
Removing and cleaning the duplicates could also be a separate task. This is also ignoring a few directories that added a lot of duplicates (jsf/delegatedaccess) and some of the duplicates maybe should stay there or even have their dates updated, which this plugin would do if they header format was correct.

**Pull request merged**
