### PR TITLE
SAK-29850 roster -> roster2

### PR DESCRIPTION
**Pull request by axxter99**
SAK-29850 roster -> roster2

### CODE REVIEW

**Comment by ern** [comment]
Just doing a quick search for other locations that still have "sakai.site.roster" yields:
```
kernel/component-manager/src/main/bundle/org/sakaiproject/config/toolOrder.xml
sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef.xml
sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EventRegistryServiceImpl.java
```
Do you think it worth updating these as well?

**Comment by juanjmerono** [comment]
All the changes has sense to me, maybe sitestats requires some deep testing, I think it saves toolId's in report's definition, so we need to figure out what happens if we change this value without changing the database.

**Comment by axxter99** [comment]
ern: SAK-x? 

<tool id = "sakai.site.roster" />
+ <tool id = "sakai.site.roster2" />

......
- <tool id = "sakai.site.roster" />
+ <tool id = "sakai.site.roster2" />

?

**Comment by axxter99** [comment]
Cheers!😀

**Pull request merged**
