### PR TITLE
SAK-29063 Upgrade to Tomcat 8

### PR DESCRIPTION
**Pull request by buckett**
This gets Sakai starting up in Tomcat 8 and a login working. The changes to DavServlet mean this change means /dav will fail to work against Tomcat 7.

### CODE REVIEW

**Comment by buckett** [comment]
We probably need to raise this on the list before we think about merging.

**Comment by ottenhoff** [comment]
Can we avoid the DAV change by using java.net.URLDecoder or commons URLCodec?

**Comment by buckett** [comment]
Possibly, switching the class was the path of least resistance.

**Comment by jonespm** [comment]
Yeah, I think using something standard non tomcat library would be a good idea, not sure the ideal replacement.

Also it looks like this jira is SAK-25883, not SAK-29063.

**Comment by buckett** [comment]
If we fix this so that people can use tomcat 7 we're still compiling against one version and running against another. Anyone not running against the version specified in `master/pom.xml` risks a runtime blowup because the classes aren't the same.

Even if this works now, in the future (in a month) someone may change DavServlet, nobody will check that it still works against tomcat 7 until they hit the problem at runtime.

As long as we're compiling against Tomcat I think the safe thing todo is to just specify one version.

**Comment by ottenhoff** [comment]
> As long as we're compiling against Tomcat I think the safe thing todo is to just specify one version.

I agree

**Comment by buckett** [comment]
Rebased onto master to fix merge conflict.

**Pull request merged**
