### PR TITLE
SAK-31135 gradebookng datepicker

### PR DESCRIPTION
**Pull request by joejacob**

### CODE REVIEW

**Comment by ern** [comment]
The tilte "bug fix" should be better articulated.

**Comment by steveswinsburg** [comment]
This is going to 11.x or master?

**Comment by joejacob** [comment]
This is for 11.x

**Comment by joejacob** [comment]
Also, issue #2176 seems to address this bug.

**Comment by steveswinsburg** [comment]
Shouldn't this go into master as well though? Generally we go to master first then back to 11.x. Is there a similar fix for master?

**Comment by payten** [comment]
Hi @steveswinsburg, we've just recently fixed the Bootstrap button styling via PR https://github.com/sakaiproject/sakai/pull/2507.  This has been merged into master.

I notice there are also some JavaScript changes in this commit, I'm not aware if those are required?

**Comment by steveswinsburg** [comment]
Thanks @payten, @joejacob could you rebase and check if this is still needed? Cheers.

**Comment by steveswinsburg** [comment]
Two outstanding questions from me above:
1. This is a direct merge to 11. Standard practice is to go to master first, then to the release branch.
2. Is this still required, post #2507?

@joejacob could you please review? Cheers 👍 🍰 🐨

**Comment by steveswinsburg** [comment]
Closing due to lack of response.

**Pull request closed without merging**
