### PR TITLE
SAK-28055 In assignment with submission for groups the assign grade

### PR DESCRIPTION
**Pull request by juanjmerono**
override includes instructors

### CODE REVIEW

**Comment by juanjmerono** [comment]
Some strange spaces here too :disappointed: 
Let me revise this one to fix spaces vs tabs issues.

**Comment by ottenhoff** [comment]
Yes, it a two-step process:

1) squash the two commits using git rebase 
2) git push --force

**Comment by bjones86** [comment]
Those commands are nice to know :) It may be helpful for other people new to Git to put them into the document @ https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup

**Comment by juanjmerono** [comment]
I think now the space issues are fixed and everything in the same commit. Thank you @bjones86 for your command guide to squash :+1:

**Pull request merged**
