### PR TITLE
SAK-32189 Configurable tools and subsites buttons now full-width on a

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**
mobile sized screen.

### CODE REVIEW

**Comment by RebeccaOxfordUni** [comment]
Note that one needs to set $tool-menu-icon-on-left: true in reference\library\src\morpheus-master\sass\_defaults.scss
I also made the subsites buttons look a little better in the default set-up icons above the title.

Screenshot from before these changes:
prefixwithsubsites

Screenshots from after these changes:
mobileiconslhs
mobileiconsabovewithsubsites

See the Jira for more test screenshots.

**Comment by RebeccaOxfordUni** [comment]
We need to wait for an answer to my question in the merged PR below before this PR is merged:

https://github.com/sakaiproject/sakai/commit/17da9855378320671e5fd2613713ffdf0da9bebe

**Comment by lardo-de-arnaud** [comment]
rebecca says she doesnt think this does need to wait for the subsites flyout code to be put back in. This code is independent and shes pretty surem it can be merged now.

**Comment by lardo-de-arnaud** [comment]
could somebody review this?

**Comment by RebeccaOxfordUni** [comment]
@adrianfish Are you willing to merge this PR?  This makes the buttons full width (not square) on a mobile but doesn't turn this on by default, it is the PR for SAK-32260 that makes the icons on the left hand side by default and full width on a mobile by default.
I'm having trouble doing the few required tweaks for SAK-32260 without this code being merged to master.
Thanks

**Comment by adrianfish** [comment]
I suggest actually setting $tool-menu-icon-on-left: true by default. Otherwise nobody will see this change. We can set it to false when the 12 branch is cut if it's not approved of. Set it to true and I'll test it out tonight. If it's okay and nobody else chips in, I'll merge it this evening. Cool?

**Comment by RebeccaOxfordUni** [comment]
@adrianfish  SAK-32260 is setting the tool icons on the left by default, this PR is improvements that we definitely want regardless of whether SAK-32260 is approved or not.  To keep things cleaner I'm going to shift the few extra CSS changes (other than defaulting to icons on the left) onto this PR.  Can you test this PR and SAK-32260 together later on (when I've done the tweaks) and then merge them both tonight?

**Comment by lardo-de-arnaud** [comment]
I agree with you @adrianfish, about sticking in the "tool icon on left" change in for 12.

**Comment by lardo-de-arnaud** [comment]
that is not to say that the 'icon on left' change should be done under this PR, -  as rebecca says, it's part of SAK-32260

**Comment by adrianfish** [comment]
@RebeccaOxfordUni Yep. I'll test both and get them in. Unless I get vetoed meanwhile.

**Comment by RebeccaOxfordUni** [comment]
A second commit includes some minor CSS changes to make the tool buttons the same height as NYU use (only when the tool menu icons are on the left) and align the icon and tool text correctly.
mobilewithnyuheightbuttons
desktopwithnyuheightbuttons
 
Please test this PR with SAK-32260 at the same time so that you can see the icons on the left and the tool buttons one per line on the mobile site.

**Comment by adrianfish** [comment]
Did you squash the commits? I'm only seeing one on your SAK-32189 branch.

**Comment by buckett** [comment]
I'm seeing 2, 0c3810bd58634ea4f54409e6486f62cb98cbb9ff and 3c38f44eacc899513c1612c3d13772d56248fd1e

**Comment by adrianfish** [comment]
Yep, got it. Forgot to fetch.

**Pull request merged**
