### PR TITLE
SAK-45382 WebDav remove use of static cover

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Review by bjones86 — APPROVED** [review]

**Review by ern — CHANGES_REQUESTED** [review]
Removing the static covers is great but can we can take this a step further and stop using ComponentManager (another static cover)?

**Comment by axxter99** [comment]
@ern SpringBeanAutowiringSupport?

**Comment by ern** [comment]
I think for the dav tool adding a SakaiContextLoaderListener  and an applicationContext.xml with appropriate beans will probably be best

**Comment by bjones86** [comment]
@axxter99, is this ready now? Or still work in progress?

**Comment by csev** [comment]
Cool - this was my first contribution to Sakai back in 2002 :)

**Review by ern — APPROVED** [review]

**Pull request merged**
