### PR TITLE
SAK-29402 : Role-based access to Resources

### PR DESCRIPTION
**Pull request by frasese**

### CODE REVIEW

**Comment by ottenhoff** [comment]
This seems like a pretty nice feature. Anyone up for testing this?

**Comment by buckett** [comment]
The build failure looks related to this change.

**Comment by frasese** [comment]
These changes should be checked after https://jira.sakaiproject.org/browse/SAK-29401

**Comment by buckett** [comment]
This pull request depends on #693

**Comment by buckett** [comment]
This branch doesn't merge cleanly.

**Comment by frasese** [comment]
Rebased

**Comment by buckett** [comment]
Doesn't compile

**Comment by frasese** [comment]
The master project in trunk seems to be broken. Is that possible?

**Comment by buckett** [comment]
I think the main Sakai project is building ok: https://travis-ci.org/sakaiproject/sakai/builds

**Comment by frasese** [comment]
Ok, was my fault. I was using the wrong java environment. Now, everything seems right.

**Comment by buckett** [comment]
I've created #1433 which has fixes for the Test framework upgrade and configuration changes on it.

**Pull request closed without merging**
