### PR TITLE
SAK-47475 grader: ensure docx opens in preview  panel

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-47475

### CODE REVIEW

**Comment by feralvarez95** [comment]
Should we include odp files? I think that the [sakai-document-viewer](https://github.com/sakaiproject/sakai/blob/master/webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js#L108) is currently handling them.

**Comment by adrianfish** [comment]
@feralvarez95 ODP isn't currently handled by BaseContentService.getHtmlForRef, so that would have to be added. It will get handled by the libre conversion perhaps.

**Comment by adrianfish** [comment]
@feralvarez95 Okay, talking right out of my culo there. odp is handled in the browser plugin, the webjar. So, maybe we should list it.

**Comment by feralvarez95** [comment]
> @feralvarez95 I've updated the PR. See the comment for details. Lot cleaner now, and more efficient if you've got the LibreOffice converter setup, because ODT and ODP don't need to be converted on the backend.

Yes, cleaner and better. Great!!

**Review by ern — APPROVED** [review]

**Pull request merged**
