### PR TITLE
SAK-29939 use CREATE TABLE IF NOT EXISTS and INSERT IGNORE INTO 

### PR DESCRIPTION
**Pull request by ottenhoff**
to avoid lots of startup issues with MySQL

### CODE REVIEW

**Comment by ern** [comment]
Nice cleaning up the mysql scripts....

**Comment by buckett** [comment]
I'm not sure this is the correct solution. I think the `SqlService.ddl` method attempts to run a .sql file and if the first line suceeds then it attempts to run the rest of the lines and if the first line fails it assumes the files has already been run and doesn't report the first error and doesn't attempt to run the rest of the file.

This change will mean it will always attempt to run the whole file because the first line won't have failed.

**Comment by ottenhoff** [comment]
> I'm not sure this is the correct solution.

Agree, I'm not positive it's the right solution either. But depending on table creation failing seems odd.

> I think the SqlService.ddl method attempts to run a .sql file and if the first line suceeds
>  then it attempts to run the rest of the lines and if the first line fails it assumes the files
> has already been run and doesn't report the first error and doesn't attempt to run the
> rest of the file.

Right, it does this for nearly every tool. It stops running the SQL file as it hits a hard error. 

> This change will mean it will always attempt to run the whole file because the first line 
> won't have failed.

This is correct.

**Comment by buckett** [comment]
It just means that all the statements in the file will get run all the time, if there's a statement that doesn't have an IF version then it's not possible to include it without having it write out an error.

I also worry that we're going down one path for MySQL and not changing Oracle which makes supporting the 2 database more work in the long run.

**Comment by ern** [comment]
This conversation should probably be happening on the JIRA!

**Pull request closed without merging**
