### PR TITLE
SAK-32244 Changed the word Meeting to Event in GB properties file.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Can another school that runs with en_GB approve these changes? I don't understand if this is EN-wide, EN-GB specific, or Oxford-specific.

**Comment by ottenhoff** [comment]
Are we sure this isn't just an Oxford-specific edit?

**Comment by RebeccaOxfordUni** [comment]
@adrianfish do you want this change at Lancaster?  It affects sign-ups only.  We think you are the only other GB Sakai user.  I can close the PR if you don't want the change.

**Comment by adrianfish** [comment]
Makes sense to me. Meeting is too specific imho.

**Comment by ottenhoff** [comment]
This still seems super odd to me, but I trust that this is a GB-specific edit and not an EN-specific edit

**Pull request merged**
