### PR TITLE
SAK-40092 - Don't allow instructors to do a submission in behalf of a…

### PR DESCRIPTION
**Pull request by danielmerino**
… student when they can't do it.

### CODE REVIEW

**Comment by danielmerino** [comment]
Please don't merge. I have done a quick test in Atica and this is not working. Not sure why, I'm investigating it.

**Comment by danielmerino** [comment]
Finally it is working in Atica. You can merge it if you want.

**Comment by danielmerino** [comment]
@mpellicer could you remove the "WIP" label, please? It can give the false impression that this is still under development but it's ready to be merged.

**Comment by mpellicer** [comment]
Done @danielmerino , thanks for the contribution

**Pull request merged**
