### PR TITLE
SAK-40734: 'Save and Release to Student' button isn't blue

### PR DESCRIPTION
**Pull request by jesusmmp**

### CODE REVIEW

**Comment by fostersdesign** [comment]
Although we haven't defined this yet, I believe there should only be one primary action button in a form. Therefore, I think we need to decide which of these two save buttons should be the primary button.

**Comment by ottenhoff** [comment]
Agree on one primary ... Save and Release seems primary to me

**Comment by fostersdesign** [comment]
If we change the primary to be the "Save and Release" button, then I'd recommend changing the order of the buttons so that the "Save and Release" button is the left-most button (in ltr languages). (Again, we haven't defined this in a guide yet, but it should be best practices and is common place throughout Sakai now.)

However, changing the order of these buttons might have critical teaching implications if markers are used to clicking the left-most button to save but not release the grades to students. They may not noticed the order change of the buttons and unintentionally release the grade before they were ready to.

How should we handle this change?

I'm in favour of leaving the "Save and Don't Release to Student" button as the primary action button because it is the safer and probably the more-used button, since most instructors that I've worked with prefer to release an assignment's grades to all students at once after they have finished grading all of the assignment's submissions.

**Comment by ottenhoff** [comment]
Ok whatever is more-used button ... if you think it's Dont Release, that's fine with me

**Comment by ern** [comment]
Closing per discussion on Core Team 10/09/2018, The best solution is to have the button "Save and Don't Release" as the primary.

**Pull request closed without merging**
