### PR TITLE
SAK-32632 Added the admin role to solve the problem with rubrics only for admins

### PR DESCRIPTION
**Pull request by ddelblanco**

### CODE REVIEW

**Comment by ern** [comment]
Probably makes sense to close this until rubrics is integrated?

**Comment by jonespm** [comment]
Well, seems like the PR is good, but not sure about your issue. Seems like it's going to be something we want to get in.

**Comment by ddelblanco** [comment]
It does not mach any user name. It receives the permissions in the token. Sakai's integrated rubrics service generates the token and it is generated based in the service.

**Comment by ern** [comment]
Ok I see it now, thx for pointing it out!

**Pull request merged**
