### PR TITLE
INFRSTR-310 Allow the build to work with travis-ci.org

### PR DESCRIPTION
**Pull request by buckett**
This means our build output becomes reasonable again and we can cache our m2 repository so that builds are a little faster on travis-ci.org

### CODE REVIEW

**Comment by buckett** [comment]
For things like this is it worth creating a SAK?

**Comment by jonespm** [comment]
I usually create one when I do a release under the Release Management component, just for tracking purposes. I think for something like this, it would be nice to have some detail on an INFRSTR ticket, but probably isn't a huge deal.

**Comment by buckett** [comment]
Good idea, done.

**Comment by jonespm** [comment]
Sounds good if it gets it working, haven't had time to look at this myself.

**Pull request merged**
