### PR TITLE
SAK-44159 Improvements to Reorder in the Lessons tool

### PR DESCRIPTION
**Pull request by davidpbauer**
Reorder is still in one list. Sections and columns are outdented and
section name has been added to Section break.
Added preview link to reorder items
Items on the reorder page that used to be blank or did not
display anything useful now have a preview link to see the
content.
Move the add items from another page link to the main add content menu.
Add new embed items to the reorder page. Add back icon colors. Add new
icons for new reorder items. Fix z index issue with section dropdown menu.
Removed dropdown and replaced with two icons that accomplish
the same actions for a section.

### CODE REVIEW

**Comment by adrianfish** [comment]
@davidpbauer Is there a specific merge order we need to look out for in these PRS? Interdependencies?

**Comment by davidpbauer** [comment]
I believe I've split them up in a way that they are independent of each other and could be merged in any order.  That said, I'd recommend going in their numbered order (#8477, #8478, #8479, #8480, #8489)

I'm trying to find some time today to finish adding details to the Jira tickets and can double-check each pull request as I do so. I'm also happy to comb back through all of the changes after they are merged to make sure all of our work made it into a pull request.

**Comment by adrianfish** [comment]
@davidpbauer I've just been testing this out, and it looks a load better. However, deleting the items doesn't stick. You save and go back to the main page, and the items are still present. I tried this on master, and it's the same - so maybe it's another bug in master preventing the deletion.

**Comment by ottenhoff** [comment]
> @davidpbauer I've just been testing this out, and it looks a load better. However, deleting the items doesn't stick. You save and go back to the main page, and the items are still present. I tried this on master, and it's the same - so maybe it's another bug in master preventing the deletion.

nothing in tomcat logs about a hibernate error ... hibernate 5 does not like delete from TABLE where x = ?

**Comment by adrianfish** [comment]
@ottenhoff I'll check. Thanks.

**Comment by davidpbauer** [comment]
Locally, I'm unable to delete items via Reorder or the main Lessons page which leads me to believe it's related to org.sakaiproject.lessonbuildertool.model.SimplePageToolDaoImpl#deleteItem and not anything in this PR. I didn't see any errors in the logs.

**Comment by adrianfish** [comment]
@davidpbauer That's my conclusion, too. Nothing to do with this PR.

**Review by adrianfish — APPROVED** [review]
Approved. I tested this out, and it works as expected. There's a bug with deleting items, probably related to the hibernate 5 update, but that needs to be a separate JIRA.

**Pull request merged**
