### PR TITLE
S2U-23 5.1.1.19 Tests & Quizzes: Add the option to show the student t…

### PR DESCRIPTION
**Pull request by JuanDavid102**
…he right or wrong questions, but without indicating which is the correct answer

### CODE REVIEW

**Review by bgarciaentornos — APPROVED** [review]

**Review by ern — COMMENTED** [review]
@JuanDavid102 since this is a PR to master and not the S2U branch it should be an SAK issue

**Review by ern — CHANGES_REQUESTED** [review]
convert to SAK

**Comment by bgarciaentornos** [comment]
@JuanDavid102 can you contribute this under a SAK- jira when possible? Thanks!

**Comment by JuanDavid102** [comment]
Ok. I created the jira. It is that: https://sakaiproject.atlassian.net/browse/SAK-50424

**Comment by JuanDavid102** [comment]
@ern @bgarciaentornos 
Now it is in another PR: https://github.com/sakaiproject/sakai/pull/12824

**Pull request closed without merging**
