### PR TITLE
SAM-2505 Calculated question: Correct answer is graded as wrong when the...

### PR DESCRIPTION
**Pull request by raulsv**
... answer uses comma as decimal separator instead of using the point

### CODE REVIEW

**Comment by ottenhoff** [comment]
Hi @raulsv, how does this modification handle a USA student entering "1,234.56" as the answer?

**Comment by raulsv** [comment]
Thanks Sam, grading will not work if the student enters "1,234.56". So we need to find a fix for that so that it allows at the same time to have "1,234.56"(USA locale) and "1.234,56" (Spain locale). Any suggestions?

**Comment by juanjmerono** [comment]
I think the only way to do this is normalize the format when the user introduces the answer. In that moment you know the user's locale and you could change the decimal/thousands separator, if is different from USA.
During the correction process you are not able to know if "3,145" is 3145 or 3.145 because you don't know the locale used to introduce the answer.

So, no matter what the user's locale was, in the database you will have the number with "." as decimal separator and "," as thousands separator.

Change previous database data is not mandatory, the answers of the previous tests will not change, and the new answers will work. If you want to re-grade some specific test you must change database value assuming some locale for the response.

**Comment by juanjmerono** [comment]
Please, open again the PR when you have a good solution for this.

**Pull request closed without merging**
