### PR TITLE
RSF-18; add dependences needed for rsf to build

### PR DESCRIPTION
**Pull request by clhedrick**
I need this for the rsf project to build. It's hard to believe others are seeing it, or we'd get complains about builds breaking. But if others are seeing problems building rsf, please accept this PR.

### CODE REVIEW

**Comment by ern** [comment]
Looks good though this issue should have been a SAK as these changes are in the sakai specific part of rsf.

**Comment by jonespm** [comment]
I'm not 100% sure how this was working either, but I think this property and these versions should all be moved up into dependencyManagement in master

**Comment by ern** [comment]
So these dependencies are isolated to just this project and there is no need for anyone to know these versions if your using the sakai-rsf artifacts which every tool does. That is whay the version is managed here and not from master.

**Comment by jonespm** [comment]
@ern I think the reason it's more helpful to have this property in master is when we actually go to release we have to change this from -SNAPSHOT to an actual released version. 

We *might* remember to change it in the sub-project but this is prone to error, and really we want to change these back to -SNAPSHOT after the release is done so it picks up the latest version of these libraries. I think the exception would be if it changes so infrequently that we don't ever have to use -SNAPSHOT and can always have a released version.

**Comment by clhedrick** [comment]
I don't care one way or the other, but this property doesn't necessarily change when a Sakai release is made. It's the RSF version, not the Sakai version. They're different. I assume that there's an intent to do an RSF release at the same time. When RSF releases, we'd want to change this dependency.

**Comment by ern** [comment]
Yeah I am fine with moving this up to master... It's only needed by the rsf project which is why it was added there. I like how the sakai rsf project hides this dependency.

The only time we would set this to a SNAPSHOT version is if someone was actually doing something in the rsf project (highly unlikely). The spring upgrade is an example but this version will probably stay fixed for a while now.

**Pull request merged**
