### PR TITLE
SAK-46341 Email remove actions only available to an admin user

### PR DESCRIPTION
**Pull request by victorfv2**

### CODE REVIEW

**Comment by ern** [comment]
@victorfv2 Fix email tool is a very uninformative description can you please update

**Comment by mpellicer** [comment]
Related to #9746 changes

**Comment by mpellicer** [comment]
@ern When are you planning to cut the branch? Thanks

**Review by ern — APPROVED** [review]

**Comment by ern** [comment]
Miguel this needs to be rebased as it can't fast forward

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
