### PR TITLE
S2U-21 Tests & Quizzes: Add new setting for SEB

### PR DESCRIPTION
**Pull request by mollerentornos**
Blocking ctrl+alt+del options by default

### CODE REVIEW

**Review by stetsche — CHANGES_REQUESTED** [review]
Well done @mollerentornos, looks pretty good! Only one minor thing, could you append `_KEY` to the constant and move it above `SEB_WEBVIEW_VERSION_KEY`, just for consistency?

**Comment by mollerentornos** [comment]
Uploaded changes, thanks you!

**Review by stetsche — APPROVED** [review]
Excellent!

**Comment by bgarciaentornos** [comment]
Cla submitted and pending for approval

**Comment by stetsche** [comment]
CLA signed!

**Pull request merged**
