### PR TITLE
Cafe

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Thanks for the cleanup Dave. I was wondering if we still wanted to support
cafe though?

sent from my mobile device

**Comment by axxter99** [comment]
-1

**Comment by ern** [comment]
I recall that cafe should be removed as it caused some confusion. Also with the removal of the indies and the move to a simpler build I think cafe has out-lived its usefulness?

**Comment by buckett** [comment]
If cafe works again and David's keeping it up to date I think it's worthwhile having.

It's useful to have a cutdown build that you can both deploy with and import into Eclipse so you don't see everything at once. It also helps us keep Sakai modular and think clearly about where responsibilities and functionality lies.

**Comment by steveswinsburg** [comment]
I might get shot for this but if we had working sets in Eclipse we could manage this a bit better without cafe. Eclipse doesnt grind to a halt anymore (hooray for Moore's law). That would require committing the .project files though I think.

Probably needs to go to core team if we want the cafe build back in.

**Comment by buckett** [comment]
:gun: :smile: 

How are you generating you .classpath/.project files @steveswinsburg?
m2eclipse plugin or mvn eclipse:eclipse?

**Comment by steveswinsburg** [comment]
I use mvn eclipse: eclipse. Sets it up really well.

sent from my mobile device

**Comment by ern** [comment]
Yeah we should never add IDE specific files to the code base!

I also use mvn eclipse:eclipse and import everything no issues.

**Pull request closed without merging**
