### PR TITLE
SAK-43199 Added toggle to switch graders

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-43199

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 12
           

Complexity increasing per file
==============================
- webcomponents/tool/src/main/frontend/grader/grader-toggle.js  2
- webcomponents/tool/src/main/frontend/sakai-view-preferences.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5039684&bid=16597704)

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 12
           

Complexity increasing per file
==============================
- webcomponents/tool/src/main/frontend/sakai-view-preferences.js  5
- webcomponents/tool/src/main/frontend/grader/grader-toggle.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5039684&bid=16597704)

**Comment by ern** [comment]
Wondering if this should've been part of the existing templates vs it's own web component? Do we plan to reuse this elsewhere?

**Comment by adrianfish** [comment]
We may well use it elsewhere, but initially, I was intending to show this in two places in Assignments, hence the component. At some point we'll be throwing this code away, at least for the grader, so I don't really care how we do it. In fact, I actually prefer it in the component, rather than polluting portal and assignments with throwaway stuff.

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 12
           

Complexity increasing per file
==============================
- webcomponents/tool/src/main/frontend/sakai-view-preferences.js  5
- webcomponents/tool/src/main/frontend/grader/grader-toggle.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=5039684&bid=16597704)

**Pull request merged**
