### PR TITLE
SAM-2582 - UI authorSettings.jsp and publishedSettings.jsp fixes for datepicker.

### PR DESCRIPTION
**Pull request by fgeraci**
This will effectively hide the datepicker on load and solve the icon-as-triggers problem.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Hi @fgeraci  can you put the JIRA number in the git commit?  And in the pull request title?

**Comment by fgeraci** [comment]
Hey Sam,

Ooops. On the road. I sure will as soon as I can.

Have a nice weekend.

Fernando

**Comment by ottenhoff** [comment]
Hi @fgeraci can you modify the commit to include the JIRA number?

**Comment by jmarianolujan** [comment]
Hi @fgeraci, during the last Sakai Core Team call, it was discussed that this pull request might no longer be relevant since the jira it was created for (SAM-2582) seems like a duplicate of (SAM-2607). Could you take a look at SAM-2607 and if you agree, close this PR or reimplement it for SAM-2607 which is OPEN.

SAM-2582 was addressing more than one problem, being one of them already resolved. That's the main reason why it was closed.

SAKAI CORE TEAM call: http://etherpad.ctools.org/p/rmmt-2015-09-29

**Comment by buckett** [comment]
Closing as there hasn't been any further discussion. If you feel this pull request is still needed please re-open it and explain what parts are still needed.

**Pull request closed without merging**
