### PR TITLE
SAK-31996: Hitting edit twice when list is loading can destroy a list

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by bjones86** [comment]
There is already a fancy JavaScript algorithm provided in reference to disable all controls on the page (including the button which was clicked) and overlay a spinner on the button itself.

I'd like to try to promote using the central approach for situations like this, so that all tools have a consistent look and feel.

You can find the file @ /reference/library/src/webabb/js/spinner.js. The file is commented/documented and fairly straight forward to use. I can provide assistance if you have questions.

**Comment by nicholaswilson100** [comment]
Sounds good to me

**Comment by nicholaswilson100** [comment]
Thanks @bjones86 much neater (and more centralised).

**Comment by bjones86** [comment]
Awesome, thanks @nicholaswilson100

**Pull request merged**
