### PR TITLE
SAK-44978: Error when modifying the final grades in ORACLE

### PR DESCRIPTION
**Pull request by victorGomollon**
When modifying the final grade of a user, it produces a null error in the "IS_EXCLUDED" field of the "GB_GRADING_EVENT_T" table in the ORACLE database.

### CODE REVIEW

**Comment by bjones86** [comment]
Does this happen because there's no default value specified for the `IS_EXCLUDED` field? If so, maybe adding the default would be a better approach?

**Comment by bjones86** [comment]
@victorGomollon does this error still happen after applying the conversion script @ https://github.com/sakaiproject/sakai-reference/pull/90 ?

**Comment by victorGomollon** [comment]
@bjones86 Although the default value is set to 0 in "IS_EXCLUDED", when we create the object from the java with the constructor, it assigns the attribute "status", the value null because we are using a constructor that does not initialize this value. Because of this, in the oracle DBs (like ours), the following error was occurring:
`25-ene-2021 13:46:48.736 ERROR [ajp-nio-127.0.0.1-8014-exec-5] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions ORA-01400: no se puede realizar una inserciÃ³n NULL en ("SAKAI_PR"."GB_GRADING_EVENT_T"."IS_EXCLUDED")25-ene-2021 13:46:48.738 ERROR [ajp-nio-127.0.0.1-8014-exec-5] org.sakaiproject.gradebookng.business.GradebookNgBusinessService.updateCourseGrade An error occurred saving the course grade. class org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

**Comment by bjones86** [comment]
Ah, I see. So perhaps rather than changing the constructor that is called, there should be a fix applied to the other constructor?

**Comment by victorGomollon** [comment]
Yes, it can be applied without problems. It would be enough to set in the other constructor this attribute with its default value, just as it is done in the constructor that is used now. Even so, we have not seen it necessary, since at the moment the constructor by defect was only being used in this case to then set one by one the parameters, when it is better to delegate this function directly to the constructor as we are doing at the moment with this change.

**Comment by bjones86** [comment]
I see your point, but leaving the problem in the other constructor allows for future mistakes if other programmers start using it.

**Review by bjones86 — CHANGES_REQUESTED** [review]
Please fix the issue in the original constructor.

**Review by bjones86 — APPROVED** [review]
Thanks, @victorGomollon!

**Pull request merged**
