### PR TITLE
SAK-30064: AnnouncementComparator is not transitive, can throw error …

### PR DESCRIPTION
**Pull request by cschauer**
…with TimSort

### CODE REVIEW

**Comment by cschauer** [comment]
Needs to return 0 if the two items are equal

**Comment by buckett** [comment]
It's really good when changes like this include a Test to show the error. Also you're comment in the pull request is really useful, but it won't easily be found when someone looks at the code in a year's time. Putting things like that in the commit comment makes it much more likely the next programmer can understand the change you were making.

**Comment by cschauer** [comment]
I updated the commit message. Unfortunately the AnnouncementComparator is a private inner class of AnnouncementAction. I wasn't sure of any way to add a test for it.

We discovered the problem when a user imported the same announcement from a site multiple times. This resulted in multiple announcements with the same date and the sort threw an "IllegalArgumentException: Comparison method violates its general contract!"

**Comment by ern** [comment]
I understand you tried to keep this change small but as you mentioned AnnouncementComparator is just not ideal in its current form.

I believe it was implemented this way because it sought to encapsulate this logic to the parent class  AnnouncementAction, since it makes use of its member variables.

At this point to avoid redesigning it probably makes sense to add a method to the outer class providing access to AnnouncementComparator so that it may be tested then look at moving references to using this method.

This type of change would continue to provide the encapsulation but provide a more well defined use from the outer class AnnouncementAction and allow for testing.

**Comment by ncaidin** [comment]
Thanks for all the contributions @cschauer  and your icla as well, which is now on file.

**Pull request closed without merging**
