### PR TITLE
SAK-47716 assignments: add user photos on grading page

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-47716

### CODE REVIEW

**Comment by adrianfish** [comment]
Screenshot 2022-08-24 at 17 52 03
Screenshot 2022-08-24 at 17 52 12
 
Screenshot 2022-08-24 at 17 52 18
Screenshot 2022-08-24 at 17 52 35

**Comment by mpellicer** [comment]
I'm sure you're not kidding me, right @adrianfish ? Did you assign this to me by mistake or what is the reason? Thanks, just asking because I don't know where we are.

**Comment by adrianfish** [comment]
Not a mistake. You were just first in the list, probably because you've reviewed stuff like this before.

**Comment by mpellicer** [comment]
Ahh that makes sense, thanks for clarifying @adrianfish.

Unfortunatelly, I'm going to decline the invitation, I love reviewing PRs and participating into discussions, but this specific development is involved in some controversy and I'm not good with it, sorry for that.

Good job btw, looks like a cool feature.

**Comment by adrianfish** [comment]
Understood. I've requested a review from Sam.

**Review by ern — APPROVED** [review]

**Pull request merged**
