### PR TITLE
SAK-43155 Assignments Work Log Feature

### PR DESCRIPTION
**Pull request by jorgecanovas**
Original branch and details: [https://github.com/sakaiproject/sakai/pull/8996](https://github.com/sakaiproject/sakai/pull/8996)
SAK: [43155](https://jira.sakaiproject.org/browse/SAK-43155?focusedCommentId=257951&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-257951)

### CODE REVIEW

**Review by mpellicer — APPROVED** [review]
For me this has been a great piece of work and it had super active support for all the comments and concerns during the past months, it's been a very long PR and the contributors may provide early life support for it, they are also using it in production.

For me is a clear go but I'll leave the decisions to other actors.

Thank you so much for the great work @jorgecanovas, don't give up, never surrender.

**Comment by csev** [comment]
How close is this to being merged?   My work in #9769 touches some of the same files as this  PR.  I think my PR should be ready to merge in 3-5 days.  I can go in any order.   I am just curious as to the readiness of this PR so I can plan.

**Review by ern — CHANGES_REQUESTED** [review]
I will being reviewing this today, just tagging this until I have reviewed it.

**Comment by SedueRey** [comment]
@csev I would prefer you to wait until @ern ends with the review, another rebase for another PR would be ... painful.

**Comment by ern** [comment]
Yeah I've got some changes coming for this.

**Comment by ern** [comment]
I've refactored this to match the patterns that are being used in assignments.

@jorgecanovas @SedueRey can you review?

**Comment by SedueRey** [comment]
@ern sure, we'll test it in our local. Thanks!

**Review by ern — APPROVED** [review]
There could be some more improvements but they could be added later.

**Pull request merged**
