### PR TITLE
S2U-18 SAK-49622 T&Q Fix question pool item sorting - s2u-22x

### PR DESCRIPTION
**Pull request by stetsche**
https://sakaiproject.atlassian.net/browse/SAK-49622

### CODE REVIEW

**Comment by jesusmmp** [comment]
Let me test this patch before merge. Thanks @stetsche!

**Comment by mpellicer** [comment]
Please add S2U-18 to the PR and the commit title.

**Review by jesusmmp — APPROVED** [review]
Just tested!

**Comment by stetsche** [comment]
Great @jesusmmp, thanks!

**Pull request merged**
