### PR TITLE
SAK-41750 Sitestats: fix report NPE (who -> custom)

### PR DESCRIPTION
**Pull request by bgarciaentornos**
Just removing the initial check for null, the other changes are just indentation.

### CODE REVIEW

**Comment by bgarciaentornos** [comment]
Yep, I took that into account, both things work.

**Comment by mpellicer** [comment]
So it was caused by #6655?

**Comment by bgarciaentornos** [comment]
Yes, I linked both jiras.

**Comment by mpellicer** [comment]
Thanks, awesome work @bgarciaentornos

**Pull request merged**
