### PR TITLE
SAK-41954 Update templates in CKEditor

### PR DESCRIPTION
**Pull request by davidpbauer**
This change updates the templates in the CKEditor, removes the old tempaltes,
turns on bootstrap styling in the editor, and makes the Templates label on
the button visible.

### CODE REVIEW

**Comment by ern** [comment]
We could use a README in the templates area with some useful information about these new templates.

**Comment by davidpbauer** [comment]
I've added a README that explains the change and provides users with the previous version of the templates. Let me know if there is anything else.

**Comment by ottenhoff** [comment]
Thanks for the PR. Any thoughts on using Bootstrap simple grid vs custom grid? Advantage of Bootstrap grid in my mind is simplicity of the HTML

**Comment by davidpbauer** [comment]
Hey Sam. One of our instructional designers wrote the actual templates, so I'm not sure if the Bootstrap grid wasn't used because he wasn't aware of it or if it was because he was going for some very specific styling that didn't work with the Bootstrap defaults.

I'm always in favor of simpler HTML and using the CSS classes/components that already exist in Bootstrap. So, I can either pass this back to our ID and see what he thinks or just keep it as is for now. Let me know which you'd prefer.

**Comment by lgekeler** [comment]
@ottenhoff @ern  There's a tst failing on accessibility and a question from David on grid classes. Functionals would love to see this in 20.

**Comment by ottenhoff** [comment]
It would be good to hear from your ID

**Comment by davidpbauer** [comment]
I believe the accessibility checker is yelling about missing alt text from the images, but they are just placeholders and need to be replaced with real images by the instructor anyway. We can add some placeholder alt text if needed.

I spoke with Paul Dagnall about the templates he created and he said that he wrote them with the custom html/css because he wanted a specific style that the Bootstrap grid wouldn't cooperate with. However, he offered to revisit them and rewrite them. Below is a screenshot with the "insight" template that doesn't work as well in a Bootstrap grid.

Do we want to merge this pull request and open a new one with updates to the templates once he has time to work on it or should this just remain open and in limbo until then?

image

**Comment by ottenhoff** [comment]
Let's add dummy alt text and then merge in .....

**Comment by davidpbauer** [comment]
I just realized the images without alt text are in the README.md file and are just a copy-pasted record of the old templates in case someone wanted to put them back. All of the images in the new templates are fine.

**Pull request merged**
