### PR TITLE
SAK-43357 allow rubrics component to save evaluations

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-43357

### CODE REVIEW

**Comment by adrianfish** [comment]
This needs testing via pulling the change and trying it out. It's rubrics ...

**Comment by mpellicer** [comment]
Tested locally, after grading using a rubric, adding comments, and attaching files, the rubric values are persisted.
image

However, I found some Javascript errors while editing comments:
video


I think the values are saved despite the errors.

**Comment by adrianfish** [comment]
That ckeditor error exists in master already. It needs fixing, but is not a critical and should be in another jira.

**Comment by mpellicer** [comment]
Well, I tested the changes and they worked for me, thanks @adrianfish

**Pull request merged**
