### PR TITLE
SAK-31803 - JobScheduler. Trigger help link throws 404

### PR DESCRIPTION
**Pull request by mpellicer**
SAK-31803 - JobScheduler. Trigger help link throws 404

### CODE REVIEW

**Comment by jonespm** [comment]
We actually created a help guide for this in the local help file for Sakai. The link should be updated to that, I thought I already created a jira to do that.

/portal/help/TOCDisplay/content.hlp?docId=howdoicreatecronexpressions

**Comment by mpellicer** [comment]
@jonespm 

I made a search before the PR and that link was up to date, only the UI needed an update.

**Comment by jonespm** [comment]
I'm just saying we added this actual content to the local Sakai help in 11 so if/when the link does change it's always right there and won't need updating. It seems better to use a local link to the help rather than a remote since this link has changed 2-3 times.

**Comment by mpellicer** [comment]
Ahh good

**Pull request merged**
