### PR TITLE
KNL-1381 set connection to ReadOnly=true when doing a dbRead so we ca…

### PR DESCRIPTION
**Pull request by ottenhoff**
…n make use of slave database connections

### CODE REVIEW

**Comment by ottenhoff** [comment]
@buckett thoughts on this modification? The goal is to allow use of slave servers to boost performance.

**Comment by buckett** [comment]
As I understand it replication between Master and Slave is asynchronous and this is just marking an individual statement as read-only so we may get into the situation where a transaction is started, a site is written to the DB (master), then it is read back (slave) but it hasn't yet been replicated so isn't found.

I'm not saying that this shouldn't get merged, just that it may well end up with rather obscure bugs which will be rather hard to track down and fix.

I think the safer way to approach this would be to use the slaves initially for everything and then when a request/transaction attempts a modification it switches to the master and continues to use the master until the request/transaction is complete.

It would be easier to address if Sakai had a more consistent way to manage it's transactions.

**Comment by ottenhoff** [comment]
> As I understand it replication between Master and Slave is asynchronous 

> As I understand it replication between Master and Slave is asynchronous 

It typically happens as quickly as the binlog can be written/read. In my experience, the lag is usually no more than 1 second for a typical cluster.

>  so we may get into the situation where a transaction is started, a site is
> written to the DB (master), then it is read back (slave) but it hasn't yet been 
> replicated so isn't found.

This is definitely a risk of using a master/slave setup.

> I think the safer way to approach this would be to use the slaves initially
> for everything and then when a request/transaction attempts a modification 
> it switches to the master and continues to use the master until the request/transaction is complete.

But then we would have to manage slaves and masters in Sakai. I'm not really interested in managing this within Sakai. I want to let the Maria JDBC connector handle these scenarios. But there is no purpose in having a read-only slave unless you tell the JDBC connector that a query is ReadOnly.

**Comment by buckett** [comment]
>
> so we may get into the situation where a transaction is started, a site is
> written to the DB (master), then it is read back (slave) but it hasn't yet
> been
> replicated so isn't found.
>
> This is definitely a risk of using a master/slave setup.
>
I think this is fine when a different user doesn't get the latest value,
what I was concerned about is where there's some code todo an update that
then reads back the values it's just written in the same request. There
have been issues in the past where code only worked when the caches were
enabled and I think this maybe a similar case.

> I think the safer way to approach this would be to use the slaves initially
> for everything and then when a request/transaction attempts a modification
> it switches to the master and continues to use the master until the
> request/transaction is complete.
>
> But then we would have to manage slaves and masters in Sakai.
>
I wasn't suggesting going that far, just that once a request had used a
connection to write changes to the DB it didn't switch back to the slave
until that transaction/request was over. We could control this switching by
not marking the connection as read-only again until the transaction is
complete (maybe threadlocal).

> I'm not really interested in managing this within Sakai. I want to let the
> Maria JDBC connector handle these scenarios. But there is no purpose in
> having a read-only slave unless you tell the JDBC connector that a query is
> ReadOnly.
>
Yep we want to let Maria DB connector do as much of the work as possible.
I'm not saying that this shouldn't be done, I'm just not convinced that we
can just apply this change and know that it's safe to run with the Maria DB
connector passing all read only requests to a slave DB.

I'm not objecting to this going in at all as for people running in normal
setups it shouldn't affect anything at all just passing comments.

-- 
  Matthew Buckett

**Comment by ottenhoff** [comment]
I agree that this may not mean you can safely run with master/slave both on the connection string ..... but it's a start down that road.....

**Pull request closed without merging**
