### PR TITLE
SAK-40800 add acceptance tests project

### PR DESCRIPTION
**Pull request by steveswinsburg**
This has been sitting in a branch for a while and there are people that want to work on it. This has no functional impact on Sakai but I would like to have this in master so that it is easier for people to contribute to.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
This is likely to need some updates (still on 19-SNAPSHOT) but I'm happy to do that so let me what what you pickup.

**Comment by ern** [comment]
Stave does it not make sense to create a separate repo? One benefit would be that QA can have write access to manage the test scripts? I will add this as a discussion item to an upcoming core call.

**Comment by ern** [comment]
Discussed on the core call and everyone was in agreement about moving this into its own repo that is managed by QA. Thoughts Steve?

**Comment by jonespm** [comment]
Maybe create it as a separate repo and add it into sakai as a submodule. Then others can contribute but it will still appear in the main repo.

The only negative would be that someone would have to clone with `--recurse-submodules` or `submodule init `

**Comment by steveswinsburg** [comment]
I don't like it as a separate repo and haven't ever seen it setup this way. The core idea is that developers write feature files as they write features. If you move it to a separate repo then developers will never contribute and it will be left to QA to handle entirely, and it will get out of sync again.
This way the code and features get versioned together and it is simpler to create a PR that adds feature to project X and a corresponding feature file.
Plenty of discussion about this on the net where other devs express their POV. The main takeaway from all of that is keeping it simple and adding complexity later if required.

So IMO this should stay in the main repo until the need arises that it moves. QA would still be sending PRs either way right?

**Comment by jonespm** [comment]
Well I'd be up for seeing how it goes. It's pretty self contained so easy to change if that was the issue. I'd like to see this hooked up to Travis so that developers actually run and notice that something is going wrong. Maybe based on these instructions? This could be in a new issue. https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by adrianfish** [comment]
We don't really have any process developed with QA around automated testing - it's all in flux at the moment. We've discussed this on the core call few times now and it's been unanimous that we put this into a repo other then core, then bring it in when the process has matured a bit.

**Comment by ern** [comment]
I understand everything you have linked and are saying.

Here is what I am suggesting before this goes into master:
- we need the appropriate infrastructure setup
- QA needs to understand how to use this
- workflows in JIRA and such need to be established and followed (by Devs and QA)
- we all need some experience with XBDD

Your arguments suggest that were disagreeing with you, when this is not the case. Simply we want to see this all in action before adding it to master is all.

So setting this up in a separate repo and getting all the pieces lined up and working and once everyone has a little more experience with how this all works then we consider moving it to the sakai repo.

It just doesn't make any sense putting this into master with no support or process around it.

**Comment by ern** [comment]
Closing this per Steve

**Pull request closed without merging**
