### PR TITLE
SAK-47738 Library tests & quizzes poor color contrast of print assess…

### PR DESCRIPTION
**Pull request by Sharadhi98**
…ment

### CODE REVIEW

**Comment by ottenhoff** [comment]
This doesn't look right to me. Why is the portal dark/light relevant here?

**Comment by Sharadhi98** [comment]
It's relevant because the color needs to change based on the light or dark theme chosen by the user in Sakai. The ticket also requires checking the color contrast for both themes.

**Comment by ottenhoff** [comment]
but printing is always done on a white background. i dont get it. i submitted a different PR

**Comment by ern** [comment]
Closing this PR as were accepting #12977 which solves the same issue

**Pull request closed without merging**
