### PR TITLE
SAK-50010 Rubrics: Reset criterion comments per student esp. for Grader

### PR DESCRIPTION
**Pull request by hornersa**
Jira: https://sakaiproject.atlassian.net/browse/SAK-50010

There's an unfortunate downside with the proposed solution that I demo in a screencast attached to the jira linked above: a visible "glitching" that occurs anytime a criterion comment popover is opened. That said, the proposed fix should pass the test plan.

Note that as of this writing, I'll be away for about a week and a half (returning mid-July). In the meantime, please feel free to revise this PR with other commits to resolve this jira whose priority is Critical/Blocker. Nevertheless, I hope the proposed solution is at least in the right direction for getting this issue resolved soon.

### CODE REVIEW

**Comment by adrianfish** [comment]
@hornersa Hi Sean, I've opened another PR (https://github.com/sakaiproject/sakai/pull/12719) addressing this issue. The problem seemed to be that lit was not updating the textarea's value as you moved between users. So .. ahem .. my pr explicitly does that in the updated() callback. I've also moved to using dropdowns instead of popovers. They are more accessible. So, we have a choice between two approaches between our two prs.

**Comment by hornersa** [comment]
@adrianfish - I did some test driving of PR (https://github.com/sakaiproject/sakai/pull/12719). I think it's in the right direction. That said, there are some regressions I observed which I demo in the screencast, AF-ProposalConcerns-20240710.mp4, attached to https://sakaiproject.atlassian.net/browse/SAK-50010. The most serious ones are in Gradebook.

**Comment by hornersa** [comment]
Closing a rubric comment when grading with the Assignments legacy grader refreshes the page. A similar regression to the behavior in Gradebook except there's no javascript prompt. You'll likely also want to test drive your solution by grading in the Discussions tool, perhaps with the test plan in https://sakaiproject.atlassian.net/browse/SAK-50004.

**Comment by adrianfish** [comment]
@hornersa Thanks for doing that testing, very helpful. I'll replicate your results and get it fixed. Nice spot :)

**Comment by adrianfish** [comment]
@hornersa Fixed the case with gradebook, and I also tested with Samigo, which worked fine.

**Comment by hornersa** [comment]
I'm closing this PR as it should be supplanted by PR (https://github.com/sakaiproject/sakai/pull/12719).

**Pull request closed without merging**
