### PR TITLE
SAK-31851 - REGRESSION - When using the link from 'Copy link' in forums, you are …

### PR DESCRIPTION
**Pull request by juanjmerono**
…not redirected to the specific conversation

### CODE REVIEW

**Comment by ern** [comment]
This change looks fine but if your looking for a link to a specific post, the entity reference would probably make more sense.

**Comment by juanjmerono** [comment]
Lessons use a link like this: /direct/forum_topic/<topic-id>
But this link goes to the topic level not the message level. I think it makes no sense that the "copy link" button at message level gives you a link that redirect you to the topic level, also the link access to the tool without the portal (lessons use this link inside an iframe), so that's why I used the other link. I don't know if there is another direct link to the message.

**Comment by jonespm** [comment]
Yeah /direct/forum_message ? Though it *looks* like only the old picker actually used this.

**Comment by juanjmerono** [comment]
/direct/forum_message/<message-id> it's not working for me.
/direct/forum_message/topic/<message-id> works but is returning raw information about the message not redirecting to the html view like /direct/forum_topic does 😞

**Comment by ern** [comment]
Yeah if you can't get what you need then I think what you have here is fine.

**Comment by juanjmerono** [comment]
I didn't find anything better, I'm still wondering why /direct/forum_message/<message-id> is returning 404 but I don't have time to dig into it :(

**Comment by jonespm** [comment]
Yeah looks to me like in ForumMessageEntityProviderImpl it's just not fully implemented. This seems fine. Thanks.

**Pull request merged**
