### PR TITLE
SAK-29354 Add job to backfill a tool into sites.

### PR DESCRIPTION
**Pull request by buckett**
This quartz job allows you to add a specific tool ID to to a selected set of sites, if the tool already exists in the site then it isn’t added.

### CODE REVIEW

**Comment by baholladay** [comment]
You should use the site service paging for getting all sites so that large institutions can run this job.

PagingPosition pp = new PagingPosition(page, pageMax);
List<String> siteIds = siteService.getSiteIds(SiteService.SelectionType.ANY, type, null, null, SiteService.SortType.NONE, pp);

**Comment by buckett** [comment]
We're just talking about a list of IDs here, not full Site objects, it's a one off job.

UUID is 36 bytes * 100000 sites / 1000000 (to MB) = 3.6MB

Plus overheads for the List (Vector in this case). Have you seen problems retrieving all the site IDs in one go?

**Comment by baholladay** [comment]
Good point, it may not be needed for just the IDs. It'd be interesting to see what the performance is for large sets of site ids. Hopefully the API is efficient and not grabbing more than just the IDs behind the scenes.

**Comment by ern** [comment]
I think this is fine as sites are lazily loaded, for example if you need the entire Site data to be loaded you would need to call Site.loadAll().

**Comment by buckett** [comment]
I had a quick look and it seems it only selects/reads the IDs. We've loaded all our sites locally (81k) without any problems.

For handling things like this it would be better if the SiteService API had a method that accepted a `java.util.function.Consumer` that way we don't have to worry about connections leaking but can allow people to process the results as they come back from the DB.

**Pull request merged**
