### PR TITLE
SAK-46028 site info > sort section sets alphabetically

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-46028

The UI to select rosters has a sorting issue: the sections within each set are sorted, but the sets themselves are not. Instead, they appear in the order they are retrieved from the database. Example screenshot can be seen on the JIRA ticket.

This PR sorts the sets alphabetically. It also addresses an issue in the Add Roster UI, where the drop down produces two spinners (one on the drop down itself, and one beside it), by retaining only the overlay spinner.

### CODE REVIEW

**Review by ottenhoff — APPROVED** [review]
looks good. case sensitive or String.CASE_INSENSITIVE_ORDER ?

**Comment by bjones86** [comment]
As it is now it's case sensitive. Sound appropriate?

**Comment by ottenhoff** [comment]
Unfortunately it's more complex! Check out SAK-45025 (7bd3f7d53cd684381a2f58deb45541a1f8b5fb5f)

`new AlphaNumericComparator().compare(factor1, factor2);`

* Group 1
* Group 2
* Group 10
* Group 11

**Comment by bjones86** [comment]
Cool, wasn't aware of that.

**Review by ottenhoff — APPROVED** [review]

**Pull request merged**
