### PR TITLE
SAK-32214 Be able to expand folders and copy to/from other sites in m…

### PR DESCRIPTION
**Pull request by juanjmerono**
…obile view

### CODE REVIEW

**Comment by ottenhoff** [comment]
Why is this a good change? 

The user is on a tiny device and these advanced options are being hidden from the user to create an easier-to-use interface?

**Comment by juanjmerono** [comment]
I don't know if is good or not use a mobile to manage resources, but in case you want to copy a file in the same site (forget about copy from other sites) from: /folderx/foldery/ to /foldera/folderb/ you can do it easily in desktop (expanding folders, just 3 clicks select, copy and paste), but in mobile you need to access folderx, then foldery, click copy, the return to home, access foldera, then folderb and finally paste, I guess this should be easier to do. Anyway I'm open to suggestions or even close this PR, it is not critical at all.

**Comment by lardo-de-arnaud** [comment]
i'd support this, people complain here that clicking on the + in a folder doesnt expand the folder. We also want to be able to copy from other sites. https://jira.sakaiproject.org/browse/SAK-31800

**Comment by ern** [comment]
Screenshots?

**Comment by RebeccaOxfordUni** [comment]
Juanjo - I've changed SAK-31800 so that the Copy Content option is shown on a tablet sized screen (as well as desktop) but not on a mobile.  My Jira includes one of the changes you made on this Jira (the <tr class="hidden-xs hidden-sm"> change) so perhaps you can remove it from here.  From Adam's comment above we would like your 'expand folders' change for a tablet sized screen, perhaps Sam @ottenhoff would like to comment about the 'expand folders' change for a tablet?

**Comment by jonespm** [comment]
Closed this in favor of #4042 that just shows it in sm not xs

**Pull request closed without merging**
