### PR TITLE
SAK-42686 - Edge: Error saving T&Q responses for other questions afte…

### PR DESCRIPTION
**Pull request by mpellicer**
…r numeric validation failure

### CODE REVIEW

**Comment by smarquard** [comment]
Using Edge, with this patch it no longer sends the invalid value to the backend, but I find the behaviour a little confusing from a UX point of view.

If you're on Q1 with one-question-per-page and you fill in an invalid question then click Next, you get the popup but in the background Q1 is being submitted (blank) and you're moved on to Q2, so when you dismiss the popup, you're now on a different question (and may not realise that).

And the behaviour between Chrome and Edge is still different: in Chrome, you don't move on to the next question.

**Comment by smarquard** [comment]
Also in Chrome, if I enter an invalid value and then do nothing (don't change focus, don't click elsewhere), when the autosave runs it still submits the invalid value:

````
2019-10-25 15:39:20,047  INFO ajp-nio-8009-exec-5 org.sakaiproject.tool.assessment.services.GradingService - storeGrades userid=94f00f3b-b9d5-41ca-b340-5a2d2ca6ff51 publishedAssessmentId=81790 itemGrading size=1 publishedItemHash size=2
2019-10-25 15:39:20,066  WARN ajp-nio-8009-exec-5 org.sakaiproject.tool.assessment.services.GradingService - Fin Format Exception while processing response.
org.sakaiproject.tool.assessment.services.FinFormatException: Not a valid FIN Input. studentanswer=23andme
        at org.sakaiproject.tool.assessment.services.GradingService.validate(GradingService.java:2117)
        at org.sakaiproject.tool.assessment.services.GradingService.getFINResult(GradingService.java:1998)
        at org.sakaiproject.tool.assessment.services.GradingService.getFINScore(GradingService.java:1902)
        at org.sakaiproject.tool.assessment.services.GradingService.getScoreByQuestionType(GradingService.java:1414)
        at org.sakaiproject.tool.assessment.services.GradingService.storeGrades(GradingService.java:994)
        at org.sakaiproject.tool.assessment.services.GradingService.storeGrades(GradingService.java:840)
        at org.sakaiproject.tool.assessment.ui.listener.delivery.SubmitToGradingActionListener.persistAssessmentGrading(SubmitToGradingActionListener.java:492)
        at org.sakaiproject.tool.assessment.ui.listener.delivery.SubmitToGradingActionListener.submitToGradingService(SubmitToGradingActionListener.java:327)
        at org.sakaiproject.tool.assessment.ui.listener.delivery.SubmitToGradingActionListener.processAction(SubmitToGradingActionListener.java:134)
        at org.sakaiproject.tool.assessment.ui.bean.delivery.DeliveryBean.save_work(DeliveryBean.java:2034)
        at org.sakaiproject.tool.assessment.ui.bean.delivery.DeliveryBean.auto_save(DeliveryBean.java:2013)
````

**Comment by smarquard** [comment]
To test the autosave behaviour, set a low value in sakai.properties, e.g. every 15s:

samigo.autoSave.repeat.milliseconds=15000

**Comment by mpellicer** [comment]
Thanks for the information @smarquard, 

About the autosave event, I'm able to reproduce the problem, I've implemented changes when autosaving to validate all the FIN inputs before sending them to the server.

About the new behavior introduced, I agree, I find it confusing too, but I don't think is a good idea to abort the submission when you click next, previous, submit for grading, autosave or auto-submit, I think we should just wipe the incorrect value and ensure the complete exam is submitted, despite this behavior, now works way better than the existing logic.

**Comment by mpellicer** [comment]
@smarquard I'm not happy 100% with the implementation and how it works, I'd like to accept suggestions from anyone. Despite it's approved, I'm going to wait for feedback before merging it....

**Comment by smarquard** [comment]
I'm guessing the difference between Chrome and Edge is that in Chrome when you click Next button it is explicitly changing the focus away from the input field and see you get the alert from that, whereas in Edge you can click Next to submit the form without a loss-of-focus event?

**Comment by mpellicer** [comment]
Exactly, I've tested in Firefox and works like Edge, it does the submission despite the validation (But the value is wiped before submitting it to the server which is good).

**Comment by mpellicer** [comment]
@smarquard , thoughts on this?

This version of the PR resolves most cases, however, the behavior in Edge and Firefox is pretty annoying,  the user can click on Next - Previous and Submit grading, if the FIN value is incorrect the action is performed and the value is not sent to the server, displaying an alert to the user.

**Comment by smarquard** [comment]
@mpellicer I think it's an improvement, but still not ideal. For example if you set linear navigation in settings, then you're not allowed to return to a previous question, so you could enter an invalid response, click Next, and you move on to the next question with no ability to fix the issue.

I think the best solution would be to cancel user-initiated navigation actions (Previous, Next, Save, Submit for Grading) if there's a validation error (so make the Edge/FF behaviour consistent with Chrome), but clear and submit for auto-save or auto-submit actions.

**Comment by mpellicer** [comment]
@smarquard, completely agree, is a bit confusing but is the best I can do with the existing implementation, there is many JS logic linked to those actions spread in several files, and we should support autosave, auto-submit and user actions, this approach supports all of them.

This behavior is weird but may resolve more than 90% of the cases with these questions and it's safe in terms of user navigation in Samigo which is easily breakable, and the user is always informed by a popover and an alert window.

About tour concerns:

- You're right, there are eleven navigation buttons! Added the missing ones.
- Quite confusing, agree, the user needs to focus on a different element to re-enable the buttons, but is always informed by the popover.
- Auto-save wipes the incorrect value and needs to re-enable the buttons because an empty value is correct, then the user is informed, if enters an invalid value and click Next/save the validator will wipe the value and inform the user, but will perform the action. This is a really cutting-edge situation because the user is always informed.

**Comment by mpellicer** [comment]
I've merged it, this resolves many cases and I'm open to continue improving the behavior.

**Pull request merged**
