### PR TITLE
SAK-48849 Lessons: Edit embedded multimedia was opening the wrong dialog

### PR DESCRIPTION
**Pull request by davidpbauer**
The switch to BS 5 changed the edit link next to an embedded image from opening the multimedia dialog to opening the movie dialog, which broke everything. The link was labeled wrong previously, which was probably why it was accidentally switched.

### CODE REVIEW

**Comment by jonespm** [comment]
Thanks @davidpbauer. Awesome if this is all it was! I'll test this out tonight.

**Comment by jonespm** [comment]
Okay this fixes almost everything. The "Change File or URL" link does nothing. But everything else including groups, pre-reqs and visibility is working now.

**Review by jonespm — APPROVED** [review]
Approving since it fixes many of the problems of this dialog. The link to change media should be either fixed or opened as a new issue as that isn't working.

**Comment by davidpbauer** [comment]
The "Change File or URL" link should be working again. It needed some extra nonsense to work with the new bootstrap dialogs. In my testing, I found that changing the image out for a new one loses the group release information, but I confirmed that's existing behavior in Sakai 22.

**Comment by jonespm** [comment]
Okay, everything on it looks good to me. Going to merge this.

**Review by jonespm — APPROVED** [review]

**Pull request merged**
