### PR TITLE
SAK-29896 Upgrade to newer Sakai Maven plugin.

### PR DESCRIPTION
**Pull request by buckett**

### CODE REVIEW

**Comment by buckett** [comment]
Don't merge this just yet as the nightly servers will need updating to no longer have custom catalina.properties.

**Comment by buckett** [comment]
Actually, they probably should work fine, as the extra folders added to the classloaders will all be empty, but once working fine, we should cleanup the nightly servers.

**Comment by jonespm** [comment]
Yeah, nightly servers should be fine, they clean up all the folders nightly.

I'd modify the pack-demo for this at https://github.com/sakaiproject/sakai/blob/master/pack/pack-demo/build.xml

Around line 204 it modifies the catalina.properties.

**Comment by buckett** [comment]
Thanks @jonespm, fixed up.

**Pull request merged**
