### PR TITLE
SAK-29540 Improve discoverability of To and BCC name lookup in Messages tool

### PR DESCRIPTION
**Pull request by whumph**
Improve discoverability of To and BCC name lookup in Messages tool.

Update select2 to 4.0.0
Add pull-down icon to To and Bcc boxes
Add placeholder text to To and BCC text boxes when no users have been chosen

### CODE REVIEW

**Comment by bjones86** [comment]
Can you please ammend and/or squash your commits to prefix with SAK-29540.

Instructions and Sakai-Github workflow can be found @ https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup

**Comment by whumph** [comment]
OK, done.

**Comment by ottenhoff** [comment]
It's certainly not a Sakai requirement, but my preference for libs like this is to put them into reference/library/src/webapp to at least encourage the idea of re-use and using the same version of a lib as other tools.....

**Comment by whumph** [comment]
OK, select2 is moved into reference/library/src/webapp/js/jquery/select2/4.0.0 . I moved the tweak to select2.css into a css file specific to msgcntr.

**Comment by ottenhoff** [comment]
Nice. LGTM

**Pull request merged**
