### PR TITLE
SAK-47320 Lessons double/multi click reorder save button may cause infinite loop

### PR DESCRIPTION
**Pull request by austin48**
https://sakaiproject.atlassian.net/browse/SAK-47320

### CODE REVIEW

**Comment by austin48** [comment]
I tried disabling the original save button, but after the submit it didn't seem to complete the save, so I had to change the submit button to hidden and create a new "button" to trigger the submit.

**Review by bjones86 — APPROVED** [review]

**Comment by austin48** [comment]
Hello @bjones86, thanks for approving the PR.  But do you know what the Cypress error is about?

**Comment by bjones86** [comment]
Looks unrelated to the changes here (asignments, rubrics, samigo). Likely just fallout from the big refactors that have taken place lately.

**Comment by austin48** [comment]
ok, thanks!

**Pull request merged**
