### PR TITLE
SAK-32233 Merge velocity admin tools together.

### PR DESCRIPTION
**Pull request by buckett**
This means we just have less projects in the IDE and similar tools are together as there is very little value in having separate projects for each tool.

### CODE REVIEW

**Comment by ern** [comment]
We may need some db scripts since message bundle names are changing for those using the message bundle manager. Or we need to at a minimum need to have some notes in the release documentation about this.

**Comment by ottenhoff** [comment]
Rebase and then a merge?

**Comment by buckett** [comment]
Rebased.

**Comment by buckett** [comment]
Apart from the authz helper these are really all admin tools so although it would be nice to move the i18n changes in the DB I'm not sure it's worth the effort.

**Pull request merged**
