### PR TITLE
SAK-42814 Signup: Previous title pre-filled when adding new event

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by mpellicer** [comment]
Just a pattern I adopted, use a constant instead of "".

Let me update the PR, not a big deal.

**Comment by mpellicer** [comment]
While the discussion is open, I've reverted to use the constant.

**Comment by jonespm** [comment]
Yeah was just thinking about it is all. I feel like even just using new String() as an initial value is more readable than using this constant, just like

`this.customLocation = new String();`

This has been [tested to create an empty string.](https://stackoverflow.com/q/2812674/3708872) and to me is easier to read, internal to java and follows typical patterns.

**Comment by mpellicer** [comment]
I like that @jonespm, let's use that pattern.

**Comment by adrianfish** [comment]
I like the self documenting nature of the constant - the intent's really clear. It's never meant to be anything other than an empty string. I do agree that we should try and use Optional in cases like these though, in the receiver, if the problem being addressed is a potential NPE. Optional should be spreading through Sakai like the bubonic plague through a rural 14thC town.

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakai/sakai/pullRequest?prid=4559950&bid=15334892)

**Comment by ern** [comment]
Be nice if this class used lomboks @Data, probably have more than 50% reduction!

Opened #7656 which additionally has the cleanup.

**Pull request closed without merging**
