### PR TITLE
SAK-31192 - include conversion for SAM-1200 to 11.x scripts

### PR DESCRIPTION
**Pull request by curtisvo**
I tracked down some problems we were having with Samigo in 11.x to some missing database conversions.

### CODE REVIEW

**Comment by jonespm** [comment]
I believe that the process of moving all conversions that are required from the 12 scripts to the 11 scripts hasn't entirely happened. I don't think we should just do one offs like this, and even in this case, it will need to be removed from the 12 scripts.

I feel like there are a few changes out of sync right now wrt conversion scripts and I don't think anyone has looked at them yet. I'd prefer to just close this and take care of it before the beta or even a future release candidate.

**Comment by curtisvo** [comment]
Ok, no problem. I'm not too familiar with the release procedure, so I'll go ahead and close this. At least I know how to send a PR now!

**Comment by jonespm** [comment]
Yeah, thanks for the info @curtisvo. It's pretty easy to do once you do it. But I think this cleanup is a little more complex. I've been meaning to try to get these conversions organized and at least get the MySQL tested by the end of the week so we can "cut" a beta. I might need some help to test the Oracle.

**Comment by juanjmerono** [comment]
There is another jira related to the same problem with at least two tickets.
https://jira.sakaiproject.org/browse/SAK-31065

**Pull request closed without merging**
