### PR TITLE
SAK-48631 Portal: Theme switch should only display if enabled

### PR DESCRIPTION
**Pull request by hornersa**

### CODE REVIEW

**Comment by kunaljaykam** [comment]
Link to the JIRA: https://sakaiproject.atlassian.net/browse/SAK-48631,

Having the option to disable the theme switcher was necessary so thank you for doing that. And I think the theme switcher should be enabled by default. Tell me what you think.

**Comment by hornersa** [comment]
@kunaljaykam - I'm open to that. I'll soon force push an update that sets as the new default portal.themes.switcher=false.

**Review by kunaljaykam — APPROVED** [review]
LGTM!

**Comment by hornersa** [comment]
@ern - I'm not familiar with the issue you're referring to. The intent behind my filing and fixing SAK-48631 was to maintain the prior properties-based logic that determines whether the dark-mode/light-mode switch displays and consequently to allow our institution to continue opting out of dark-mode. 

Fwiw, our institution disables this switch because of the immense amount of user-contributed rich text containing (sometimes inadvertent) color styling that would not be visible in dark mode-- consequently inducing frustration from students and faculty, support issues, etc.

**Comment by adrianfish** [comment]
I understand the intent of this PR to be merely to honour the properties when rendering the account nav template. The PR also sets the default for the account menu switcher to be visible, which I think is good. The default is still for the UI to load in "light" mode, so it's a user choice to select dark.

**Pull request merged**
