### PR TITLE
SAM-3330 use mxParser supported math expression library

### PR DESCRIPTION
**Pull request by ottenhoff**
CCing people who have worked on this code before : @alejandrogj, @davidpbauer, @jonespm

### CODE REVIEW

**Comment by ottenhoff** [comment]
There are new tests included. The old parser is *broken* ..... it returns bad results. I don't have plans to work more on this .....

**Comment by jonespm** [comment]
Are there any plans on supporting the use of the old FACTORIAL? What would happen for old tests that happen to use this? (Maybe we aren't supporting we can include something in the release notes about how to check for usage of this?)

I see the backward compatibility for the other methods. Including these methods handled for backward compatibility those in the test cases would be nice..

Mentioning the new factorial in the text strings there could be helpful too.

**Comment by ottenhoff** [comment]
I don't have any plans to write support for FACTORIAL. We can suggest it upstream.

I don't want to beat a dead horse here, but the current, custom SamigoExpressionParser does not properly calculate routine formulas. I'm not so worried about losing FACTORIAL. It's a bad expression parser.

**Comment by ern** [comment]
OK, I didn't know that the existing parser was broken so this at least gets it back to a working state?

**Comment by ottenhoff** [comment]
The existing parser makes incorrect calculations .... Ask the existing parser to calculate this:

`(185.9*1000*3.8/1200)/(1-1/(1+3.8/1200)^360)`

Ask the existing parser for `sin(pi)` as seen in the previous tests ..... all of my Googling indicates that value is incorrect .....

**Comment by jonespm** [comment]
Yeah, I didn't know it was broken either. I just didn't want to see any support requests from anyone wondering about any old equations weren't working. Maybe Wilma can make a note of this in the help docs that this has changed as users won't read the release notes.

**Comment by jonespm** [comment]
I checked a couple clients and don't see anyone using FACTORIAL anyway, so odds are nobody ever used it. I'll merge this so we can get it tested out.

**Pull request merged**
