### PR TITLE
SAK-43801 Added Arabic translation (35%)

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by ern** [comment]
Since this is not a close 100% does it make sense for it to go to the legacy-language-packs?

**Comment by mpellicer** [comment]
This is a new contribution, this is a request from the new maintainer, they want to see the translation progress in master to demo Sakai to some Arabic institutions, important in terms of Marketing.

**Comment by ottenhoff** [comment]
Agree, this is great progress, it seems like they are rapidly headed to full coverage

**Comment by mpellicer** [comment]
They went from 35% to 42% so they are very constant.

https://www.transifex.com/apereo/sakai-trunk/

**Pull request merged**
