### PR TITLE
SAK-23873 update to use jquery-ui 1.11.3 because of its aria accessibility improvements

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by csev** [comment]
Sam, whlie you are in all these files, could you also add a line to include the jquery migration code as well?  Our new standard is to include jquery, jquery migrate, and jquery ui.  And really while you are at it, why not just use the new call in headscripts.js

https://github.com/sakaiproject/sakai/blob/master/reference/library/src/webapp/js/headscripts.js

function includeLatestJQuery(where)

This checks if the load has already happenned and makes sure that all three things are loaded in the latest version.  Unfortunattely we don't have an equivalent for includeLatestJQueryCSS - perhaps we should

**Comment by csev** [comment]
The convention for the call is to pass the name of the file doing the including

includeLatestJQuery('tabs.jsp')

It helps when watching the console and debugging multiple JQueries fighting with one another.

**Comment by ottenhoff** [comment]
Okay, new set of commits pushed per @csev comments. Note that our date/time picker is currently broken because of SAK-29662 and inclusion of jquery.mobile.min.js in morpheus code

**Comment by csev** [comment]
Thanks - I love this - mlets merge away and get to the testing.

**Comment by csev** [comment]
Sam - I looked this over - It needs to be megged by hand - could you do that?

**Comment by ottenhoff** [comment]
I have rebased my commits.......

**Pull request merged**
