### PR TITLE
SAK-31978: Images elements not responsive when inserted via CKeditor

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by fostersdesign** [comment]
This fix looks logical (and is mentioned in this article too: http://devcollaborative.com/ckeditor-responsive-images). I am worried about unintentional consequences for fringe cases that are possible when setting this for all images and related items that are mentioned, but I have seen how it can work properly in Sakai. 

This PR was discussed on today's Sakai Core Team Call. Adam M. mentioned this fix went into production at Oxford this morning. The team decided to let Oxford test it in production for a week or two to see if there were any issues brought forward. If not, then it could be contributed to master.

**Comment by ottenhoff** [comment]
Does it make any sense to just target imgs inside div.portletBody ?

**Comment by fostersdesign** [comment]
That would help limit the selector's potential impact to just the areas most likely to contain large images/content.

**Comment by nicholaswilson100** [comment]
The attachment 'staple' icon in Assigment when viewing submissions is tiny if this general img class goes ahead so there is a fix for that here too.

**Comment by buckett** [comment]
@ottenhoff Do you mean `div.Mrphs-portalBody`? What stuff do you think the selector shouldn't apply to?

**Comment by ottenhoff** [comment]
I don't have much of an opinion here. Why doesn't normalize/bootstrap/etc implement this by default? Are there any downsides? If no, let's just merge ....

**Comment by nicholaswilson100** [comment]
To me there's an argument for targeting the images we want resized.  We're having a few problems here at Oxford with images here and there being affected by this change (resource icon, mneme icon, assignments icon and that's so far) and looking tiny or the wrong size.

**Comment by nicholaswilson100** [comment]
@fostersdesign  said: "The team decided to let Oxford test it in production for a week or two to see if there were any issues brought forward. If not, then it could be contributed to master."  and there are some issues.

**Comment by nicholaswilson100** [comment]
If not div.Mrphs-portalBody then maybe another more specific targeted selector(s)?

**Comment by buckett** [comment]
One issue we're seeing is that in some tables small icons are used, the cell is set to a small width (smaller than the icon) and then placing an image in it forces the cell to expand to contain the image.

The reason for doing this is so that the column is always the width of the icon and doesn't expand any further as the table gets wider so space isn't wasted on that column.  However with the `max-width: 100%` this allows the small table cells to collapse to their specified size and so they do.

You can see the problem in this: https://jsfiddle.net/prxc7uLd/1/ along with possible fixes for these icons in cells.

**Comment by nicholaswilson100** [comment]
The paste icons in Resources are very small and unusable if this img class change goes ahead so there is a fix in the PR for this too.

**Comment by lardo-de-arnaud** [comment]
We have fixed issues with Resources's Paste icon and the attachment in Assignments, they will be included with this patch. I have had a pretty good look at all other tools (save Samigo) and couldn't see any other problems. 

There's also a couple of little fixes for Mneme but not being a Samigo gaff, we haven't looked at that tool.

**Comment by ern** [comment]
Adam mentioned there are 2 other minor issues that he would like to add to this issue in assignments, resources...

**Comment by lardo-de-arnaud** [comment]
there's the issue of the teensey weensey attachment (paperclip) icon in Assignments plus the teensey weensey paste icon resources

**Comment by nicholaswilson100** [comment]
I'm getting a bit confused by github comments, Jira comments, emails and test plans. Could we just talk about a test plan please...which bit of it fails (or is there a new part to it)?

**Comment by alejandrogj** [comment]
Another issue that would rise is the Hot Spot questions. The areas for the answers that the instructor sets won´t make sense if the images are responsive.

I´ve created a ticket for this -> https://jira.sakaiproject.org/browse/SAM-3153

It would be great to implement this feature and change the Hot Spot question to a responsive html image map (<map>)

**Comment by nicholaswilson100** [comment]
If this is a bug with SAK-31978, then I don't mind including it in this PR (since it hasn't been merged yet).  (If so, is there a test plan/any steps to reproduce at all?)

**Comment by alejandrogj** [comment]
@nicholaswilson100 

SAMIGO stores the (x,y) coordinates of the image for each answer in the Hot Spot questions. When the students take the assessment they click in a area of the image and SAMIGO compares the coordinates of the student´s click with the correct answer. With this ticket the images will have different size depending on the screen size so the grading wil be incorrect.

To fix this we should make the Hot Spot questions responsive, using a html "map" instead of an "img" and using some javascript to make the map responsive. (http://mattstow.com/experiment/responsive-image-maps/rwd-image-maps.html).

Another solution is to set a special CSS class for the Hot Spot images and set their max-width to "none" to get the same behaviour as before in these type of questions.

**Comment by jonespm** [comment]
@alejandrogj Yeah, the second idea seems the easiest for now. I'd do that as part of this fix. Instead of the ".attachmentsIcon" class can we just get a class in the _defaults.scss so anything can use to clear this? Like maybe ".nonresponsive" ? I feel like there will be other ones that come up like this.

**Comment by alejandrogj** [comment]
Maybe @SedueRey  could help us here. I think there are two ways to achieve this:

- Change the styles in the SAMIGO tool. Do something like


```
.studentImageContainer img{
    max-width: none
}

.authorImageContainer img {
    max-width: none
}
```
- Move the styles in imageQuestion.student.css and imageQuestion.author.css to morpheus (sakai/library/src/morpheus-master/sass/modules/tool/samigo/). Create a .non-responsive class and make 
the imgs of the hot spot question extend that class.

These are just two quick ideas, maybe there is a best way to solve this.

**Comment by lardo-de-arnaud** [comment]
now that the SAMIGO fix has been addressed SAM-3153 - there shouldnt be anything holding this back.

**Comment by ottenhoff** [comment]
This needs a rebase

**Comment by nicholaswilson100** [comment]
I've rebased this and another PR has been created (!).  I didn't close the old one, just rebased the branch.  New PR is here: https://github.com/sakaiproject/sakai/pull/4033

**Comment by buckett** [comment]
I'm guessing you pushed a version of the branch that didn't have any changes on it and so was the same as `master`. When github sees that a pull request branch and the branch it's requested to be merged into are the same it closes the PR. This is so that as a maintainer if you do merging locally you don't have todo anything in github, just push the merged branch.

**Pull request closed without merging**
