### PR TITLE
WIP GBNG Wicket 6 to Wicket 9

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
@jonespm you made a modification to Gradebook around tabs ... they weren't being colored correctly on the active tab. it seems like this PR will modify the markup for tabs? thus losing your mod.

**Comment by jonespm** [comment]
Did some brief testing on this today to see if I could find where 320af93 would be removed.

But got an error when clicking on a student in a site created from a sample roster

`Unexpected RuntimeException: Last cause: Could not find child with id: categoriesList in the wicket:enclosure`

This is from 
`        at org.sakaiproject.gradebookng.tool.panels.GradeSummaryTablePanel.onBeforeRender(GradeSummaryTablePanel.java:90) ~[classes/:?]`

Have you seen this before? I can see the categoryList there but not sure why this is broken.

**Comment by ottenhoff** [comment]
I have not seen the GradeSummaryTablePanel error yet. Are you testing as a student?

**Comment by jonespm** [comment]
No, I was testing as an instructor when clicking on a student in the list.

**Comment by ottenhoff** [comment]
Thanks, I can replicate. I'm also stumped.

**Comment by jonespm** [comment]
I was able to get this up by moving the 

`		super.onBeforeRender();
`
to the very end of the overridden method instead of the beginning.

```
diff --git a/gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java b/gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
index dc13da0a430..7c7f8865c5f 100644
--- a/gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
+++ b/gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
@@ -87,7 +87,6 @@ public class GradeSummaryTablePanel extends BasePanel implements IAjaxIndicatorA

        @Override
        public void onBeforeRender() {
-               super.onBeforeRender();

                final Map<String, Object> data = (Map<String, Object>) getDefaultModelObject();

@@ -488,6 +487,7 @@ public class GradeSummaryTablePanel extends BasePanel implements IAjaxIndicatorA
                                });
                        }
                });
+               super.onBeforeRender();
        }

        private void addInstructorAttributeOrHide(WebMarkupContainer sakaiRubricButton, Assignment assignment, String studentId, boolean showingStudentView)
```
My guess is that this huge categoriesList creation code needs to run before that, either in the `onInitialize `or just before the super is run? I tried to refactor it up into there and just was a lot of failures and errors. 

```
		addOrReplace(new ListView<String>("categoriesList",
				this.isGroupedByCategory ? categoryNames : Arrays.asList(getString(GradebookPage.UNCATEGORISED))) { 
```

**Comment by jonespm** [comment]
The good news is that with that change the tabs look about the same as in prod but there's a few other styling issues that could probably be slightly improved.

**Comment by ottenhoff** [comment]
Wow Matt how did you think of that! Nice.

**Comment by jonespm** [comment]
I tried to ask GPT but it couldn't figure out what was wrong. It did suggest to ensure the component exists in Java and it wasn't being removed. I also asked if it matters if I call the super method at the end of the beginning and it said:

> * Calling super.method() at the beginning: This is useful when you want the behavior of the superclass method to execute first, followed by additional functionality specific to the subclass. This approach ensures that the superclass behavior is preserved and then extended upon.

> * Calling super.method() at the end: Conversely, placing the call to super.method() at the end allows the subclass to execute its functionality first, followed by the behavior of the superclass method. This is helpful when you want to ensure that the subclass's behavior takes precedence over that of the superclass.

So based on the stack trace it just seemed like it was needing to run here after everything else was done and I just tried it out. This seemed easier than a larger refactor. I'm not sure the behavior difference. I was looking through the code for Enclosure and I think this might have been it where there was actually a bug in wicket versions before 7 where the configure method wasn't called, and now when it was called early it didn't work. 

https://github.com/apache/wicket/commit/c97e3f4b0e7c7300c41d4608547d8bd16f37498f

Possibly doing some splitting and having some of this in the `onInitialize` would also work but I've tested this out and didn't see any problems.

**Review by ern — APPROVED** [review]

**Pull request merged**
