### PR TITLE
SAK-40028 - Add the groups to a duplicated assignment when the origin…

### PR DESCRIPTION
**Pull request by danielmerino**
…al asignment have any

### CODE REVIEW

**Comment by danielmerino** [comment]
This patch is not working properly. A WARN is thrown:

21-may-2018 10:33:59.487 WARN [ajp-nio-8019-exec-3] org.sakaiproject.assignment.tool.AssignmentAction.doDuplicate_assignment org.sakaiproject.assignment.tool.AssignmentAction@739e9ea:doDuplicate_assignment Found shared references to a collection: org.sakaiproject.assignment.api.model.Assignment.groups; nested exception is org.hibernate.HibernateException: Found shared references to a collection: org.sakaiproject.assignment.api.model.Assignment.group

Not sure how to copy the groups in the refactored code of Assignments. In 11.x the getGroups returns a String collection and I cat get them from SiteService, but in trunk a collection of Groups is returned but it seems that they can't be shared. @ern any hint, please?

**Comment by danielmerino** [comment]
Closing this PR as it doesn't work in master and I don't have resources to fix it, plus it is not as critical in master as it is in 11.x. The PR for 11.x works fine.

**Comment by ern** [comment]
All you need to do is to create a new HashSet()
```
assignment.setGroups(new HashSet<>(existingAssignment.getGroups()));
```

**Comment by danielmerino** [comment]
I close this branch as @jesusmmp has a patch to fix this issue.

**Pull request closed without merging**
