### PR TITLE
SAK-31931 Make URLs relative in Overview (Site Information Display)

### PR DESCRIPTION
**Pull request by buckett**
When editing the Site URL in Site Information Display the URL is made relative if it's pointing to the current host. This change also adds support for a set of aliases that the current service is know as.

Having host relative URLs makes is much easier to move the content to a test server and have all the links work.

### CODE REVIEW

**Comment by jonespm** [comment]
Travis failing some tests in master
```
[ERROR] /home/travis/build/sakaiproject/sakai/dashboard/impl/src/test/org/sakaiproject/dash/mock/MockServerConfigurationService.java:[35,8] org.sakaiproject.dash.mock.MockServerConfigurationService is not abstract and does not override abstract method getServerNameAliases() in org.sakaiproject.component.api.ServerConfigurationService
```

**Comment by buckett** [comment]
Thanks @jonespm fixed.

**Comment by ottenhoff** [comment]
Can we squash and merge for easier branch maintenance, or do we need to preserve authorship here?

**Comment by buckett** [comment]
Yeah, fine to squash and merge.

**Comment by buckett** [comment]
PR needs changes for the kernel API changes in other places.

**Comment by buckett** [comment]
Pushed tests fix.

**Pull request merged**
