### PR TITLE
SAK-29679 : Short URL is not working for resources

### PR DESCRIPTION
**Pull request by frasese**

### CODE REVIEW

**Comment by buckett** [comment]
Why does this fix it? Did a jQuery upgrade make the datatype parameter required to correctly parse the result? Or has something changed in enitybroker?

**Comment by jonespm** [comment]
It sounds like jquery 1.9 is doing a "better guess" at the datatype and doing it incorrectly now? http://stackoverflow.com/questions/15977876/jquery-1-9-ajax-datatype-default-changed

Probably something could be changed in entitybroker to also fix this. I also don't know why this method name is changing here.

**Comment by frasese** [comment]
The change of name is because content tool has its own implementation of "toggleShortUrlOutput", and has a conflict with the generic one.

**Comment by juanjmerono** [comment]
You've changed these files:
   reference/library/src/morpheus-master/js/morpheus.scripts.js
   reference/library/src/morpheus-master/js/morpheus.scripts.min.js

But these files are unused, see https://github.com/sakaiproject/sakai/pull/922
You only have to change:
   reference/library/src/morpheus-master/js/src/sakai.morpheus.short.url.js

Please, avoid change those files, I'm going to remove both soon.

**Comment by buckett** [comment]
This isn't currently merging.

**Comment by frasese** [comment]
Rebased and removed changes in reference/library/src/morpheus-master/js/morpheus.scripts.js and
reference/library/src/morpheus-master/js/morpheus.scripts.min.js

**Pull request closed without merging**
