### PR TITLE
SAK-50536 Profile remove outdated features

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-50536

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Farewell social networking in my baby! 😢 

Great to see this tool is still around though 😄

**Comment by adrianfish** [comment]
@steveswinsburg I know, I know. You tried your best to keep users in Sakai and stop them drifting off to MySpace :) It was funny pruning the properties files and just taking a trip down memory lane. 33K lines of code removed - all that effort. Anyway, that's what we need to do, trim, reduce redundancy etc. Portal chat's gone. The connections manager, that's gone. Actually, that reminds me - I need to remove the connections bits from Roster.

**Comment by steveswinsburg** [comment]
I had a dream that Sakai would defeat Facebook and Twitter simultaneously. But MySpace 😆

**Comment by adrianfish** [comment]
@steveswinsburg You didn't account for MySpace. It outflanked us all.

**Comment by steveswinsburg** [comment]
I have grown in my abilities and won't make that mistake again. Already working on a way to take it down.

**Comment by adrianfish** [comment]
@steveswinsburg I can't even remember what Profile 1 was

**Review by ern — APPROVED** [review]

**Comment by ottenhoff** [comment]
Pretty awesome, thanks all!

**Pull request merged**
