### PR TITLE
SAK-30034 Webservice to change the user timeone

### PR DESCRIPTION
**Pull request by ddelblanco**
Add a webservice to change the user timezone:

sakai-ws/rest/sakai/setUserTimeZone?sessionid=ac37f8fd-eae4-4104-9020-e2300b33ab7e&eid=theuseid&timeZoneId=Europe/Oslo

### CODE REVIEW

**Comment by mcarropellicer** [comment]
Thank you so much @ddelblanco, great work. This PR also resolves a bug of https://jira.sakaiproject.org/browse/SAK-29895 (Adds preferencesService to the context).

Hope someone merges this soon!

**Comment by ern** [comment]
Hi Diego,
Can we get a unit test for this new web service?

**Comment by ddelblanco** [comment]
1. Check the timezone of the user in preferences(so you can view that it changes)
2. Call the webservices with rest (it is the easier way to test it) 
2.1 Open a session with: HTTPS://YOURSERVER/sakai-ws/rest/login/login?id=ADMINID&pw=ADMINPASSWORD
2.2 call it: HTTPS://YOURSERVER/sakai-ws/rest/sakai/setUserTimeZone?sessionid=YOURSESSIONID&eid=THEEXTERNALUSERID&timeZoneId=Europe/Oslo
3. Go to the user preferences again and check if their timezome is the right one.

**Comment by ddelblanco** [comment]
Ohh... I can view now... unit test!!!  Not asking for how to test. I'll work on it.

**Comment by ddelblanco** [comment]
Just updated with the test unit. Earle, please take a look. Maybe I've "mocked" too much things... but seems that works.  If this is fine I'll add another to the other PR with webservice that I've open.

**Comment by ern** [comment]
Sorry I didn't see this earlier thanks Diego for doing the test...

**Pull request merged**
