### PR TITLE
SAK-32270 Make tools/subsites list scrollable on a mobile screen.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**
Post fix:

toolsscrolled

### CODE REVIEW

**Comment by adrianfish** [comment]
It's not working for me. I built your branch from scratch and am getting the same behaviour:

screen shot 2017-03-13 at 20 50 19

**Comment by RebeccaOxfordUni** [comment]
Thanks for looking I'll sort it out now.

**Comment by RebeccaOxfordUni** [comment]
Adrian, are you able to check this fix again?  I've done a pull and complete build of master and created a new temporary branch with a cherry-pick of this commit and re-build of portal and library and this fix still looks fine.  Git status doesn't show any rogue code change that didn't get into this commit.
Thanks for your help with getting this merged.

**Comment by adrianfish** [comment]
That's odd. I rebuilt the whole thing and hosed my cache multiple times. I'll have a go tonight - on the day job now.

**Pull request merged**
