### PR TITLE
SAK-48515 Lessons: buttons at top of page need different alignment

### PR DESCRIPTION
**Pull request by hornersa**
Refer to the screencast, SAK-48515-ProposedFixDemo.mp4, which is attached to the jira: https://sakaiproject.atlassian.net/browse/SAK-48515

### CODE REVIEW

**Comment by hornersa** [comment]
After creating the PR, I observe a problem of button alignment in the student view. I'll try to work on that tomorrow (Friday) and force push a revision when done.

**Comment by hornersa** [comment]
The fix was easier than I anticipated. I attached another screencast to the jira (SAK-48515-ProposedFixDemo_StudentView.mp4) to show what the student view looks like with this proposed fix.

**Comment by adrianfish** [comment]
I really don't like the idea of moving back to the tabs, I have to say. Can we not just add those three buttons to the same button row, so it wraps with the rest of them? You could use similar logic to just remove the text labels from the buttons as the screen shrinks, and it would all just wrap. I don't know how hard this would be without trying it myself, but it seems to make sense to just link those two bars together in some way so we don't have to return to the horrendous tabs :) Maybe I'm asking the impossible, if so, just say so.

**Comment by hornersa** [comment]
@adrianfish - I'm returning to work today after being away for a week. I'll try to implement your suggestions within the next few weeks or so.

**Pull request merged**
