### PR TITLE
SAK-32733: make accept until date 1 day later than end date by default.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**

### CODE REVIEW

**Comment by jonespm** [comment]
I think something like this should be either be configurable or have some T&L input before changing. I also think it should have consistency with dates in other tools like Samigo.  I think all of the times are wrong.

Right now Assignment hardcodes the start date to be 12PM today, the due date to by +7 days at 5PM and the accept until to match the due date.

Samigo hard codes the start date to be "now" the due date to be none and the accept until date to be "now". What's sensible for all of these defaults? I feel like it should be

Start date "now" due date "now +7 days" accept until "now + 8 days" though I can see these all being configurable?

Properties
assignment.startdate = <seconds offset from now default 0>
assignment.duedate = <seconds offset from now default 7*24*60*60>
assignment.acceptuntil = <seconds offset from now, default 8*24*60*60>

(Though maybe these should just be general properties and affect both tools?)

**Comment by RebeccaOxfordUni** [comment]
I have made these dates (and the peer review evaluation date) configurable.
The work for SAK-32731 is incorporated in this PR.

**Comment by RebeccaOxfordUni** [comment]
My previous code had a conflict with the substantial changes that Earle has made.  As the assignmentaction.java file has moved location and the code changed significantly I have re-worked this Jira and also included a new request to have the visible date configurable.

**Comment by RebeccaOxfordUni** [comment]
Are you able to merge this now please Matthew @jonespm

**Comment by RebeccaOxfordUni** [comment]
Another one where I'd be grateful if it could be merged Matthew @jonespm.

**Comment by lardo-de-arnaud** [comment]
Are people generally in favour of this? I wouldnt want Rebecca to do yet more conflict resolution and then the community decides this isn't a desirable "improvement".

**Comment by RebeccaOxfordUni** [comment]
Thanks for reviewing Earle.  I've resolved the conflict.

**Pull request merged**
