### PR TITLE
SAM-3178 Force "direct" links to redirect to Login servlet

### PR DESCRIPTION
**Pull request by dnhutchins**
PR against master instead of 11.x

### CODE REVIEW

**Comment by ottenhoff** [comment]
Is this code currently running in production somewhere? 

@jonespm any thoughts?

**Comment by dnhutchins** [comment]
Not just yet, it will go in as part of our 10>11 upgrade at UVa.

**Comment by ncaidin** [comment]
Hi @dnhutchins , I don't see a contributor license agreement on file for you.

Please see https://www.apereo.org/licensing for information about licensing agreements, especially for the ICLA.

**Comment by ottenhoff** [comment]
@dnhutchins and @ncaidin any update on CLE?

**Comment by dnhutchins** [comment]
We submitted both the CCLA and ICLA, not sure where it may be in the Sakaiproject order of operations though.

**Comment by ncaidin** [comment]
The CCLA and ICLA are on file now. There were a couple of issues. The ICLA missing a signature on the first attempt was the main holdup, but now we have a good copy. Cheers.

**Comment by ottenhoff** [comment]
Working well for me in testing

**Pull request merged**
