### PR TITLE
SAK-22432 - Template descriptions are not copied

### PR DESCRIPTION
**Pull request by mcarropellicer**
Template descriptions are not copied when creating a new site.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
The comment  above the line modified says
// description is site-specific. Shouldn't come from template.

What has changed to make the description now come from the template?

**Comment by mcarropellicer** [comment]
It's a direct contribution from Oxford University, IMO this should be controlled by properties.

**Comment by jonespm** [comment]
Looks good to me, I would just make the default true

**Comment by ottenhoff** [comment]
I agree with jonespm. This seems like it would be expected behavior. Let's make it true by default.

**Comment by mcarropellicer** [comment]
Thanks for the feedbacl @ottenhoff @jonespm , defaults to true.

Miguel

**Pull request merged**
