### PR TITLE
SAM-1117 - Option to not display value of question

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
Depends on SAM-948 PR to be merged first on #1680. This is also missing a conversion script which I'll work out by Monday.

**Comment by raulsv** [comment]
Hi

This ticket should take the Jira [SAM-2695](https://jira.sakaiproject.org/browse/SAM-2695) into account.

**Comment by jonespm** [comment]
@rauelsv Yeah if you look at the changes to samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp it doesn't touch/hide the discount. Do you think that should be included as not displayed as well? It's only applicable for multiple choice questions.

**Comment by jonespm** [comment]
Okay @raulsv I changed it so this setting also hides the value of the "discount". I don't like the name of that, maybe I can think of something better, like "Incorrect answer deduction"?

**Comment by raulsv** [comment]
Thanks @jonespm. I like your proposal: "Incorrect answer deduction". The discount field affects to 'True or false' questions too. Regards.

**Comment by ern** [comment]
Core Team reviewed and is ready for merge

**Pull request merged**
