### PR TITLE
LSNBDLR-722 stop users seeing half saved items in their lessons page

### PR DESCRIPTION
**Pull request by buckett**
This attempts to stop users seeing half saved items in their lessons page.

### CODE REVIEW

**Comment by buckett** [comment]
@clhedrick We needed something for our 11.x instance that wasn't too much of a change but in the long run a bit of a refactor of how the inserts are done might be the way to go.

**Comment by clhedrick** [comment]
This is OK with me as long as it doesn't cause performance issues.

**Comment by buckett** [comment]
We see this because our search implementation is very eager about indexing content and as soon as something is in the queue it will start processing it. We're using solr rather than elasticsearch so it may be much harder to replicate on Sakai master if elasticsearch doesn't index as frequently.

**Comment by buckett** [comment]
@clhedrick Has another pull request that changes how lessons behaves and it saves in one transaction now so closing this one.

**Pull request closed without merging**
