### PR TITLE
SAK-31677 Allow admin users to add themselves to site in any role

### PR DESCRIPTION
**Pull request by ansorgej**
Allow admin to add self to any site in any role, even if the role does not have site.upd.site.mbrshp

### CODE REVIEW

**Comment by bjones86** [comment]
LGTM

**Comment by buckett** [comment]
I'm not sure why the `checkCurrentUserRoleChange()` code is there at all, as if you're already a member of the site you can't use the `SiteAddParticipantHandler` code because if you try to re-add yourself to the site you get an error saying
screen shot 2016-09-30 at 11 31 56

**Comment by buckett** [comment]
I've dug into this and I think that we can simplify it all a bit and have a PR in #3422

**Comment by buckett** [comment]
Closed as I think #3422 is the way to go.

**Pull request closed without merging**
