### PR TITLE
SAK-40810 - Rubrics doesn't start due to Spring dependencies upgrade

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by mpellicer** [comment]
@bgarciaentornos can you try in your dev environment too?

**Comment by bgarciaentornos** [comment]
It's working for me, let's merge this soon!

**Comment by bgarciaentornos** [comment]
It's working for me, let's merge this soon!

**Comment by bgarciaentornos** [comment]
It's working for me, let's merge this soon!

**Pull request merged**
