### PR TITLE
SAK-29027 - TA's with site.upd can see announcements of any

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
Just an idea to change the permission for instructor check in announcement to annc.all.groups instead of site.upd. Was mentioned that this caused a regression otherwise. 

Correct PR :)

**Comment by buckett** [comment]
What about doing:

```
	private boolean isUserInstructor(String userId, Site site){
		if(site != null && site.getMember(userId) != null){
			if(m_securityService.unlock(userId, eventId(SECURE_ALL_GROUPS), m_siteService.siteReference(site.getId()))){
				return true;
			}
		}
		return false;
	}
```

And updating the method name? There is already code that uses ```eventId(SECURE_ALL_GROUPS)``` in other places. And although the email archive doesn't register this function it isn't group aware.

**Comment by jonespm** [comment]
Sure that sounds good, 

While it looks like only EmailArchive and Announcements extend this, there *could* come some custom tool out there that also is, and EmailArchive could be group aware in some future release, which is why the fallback was there in the first place. 

Not sure what a better name would be. It's basically a check to see if the user should get all access to see everything.

**Comment by juanjmerono** [comment]
I've tested this patch and it works as expected. Are you thinking in improving it with Matthew's suggestion or should I merge this one into master?

**Comment by buckett** [comment]
I've opened a new pull request as #171

**Pull request closed without merging**
