### PR TITLE
SAK-29330 remove all traces of the idea that an eid could be case-sensitive

### PR DESCRIPTION
**Pull request by ottenhoff**
Lowercase the login id in authenticateUser!

There is no way JDoe !== jdoe

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Yes.

**Comment by baholladay** [comment]
+1

**Comment by jonespm** [comment]
It could be possible that some school randomly assigns user names similar to passwords, and they'll already have existing users with mixed case and this cause a problem. It seems 99% safe, but case sensitive user names were an initial design decision and prompted long discussions back in the early jiras. (https://jira.sakaiproject.org/browse/SAK-1324?focusedCommentId=24108&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24108)

**Comment by ottenhoff** [comment]
A school that believes JDoe is distinct from jdoe is in for a world of hurt..........

**Comment by jonespm** [comment]
Yeah, I agree with you that this is overall a good idea and it's a bad design decision, Every system I've designed have been case insensitive on login. If we put this in the release notes that from this point forward eid is case insensitive it should be fine. Big sites like Facebook even go so far as to storing 3 different passwords for user convenience on case, since it can be annoying not being able to login. (Especially on mobile)

- Your original password.
- Your original password with the first letter capitalized. This is only for mobile devices, which sometimes capitalize the first character of a word.
- Your original password with the case reversed, for those with a caps lock key on.

**Comment by buckett** [comment]
There are some places in Sakai that still store data against the EID. For example the Roster 2 tool looks up a user's hidden memberships by EID  `org.sakaiproject.roster.impl.SakaiProxyImpl#filterHiddenMembers`

Locally we don't use this feature, but I've no idea if anyone else does.

**Comment by buckett** [comment]
I think this broken the kernel-impl tests (travis failed to build the pull request).

**Comment by jonespm** [comment]
Yeah, nightly is failing too. The tests are failing in AuthenticatedUserProviderTest. One of the tests makes sense, but I can't figure out how the tests for the provided users work and are provisioned.

**Comment by jonespm** [comment]
Added PR for the failing tests at #481

**Pull request merged**
