### PR TITLE
SAK-33617 : Content-review-impl Urkund : Include OptOutUrl

### PR DESCRIPTION
**Pull request by frasese**
As the content-review API does not offer a method to get only one ContentReviewItem by id, we need to get all reports and store them in a cache indexed by ContentId.

### CODE REVIEW

**Comment by ern** [comment]
Does
org.sakaiproject.contentreview.dao.ContentReviewItemDao#findByProviderAndContentId
meet your needs?

**Comment by mpellicer** [comment]
Hi @ern, 

I would like to provide more context here, this feature will be added to 11.x, 12.x and Master, as you know 11.x and 12.x has diverged so we'll do both PRs, this is the PR for 11.x.

We'll take a look @ org.sakaiproject.contentreview.dao.ContentReviewItemDao#findByProviderAndContentId, thank you!

Miguel

**Comment by frasese** [comment]
Hi @ern,
Yes, org.sakaiproject.contentreview.dao.ContentReviewItemDao#findByProviderAndContentId is exactly what we need, but...
1. This is not available in 11.x (only in 12+). This PR is only for 11.x
2. We need to get that info from assignments, so we should not use the ContentReviewItemDao but the ContentReviewService. And that service does not offer a way to get a single ContentReviewItem (by contentId).

Actually, we should think to upgrade the ContentReviewService API with these kind of methods. I think this will help you a lot with the assigments refactor process. But anyway... that is apart from this PR...

**Comment by ern** [comment]
The cache should probably be in the ContentReviewService vs the AssignmentService.

**Comment by frasese** [comment]
Sure, we can remove the cache from assignmets, but then, we need to modify the content-review API. We need a way to get one ContentReviewItem.
Do you agree?

**Comment by frasese** [comment]
The problem is... if we modify the content-review API (I was thinking to add a new method like public ContentReviewItem getContentReviewItem(String contentId, String taskId, String userId)), we will break all other implementations.

This will be solved easily in 12+, because all implementations are inside the Sakai code. But for 11.x, the implementations come from contribs, so we can not update them all.

**Comment by ern** [comment]
You wouldn't need to modify any api, put a cache in the impl for:
List<ContentReviewItem> getReportList(String siteId)

Where your cache can be just cache List<ContentReviewItem> for a given site, just make sure you do invalidation!

**Comment by frasese** [comment]
There are some points I'd like to discuss here:
- We have removed the cache from the assignments service.
- We have added a new method : findReportByContentId. This method calls the content-review#getReportList method and looks for the given report by contentId.
- I don't like to go through the whole list every time to find the report, and that's why we put the cache in the first instance. To have an index. 
- I really don't know if is necessary to put a cache in the content-review#getReportList implementation. As you said the other day, hibernate already has its own cache.

What do you think about all of this?

**Comment by ern** [comment]
- We have removed the cache from the assignments service.
  - Great
- We have added a new method : findReportByContentId. This method calls the content-review#getReportList method and looks for the given report by contentId.
  - Since this is a new method to the api is Urkund doing some thing different than the other content review impl's or is this something benefitting all content review impl's?
- I don't like to go through the whole list every time to find the report, and that's why we put the cache in the first instance. To have an index.
  - Are you retrieving each report vs calling a bulk method to get all reports, the bulk method would probably be more efficient and caching it even better. Iterating over cached elements is fast.
- I really don't know if is necessary to put a cache in the content-review#getReportList implementation. As you said the other day, hibernate already has its own cache. Anyway, this change will be in the Urkund (contrib PR) implementation and it should be independent from this PR.
  - this is not for master or 12.x so I don't understand this last point.

**Comment by frasese** [comment]
* ~~We have removed the cache from the assignments service.~~
  * ~~Great~~
* We have added a new method : findReportByContentId. This method calls the content-review#getReportList method and looks for the given report by contentId.
  * Since this is a new method to the api is Urkund doing some thing different than the other content review impl's or is this something benefitting all content review impl's?
    * This new method is not in the content-review API but in the assignments service [https://github.com/sakaiproject/sakai/pull/5019/files#diff-36d7daf9ff6912ed634cfd484790f5d8](https://github.com/sakaiproject/sakai/pull/5019/files#diff-36d7daf9ff6912ed634cfd484790f5d8). I think this method will be useful for all implementations and, for Sakai 12+ we should provide this method in the content-review API, but if we do that in 11x we will need to update all implementations and it's not possible becuase they are from contrib repos. So I would left it just in assignments.
* I don't like to go through the whole list every time to find the report, and that's why we put the cache in the first instance. To have an index.
  * Are you retrieving each report vs calling a bulk method to get all reports, the bulk method would probably be more efficient and caching it even better. Iterating over cached elements is fast.
    * So, do you think this iteration is right ?? [https://github.com/sakaiproject/sakai/pull/5019/files#diff-36d7daf9ff6912ed634cfd484790f5d8R10928](https://github.com/sakaiproject/sakai/pull/5019/files#diff-36d7daf9ff6912ed634cfd484790f5d8R10928)
* ~~I really don't know if is necessary to put a cache in the content-review#getReportList implementation. As you said the other day, hibernate already has its own cache. Anyway, this change will be in the Urkund (contrib PR) implementation and it should be independent from this PR.~~
  * ~~this is not for master or 12.x so wouldn't worry about it~~

**Pull request merged**
