### PR TITLE
SAM-2466 Attachments buttons not working in samigo .

### PR DESCRIPTION
**Pull request by sinmsinm**
Reverted some unnecessary redirects on faces-config

### CODE REVIEW

**Comment by ottenhoff** [comment]
So where did these redirects come from?  SAM-2378 and @csev?

**Comment by buckett** [comment]
The <redirect/> tags are to stop the tool generating HTML in response to at POST request. If you removed the redirect tags then you start getting message in the logs from:

https://jira.sakaiproject.org/browse/SAK-27768

**Comment by sinmsinm** [comment]
Hi, removing those redirect from questions item I didn't appreciate any extra log. 

When I was looking for the bug I noticed that debug from SamigoJsfTool was processing the request to the  <question type>.jsp  twice instead of doing question first and filepicker later. On 10.x (or if you remove the redirect on this path in trunk) the behaviour is the correct. I presume that only affects to those few paths I changed (question items) because attachment buttons works when editing parts. I feel that in those part some HTML processing was required.

**Comment by sinmsinm** [comment]
I've checked the log and It's true I see this log line: 
2015-02-24 09:41:36,892  WARN http-bio-8080-exec-8 org.sakaiproject.portal.charon.handlers.SiteHandler - It is tacky to return markup on a POST CTI=sakai.samigo URL=http://localhost:8080/portal/site/ad6130f4-9859-41c6-9267-2b4b0c663b48/tool/8d271cbf-c64c-4841-83ef-f6e4d3d08b8c/jsf/author/editAssessment

By the way, I add more information here in the case that the question type is a multiplechoice :
If you enable debug on SamigoJSFTool you'll see that when push to the attachment button that dispatch method is called twice. If you have the <redirect /> both  calls targets are /jsf/author/item/multipleChoiceSurvey 
Instead, if you remove the <redirect/ > to the question types definitions then first points to /jsf/author/item/fileUpload and the second points to /jsf/author/item/sakai.filepicker.helper/tool 

It's like the processing prevented by <redirect/> is needed at some point to launch filepicker. Isn't it?

**Comment by ottenhoff** [comment]
> It's like the processing prevented by is needed at some point to launch filepicker. Isn't it?

Yes, I agree. What is your recommendation @sinmsinm?  Do you believe this PR should be merged?

**Comment by sinmsinm** [comment]
I would merge it.  This PR has been opened for some days and nobody suggested an alternative to get attachment buttons working again.

**Pull request merged**
