### PR TITLE
SAK-30896: "Web site" should be "website" in Resources Upload page

### PR DESCRIPTION
**Pull request by andrewbihl**
Changed "web site" to "website". This displays in the Upload page of the Resources section.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Hi @andrewbihl : can you create a JIRA for this modification?

https://github.com/sakaiproject/sakai/blob/master/CONTRIBUTING.md

**Comment by andrewbihl** [comment]
@ottenhoff I went ahead and made a JIRA for the issue and changed the pull request title to the name of the JIRA issue: 

https://jira.sakaiproject.org/browse/SAK-30896

**Comment by bjones86** [comment]
This commit should have probably been amended to include the JIRA ID as a prefix in the commit message.

**Comment by ottenhoff** [comment]
check the git log ;)

**Comment by bjones86** [comment]
Nice! My bad, "Commits" tab lying to me :(

**Comment by ottenhoff** [comment]
Commits tab is accurate for the submitter's branch but Github squash/merge magic introduced on April 1: https://github.com/blog/2141-squash-your-commits

**Pull request merged**
