### PR TITLE
KNL-1412 Add back in the main SecurityService cache.

### PR DESCRIPTION
**Pull request by buckett**
This accidentally got removed in KNL-1271 and should have been refactored to just be a normal Cache. Most of this isn’t actually new code but just adding back of code that was wrongly removed.

### CODE REVIEW

**Comment by buckett** [comment]
This is mainly the original code back in without changes.

**Comment by jonespm** [comment]
I know it wasn't you that originally added this but it doesn't make sense to me to have cacheDebugDetailed in there. It seems like having regular debug logging on this class rather than a special obscure property would make more sense. Maybe another ticket.

**Comment by jonespm** [comment]
Other than that looks good, and see it now after reviewing the original again. Biggest risk with code cleanup is removing the little big of code that was still doing something useful. Ideally you catch it before production! ;)

**Comment by ern** [comment]
Awesome thanks Buckett :+1:

**Pull request merged**
