### PR TITLE
SAK-45534: SAMIGO: Solving problems of calculation pattern

### PR DESCRIPTION
**Pull request by jesusmmp**
https://jira.sakaiproject.org/browse/SAK-45534.
You cannot parse html-level languages ​​with infinite nests with regular expressions.

Review @davidpbauer

### CODE REVIEW

**Comment by davidpbauer** [comment]
Is this change necessary? Currently, the test plan with the attached exported assessment in Jira is passing on nightly.

If there is still an issue, I think we need an updated test plan that is currently failing.

**Comment by jesusmmp** [comment]
@davidpbauer New test plan has been added.

Things like: [[3 * [phi]] ] or [ [[phi] * 3]] are bad formatted and not UI warning/error appears because 3* [phi or phi] * 3 can't be calculated.

**Comment by davidpbauer** [comment]
Thanks for updating the test plan. Would it be simpler to instead strip out any spaces between any [ or ] characters or account for them in the regex? I noticed that while this change will now catch the particular scenario you've added in the test plan, if you slightly modify it so that [[3 * [phi]]] is correct but [[{x}+{y}]] is incorrect like [[{x}+{y}] ]  then the {x}+{y} is missed with no warning because it's not considered a calculation with a space between ] and ]. Should [ [ {x} + {y} ] ] be allowed if it was added by an instructor?

Anyone else have any thoughts? The code itself looks fine, I'm just not sure about the need for all of the text replacing back and forth.

**Comment by jesusmmp** [comment]
@davidpbauer With this patch you can now "pre-evaluate" expressions between [[ ]] that are bad formatted and a warning is shown to the instructor.
No, [ [ {x} + {y} ] ] shouldn't be allowed. I'm not sure about changing UI input ( strip out any spaces between any [ or ] characters)

**Review by juanjmerono — APPROVED** [review]

**Pull request merged**
