### PR TITLE
SAM-3391 - Disable backbutton doesn't work when delivered via lessons.

### PR DESCRIPTION
**Pull request by jonespm**
Also applied similar fix to assignment grading.

### CODE REVIEW

**Comment by jonespm** [comment]
Perhaps there's a better suggestion for this pattern. Seems like the headscripts aren't loaded in this samigo form when invoked via iframes.

**Comment by ern** [comment]
Sometimes in lessons you can be nested multiple levels so this while this works in the first level of nesting it may not in other levels. My understanding of this is that it is a larger issue with lessons and its use of iframes. As you mentioned Sakai doesn't inject any headers into these nested iframes which is another issue all together.

**Comment by jonespm** [comment]
Yeah, this is defined in headscripts.js. I'm not entirely sure why it's not available but I'm also not sure if the iframe could disable button navigation for the browser either without going to the main page. 

This wouldn't work if nested twice, but I didn't see it in this case. The worst case is that the back button just wouldn't be disabled. It could do a loop looking through all the parents until it got to the top but that seemed like an ugly pattern to be using.

**Comment by jonespm** [comment]
Figuring out why headscripts isn't included might be worthwhile, I feel like this whole feature to disable the back button was just a "nice improvement". Really the better improvement would be having the back button work in all cases, but that's another story.  I just noticed this was a problem when testing out another bug.

**Comment by jonespm** [comment]
This probably isn't even useful in the assignments code, I only saw this in Samigo delivery. It probably could use headscripts though instead, as long as that works directly calling it in an iframe.

**Comment by jonespm** [comment]
This probably isn't even useful in the assignments code

**Comment by jonespm** [comment]
@ern I put up a new solution including headscripts in the header in #5458

**Pull request closed without merging**
