### PR TITLE
SAK-29617 : Resources Meta Data

### PR DESCRIPTION
**Pull request by frasese**

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Should these packages be converted to org.sakaiproject ones?

**Comment by buckett** [comment]
I think that makes sense, they also need the Sakai header adding.

**Comment by steveswinsburg** [comment]
Added a comment on the jira, is this a restructure of the existing 'optional properties' bit in resources? Or is it something new? A screenshot would be awesome.

**Comment by juanjmerono** [comment]
It looks great, but I'm wondering if it's possible avoiding go to the top of the page every time you click to expand or collapse any metadata section.

**Comment by frasese** [comment]
- Renamed oxford packages
- Added license texts
- About the behaviour commented by @juanjmerono , that bug also appears in trunk, so I prefer to add another JIRA
- More info and screenshots in JIRA

**Comment by frasese** [comment]
Finally, I also have solved the "scroll to top" bug.

**Comment by buckett** [comment]
This one has merge conflicts could it be rebased please.

**Comment by mcarropellicer** [comment]
Hi @buckett, seems this passed all the tests, is ready to be merged?

**Comment by juanjmerono** [comment]
I think it's safe for translations, transifex/crowding are based on english properties, so when you remove some property in the english file then this label is not exported in the destination language.
Anyway, we will take a close look after merge this PR to check if something goes wrong with transifex.

**Pull request merged**
