### PR TITLE
SAM-3010 - Add actual event string for auto graded event and fix score

### PR DESCRIPTION
**Pull request by jonespm**
update event

### CODE REVIEW

**Comment by steveswinsburg** [comment]
LGTM. There doesn't seem to be much consistency in the event names. Whoever added EVENT_ASSESSMENT_TOTAL_SCORE_UPDATE and EVENT_ASSESSMENT_STUDENT_SCORE_UPDATE broke the previous pattern 😭

**Comment by jonespm** [comment]
Yeah right, though actually it was the other way around, the previous pattern was okay, and broke by these new events. ;)

The events previously were like sam.student.score.update which match standard Sakai event patterns (https://confluence.sakaiproject.org/display/UDAT/Log+Events+Descriptions+-+Sakai+2.6.x)

SAM-1947 which was a PR #1098 earlier this year added these different camelCase ones 
sam.assessmentAutoGraded

without anyone noticing on the PR. I think they should be changed to match the other format, and all of them should be added to this SamigoConstants file. It probably wasn't very obvious until I started cleaning it up and adding to this file. I can create another jira for this though.

**Comment by ottenhoff** [comment]
+1 here and a new JIRA for consistency sounds good

**Comment by jonespm** [comment]
Yeah created this jira as https://jira.sakaiproject.org/browse/SAM-3012. Will get around to it.

**Pull request merged**
