### PR TITLE
SAK-31558 Improve speed of test when VM doesn’t have ok rnd.

### PR DESCRIPTION
**Pull request by buckett**
Checking to see if this makes travis any faster.

### CODE REVIEW

**Comment by ottenhoff** [comment]
@buckett  do you want this merged?

**Comment by buckett** [comment]
It would be helpful for us as our build server has bad randomness, but I'll create it as a Jira so it can get merged back.

**Comment by steveswinsburg** [comment]
@buckett how did you go with a Jira?

**Comment by buckett** [comment]
I think this needs to only activate through a profile as it's a linux fix.

**Comment by buckett** [comment]
I've created SAK-31558 and I'll put this in a profile so it only gets activated on linux.

**Comment by buckett** [comment]
Profile activation done and linked to jira.

**Comment by steveswinsburg** [comment]
Conflicts 😭

**Comment by buckett** [comment]
Fixed conflicts.

**Pull request merged**
