### PR TITLE
SAK-46836 Portal IE9 remove html5shiv lib

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Review by mpellicer — APPROVED** [review]

**Comment by ottenhoff** [comment]
@mpellicer should I stop here, or should I expand the search and remove other IE 9 references like this:

```
212         <!--[if lt IE 9]>
213         <script src="${pageSkinRepo}/${pageSkin}/js/ie/sakai.portal.ie.js$!{portalCDNQuery}"></script>
214 <![endif]-->
```

**Comment by mpellicer** [comment]
> @mpellicer should I stop here, or should I expand the search and remove other IE 9 references like this:
> 
> ```
> 212         
> ```

This is nice, as you wish Sam, I think we might want to start removing any kind of support for IE, count on me for that!

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Looks good to me thanks @ottenhoff

**Comment by ottenhoff** [comment]
sorry @mpellicer i added a few more!

**Comment by mpellicer** [comment]
No problem, all of this is super good!

**Pull request merged**
