### PR TITLE
SAK-30660 improve new assignment page

### PR DESCRIPTION
**Pull request by master-bob**
The "advanced" assignment options are now grouped and wrapped up into
a JQuery UI Accordion. This was done to reduce the page length.

I broke this up into two commits. The first commit has just the changes necessary. The second commit has formatting changes as a result of the first commit. The first commit wrapped a huge section in a div, so the second commit just indents the content appropriately.

### CODE REVIEW

**Comment by jonespm** [comment]
While I like this idea, this doesn't appear to be working right for me.

Also the "Files changed" diff says for the vm file 

1,156 additions, 1,141 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

So I can't actually easily see what changed here. Did you have to redo the entire template to get this to work? I'll attach a screenshot of what I'm seeing. It looks like some of the problem might be with contentReview but so much has changed with this file.

[Screenshot](http://i.imgur.com/NtVsNsI.png)

**Comment by jonespm** [comment]
I think it maybe makes sense as you say to put all of those options into one big accordion (that maybe is collapsed by default) but having 5-6 separate accordions that collapse the other ones just seems like a lot more wasted clicks to me. Did you ask the sakai-users list?

**Comment by master-bob** [comment]
@jonespm , yes. This is why I used two commits. The first commit is the changes. The second commit is the new indenting as a result of my changes. I did it this way so that one may easily view the changes made in the first commit. If ya'll didn't want the new code to be properly indented, I could easily remove that commit (another benefit of doing two commits).

We initially considered putting all the "Advanced Options" under one big collapsed Accordion section, but felt that removed semantic information from the user. If the user never clicked on the "Advanced Options" they would not know about any of the available features (like attachments or notifications). In order to strike a balance between semantic information and number of accordion sections we decided to group similar sections together. Now all the Email notification sections are under one section, titled Emails.

We hadn't considered grouping everything in one big open Accordion section, with sub-accordions in place (like in your screenshot). The issue I see with that method is the main containing section must be open, as Grading / ContentReview is rather crucial.
Granted you could move the Grading (and maybe ContentReview) section outside the accordion. But then you end up in the same spot as before. If the accordion is collapsed by default, then you are hiding information from the user. If the accordion is open by default (with collapsed sub-accordions), why even have the main accordion?

This method of using Accordions to group and hide options is also used in Samigo.

No, I did not ask the sakai-users list.

**Comment by master-bob** [comment]
Is that screenshot a mockup?

**Comment by ottenhoff** [comment]
I'm a fan of the accordion UI element. I think it's been well tested by the jquery-UI community. 

All elements inside the accordion should be relatively obscure. We should have the most-used settings open by default. 

The accordion element seems to work especially well on a mobile device ....

**Comment by master-bob** [comment]
I've updated this an added a missing property, assignmentOptions.contentReview.

**Comment by jonespm** [comment]
No, this screenshot isn't a mockup, I deployed your branch to my local 12 instance this morning. I'm not sure why it's so out of date and odd looking. I have settings setup for vericite testing. I think it's possible now to set up a mock content review for testing this area too, otherwise this can be hard to figure out changes with.

**Comment by jonespm** [comment]
Okay, the text is working, but as the (new) screenshot shows if you have content review enabled all of the additional options are grouped in this outer "assignmentOptions.contenReview" accordion. And there's 4 other accordions inside of there. This grouping doesn't make sense. And yeah, grading needs to be moved out of that area. 

This is how it looks without the accordions and I think your grouping is logical, just some tag is out of place in here.
[Imgur](http://i.imgur.com/Jsm4lR6.jpg)

**Comment by master-bob** [comment]
I will close this for now and either reopen it or open a new PR once I have time to revisit this.

**Pull request closed without merging**
