### PR TITLE
SAM-2675 Eventlog error when submitting an assessment

### PR DESCRIPTION
**Pull request by raulsv**

### CODE REVIEW

**Comment by juanjmerono** [comment]
It seems like the catch section is doing some related work looking for the same empty list.

**Comment by raulsv** [comment]
Yes, I'm going to reviewing it. Thanks

**Comment by juanjmerono** [comment]
Now, LGTM

**Comment by ottenhoff** [comment]
I know Samigo has terrible code formatting.... but can you fix the tabs/spaces issues in this change?

**Comment by raulsv** [comment]
Hi @ottenhoff 

The code formatting is fixed. Regards

Raúl

**Pull request merged**
