### PR TITLE
SAK-40153 Calendar: Updated the design of the synoptic calendar to make it more modern to match the rest of Sakai

### PR DESCRIPTION
**Pull request by fostersdesign**
https://jira.sakaiproject.org/browse/SAK-40153

The synoptic calendar appears in the Home site and is on the first page that users see when they log into Sakai. The synoptic calendar needs to be styled, including the table headers, the cell size, the colours, and the events list, to make it match the rest of Sakai.

I removed a lot of inline styles and moved all of the styles to SASS.

I've updated the look of the calendar from:

*BEFORE:*
01-synopticcalendar-before

to:

*AFTER:*
02-synopticcalendar-after

### CODE REVIEW

**Comment by ottenhoff** [comment]
What's the color contrast on the next month days? That's an item we've had to address with our accessibility reviews

**Comment by jonespm** [comment]
I also thought that @adrianfish had written the "My Calendar" widget as an eventual replacement for Calendar Summary and this was a component we could remove. Is this not the case?

**Comment by fostersdesign** [comment]
@ottenhoff : The contrast of the next month days are "1.77:1" because they are supposed to essentially be invisible. If you mouse over them, they become the same as the current month's days: "16.10:1".

**Comment by ottenhoff** [comment]
That sounds like a regression to me.... we've been down this road before and have been flagged for this exact issue .........

**Comment by fostersdesign** [comment]
@jonespm : I had heard of the new Calendar widget. I didn't know what is the state of its release, though. 

Since the original synoptic calendar has remained unstyled from Morpheus for three versions, I decided it was time to contribute the work that I had done locally for our Sakai 11. It can be used until the original synoptic calendar is removed. My work had already been done locally, so it didn't take much to port it to Sakai master.

**Comment by fostersdesign** [comment]
@ottenhoff : what if I make the date numbers transparent, so they appear as blank cells? And still have the hover for the functionality.

**Comment by ottenhoff** [comment]
We shouldn't try to use gimmicks to get around accessibility issues.

If the dates are relevant to the end user, then make them visible and legible. If they are not relevant, don't display them.

There are tons of ways to show "difference" (e.g., a different month) to a user without alienating low-visibility users. We can use font-size, boldness, text decoration, and colors. 

The use of low opacity, low contrast colors, etc., is the wrong way to convey difference going forward. I know we all have done it in the past, but we have to stop doing it.

**Comment by fostersdesign** [comment]
In this case, I'm not trying to get around accessibility issues. I'm trying to provide a progressive enhancement functionality for all users without damaging our accessibility score.

**Comment by fostersdesign** [comment]
I'll investigate fixes tomorrow and resubmit.

**Comment by steveswinsburg** [comment]
I wrote that calendar widget. I was hoping it would replace the synoptic
calendar. It does need some styling attention for accessibility but should
be pretty simple to use as it's just jQuery UI.

**Comment by fostersdesign** [comment]
@steveswinsburg, thanks for the information about the calendar widget. 

I don't intend my PR to prevent Sakai from switching to use the new calendar widget. Instead, I hope that my PR will improve the synoptic calendar until the switch is made, and for institutions who don't make the switch immediately and are still using the synoptic calendar.

**Comment by fostersdesign** [comment]
@ottenhoff - are you happy with my latest revisions?

**Comment by ottenhoff** [comment]
So your latest revision completely hides the previous month dates? I'm okay with it, but are long-time users of this widget going to complain that they no longer have access to previous month dates in the widget?

**Comment by fostersdesign** [comment]
If they hover or focus on the previous/next month dates' space, they'll see the previous dates.

**Comment by ottenhoff** [comment]
sorry, but i don't like the hover to reveal. i'm confident this is going to cause an accessibility -1 for us ....

I'm asking for a simple solution: display the previous month dates but make sure they meet WCAG 2.0 AA minimum contrast standard. you are free to use a different font, styling, color, weight, etc to make it appear differently.

**Comment by fostersdesign** [comment]
Hopefully, "third time's the charm":

04-synopticcalendar-after-take3

**Comment by fostersdesign** [comment]
Thanks, @ottenhoff!

**Pull request merged**
