### PR TITLE
SAK-32243 Hide profile2 wall by default

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by master-bob** [comment]
If deprecating, everything in ProfileWallLogic.java should be deprecated (maybe in other places as well).

**Comment by adrianfish** [comment]
I'll mark the api as deprecated, too.

**Comment by adrianfish** [comment]
I've added deprecated markers to the wall logic classes.

**Comment by ottenhoff** [comment]
This looks good to me now. @jonespm ?

**Pull request merged**
