### PR TITLE
SAK-33994 remove unused tomahawk dependency

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Might be a lot more to remove ............. one more commit coming

**Comment by bjones86** [comment]
Stand alone edu-services?!? never heard of it....

-4500 lines == fantastic though!

**Comment by ottenhoff** [comment]
Matt says it was to support a standalone gradebook and samigo. Obviously two very dead concepts.

**Comment by bjones86** [comment]
Haha, yeah that's news to me. Off with their heads!

**Comment by ottenhoff** [comment]
Can someone test this locally and confirm? It's removing lots of code. Works for me.

**Comment by jonespm** [comment]
Yeah, it works and tests out for these locally. 

It's looks like some of these classes may have been used also for the unit tests back in sections tool[1], but those tests don't look like they've been running since 2006. There's better ways to mock up impls now. So probably could get these tests running again and worth just leaving them around rather than removing them. Otherwise it's looking good.

[1] sections/sections-app/src/test/org/sakaiproject/test/

**Pull request merged**
