### PR TITLE
SAK-48698 Sections when a student disappears from a site an NPE results when membership changes

### PR DESCRIPTION
**Pull request by alejandromf**

### CODE REVIEW

**Comment by ern** [comment]
Thanks @alejandromf for the PR, I was reviewing this PR and I ended up checking it out and made some improvements. If you could give it a test that would be great I believe the NPE was in the method org.sakaiproject.component.section.sakai.SectionManagerImpl#getUserRoleFromSite

**Comment by alejandromf** [comment]
Hello Earle. I'm sorry but it doesn't work. 
When getUserRoleFromSite() returns a null, then on line 1010 it does "if (!(sakaiRoles.contains(userRole))", it goes in here and throws a RoleConfigurationException stopping the for loop.

In my example the group had 12 students, when this happened it left the group with only 4.

image

**Comment by ern** [comment]
Thanks @alejandromf for looking, much appreciated.
My apologies for not testing, I will take another stab at it!

**Comment by alejandromf** [comment]
I uploaded the changes applying yours before, but I didn't know that the "push --force" deletes your commits, sorry

**Comment by ern** [comment]
All good thanks again 👍

**Review by ern — APPROVED** [review]

**Pull request merged**
