### PR TITLE
SAK-31315 Backport DB changes from SAK-31184 for 11.x

### PR DESCRIPTION
**Pull request by master-bob**
This change backports only the database changes from SAK-31184 in
order to reduce migration issues in the future.

Also see #2761 , which adds the sakai_11_*_conversion.sql changes to master.

EDIT: This PR was made against 11.x as it specifically is for the 11.x branch, it is outside the norm of a typical PR. Please let me know if further clarification is needed.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Can we just do a complete sync of master to 11.x for references/docs/conversion before we release?

**Comment by master-bob** [comment]
That would work for the references/docs/conversion scripts (where changes have been made in master), but the feedback changes in the "feedback/src/java/*/createtables.sql" files I believe are necessary. If the changes in those files are not accepted into 11.0 than the whole point of SAK-31315 would be moot.

The point of SAK-31315 was that I felt it was less work to get these small feedback database changes into 11.0 than to write and test a conversion script for the oracle based changes as Oracle does not allow for an easy way to expand constraints.

**Comment by ottenhoff** [comment]
Okay the branch maintainer can just merge SAK-31315 into 11.x then, right? Is there anything special here?

**Comment by master-bob** [comment]
@ottenhoff, this PR should just be accepted.

Please see [this thread](https://groups.google.com/a/apereo.org/d/msg/sakai-dev/ukzRqASFu3A/-APpwKpDBwAJ) on the dev list for the reasoning. A TL:DR is this change is less complex than writing a port for the oracle tables.

**Comment by juanjmerono** [comment]
I think this change is not complex for oracle at all, even the table is already created, just removed and add the constraint again:

alter table SAKAI_FEEDBACK drop constraint cons_report_type;
alter table SAKAI_FEEDBACK add constraint cons_report_type check (report_type IN ('content','technical','helpdesk','suggestions','supplementala','supplementalb')) enable validate;

The "enable validate" have to check all the values in the table, this is the only problem you could have if you have a very big table when you move from 11.x to 11.y.

**Comment by master-bob** [comment]
@juanjmerono I did not know that was an option. My earlier research implied the table had to be recreated from scratch.

**Pull request closed without merging**
