### PR TITLE
SAK-40634 Update autosave and wordcount CKEDITOR plugins to 4.10.1

### PR DESCRIPTION
**Pull request by mpellicer**
This PR should be 100% broken as the maven artifacts of this plugins may not exist in the maven repo, I still need to learn how to do it. The image2, wordcount, autosave and ballon plugins need to be populated in the maven repos.

### CODE REVIEW

**Comment by mpellicer** [comment]
I've decided to upgrade to the wordcount v1.17.3, this PR build may be broken until the v1.17.3 is populated in the maven repos.

**Comment by mpellicer** [comment]
This is ready to go!

**Comment by mpellicer** [comment]
Looks like AccessLint is stuck so I can't merge the PR, anyone knows how to restart the AccessLint build?

**Comment by fostersdesign** [comment]
According to @juanjmerono to the Core team, this PR is causing the Jenkins build to fail on the nightlies:

> The problem is caused by this jira: https://jira.sakaiproject.org/browse/SAK-40634
> This PR: https://github.com/sakaiproject/sakai/pull/6003
> 
> I guess this pom is not right: https://github.com/sakaiproject/sakai/blob/master/webjars/ckeditor-image2/pom.xml
> 
> The parent pom should be master instead of oss-parent to be able to read ${ckeditor.image2.version} variable.
> 
> I'm wondering why that PR was not compiled by travis before the merge.

**Comment by jonespm** [comment]
The parent pom is correct. The version in the ckeditor-image2/pom.xml should have remained a static value of 4.9.2. There are comments there about that. Didn't notice that in the PR.

It cannot bind to master because it has to be released independently and master is a snapshot.

**Pull request merged**
