### PR TITLE
SAK-44579 matching unicode FIB needs help when user input from Mac is HTML-encoded

### PR DESCRIPTION
**Pull request by ottenhoff**
…

### CODE REVIEW

**Review by ern — APPROVED** [review]
👏  for unit tests

**Review by bjones86 — APPROVED** [review]
Nice stuff

**Review by jesusmmp — APPROVED** [review]
LGTM. Great work @ottenhoff !
A question... Is this problem happening on calculated questions too?

**Comment by ottenhoff** [comment]
I'm not sure. We noticed this only while inputting special characters on a Mac using the Unicode virtual keyboard. 

If you can think of some examples with calculated questions, please create a new JIRA .

**Pull request merged**
