### PR TITLE
SAK-29517: Send comments to gradebook from Assignments for internal g…

### PR DESCRIPTION
**Pull request by cschauer**
…b assignments

### CODE REVIEW

**Comment by jonespm** [comment]
Hey Chris, thanks for the the patch. It looks like there was a build error directly related to this 
```
[ERROR] /home/travis/build/sakaiproject/sakai/assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java:[5170,131] incompatible types: java.lang.String cannot be converted to java.lang.Long
[ERROR] /home/travis/build/sakaiproject/sakai/assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java:[5211,131] incompatible types: java.lang.String cannot be converted to java.lang.Long
```

I can review this after that's updated as I've heard of some other issues around getting the comments correctly sent over.

**Comment by cschauer** [comment]
Doh, that's what I get for copying the patch over from 10.4 without checking. GradebookService.setAssignmentScoreComment was changed to take the assignment id instead of the assignment title. It looks like the Assignment tool's gb integration is out of date. It uses gb assignment titles to track the gb assignments. I wonder how much effort it would take to change this to use the assignment id instead.

**Comment by steveswinsburg** [comment]
I made that gradebook service change a few weeks ago,  however retained the
functionality where it wasn't feasible to use the gb assignment id. It
would be ideal if assignments did use the id though, passing the assignment
name is dodgy.

sent from my mobile device

**Comment by ern** [comment]
I didn't see this patch til after sent in a PR for this see #990

**Comment by jonespm** [comment]
I merged 940, it looks like the same thing and had some additional comments and cleanup on it. Thanks for the contribution though, sorry this was missed.

**Pull request closed without merging**
