### PR TITLE
LSNBLDR-630 - deleteOrphanPages API inaccessible from service

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Is this good to merge?

**Comment by ottenhoff** [comment]
@clhedrick are you okay with this modification?

**Comment by clhedrick** [comment]
The code looks good. But I'd like to see it a POST if that's not going to cause you issues in your application. CSRF protection won't be done for GET because it's assumed that GET can't change things. Admittedly this isn't something that causes a big risk, but still I think the convention is that GETs should just get information.

**Comment by ottenhoff** [comment]
>  But I'd like to see it a POST if that's not going to cause you issues in your application. 

Okay, let's just remove the \@GET annotation....

**Comment by clhedrick** [comment]
Yeah, it looks OK. But isn't there a convention that GET is used only to get information. I thought POST, PUT, or DELETE was supposed to be used for changes. I don't see any security issue with GET as long as passing a session ID in the parameters doesn't bother you.

**Comment by jonespm** [comment]
It actually looks like everything in webservices is GET. I think some of these *should* probably be POST, PUT or DELETE like you're saying. I don't think it would matter that much to us.

**Comment by clhedrick** [comment]
OK, then let’s accept it as is.

On May 13, 2016, at 10:34 AM, Code Hugger (Matthew Jones) <notifications@github.com<mailto:notifications@github.com>> wrote:


It actually looks like everything in webservices is GET. I think some of these should probably be POST, PUT or DELETE like you're saying. I don't think it would matter that much to us.

**Comment by clhedrick** [comment]
I guess the idea is that REST works with GET. As long as you require a session ID as argument it’s not a CSRF danger.

On May 13, 2016, at 10:34 AM, Code Hugger (Matthew Jones) <notifications@github.com<mailto:notifications@github.com>> wrote:


It actually looks like everything in webservices is GET. I think some of these should probably be POST, PUT or DELETE like you're saying. I don't think it would matter that much to us.

**Comment by jonespm** [comment]
Yeah, right these webservices require you to supply a session id. And generally the webservice end points are IP restricted as well.  It also requires you to either be an admin or site maintainer for the site you pass in, though I'd bet 100% of the time it will be an admin session using this. (I also just noticed a slight issue with the warning message being incorrect as it was copied from the CopySite() webservice.)

**Pull request merged**
