### PR TITLE
SAK-50525 Calendar promise may not have finished loading i18n data

### PR DESCRIPTION
**Pull request by maurercw**
…ot yet be loaded on initial render

### CODE REVIEW

**Review by ottenhoff — APPROVED** [review]
thanks

**Comment by ottenhoff** [comment]
From Slack convo:

```
Related, there was a comment in there that was removed back in early September…
    // This is a hack. There’s something about the way Lion’s calendar connects and renders which
    // means we can’t wait for this._i18n in shouldUpdate. So, we add placeholders in the _i18n
    // object. Nasty. If I can work it out, I’ll come back and fix this.
    //TODO: Fix this properly
    this._i18n = { “days_message”: “”, “events_for”: “”, today: “” };
I’m guessing Adrian figured something out to get around it, but maybe only partially so?
```

**Comment by adrianfish** [comment]
@ottenhoff Ah, right. I thought an update to lion had sorted it out because I didn't see any issues when I removed those placeholders.

**Comment by ottenhoff** [comment]
@adrianfish okay with merging or should we leave open for a few days?

**Pull request merged**
