### PR TITLE
SAK-31136 remove old JSF limits around characters

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by jonespm** [comment]
For people with really old systems they *might* need a conversion. Need someone on 2.9 or earlier to check their types to see if they're TEXT or LONGTEXT. No harm in running it tho.

ALTER TABLE MFR_MESSAGE_T MODIFY BODY LONGTEXT;
ALTER TABLE MFR_TOPIC_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
ALTER TABLE MFR_OPEN_FORUM_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;

**Comment by jonespm** [comment]
Otherwise looks good, a change that should have been made years ago, eliminates all limits outside samigo.

**Comment by ern** [comment]
I am not sure removing the validation length is wise, shouldn't it just increase to the size of LONGTEXT?

**Comment by jonespm** [comment]
longtext has a 4GB limit. If someone put that much text in then they'd end up with some other error before this from antisamy (currently 100K) or something. Planning on putting a limit in the UI at SAK-31717. So really doesn't seem that necessary to have.

**Comment by ern** [comment]
So maybe the length of LONGTEXT is not the right length but if someone were to put in a text that was longer having the UI give an error is much better than some error in the log.

**Comment by ottenhoff** [comment]
Can someone provide me the Oracle equivalent of 

ALTER TABLE MFR_MESSAGE_T MODIFY BODY LONGTEXT;
ALTER TABLE MFR_TOPIC_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
ALTER TABLE MFR_OPEN_FORUM_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;

**Comment by jonespm** [comment]
I wonder what these columns are in older versions of Oracle. LONG? CLOB?

**Comment by juanjmerono** [comment]
Maybe LONG @jonespm but I think those columns are CLOB since Sakai 2.7 (Oracle 9)

**Comment by ottenhoff** [comment]
Okay it looks like these columns are already good on the Oracle database I looked at (CLOB).

**Comment by ottenhoff** [comment]
Added the MySQL conversion

**Pull request merged**
