### PR TITLE
SAK-31633 Add alt text for sorting icons in the table header columns

### PR DESCRIPTION
**Pull request by yuanhuaqu**
rA11y for signup sorting icons alt text.  Internationalized.

### CODE REVIEW

**Comment by ottenhoff** [comment]
I think the text should be active: "Sort in .." instead of passive ("Sorted in....")

**Comment by yuanhuaqu** [comment]
Thanks.  That  is the help I needed for English wording.  But before I make a change, I'd like to express that it makes sense to me when it says "Sorted in.." since the icon shows the state of already sorted order, not what order you want for your next click for sort.  Does it make sense to you too? Or you still think "Sort in ..."  will be better?  Here is the screenshot of it. 
screen shot 2016-10-20 at 1 24 47 pm

**Comment by ottenhoff** [comment]
I believe the icon should tell the user what action will be performed with a new click.

CC: @mclare

**Comment by yuanhuaqu** [comment]
I checked the other tools and seems "Sort in ..."  is the right expression.  But icon for current state or will be performed are not consistent across tools; though seems most shows current state.  (Syllabus, signup, site info, assignment.... shows current sorting state;  whereas samigo shows what's gonna performed).  Thoughts? Copied this into related JIRA.

**Comment by mclare** [comment]
I agree that it should tell the user what action will be performed with a new click.  Looking at Assignments, Announcements, Resources and Worksite Setup, it's "Sort by..." - describing what will happen to the list when the link is clicked. (note, BY instead of IN). Here's the supporting screenshots https://drive.google.com/open?id=0B2ewqZFNbUdqaXAyd2dONXE0enM

**Pull request merged**
