### PR TITLE
SAK-32358 - Sitestats: Unable to update or delete a report.

### PR DESCRIPTION
**Pull request by mpellicer**
SAK-32358 - Sitestats: Unable to update or delete a report.

### CODE REVIEW

**Comment by buckett** [comment]
This doesn't look to be the right way to fix this, I think the Site Stats beans are currently not wired up correctly. Although transaction proxies are created they have different bean IDs that aren't referenced anywhere. The normal pattern is to have the proxy have the correct bean ID and to have the internal bean have an internal ID.

**Comment by mpellicer** [comment]
So, will this require a lot of changes in the bean definitions? I can help but i don't know exactly how to proceed, so probably this will require more expertise.

Thanks

**Comment by buckett** [comment]
There's an example here: https://github.com/buckett/sakai/tree/SAK-32358 but this doesn't currently work due to the circular dependencies.

**Comment by mpellicer** [comment]
Thanks @buckett , i don't want to waste your valuable time, sorry in advance.

I've implemented the changes from your branch and it doesn't work, the log says something like this:

06-jul-2017 09:01:23.746 WARN [http-apr-8080-exec-7] org.sakaiproject.sitestats.impl.report.ReportManagerImpl.lambda$saveReportDefinition$1 Unable to commit transaction: 
org.hibernate.TransactionException: nested transactions not supported
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:154)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1471)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.hibernate4.HibernateTemplate$CloseSuppressingInvocationHandler.invoke(HibernateTemplate.java:1244)
	at com.sun.proxy.$Proxy68.beginTransaction(Unknown Source)
	at org.sakaiproject.sitestats.impl.report.ReportManagerImpl.lambda$saveReportDefinition$1(ReportManagerImpl.java:612)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:341)
	at org.springframework.orm.hibernate4.HibernateTemplate.execute(HibernateTemplate.java:296)
	at org.sakaiproject.sitestats.impl.report.ReportManagerImpl.saveReportDefinition(ReportManagerImpl.java:622)

**Comment by mpellicer** [comment]
Definitely is something we should discuss with priority, i've raised this Jira:

https://jira.sakaiproject.org/browse/SAK-32358

The Jira is similar to this issue but only affects Oracle, cannot confirm yet it has relation with the Hibernate4 upgrade.

**Comment by ern** [comment]
Hi Miguel,

I took a look at this and located the issue will be submitting a new PR soon.

The simple answer is that the transaction proxy (TransactionProxyFactoryBean) for StatsManager was not injected into the beans correctly.

**Comment by mpellicer** [comment]
Thanks @ern , let me know where i can help, i'll test your PR when available. If you gimme one example to proceed i can complete the entire work, don't want to disturb you.

We also found a potential related problem in the JobScheduler, in ContextMappingDao.

Regards, Miguel

**Comment by mpellicer** [comment]
The potential related problem is here:

https://github.com/sakaiproject/sakai/pull/4590

**Comment by ern** [comment]
Going close this as this will be fixed in pull #4605

**Pull request closed without merging**
