### PR TITLE
SAK-25903 Upgrade to Java 8.

### PR DESCRIPTION
**Pull request by buckett**
With a local build of reflect-utils this builds and starts up for me (with tests) using Java 8.
Entitybroker works (quick rough test).

These are basically the changes @jonespm suggested in email.

### CODE REVIEW

**Comment by jonespm** [comment]
Changing this to SNAPSHOT can't be made until the artifact is actually in a snapshot repository (or released) since reflectutils isn't part of the Sakai build. This would cause the builds to fail.

**Comment by buckett** [comment]
Thanks @jonespm, I should have been more explicit (than just using the tag), I just pushed this so people could see exactly what was needed.

**Comment by buckett** [comment]
And this requires Java 8 to run, rather than just making it compile with Java 8.

**Comment by jonespm** [comment]
Yeah, I think we'd give a heads up to the dev list before all of that. As of April 2015 Java 7 is EOL so that's all good timing. Just wanted to put a temporary hold on merging this PR so we can notify about the Java 8 requirement and get this library released/deployed.

**Comment by jonespm** [comment]
The nightlies got switched yesterday(2015-04-16) to running on JRE 8, but it's currently still building off of JDK 7.

**Comment by buckett** [comment]
Aaron release a snapshot version of reflectutils to the maven repository and in the short term I think we can switch to using that for Java 8 builds.

We should switch to a released version one it seems we're reasonably confident that there aren't any more issues with reflect utils and Java 8.

**Pull request merged**
