### PR TITLE
SAK-32284 move collapse to bottom of tool menu

### PR DESCRIPTION
**Pull request by ottenhoff**
nyu-collapse

### CODE REVIEW

**Comment by buckett** [comment]
With short tool content and a reasonably number of tools the page isn't scrollable and the help tool isn't visible (or whatever the last tool is):

screen shot 2017-03-09 at 09 34 25

**Comment by buckett** [comment]
I wonder if we should have placeholder below the tool menu which is the same size as the fixed position collapse item, so when the page is scrolled to the bottom the placeholder is under it and we always know that the actual content of the page is always visible.

**Comment by lardo-de-arnaud** [comment]
great change. Go for it

**Comment by ern** [comment]
Lets get conflict resolved and merged.

**Pull request closed without merging**
