### PR TITLE
SAK-30974 Start date and end date modal overlap

### PR DESCRIPTION
**Pull request by josecebe**

### CODE REVIEW

**Comment by ncaidin** [comment]
Hi @josecebe , do you have an ICLA on file with Apereo? I don't see you listed on http://licensing.apereo.org/.

Please submit an ICLA (individual contributor license) per information on https://www.apereo.org/licensing.

Please let me know if you have any questions. 

Thanks!

**Comment by jonespm** [comment]
I think looking at[ images on the jira](https://jira.sakaiproject.org/browse/SAK-30974) that the original layout of even with the overlap is better than having it on 3 rows with the date split up. If this isn't going to get changed to a picker, at most it could be a row for date and a row for time rather than 3 rows.

**Comment by mpellicer** [comment]
Hi @ncaidin, @josecebe is part of Entornos de Formación, is he covered by our CCLA or does he need to sign an ICLA?

Regards, Miguel

**Comment by jonespm** [comment]
@mpellicer Yeah, everyone needs to have their own ICLA as well as the CCLA (if they are working for a company) Then they'll come up on the [CLA list.](http://licensing.apereo.org/completed-clas)

**Comment by mpellicer** [comment]
Thanks @jonespm, he'll sign the ICLA asap.

**Comment by josecebe** [comment]
As @jonespm requested:
syllabus_pr

**Comment by mpellicer** [comment]
ICLA sent!

**Comment by ncaidin** [comment]
CLA received and processed.

**Pull request merged**
