### PR TITLE
SAK-41767 Assignment Bullhorns should check permissions against addre…

### PR DESCRIPTION
**Pull request by bgarciaentornos**
…ssee

### CODE REVIEW

**Comment by bgarciaentornos** [comment]
@ern Can you please review this? Thanks!

I've created some required permission checking methods as private, but maybe you prefer to add them to the service and make them public. Also we could extend that parameter user option to the rest of the similar methods, for the moment I just did it for the ones who needed it.

**Comment by bgarciaentornos** [comment]
Ok, but I didn't really add methods to the API so I guess this works?

**Comment by adrianfish** [comment]
@ern I think Bernardo's change here is fine, still. If he'd of changed allowGetAssignment by adding the userId he would have broken tool integrations. Moving the logic into a private method for use inside the class makes sense to me. I'm not too sure about the idea of having lots of method arguments being better than overloading, either. Won't that just lead to lots of switch type constructs inside the method, trying to work out the path to take?

**Comment by adrianfish** [comment]
@bgarciaentornos We talked this over on the core call and I think Earle probably has a point. He's really keen on keeping methods down to a minimum unless really required, even if they are private  and not part of the public api. I'd agree with him up to the point where there are loads of method arguments. So, could you look at refactoring this to just add more params to the existing methods, perhaps making use of Optional?

**Comment by bgarciaentornos** [comment]
Refactored this to use less methods as requested.

**Comment by bgarciaentornos** [comment]
I believe that's a different thing? Unless I'm looking at the wrong method.

**Comment by adrianfish** [comment]
Sorry, soy tonto. You're right :)

**Pull request merged**
