### PR TITLE
S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix

### PR DESCRIPTION
**Pull request by JuanDavid102**

### CODE REVIEW

**Comment by JuanDavid102** [comment]
Now the students with the create/edition premissions can create/edit page but can’t change the rwiki pages, unless the student has admin permissions

**Comment by mpellicer** [comment]
> Now the students with the create/edition premissions can create/edit page but can’t change the rwiki pages, unless the student has admin permissions

WDYM? When I'm a student......

- Can I create a page and set the groups?
- Can I edit a page and set the groups?
- As student do I see groups?

I think all of that should be reserved to instructors.

**Comment by JuanDavid102** [comment]
Yes, know the student can't create a pge with groups, and cannot set the groups, and can't see the groups. Unless an instructor, in the special permissions of rwiki page, checked the admin permissions to the students 
imagen

**Comment by JuanDavid102** [comment]
Because now check this permissions

**Comment by mpellicer** [comment]
But the students can create pages as usual, right? The only difference is that is not able to set groups?

**Pull request merged**
