### PR TITLE
SAK-49209 - Avoid double URL encoding - use Base62 for url within url

### PR DESCRIPTION
**Pull request by csev**

### CODE REVIEW

**Review by ottenhoff — APPROVED** [review]

**Comment by ern** [comment]
Dr Chuck there are a number of Base62 encoders in maven central, better to use one of those than rolling your own.

**Review by ern — CHANGES_REQUESTED** [review]
left comment Base62

**Comment by jonespm** [comment]
Base62 decoders, neither of these seem to be used much and haven't been updated in awhile. 

- https://github.com/unbroken-dome/base62
- https://github.com/seruco/base62

I saw this more featureful library looks more popular and has more maintenance activity. It has a lot of different Codecs in it so we could use this in other places. https://github.com/f4b6a3/uuid-creator/wiki/4.0.-Library-codecs#base-62-format
- https://github.com/f4b6a3/uuid-creator

**Comment by csev** [comment]
Matt, the problem with most Base62 encoders is that they are used for "longs" in UUID serialization.   Few actually do string-to-string-back-to-string encoding.  And I do not want to add another dependency to something that receives less open source support than Sakai.  I do not want to repeat the GenericDAO, RSF, ... folly.

**Comment by csev** [comment]
@ern I checked if the java.util.Base-64 url-safe encoding was safe for double encoding - it was not.  I will add a unit test to verify this.   I also wrote a unit test to use io.jsonwebtoken.io.Base64 which we both noticed did not add padding and is why JWTs are safe for double URL encoding.  But alas,  the jjwt-api authors fear their fork of Base64 escaping the library and so made it protected so it is only usable in class-siblings.   I am guessing they did not want anyone using it as a generic Base64, being interoperable, and then being later criticised. Methinks they would have been smarter to use Base32 with string signatures and then making it public so I could have used it :)

**Review by ern — APPROVED** [review]
Thanks for looking!

**Comment by jonespm** [comment]
I just offered a few packages as Earle had made the suggestion. I'm fine with what's here but I also generally prefer trying to find a maintained library over adding code that one of us mght have to fix a bug in someday. 

This has unit tests and I don't have time to test an alternative so seems fine to me. Thanks!

**Pull request merged**
