### PR TITLE
SAK-31713 Move library to top level project

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by ottenhoff** [comment]
I agree with this change but isn't this going to make merging a nightmare unless we also make the change to 11.x?

**Comment by steveswinsburg** [comment]
Yeah if this is solid then a case could be made for 11.x/11.2?

sent from my mobile

**Comment by jonespm** [comment]
I think it makes sense and it's better to have it at the top level, but I agree that if it's not merged back it's going to cause merge conflicts. I don't know if I'd say this belongs more in an 11.2 or a 12.0. I feel like this directory should be something that's really easy to checkout by itself, find and build.  That improves that. So maybe 11.2 does make sense. I'd wait on actually *doing* this then probably until we get much closer to 11.2, so this jira will either need a rebase and update or just a recreation then.

**Comment by ern** [comment]
Yep agree on the points discussed... Will rebase it when we get closer to 11.2.

**Comment by buckett** [comment]
We also have other changes in /reference/library so it makes local merges more complicated to perform as well.

**Comment by SedueRey** [comment]
My two cents ... if we are going to migrate library, why don't we split skins to a separate folder? It would be awesome for designers :)

**Comment by ern** [comment]
@SedueRey thats good idea we should put that in a separate issue.

**Pull request merged**
