### PR TITLE
LSNBLDR-838 Delete button in edit textbox doesn't have confirm dialog

### PR DESCRIPTION
**Pull request by Johnson-Mickey**

### CODE REVIEW

**Comment by lgekeler** [comment]
It's possible that the confirmation dialogue was removed on purpose. Many people do not want to click another time to indicate their intention. How do we answer this question?

**Comment by ern** [comment]
After a quick review it would seem that "ConfirmDelete" would indicate a confirmation is needed:
jQuery(document).ready(function($) {
	var confirmMsg = document.getElementById('confirmDeleteLangSupp').innerHTML;
    $('.ConfirmDelete').click(function() {
        return confirm(confirmMsg);
    });
});

So I am not understanding the comment on this issue?

**Comment by lgekeler** [comment]
Why are we confirming a delete in the first place is all I meant.

**Comment by ern** [comment]
Laura, I was referring to the commit message on this!

**Comment by Johnson-Mickey** [comment]
Ern, agreed that confirmation is needed. Sorry for the ambiguity.

Currently in master no confirmation pane is displayed when the delete button is pressed. This pull request would add (restore?) that behavior.

**Comment by ern** [comment]
@Johnson-Mickey yeah I am wondering if `ConfirmDelete` is broken and if the correct fix is to get that working again?

**Comment by Johnson-Mickey** [comment]
@ern I was curious about ConfirmDelete but if you grep for ConfirmDelete there isn't a CSS class defined as that in Sakai. If you take a look at the history of EditPage.html:
[LSNBLDR-44 - Made the Delete button less prominent while editing text.](https://github.com/sakaiproject/sakai/commit/9e6895657fe81fd34720d54ab823e2ddf9ede48e)
Added the ConfirmDelete stuff,
[LSNBLDR-208; move from branch to trunk](https://github.com/sakaiproject/sakai/commit/73a74aca30d4e5e2d7a347b09ee8439a0b6bb584)
Changed the CSS class from "ConfirmDelete" to "deleteButton" but didn't change the CSS selector.
I think the selector was just missed when the class name was changed, but it's possible I'm completely missing something.

**Comment by ern** [comment]
@Johnson-Mickey thanks for digging into this, would you mind as part of this PR then to remove the remaining references to "ConfirmDelete" and update/remove it from the JS?

**Comment by Johnson-Mickey** [comment]
@ern I just added another commit renaming the items that references 'confirmDelete', if I misunderstood what you were asking for let me know.

**Pull request merged**
