### PR TITLE
SAK-42866 - T&Q: Option to send to GB disappeared

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakaiproject/sakai/pullRequest?prid=4636323&bid=15535075)

**Comment by mpellicer** [comment]
Hey @jonespm, I don't see a difference here, both "sakai.gradebook.tool" and "sakai.gradebookng" tool ids return true in the current IF statement, using "sakai.gradebookng" in the if statement will be compatible only with the new gradebook.

**Comment by mpellicer** [comment]
Ahh ok, I see, I changed the condition in #7602, it was inside a loop.

I think we should use "sakai.gradebook" instead of "sakai.gradebookng", with that change the PR looks good, thank you so much for the work on this.

**Comment by jonespm** [comment]
Yeah thanks for catching that. I wanted to keep it compatible. Will update as soon as I get to a computer in an hour or so.

**Comment by mpellicer** [comment]
@jonespm I made the change, thanks!

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/sakaiproject/sakai/pullRequest?prid=4636323&bid=15535075)

**Comment by jonespm** [comment]
Thanks, not very easy to edit code from a smartphone on a bus. ;)

**Pull request merged**
