### PR TITLE
SAK-49258 Webapi: Add endpoints to get and bulk update various entities

### PR DESCRIPTION
**Pull request by stetsche**
https://sakaiproject.atlassian.net/browse/SAK-49258

### CODE REVIEW

**Comment by mpellicer** [comment]
Could you check the Maven Build please? It's failing

**Comment by stetsche** [comment]
Yes, I have a fix. I needed to do change to the GradingService

**Comment by stetsche** [comment]
@mpellicer This should be ready now!

**Review by mpellicer — APPROVED** [review]
Thank you very much @stetsche !

**Pull request merged**
