### PR TITLE
SAK-46783 - move some dependencies to shared

### PR DESCRIPTION
**Pull request by maurercw**

### CODE REVIEW

**Comment by ern** [comment]
Hi Chris we've been trying to reduce the number modules in kernel and if this doesn't eliminate an existing module not sure that it makes a lot of sense...

**Comment by csev** [comment]
I thought abut that too - but it means a super large kernel module is dragged into all the webapps just because the resource loader is in that module - the rest of the module can be in shared - if we could instead collapse the shared bit into another module that would be great.   But I think this is the most elegant approach to reduce what is drug into webapps unnecessarily.  I am thinking long-term and things like GraalVM for extremely fast startup.  And just saving memory in general.

**Comment by csev** [comment]
I think that the concept of a piece of the kernel that belongs in the webapp that is separately identified is actually a good step forward.

**Comment by csev** [comment]
A someday refactor of kernel would actually be helped by separating out the webapp and non-webapp stuff.

**Comment by maurercw** [comment]
What about adding this stuff to kernel-api instead of the new module that goes in the apps?  I know that blurs the lines a bit between APIs and shared classes available to all apps.

**Comment by maurercw** [comment]
All the changes we talked about today should now be incorporated.
kernel-common and kernel-private have been rolled up into kernel-api.
The "shared" bits of kernel-util are also up in kernel-api.
The application specific bits remain in kernel-util, and get bundled up with the war

**Review by ern — APPROVED** [review]

**Pull request merged**
