### PR TITLE
SAK-30207 content review reorgnaization

### PR DESCRIPTION
**Pull request by ern**
This is a complete reorganization of the content review project. The goals were:

- Move the content review implementations into sakai and eliminate steps to include review implementations separately.
- enable review implementations using the content review federate service introduced by @jonespm 
- remove genericdao and replace with a standard hibernate spring DAO layer and service
- left out the the roster sync logic and table contentreview_sync_item (may need to add)
- table contentreview_lock was removed using hibernates optimistic locking instead
- simplify the project layout
- almost no changes to the ContentReviewService api (for compatibility)
- DB access has been moved from turnitin impl so that any implementation can store items in the queue

TODO
- add documentation MD
- database upgrade scripts
- get feedback

### CODE REVIEW

**Comment by baholladay** [comment]
What are the properties to enable/disable TII & VeriCite?

**Comment by ern** [comment]
The option for enabling providers is the following:
contentreview.enabledProviders=VeriCite,Turnitin

you would also probably use the following if you configured more than 1 provider:
contentreview.defaultProvider=VeriCite

If you did not configure any providers which would be the default out of the box then a NoOp provider is used.

**Comment by ern** [comment]
So this PR should be ready to go as
SQL scripts were added
Documentation Updated

**Comment by baholladay** [comment]
I went over the code and changes with @ern  This is a great improvement to the old Content Review and it doesn't break the API for tools like Assignments. Looks great!

**Pull request merged**
