### PR TITLE
Removed whitespace before full stop.

### PR DESCRIPTION
**Pull request by favour-olumese**

### CODE REVIEW

**Review by jesusmmp — APPROVED** [review]

**Comment by bgarciaentornos** [comment]
Hi! Before the first code submission is accepted, you will need to submit a Contributor License Agreement (CLA). This is a one-off process that should only take a few moments to complete. See: https://www.apereo.org/licensing/agreements

Thanks!

**Comment by favour-olumese** [comment]
> Hi! Before the first code submission is accepted, you will need to submit a Contributor License Agreement (CLA). This is a one-off process that should only take a few moments to complete. See: https://www.apereo.org/licensing/agreements
> 
> Thanks!

I tried printing the form to fill it, but it is not printing. What do I do?

**Comment by bgarciaentornos** [comment]
I think you can just submit this online form directly:

https://www.apereo.org/licensing/agreements/icla

**Comment by favour-olumese** [comment]
> I think you can just submit this online form directly:
> 
> https://www.apereo.org/licensing/agreements/icla

I have filled the form. Thank you.

**Review by jesusmmp — APPROVED** [review]

**Comment by kunaljaykam** [comment]
I have checked the list. Thanks, @favour-olumese for submitting the CLA.

**Review by kunaljaykam — APPROVED** [review]

**Pull request merged**
