### PR TITLE
IGNORE: Introduced bad unicode characters on purpose - Build must fail

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Okay seems like my github actions not working as expected, correct?

**Comment by mpellicer** [comment]
@ottenhoff 

I wanted to help you with an example of a wrong PR, looks like it's not making the build fail :(

**Comment by ottenhoff** [comment]
Thank you. I've abandoned that custom Github action for a simple bash script!

**Comment by stetsche** [comment]
I am not a regex pro, but I tested it a bit and it seems to only match if the last digit is faulty.
For me it seems there is missing some negation, like `\\u[^0-9a-fA-F]...` seems to work, but I am not sure how to chain that for 4 characters

**Comment by stetsche** [comment]
Looking at it again, I think the last character is what you are actually testing, right?

**Comment by ottenhoff** [comment]
yes! nice suggestion, please check out my latest PR I now have 4 separate greps

**Pull request closed without merging**
