### PR TITLE
SAK-43542 Assignments: Provide more information in Removed Assignments/Trash list

### PR DESCRIPTION
**Pull request by josecebe**
image

This is paired with https://github.com/sakaiproject/sakai-reference/pull/179

### CODE REVIEW

**Comment by mpellicer** [comment]
Clean and neat @josecebe, thanks, would you mind providing the conversion scripts and link them to the PR?

**Review by mpellicer — CHANGES_REQUESTED** [review]
Conversion scripts required,

**Comment by josecebe** [comment]
Thanks for the review @mpellicer, I have added the conversion script https://github.com/sakaiproject/sakai-reference/pull/179

**Review by mpellicer — APPROVED** [review]

**Comment by jesusmmp** [comment]
Awesome work! @josecebe

**Pull request merged**
