### PR TITLE
SAK-31732 - Change CKEditor default body style to match regular portal

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
What do you think about this @SedueRey ? Do you think this style is appropriate to use for the CKEditor or we need a new one? tool.css didn't look right but print.css looks pretty good to me.

**Comment by SedueRey** [comment]
Could you upload a screenshot? I don't know how it looks like

**Comment by jonespm** [comment]
@SedueRey I put up an image on the jira https://jira.sakaiproject.org/browse/SAK-31732

**Comment by SedueRey** [comment]
it looks great. Thanks!

**Pull request merged**
