### PR TITLE
SAK-43537 - Tests&Quizzes: MCSC questions, the submission scores ques…

### PR DESCRIPTION
**Pull request by mpellicer**
…tions are not aligned when answers have long text

### CODE REVIEW

**Comment by ern** [comment]
Does the use of <ul><li/><ul/> make sense here?

**Comment by mpellicer** [comment]
Whats the JSF tag for a UL list?

**Comment by ottenhoff** [comment]
If Tomahawk is being used: http://myfaces.apache.org/tomahawk-project/tomahawk/tagdoc/t_dataList.html

**Comment by mpellicer** [comment]
Thank you so much @ottenhoff , looks good to me as dataList:

image

**Comment by mpellicer** [comment]
Don't mention it Sam! Thanks Sam & Earle.

**Pull request merged**
