### PR TITLE
SAK-29985 start using bootstrap classes in assignments velocity templates

### PR DESCRIPTION
**Pull request by ottenhoff**
This is my first work on making a tool more responsive so review would be appreciated....

assign-bootstrap

### CODE REVIEW

**Comment by SedueRey** [comment]
Hi, Sam

Are you thinking to fix issues on Assignments tool? Maybe you could write it on Morpheus QA Spreedsheet so anyone else may start to do it and two developers duplicate efforts.

https://docs.google.com/spreadsheets/d/1RhM6Gi6npGQVWTetRnWVW4ONrL9A_TTV5SPC0nlub4w/edit#gid=12

If you have any doubt about this spreadsheet feel free to ask on Slack ( sakaiqa or sakaimorpheusdev )

**Comment by ottenhoff** [comment]
I don't know if I am looking to fix all of those 40 issues.... 

But this PR seems to resolve many of those *alignment issues* by using the Bootstrap grid.

**Comment by juanjmerono** [comment]
I guess we could merge this and then review what issues are still present. My only concern here is about how to track things right in order to get merged into 11.x properly. The SAK-29985 is an umbrella jira (only we'll close it when the complete tool is fixed), but you solve only the add assignment screen, so it would be better to use another jira (subtask of this parent one) to be able to mark it with "11 status" and follow the cycle to merge into 11.x. Sounds reasonable?

**Comment by ottenhoff** [comment]
> you solve only the add assignment screen

I solve more than the "add assignment screen"

assign-list

assign-options

**Comment by juanjmerono** [comment]
Sorry !! That's more than I thought... Do you think the tool is fixed almost completely? I mean if you fixed 70% of the issues we can merge it (add 11 status), close this jira and open a new one for the remaining issues. The original plan was made a single PR for each tool that solves all high priority issues listed in the spreadsheet, I don't care if we use more than one, but I don't want to lose the track of any of them, because the work ends only after merge code into 11.x.

+1 To merge this and add "11 status" = Merge into the SAK-29985

**Comment by ottenhoff** [comment]
I didn't know the spreadsheet existed, but my PR uses the bootstrap grid to fix the alignment issues. I also fixed several tables and generally cleaned up the HTML.

Does anyone else want to work on Assignments this week? If yes, feel free to grab my branch and submit a PR against my branch or to submit a new PR....

**Comment by juanjmerono** [comment]
Don't worry Sam your work is awesome and really appreciated !! Let's go with this one and we'll create a new jira for the remaining issues if needed :+1:
@SedueRey anything else on this?

**Comment by SedueRey** [comment]
:+1:

**Pull request merged**
