### PR TITLE
SAK-29246 Add API method to update assignment order

### PR DESCRIPTION
**Pull request by steveswinsburg**
The gradebook UI has the ability to update an assignment's order. However this is not exposed as an API method in the GradebookService so other applications cannot interact with the ordering.

This feature adds an API method to GradebookService to allow updating of the order of an assignment.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Note that this is required for the GradebookNG work where assignments can be dragged and dropped into order.

**Comment by ottenhoff** [comment]
+1 looks good

**Comment by steveswinsburg** [comment]
The build failure doesn't look related to this.

**Comment by buckett** [comment]
I think this broke the build as after this got merged all builds are failing:
```
[ERROR] /home/travis/build/sakaiproject/sakai/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java:[2727,48] no suitable method found for getAssignments(java.lang.Long,java.lang.String,boolean)
[ERROR] method org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getAssignments(java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getAssignments(java.lang.Long,org.sakaiproject.service.gradebook.shared.SortType,boolean) is not applicable
[ERROR] (actual argument java.lang.String cannot be converted to org.sakaiproject.service.gradebook.shared.SortType by method invocation conversion)
[ERROR] method org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getAssignments(java.lang.String,org.sakaiproject.service.gradebook.shared.SortType) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getAssignments(java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sakaiproject.component.gradebook.BaseHibernateManager.getAssignments(java.lang.Long,org.hibernate.Session) is not applicable
[ERROR] (actual and formal argument lists differ in length)
```
The build failure for this pull request was for a test in elasticsearch that intermittently fails:
```
Running org.sakaiproject.search.elasticsearch.ElasticSearchTest
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.584 sec <<< FAILURE! - in org.sakaiproject.search.elasticsearch.ElasticSearchTest
testRebuildSiteIndex(org.sakaiproject.search.elasticsearch.ElasticSearchTest)  Time elapsed: 2.111 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.sakaiproject.search.elasticsearch.ElasticSearchTest.testRebuildSiteIndex(ElasticSearchTest.java:429)


Results :

Failed tests: 
  ElasticSearchTest.testRebuildSiteIndex:429 null
```

**Comment by steveswinsburg** [comment]
This should be fixed now.

**Pull request merged**
