### PR TITLE
SAK-50075 Question Pool: calculated question solution cancel button console error

### PR DESCRIPTION
**Pull request by jesusmmp**
https://sakaiproject.atlassian.net/browse/SAK-50075

### CODE REVIEW

**Review by bgarciaentornos — APPROVED** [review]
Thanks for this!

**Comment by ottenhoff** [comment]
> Thanks for this!

You're welcome! Why not just cherry-pick this into the branch?

**Comment by ottenhoff** [comment]
The problem is that new commits make reconciling custom branches more difficult. For example, if you cherry-pick a commit from upstream/master and then later do a rebase on the whole branch, the cherry-pick'ed commit will have no problems. But this is a new commit, maybe with different spacing, making reconciliation potentially difficult.

git fetch upstream
git cherry-pick -x SHA-ID
git push origin s2u-22x

**Comment by bgarciaentornos** [comment]
I know, I know...

**Pull request merged**
