### PR TITLE
SAK-46977 Added sitestats.own to all student roles in kernel ddl

### PR DESCRIPTION
**Pull request by adrianfish**
https://sakaiproject.atlassian.net/browse/SAK-46977

### CODE REVIEW

**Review by bjones86 — APPROVED** [review]

**Comment by jesusmmp** [comment]
@adrianfish Again? Where is the oracle script? Please, be careful with this kind of things.
Please, revert and complete the PR correctly.

**Comment by bjones86** [comment]
This does not need to be reverted. It just needs conversion scripts.

**Comment by jesusmmp** [comment]
Thanks @bjones86

**Comment by adrianfish** [comment]
@jesusmmp Relax, dude. I have the conversion script ready in a branch. I want the JIRA to be fully completed before I put it in.

**Pull request merged**
