### PR TITLE
SAK-30368 - Update mariadb driver to 1.3.6 so it works with Sakai

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by buckett** [comment]
Yey, nice one @jonespm 
This doesn't allow the driver to be used with MySQL servers through?

**Comment by jonespm** [comment]
Let me test real quick, I think it will work with both mysql and maria again because I was getting the same NPE before in both too.

**Comment by buckett** [comment]
I was just the first of the linked Jiras in the SAK wasn't marked as resolved.

**Comment by jonespm** [comment]
@buckett Yeah, I can't change the resolution status in this jira instance. I tested with mysql on trunk experimental and it works fine. It looks like both issues are now resolved. Thanks!

**Pull request merged**
