### PR TITLE
SAK-31901 - Support timezones other than GMT in external calendar

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
I really don't like this fix but couldn't see anything else without a large chanrge to

org.sakaiproject.calendar.api.CalendarEvent

It storing the value as org.sakaiproject.time.apiTimeRange->org.sakaiproject.time.api.Time which doesn't actually seem to have any time zone details. It can return the local time as a string(toStringLocal) but not as a long, which doesn't make sense to me. 

Maybe org.sakaiproject.time.api.Time needs a getTimeLocal ? These are all long deprecated though.

**Comment by jonespm** [comment]
So I guess the options are 
- This (minor change to the external calendaring service)
- Add to org.sakaiproject.api.Time to add long getTimeLocal or getTimeOffset (so it knows the local time in MS)
- Use toStringLocal and convert that from a string back to a long in external calendaring service (doesn't make sense, seems like it should be in the kernel)

I'm kinda leaning on #2 now :/

**Comment by jonespm** [comment]
Note, the only thing using this "external calendaring service" was signup and it looked like it always expected that the local time was going to be returned for this method, so the parameter really was redundant. This could be simplified to just always return the local time.

**Comment by ottenhoff** [comment]
@jonespm looks like tests are failing: No bean named 'org.sakaiproject.time.api.TimeService'

**Comment by jonespm** [comment]
Okay I updated the test to not fail on timeService. Should compile this time.

**Pull request merged**
