### PR TITLE
SAK-29469 Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by seththeriault**
Here's a first attempt at a CONTRIBUTING file, previously discussed on the lists. It takes information from the Confluence page and the recent conference session.

### CODE REVIEW

**Comment by bjones86** [comment]
+1

**Comment by buckett** [comment]
+1

**Comment by steveswinsburg** [comment]
This is good. Though I think we should have more focus on what the process
is rather than the specific commands people might use, so that people who
use GUI tools or might do it directly in eclipse etc, know what they need
to do rather than how to do it.

**Comment by seththeriault** [comment]
I have made one minor change to add a relative link to the README.md file.

**Comment by seththeriault** [comment]
README.md has been updated with a relative link to the CONTRIBUTING.md file. I think this is ready to be merged.

**Comment by buckett** [comment]
I'm going to be risky and merge before it's built.

**Comment by steveswinsburg** [comment]
I have updated this slightly. I also think the notes about amending commits and pushing by force is perhaps the wrong approach. We seem to have this obsession now with updating previous commits, squashing commits down into one when really it is multiple commits and rebasing instead of merging.

I'm have the view of committing early and often and actually using source control and history, not just uploading finished files.

Pushing by force destroys history and is a bad practice. I added a note saying this should only be done in your local repo but I fear we might be setting people up for pain. If they need to use these commands then they are obviously green and learn from bad examples. 

It is far safer to just push a new commit with the modifications. it also automatically alerts github that new commits are there.

I'm not saying that amending/rebasing/force should never be used, they have their place. But they shouldn't be the default approach:

Interesting article here: http://paul.stadig.name/2010/12/thou-shalt-not-lie-git-rebase-ammend.html

**Pull request merged**
