### PR TITLE
LSNBLDR-700 Created Forum widget to display latest conversations in L…

### PR DESCRIPTION
**Pull request by ouit0408**
…essons

Added new dialog for Forum summary in ShowPage.html ,related variables
and function are added in 'SimplePageBean.java' to create/edit
SimplePageItem of type FORUM_SUMMARY for Forum summary widget.
New method 'getRecentDiscussionForumMessagesByContext' added in
MessageForumsMessageManager to return given number of recent messages
for a given siteId.
Query(findRecentDiscussionForumMessagesInSite) to get recent forum messages
is added in MessageImpl.hbm.xml
New separate method 'displayMessages' added in ForumsEntityProviderImpl
to handle requests '/direct/forums/messages/SITEID.json?n=10'.

have changed each conversation url in widget to go to 'ShowItemProducer'
class where source url is set to forum tool. This displays each thread
inside Lessons with 'Return to Lessons' option at the top.
MessageId,topicId and forumId variables added in 'GeneralViewParameters'
class.

### CODE REVIEW

**Comment by clhedrick** [comment]
See the PR for announcements. As with that one, I'd prefer not to store anything in the html field.

**Comment by ouit0408** [comment]
Implemented review comment and have updated the PR.

**Comment by clhedrick** [comment]
I'm going to accept this, but there will be a followup that makes significant changes to the implementation.

**Comment by clhedrick** [comment]
I took this code, but not through the PR

**Pull request closed without merging**
