### PR TITLE
SAK-30607 Removed plus sign from Add New Site and renamed the menu option

### PR DESCRIPTION
**Pull request by fostersdesign**
I have removed the redundant plus sign ("+") from beside the "Add New Site" option in the Account menu. I have made this change to all of the sitenav.properties language files that contained the plus sign beside this option (sit_newsite).

I have also changed the wording (in English translations) from "Add New Site" to "Create New Site" to match the wording in Worksite Setup and to avoid any linguistic confusion (such as with "adding a favourite site", or with "being added to"/"becoming a member of" a site).

Please see my before and after screenshots of the change in English.

Before:
01-before

After:
02-after

### CODE REVIEW

**Comment by juanjmerono** [comment]
I'm neutral with this change but I don't understand why did you change all translation files to remove the "+", I think translators should maintain their own files. For example, in spanish this change will be overwritten with the translation of the sentence "Create New Site" that the translation manager will make in transifex. I don't know if there are other unmaintained translations, but I think it has no sense for the updated translations (they have to translate "create" also, not only remove "+").

**Comment by fostersdesign** [comment]
I removed the plus sign from the translation files because I figured it was separate from the task of translating the language.

**Comment by fostersdesign** [comment]
I have reverted all of my changes to non-English translations for this patch. Please review.

**Comment by juanjmerono** [comment]
Thank you Shawn, LGTM.

**Pull request merged**
