### PR TITLE
SAK-27494 prevent samigo from creating duplicate gradebook items (same name)

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/SAK-27494

This has been sitting around in JIRA with a patch for over 2 years now.

### CODE REVIEW

**Comment by bjones86** [comment]
Yep, I think it may have even been your suggestion/idea (from an old Longsight consultation ticket) @ottenhoff  :)

**Comment by ottenhoff** [comment]
Awesome. Thanks for seeing this one through!

**Comment by jonespm** [comment]
The comment on the jira says 
"The patch proposed by Brian works. At least duplicated gradebook items aren't saved, but some exceptions are thrown:"

Do you know if this was still the issue? It sounded like a likely problem of double clicking. We saw this come up in evaluation recently. It's pretty infrequent but it does happen. Does it actually prevent it in the future from creating these or just in that quick request?

**Comment by jonespm** [comment]
Looking back in the commentary, Earle's idea seemed like it would be have been better (catching future duplicates) and not resulted in any exceptions.

**Comment by bjones86** [comment]
Looping in @bbailla2 as this was his work, and he would be more familiar with the details.

**Comment by jonespm** [comment]
Yeah, I suppose there's no real harm to this, but it seems like all it does it allow the first transaction to finish, then the second one that comes in is going to throw a stack trace instead of inserting. So at best this is incomplete and should either also be blocked in the UI or prevented in the db layer

**Comment by bbailla2** [comment]
It's tricky, iirc the issue can't be reproduced consistently. As for the UI, we have the script to disable buttons and add spinners (preventing double click scenarios). As for the DB, unique constraints won't do on this table, since it's valid to have identical external gradebook items as long as there aren't more than one with "removed=0". I agree with you though, we should fix the stack traces, but it's not gonna be easy to pin point their root causes.

**Pull request merged**
