### PR TITLE
SAK-31420 Issue with import from site not working due to logger serialization

### PR DESCRIPTION
**Pull request by ern**
…lization

### CODE REVIEW

**Comment by buckett** [comment]
Could you explain why this fixes it as neither `org.slf4j.Logger` nor `org.apache.commons.logging.Log` implement `Serializable` although it looks like all the common implementations of both of them do.

**Comment by steveswinsburg** [comment]
Curious about this also. Had a quick look but nothing obvious, unless it was to do with SLF4J versions or something?

**Comment by hsteller** [comment]
Looking at the commit: the logger in Gradeable.java wasn't static.
Now that this was removed, there aren't any non-static loggers left to be (de)serialized in the four files in this commit.

Otherwise this is probably an slf4j version issue because there's a "ConcurrentHashMap" (i.e. one that doesn't like keys or values to be NULL) in the stack trace which apparently was an ordinary HashMap in older versions.

Now as to why there was a logger which returned "null" as its name on deserialization..uh..err...
*shrugs*

**Comment by ern** [comment]
@hsteller pretty much summed it up!

The main issue fixed here is the removal of this line.
protected Logger log = LoggerFactory.getLogger(GradeMapping.class);

The rest is just cleanup!

**Pull request merged**
