### PR TITLE
SAK-30784 LTI changes for TII LTI integration

### PR DESCRIPTION
**Pull request by bgarciaentornos**
There's a discussion on the ticket related with cleaning up null properties inside the basiclti tool. There's also CR and assignments associated changes, see TII-188.

### CODE REVIEW

**Comment by ottenhoff** [comment]
@csev any thoughts?

**Comment by ottenhoff** [comment]
Is there a more modular way of accomplishing this? Right now, the code looks like it modifies the central Sakai LTI code.

**Comment by bgarciaentornos** [comment]
It doesn't modify it as much as instroduce extra functionality. I mean, for all the other LTI cases it will work like it used to. We didn't find a different and better way to override it.

**Comment by csev** [comment]
So if I understand this code, there is a special turnitin site and these launches come from that site?  Also if you put custom parameters into a placement or tool, they are automatically added to the launch - why the explicit listing?

**Comment by csev** [comment]
I would really like to see an explanation of roughly what is going on here.

**Comment by bgarciaentornos** [comment]
It's not a turnitin site but different assignment LTI tasks that create "special" LTI tool instances, based on that global "!turnitin" tool. We need to override some resources parameters (description, title, id) with the assignment values, instead of the site or tool ones.

**Comment by ern** [comment]
Going to agree with Sam here that this should have a better pluggable way to add/remove features that extend LTI.

Like an LTIRegistry that can take things of type PluggableLTI and can plug / unplug them.

**Comment by bgarciaentornos** [comment]
It was planned to define more explicitly these kind of special LTI tools, so they are treated differently and we don't have to rely on the TII specific code. However, there was no time for doing all the changes that would be needed, so it was just a quick workaround that wasn't too intrustive on the current LTI behaviour (all the other LTI tools will work just like they used too).

**Comment by bjones86** [comment]
I'm thinking this should be closed. We have sakaicontrib/sakai-turnitin to track changes related to the TII LTI integration that is not part of the actual Turnitin code. I think the plan was to get everything into sakaicontrib/sakai-turnitin first (for 11), then when everything is ready, we merge sakai-turnitin back to sakaiproject/sakai.

Also, I think we may already have this code in sakaicontrib/sakai-turnitin.

@buckett thoughts? Can you confirm or deny my assumptions?

**Comment by bjones86** [comment]
I've confirmed that we already have this code in sakaicontrib/sakai-turnitin. Also, one of my colleagues is working on removing this code, as it's a bit of a hack. He will be submitting a PR to sakaicontrib/sakai-turnitin for this work in the near future.

As such, I'm closing this PR.

**Pull request closed without merging**
