### PR TITLE
SAK-39972 set better minimums for Grade Point schema

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Is missing D+ and D- normal and usual for schools that use a GPA scheme? Or are we building one institution's unique scale into the Sakai codebase?

**Comment by steveswinsburg** [comment]
Also, SettingsGradingSchemaPanel has a map that has to be updated to match this so the GPA stats are correct. Unfortunately this was the only way to get it done at the time, might be simpler now.

**Comment by steveswinsburg** [comment]
@ottenhoff will defer to @lgekeler for advice on that one.

**Comment by jonespm** [comment]
The collegeboard scale has an A+ at 4.0 and no D-. 
https://pages.collegeboard.org/how-to-convert-gpa-4.0-scale

It seems like some schools don't have a A+, D+ or D- like Wellesley
http://www.wellesley.edu/registrar/grading/grading_policy

While Michigan LSA has basically everything
http://www.wellesley.edu/registrar/grading/grading_policy

It seems like this may need to be adjusted per institution, maybe just go with collegeboard?

**Comment by ottenhoff** [comment]
@steveswinsburg you currently have a block on this. How do you want to proceed?

My recommendation is to proceed with this PR as is.

**Comment by steveswinsburg** [comment]
Settingsgradingschemapanel needs an update before this goes in.

**Comment by steveswinsburg** [comment]
Merged this in as I am almost done on the supplementary changes required for this which I am doing as part of SAK-39982

**Pull request merged**
