### PR TITLE
SAK-49293 - Get background color back in assessment settings

### PR DESCRIPTION
**Pull request by danielmerino**

### CODE REVIEW

**Comment by mpellicer** [comment]
I'd like to evaluate the use of input color here:

https://developer.mozilla.org/es/docs/Web/HTML/Element/input/color

Maybe a combination of a color and text inputs.

**Comment by danielmerino** [comment]
Thanks, Miguel, I have done a quick test and it says that "the attribute [type] is not valid according to the specified TLD".

I have no idea of JSF and I don't know if it's fixable. Do you use that input type in any other code of Samigo that I could study?

**Comment by mpellicer** [comment]
> Thanks, Miguel, I have done a quick test and it says that "the attribute [type] is not valid according to the specified TLD".
> 
> I have no idea of JSF and I don't know if it's fixable. Do you use that input type in any other code of Samigo that I could study?

That's why I suggested using a text input, and a color input, the text input is controlled by the color input. I mean, I'm fine using a simple text input, but I believe we should add a minimum validation.

**Comment by danielmerino** [comment]
I'm afraid I don't know how to do that... Any code sample that I could get inspiration of?

I have tried to put a non HEX value in the textfield and it is saved but it doesn't break anything. The preview feature works fine with no background color if the value is not correct. I think that we are safe, besides this feature will be disabled by default.

**Comment by mpellicer** [comment]
Could you post some screenshots of the UI please? Just the settings page. Thanks

**Comment by danielmerino** [comment]
imagen

**Review by mpellicer — APPROVED** [review]
I'm fine with this, any other comments?

**Comment by mpellicer** [comment]
Thank you very much for the contribution @danielmerino , terrific work.

**Comment by mpellicer** [comment]
@danielmerino @vacercon UPV has reported the same issue, do you want me to improve this to support the color picker?

**Comment by mpellicer** [comment]
@danielmerino This is the patch we're going to put in UPV.

https://github.com/mpellicer/sakai-apereo/commit/d550909e02e5b9ffb4aab5296c95807c7ae44923

As you can see it uses the standard color picker and updates the text input, and the opposite if it's a valid color. Could you evaluate the additional commit and see if there are concerns?

Thanks

**Review by mpellicer — CHANGES_REQUESTED** [review]
Requested an evaluation of adding a color input instead of a link.

**Comment by mpellicer** [comment]
GRE-141577

**Comment by danielmerino** [comment]
Hi Miguel, I have tested it. It works fine but when a color is saved and the configuration is edited, the color picker is not refreshed with the stored hexadecimal value. It starts with black color and it only refreshes when some change is done and the focus is lost. Losing the focus with the same value doesn't change the color though.

I'm not sure if I'm being clear, if you don't understand this just tell me in slack and we can talk about it.

**Comment by mpellicer** [comment]
> Hi Miguel, I have tested it. It works fine but when a color is saved and the configuration is edited, the color picker is not refreshed with the stored hexadecimal value. It starts with black color and it only refreshes when some change is done and the focus is lost. Losing the focus with the same value doesn't change the color though.
> 
> I'm not sure if I'm being clear, if you don't understand this just tell me in slack and we can talk about it.

I covered the case and updated the commit, when it's initialized it picks the previous value too.
https://github.com/mpellicer/sakai-apereo/commit/ba009f35265f7dca38a0e1aff4b95b70078abd8e

**Comment by mpellicer** [comment]
> > Hi Miguel, I have tested it. It works fine but when a color is saved and the configuration is edited, the color picker is not refreshed with the stored hexadecimal value. It starts with black color and it only refreshes when some change is done and the focus is lost. Losing the focus with the same value doesn't change the color though.
> > I'm not sure if I'm being clear, if you don't understand this just tell me in slack and we can talk about it.
> 
> I covered the case and updated the commit, when it's initialized it picks the previous value too. [mpellicer@ba009f3](https://github.com/mpellicer/sakai-apereo/commit/ba009f35265f7dca38a0e1aff4b95b70078abd8e)

Ensure that your version has this IF sentence:
https://github.com/mpellicer/sakai-apereo/commit/ba009f35265f7dca38a0e1aff4b95b70078abd8e#diff-7f15251a79ba607d2e8c8d6838587cccd20f20d98520e069df91ea0d52efe3eeR201

**Comment by danielmerino** [comment]
Now it works perfect, Miguel. Thanks a lot, an amazing work!

**Comment by mpellicer** [comment]
> Now it works perfect, Miguel. Thanks a lot, an amazing work!

No problem! Would you mind picking the changes from my branch and update this PR?

**Comment by mpellicer** [comment]
Thanks Dani, this is ready to go!

**Review by mpellicer — APPROVED** [review]

**Pull request merged**
