### PR TITLE
LSNBLDR-123 When a file or URL is changed, all properties from the original file are replaced except for the Item Description

### PR DESCRIPTION
**Pull request by joaquinmarques**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Please delete bad code instead of commenting it out

**Comment by joaquinmarques** [comment]
Updated

**Comment by jonespm** [comment]
I was trying this out locally and it doesn't appear to be working for me. The description is still the same and the alt text still seems to be the same as the original file. It seems like the alt text should match the new file uploaded?

**Comment by jonespm** [comment]
I also don't know about this change either. The comment on 
https://jira.sakaiproject.org/browse/LSNBLDR-432

Is that "Note that this patch may be at odds with LSNBLDR-123. However, I would argue that the system should not be deleting any user-supplied data without explicit consent from the user."

I think the "ideal" solution would be that alt-text and description can be changed if the user desires on the popup for uploading rather than the popup for editing. I don't know if I'd take this as-is as it would basically erase the LSNBLDR-432 change.

**Comment by joaquinmarques** [comment]
Closed due to conflict with LSNBLDR-432

**Comment by joaquinmarques** [comment]
Closed due to conflict with LSNBLDR-432

**Pull request closed without merging**
