### PR TITLE
SAK-29158 Turkish Translation of Sakai 11.0

### PR DESCRIPTION
**Pull request by eemirtekin**
I have updated Turkish translation of all Sakai files for 11.0

### CODE REVIEW

**Comment by steveswinsburg** [comment]
There are conflicts, you'll need to pull master into your branch and resolve any conflicts before this can be merged.

**Comment by eemirtekin** [comment]
Hi @steveswinsburg 
We are doing these translations with crew in https://crowdin.com/project/sakai-cle.
Don't you take any updated language files from crowdin?
Until now, we thought that you received these files. We saw that you haven't get these updated language files.  Also, How can I understand where these conflicts come from.

Thanks in advance.

**Comment by steveswinsburg** [comment]
Hi @eemirtekin, merge conflicts occur if the file has changed since you branched it and modified it. If you just pull master into your branch and push up the modifications, that should sort it out.

**Comment by eemirtekin** [comment]
Hi @steveswinsburg 

When i forked the sakai master project, i added language files and pull request it. The variance was only in the language files . The purpose is updating new translations to the current versions. Can you add these language files, If i send to you.

Thanks in advance.

**Comment by steveswinsburg** [comment]
Yep, I can see the changes are only for the language files. What I mean is that in the time between you forking the code and sending this PR, another commit has gone into master that touched one of these file so yours is now out of date. 

If you just pull the sakai master into your branch again, then push the updates to your branch, git will sort it out. There will likely be a few conflicts, if your files are the authoritative source, just resolve the conflicts using your versions of the files. That is what anyone would need to do if they took your patch.

Once you push, this PR will automatically be updated and we can merge it.

**Comment by ern** [comment]
Just as a note it would have been easier for you to make these changes if you did not work on your master but rather a feature branch which could aptly be named the same as the JIRA issue i.e. "SAK-29158".

For now its best to close this PR and for you to follow these instructions and then resubmit the PR.
see https://confluence.sakaiproject.org/display/SAKDEV/Git+Setup

Your next PR should be from branch eemirtekin:SAK-29158 and not eemirtekin:master

**Pull request closed without merging**
