### PR TITLE
SAK-29271  - Merge the base code for the feedback tool

### PR DESCRIPTION
**Pull request by mcarropellicer**
SAK-29271  - Merge the base code for the feedback tool.

The base tool constains some known bugs that must be solved in several Jiras.

-The tool does not insert any row in the MySQL table.
-Needs Oracle support
-Fix some bugs
        -helpdeskUrl has no effect over the application
        -Help links causes 404
        -Use of "mail.support" instead of "Constants.PROP_TECHNICAL_ADDRESS"

More bugs ans fixes in SAK-29271 dependencies.

### CODE REVIEW

**Comment by juanjmerono** [comment]
The tool adds its own jquery file, but portal uses the same version, so it should use common portal jquery js rather than its own file, right?

**Comment by adrianfish** [comment]
Yes, portal strips out the duplicate.

**Comment by juanjmerono** [comment]
I'm wondering if jquery plugins should be moved to common library folder also.

**Comment by mcarropellicer** [comment]
Thanks for the feedback @juanjmerono.

https://jira.sakaiproject.org/browse/SAK-29271 contains a bunch of issues that should be resolved, I've added the JQUERY concern to the list (https://jira.sakaiproject.org/browse/SAK-29572).

**Comment by mcarropellicer** [comment]
This contains all the resolved Jiras of the parent's ticket, it's ready to be evaluated, discussd and merged.

**Pull request merged**
