### PR TITLE
SAK-29485: Default theme changes

### PR DESCRIPTION
**Pull request by udayg**
SAK-29485: Default theme changes based of suggestions during PMC meeting on 6/3/15
Note: Icons are still images , they have to be fonts instead ( SAK-29489 -pending )

Live preview: http://qa01-sakai.marist.edu/portal

desktop
mobile

### CODE REVIEW

**Comment by ottenhoff** [comment]
Hi Uday, you are fast! I don't know if you want more suggestions on this ticket, or if you want suggestions in a new JIRA...

but one quick suggestion: The down arrow.png on the active site is a grey on dark grey and should have more contrast.  Maybe that can just become a font when fontawesome is incorporated?

**Comment by udayg** [comment]
I am OK with any thing new JIRA or suggestions here.
Yes, all Icons will be font eventually so, I would not look at the icons for now :) .

**Comment by ottenhoff** [comment]
Okay great.  Anyone else have comments on this?  I think it looks very good and is based on the conversation we had in the PMC meeting.

**Comment by SedueRey** [comment]
LGTM, great work

**Pull request merged**
