### PR TITLE
SAK-43202 Only add item id on existing associations

### PR DESCRIPTION
**Pull request by adrianfish**
https://jira.sakaiproject.org/browse/SAK-43202

Also, fixed style scoping on sakai-rubric-criteria-grading.js

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/sakaiproject/sakai/pullRequest?prid=4982322&bid=16454043)

**Comment by ottenhoff** [comment]
Can the gradebook tool alone (not a gradebook item) have an association with a rubric? If not, these are unnecessary calls. 

I don't know why these end up in a never-ending loop using automated testing, but they do, and it's extremely difficult to debug.

**Comment by adrianfish** [comment]
The gradebook tool can have associations with rubrics, without external tools being involved, like Assignments. Or do you mean it happens when there are no items in the gradebook at all?

**Comment by ottenhoff** [comment]
But only a gradebook *item* can have an association with a rubric, right?

**Comment by adrianfish** [comment]
Yes, just an item

**Comment by ottenhoff** [comment]
Can we avoid this unnecessary call when we don't have an entityId (aka gb item)?

GET /rubrics-service/rest/rubric-associations/search/by-tool-item-ids?toolId=sakai.gradebookng

**Pull request merged**
