### PR TITLE
SAK-32660 Moved Roster2 to use portal.i18n library

### PR DESCRIPTION
**Pull request by adrianfish**

### CODE REVIEW

**Comment by ern** [comment]
@adrianfish this looks fine, however there is a new web service that allows for tools to get translations, see [SakaiI18n.java](sakai/tree/master/webservices/cxf/src/java/org/sakaiproject/webservices/SakaiI18n.java)
It would be nice for tools to begin using that vs having their own endpoint!!!!

**Comment by adrianfish** [comment]
All that class does is reserialize the bundle into a props file. The jquery i18n lib loads them into memory in the browser, directly from the props file on the server, so there's no endpoint, just the files. However, is it fair to say that the class flattens multiline properties reliably? jquery-i18n-properties parses the java props files, and the parsing code is a bit lairy. It might make sense to hook a javascript lib to that endpoint and simplify the code on the client. I might look at that. What do you think? Could the class be modded to produce JSON if requested?

**Comment by ern** [comment]
Well reading java props directly would circumvent all the java prop handling in Sakai like MessageBundleManager where props come from the DB. So this would be very bad!

**Comment by adrianfish** [comment]
How do you use SakaiI18n, then? What pulls those key/value pairs?

**Comment by adrianfish** [comment]
and ... does SakaiI18n transparently pull translations via the MessageBundleManager. Basically, if I switch portal.i18n.loadProperties to pull properties from SakaiI18n, will that be a better approach than just coding up props files and pulling them via ajax?

**Comment by adrianfish** [comment]
Merge #4629 before this. I'll refactor 4629 after to use this approach.

**Comment by adrianfish** [comment]
@ern I've rebase this onto master, but I need to work out how to load roster's properties from the roster webapp. I don't think this is possible seeing as Sakaii18n is in a webapp classloader. In other words, am I right in saying that you have to put your properties in the shared classloader to make them available? If so we either have to add an impl to our tools when we don't really need one, or we add the properties to the shared properties loader. What do you reckon?

**Pull request closed without merging**
