### PR TITLE
SAK-40993 MariaDB j & MySQL j

### PR DESCRIPTION
**Pull request by axxter99**
MariaDB j 2.3.0

Mysql j 5.1.47

### CODE REVIEW

**Comment by axxter99** [comment]
mysql-connector-java-8.0.13?

**Comment by mpellicer** [comment]
I had troubles with MySQL connector 8.x, reverted to 5.1.47 and everything went well again.

**Comment by mpellicer** [comment]
https://groups.google.com/a/apereo.org/forum/#!msg/sakai-dev/ejBSP-fKS6g/RU7zx3glDQAJ

**Comment by ottenhoff** [comment]
I believe there are serious issues with mysql-connector 5.1.47 .  I recommend reverting this change.

**Comment by mpellicer** [comment]
What kind of issues @ottenhoff ? I'm using 5.1.46 in all of our instances, didn't upgrade to .47 yet.

Feel free to revert this change if there are serious issues, I merged this because I expect the PRs are tested.

**Comment by ottenhoff** [comment]
Hi Miguel, I can't find notes on the errors we saw, but I believe we saw some OOM errors. I have looked in the MySQL tracker and am not seeing any major issues reported there..... So I guess we wait to see how this goes.

**Pull request merged**
