### PR TITLE
LSNBLDR-709 Added calendar component for Lessons page.

### PR DESCRIPTION
**Pull request by ouit0408**
New option 'Embed Calendar' is added in the list on Lessons page.
SimplePageItem of type 'Calendar' created for calendar widget.
Calendar shows events from all the merged calendars in the Lessons tool.

Exposed method 'getCalendarReferences' in CalendarService to get
references from all calendars for a site.
Added attributes 'description' and 'eventImage' in the EventSummary class
which will be used in the json returned by CalendarEventEntityProvider.
Created map for event type and image in the CalendarUtil class which can be
accessed using method 'getEventImageMap'.

### CODE REVIEW

**Comment by clhedrick** [comment]
I installed this. A couple of things:
1) The tool is always added to the end of the page. It needs to work if you click the + in the middle of  page. In the popup menu that lists tools, to the <A> add the class add-before-param. That will cause the item number of the item you're supposed to add the before to be put in the addBefore parameter of the URL. The picker has to get that parameter and add it as a hidden field in the form that's submitted to the bean. Look at any of the existing pickers for the code.
2) If i add the tool and then refresh the page, it gets added an additional time
3) Please look at formatting the display. The calendar is white on a white column background. I'm not sure how I'd handle that. Either put blue behind the whole thing (e.g. look at the Checklist tool) or maybe put blue behind the header and a margin around the rest. Look at the latest version of the forums summary.

**Comment by ouit0408** [comment]
IThanks Charles for your input, I will implement the comments. About the 2) point this problem happens with the comments tool too as we are not clearing 'addtool' param from the request therefore it gets added 2 times. we should clear the 'addtool' param from the request once it's been added. I reckon same problem will occur for 'STUDENT_CONTENT' and 'STUDENT_PAGE'.

**Comment by clhedrick** [comment]
The problem with comments tool going the wrong place is fixed in both master and 11.x. I think it was fixed for 11.1, however I can't find which Jira did the fix.

**Comment by ouit0408** [comment]
'2) If i add the tool and then refresh the page, it gets added an additional time' I was speaking about this comment  not about the place. If we add comments tool or calendar and then refresh page both gets added twice.

**Comment by clhedrick** [comment]
Ah. I’ll look into it.

On Sep 6, 2016, at 9:42 AM, Neelam Bhandari <notifications@github.com<mailto:notifications@github.com>> wrote:


'2) If i add the tool and then refresh the page, it gets added an additional time' I was speaking about this comment not about the place. If we add comments tool or calendar and then refresh page both gets added twice.

**Comment by ouit0408** [comment]
I have implemented the comments and have updated the pull request. i have attached the screenshot of lessons-calendar.
lessons-calendar

**Comment by clhedrick** [comment]
OK, I'm going to accept this later in the day. The version I'll accept will have two changes:
1) the item will be in the same section of the add menu as "embed announcements" not the top section
2) the buttons in the calendar will be flat, to match the rest of Sakai 11.

**Comment by clhedrick** [comment]
Ugh. More issues. I think you need another iteration:
1) put the item in the add menu in the same section as "embed announcments"
2) set auto height so we don't get a vertical scroll bar
3) the buttons should be flat, to match the rest of Sakai
4) internationalize the calendar widget. There are English strings passed in the config for fullCalendar. To internationalize Lessons Javascript: Add the strings to messages.properties. Display them in ShowPage.html in the block of strings. In the Javascript, use msg to pull the definition out of the block of strings.
5) The calendar widget doesn't seem accessible. I'm not seeing labels for the next and prev buttons, so I'm guessing not. I didn't check anything else after finding that. I don't think we should accept any new widgets that aren't accessible.

I would have done 1 - 3 myself, but with Internalization and accessibility missing, I think you should do it.

**Comment by clhedrick** [comment]
Fullcalendar developers are looking at accessibility. See https://github.com/fullcalendar/fullcalendar/issues/2536. But they seem not to be resolved. I'm not sure what level we want to demand. But at least having button labels accessible seems like a minimum.

**Comment by ouit0408** [comment]
I have implemented above comments and have updated pull request. For accessibility I have added labels for buttons so that it is accessible on mouse over.

**Comment by clhedrick** [comment]
I just tried the current version of the PR. Something has to be missing. There's nothing in the pulldown that lets me add this component.

**Comment by nicholaswilson100** [comment]
I'm taking over this PR as Neelam has stopped working on it and creating a new one.

**Comment by nicholaswilson100** [comment]
The new Pr is https://github.com/sakaiproject/sakai/pull/3660

**Comment by ern** [comment]
closing since a new PR incorporates this see #3660

**Pull request closed without merging**
