### PR TITLE
SAK-33857 Remove useless gradebook code

### PR DESCRIPTION
**Pull request by steveswinsburg**
There is a bunch of code in the gradebook service that is unused. This removes it and cleans it up a bunch.

https://jira.sakaiproject.org/browse/SAK-33857

### CODE REVIEW

**Comment by ern** [comment]
This probably makes sense to remove after the 12.0 release.

**Comment by steveswinsburg** [comment]
Updated and ready to go.

**Comment by ern** [comment]
Steve, can you address the conflicts here?

**Comment by jonespm** [comment]
I think it's a good time to merge over the next month or so whenever these conflicts are resolved

**Comment by steveswinsburg** [comment]
Maybe get the rest of the latest gbng backports done first (for the updated
graph code), then merge.

**Comment by steveswinsburg** [comment]
Updated with master

**Comment by steveswinsburg** [comment]
@jonespm and @ern - I dont intend to fix all of the Gradebook Classic issues that codacy has, should we just merge this now?

**Comment by jonespm** [comment]
Ya I wouldn't worry about those, I think the time is good to merge this.

**Comment by steveswinsburg** [comment]
It is done 👐

**Pull request merged**
