### PR TITLE
First initial commit for EmailTemplate Service implementation in Sami…

### PR DESCRIPTION
**Pull request by gillmanjc**
…go - SAM-1262

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Looks good, so is publishAssessment being used as the template for the emails?

**Comment by gillmanjc** [comment]
Hi Steve
Yes publishAssessment.xml is suppose to be used as the template for emails. The committed changes are far from a working implementation. As I have mentioned, the changes in the PR thus far is just start of the EmailTemplateService Implementation.

**Comment by steveswinsburg** [comment]
Ok great. Yeah I meant if the publishAssessment template is actually being used when sending emails now. If so, awesome. Do you know how many emails there are in in Samigo that need to be converted over?

**Comment by gillmanjc** [comment]
Hi Steve
Please do not these initial commits are every basic and does not have much meat on them. As mentioned, due to time constraints and the fact that now patch was provided, all had to be done from scratch. This means that although the ground work has been done, the publishAssessment template still needs to completed. I have send through the summary of hours used.. can you please have a look and let me know how you think we must move forward? The hours I have been given has now almost been maxed out.

**Comment by steveswinsburg** [comment]
Lets focus on the other two before returning to this one, those are more complete.

**Comment by steveswinsburg** [comment]
Since this is incomplete I will close so it is not accidentally merged. However it would be good if we could get those code somewhere, maybe attached to the jira?

**Pull request closed without merging**
