### PR TITLE
SAK-12148 fix first-time startup errors around SakaiBootstrap

### PR DESCRIPTION
**Pull request by ottenhoff**

### CODE REVIEW

**Comment by ottenhoff** [comment]
CC: @austin48

**Review by adrianfish — APPROVED** [review]

**Comment by austin48** [comment]
does this also fix [SAK-47265](https://sakaiproject.atlassian.net/browse/SAK-47265)?

**Comment by austin48** [comment]
thanks, it _partially_ fixes SAK-47265.  One of the indexes (SAM_AG_AGENTID_I) in that jira still wasn't created after applying this patch.

note, when applying the patch (on my MacBook), I had to use --ignore-whitespace because it looks like the patch adds different line endings <CR>.  I'm not sure if that would affect github merging.

**Comment by ottenhoff** [comment]
Okay, can you add SAM_AG_AGENTID_I to this PR via the Edit PR button?

**Comment by austin48** [comment]
I don't think I have edit permission for this PR?  but here's the original index

./docs/conversion/sakai_2_6_0_mysql_conversion.sql:152:

create index SAM_AG_AGENTID_I on SAM_ASSESSMENTGRADING_T (AGENTID);

**Pull request merged**
