### PR TITLE
SAK-13910 - Allow hard-coded 'reply-to' address to be overridden

### PR DESCRIPTION
**Pull request by mcarropellicer**

### CODE REVIEW

**Comment by ottenhoff** [comment]
This looks good to me. +1 . Nice job Miguel

**Comment by mcarropellicer** [comment]
Oooops, accidentally unpublished the branch.

**Comment by mcarropellicer** [comment]
Definetely the Windows GitClient (GUI) does not like me, it added more commits to this Pull Request.

How can i rollback to https://github.com/mcarropellicer/sakai/commit/ae18aef1ce6a7861cd3c52029ed134bf7f4a07ee?

**Comment by mcarropellicer** [comment]
I will generate a new pull request with correct data, sorry for the mistakes.

**Comment by mcarropellicer** [comment]
I've been able to restore the branch to the original commit with "git revert --hard COMMIT_ID"

Is correct now?

**Comment by ottenhoff** [comment]
Looks good.

**Pull request merged**
