### PR TITLE
SAK-42085: Instructor: Manage Rubrics Cannot access the Add Rating ic…

### PR DESCRIPTION
**Pull request by ajordanedf**
…ons and Edit Rating icons

### CODE REVIEW

**Comment by adrianfish** [comment]
Actually, I think is just the wrong approach. I think we should actually show the + button at all times if you have permission to add a rating. I really don't like those icons flashing in and out of existence like that. I suggest to close this and take the easier path of just having those + icons showing all the time.

**Comment by ajordanedf** [comment]
Hi Adrián, I think the user experience will be much better if we make the icons appear and disappear as you navigate, it is beautiful and gives the site some dynamism, what do you think?

**Comment by mpellicer** [comment]
@adrianfish what do you think?

> Hi Adrián, I think the user experience will be much better if we make the icons appear and disappear as you navigate, it's most intuitive, prettier and gives the site some dynamism, what do you think?

**Comment by adrianfish** [comment]
@ajordanedf I prefer things to just be visible, unless it makes things really cluttered. I think things flashing on and off can actually be counter intuitive, unless used very carefully. The other edit elements are visible all time, like the edit icon.

**Comment by ern** [comment]
If the icon adds clutter then it would make sense to make controls visible when focused. Also are there any accessibility concerns.

**Comment by adrianfish** [comment]
Closed for now. We need input from the UI designer on this, we couldn't reach consensus here on the PR, and too much has changed in the rubrics layout since the PR went in.

**Pull request closed without merging**
