### PR TITLE
SAK-44413 - Remove sakai.force.secure.url property

### PR DESCRIPTION
**Pull request by csev**
This is high risk.  Please review.

### CODE REVIEW

**Comment by ottenhoff** [comment]
Fair to say that not setting serverUrl means an instantly broken Sakai? I'm def okay with this in PROD. Does it matter for DEV? 

It seems like a reasonable thing to be required to set.

**Comment by bjones86** [comment]
I think `serverUrl` already defaults to http://localhost:8080

**Comment by csev** [comment]
@bjones86 is correct - if it is not present, it must default to http://localhost:8080 or a whole bunch of stuff goes per shaped.  But that does bring up a use case - of when a person deploys Sakai without setting serverUrl - and before this change, it might guess it correctly from the request.  Not really a good way to run production.  With this change, the default is http://localhost:8080 and if you want something other than that - set the property.  (great comments - thanks)

**Review by ottenhoff — APPROVED** [review]
Agree

**Pull request closed without merging**
