### PR TITLE
SAK-40624 Update version of ckeditor image2 in pom

### PR DESCRIPTION
**Pull request by jonespm**
Relates to #6003

### CODE REVIEW

**Comment by ottenhoff** [comment]
Thansk @jonespm

**Comment by jonespm** [comment]
Sure, let me know if you have any questions about SAK-40658 when updating that. I'm still in Slack and github, but don't have any easy way to release anything at the moment. Should be easy for @ern  (or whoever is doing releases now)

**Comment by ern** [comment]
Thanks @jonespm.

**Comment by mpellicer** [comment]
@jonespm The good thing about https://jira.sakaiproject.org/browse/SAK-40634, despite it broke the Jenkins build only, is that 2 of 3 plugins use webjars and a human-readable version.

Thanks for fixing this

**Pull request merged**
