### PR TITLE
SAK-44246 - Quartz throwing NPEs on GetArchivesJob

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Review by bjones86 — APPROVED** [review]
Interesting. How come this job needs the treatment but others don't?

**Comment by jonespm** [comment]
I honestly don't know why this one isn't working. 

I compared GetArchivesJob to ImportJob, which is working fine and didn't see much difference.

* ImportJob injects ArchiveService and SessionManager. 
* GetArchivesJob injects ServerConfigurationService and SchedulerManager

I debugged though this code and in the method I changed, when autowireBean is run, these values are populated as expected in ImportJob. These are not populated in GetArchivesJob. However they are after running autowireBeanProperties. 

I also believe that this was working fine before the upgrade in previous versions of Sakai. 

I read some things about how it doesn't work if there isn't a NoArgsConstructor but adding that does nothing.

The only difference I could see between these two jobs is ImportJob isn't setup as it's own bean in components.xml, it's only as part of AutowiredJobBeanWrapper. GetArchivesJob has a standalone bean as it's used in AutoRun and SchedulerManager. I tried to figure out how to re-do this to make these the same but didn't get anything working. 

I'm up for any other ideas, but this change seemed to fix the problem and didn't seem to have any regressions.

**Comment by bjones86** [comment]
Yeah that's strange. I don't know much about it either so barring anyone else bringing something to the table, I think this is fine as is.

**Comment by ern** [comment]
The reason for this is because the SakaiApplicationContext is a GenericApplicationContext it would need to be a AnnotationConfigApplicationContext as autowiring is needed for annotations!!!

**Pull request merged**
