### PR TITLE
SAK-48251 Users: issue with passwords surrounded by spaces when importing users from file

### PR DESCRIPTION
**Pull request by V100X**
Jira: [SAK-48251](https://sakaiproject.atlassian.net/browse/SAK-48251)
Issue preventing users -imported with a password containing leading or trailing spaces- to log in.

[SAK-48251]: https://sakaiproject.atlassian.net/browse/SAK-48251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bgarciaentornos — CHANGES_REQUESTED** [review]
I think this might fail with null passwords

**Review by bgarciaentornos — APPROVED** [review]

**Comment by bgarciaentornos** [comment]
LGTM (this code is only for the csv import)

**Review by mpellicer — CHANGES_REQUESTED** [review]
I'd like more information about this change, add some comments please

I know the issue and we suffered this a lot in the past, but simply add some comments and use variables, they are free!!


String userPass  = user.getPassword();
// Set an empty String password for null passwords.
if (userPass == null) {
  userPass = "";
}
// when importing user passwords from CSV they can contain spaces that cause login problems accidentally.
userPass = userPass.trim();

userDirectoryService.addUser(null, user.getEid(), user.getFirstName(), user.getLastName(), user.getEmail(), userPass, user.getType(), user.getProperties());

**Comment by V100X** [comment]
Makes sense @mpellicer, Thanks

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Nice thanks @V100X !

**Pull request merged**
