### PR TITLE
KNL-1271 Remove old caching code. 

### PR DESCRIPTION
**Pull request by buckett**

### CODE REVIEW

**Comment by ottenhoff** [comment]
Very nice.  +1

**Comment by csev** [comment]
I love it when we remove code!

**Comment by buckett** [comment]
@clhedrick This contains some changes to lessons. Basically you were specifying a time when adding items to the cache (call has been deprecated for a while), so I changes the code so that cache is setup with a default TTL the same as you were using and changed to using the call without the explicit timeout.

Seem ok?

**Comment by buckett** [comment]
When the constant is only used once I find it easier to read code that has the constants embedded, otherwise you're jumping around the code. As an example this is better:
```
Cache cache = new Cache().ttl(300).idle(50).size(500);
```
than:
```
public static final int CACHE_TTL_SECONDS = 300;
public static final int CACHE_IDLE_SECONDS = 50;
public static final int CAHE_SIZE = 500;

[..lots of code..]

Cache cache = new Cache().ttl(CACHE_TTL_SECONDS).idle(CACHE_IDLE_SECONDS).size(CACHE_SIZE);
```

**Comment by buckett** [comment]
I've updated the lessons code to use constants.

**Pull request merged**
